### ISSUE TITLE
misc: some basic goals

### ISSUE THREAD

**Issue by membphis** [apache/apisix-ingress-controller#1]
ingress本身是为了k8s入口流量转发，为了达到这样的效果，需要一层代理，我们用apisix实现
所以ingress本身的能力偏向管理，性能要求属于apisix自身特性
需要达到一些管理效果：
1、yaml文件的定义，兼容k8s 现有ingress的配置；
（测试现有ingress的yaml能否被aipsix ingress controller正确执行）
2、能支持apisix中新增的对象，比如route、upstream、plugin等；
（测试apisix对象是否能够通过yaml正确定义）
3、apisix的热加载；
（测试yaml变更之后，是否是热更新）
4、与k8s中的状态同步；
（测试k8s服务生命周期是否正常同步到apisix）
其他一些功能测试：
5、apisix本身的healthcheck等；
（测试k8s pod出现异常时，apisix能否及时调整流量）
6、ingress controller热备切换；
（测试ingress controller的高可用）

I got them from @gxthrj .

**Comment by gxthrj** [comment]
close this misc now. We have a basic implements.
