### ISSUE TITLE
request help: support jwt-auth plugin for ApisixConsumer

### ISSUE THREAD

**Issue by sff0219** [apache/apisix-ingress-controller#1001]
### Issue description

We are currently facing a similar issue with these two issues https://github.com/apache/apisix-ingress-controller/issues/986 and https://github.com/apache/apisix-ingress-controller/issues/990.

In Kubernetes we want to create a consumer with the `jwt-auth` plugin enabled by using `ApisixConsumer`. However we found out that now only `basic-auth` and `key-auth` are supported in this way. We could still add a consumer with `jwt-auth` via apisix admin api but it would be ideal to use `ApisixConsumer` from apisix ingress controller directly.

**Comment by AlinsRan** [comment]
Let me do it!

**Comment by tao12345666333** [comment]
Assigned 

Thanks

**Comment by tao12345666333** [comment]
#1009  has been merged. I will close this one.
