### ISSUE TITLE
request help: update docker hub v1.4.0

### ISSUE THREAD

**Issue by stone2world** [apache/apisix-ingress-controller#1008]
### Issue description

docker hub v1.4.0 need update

some bug fixed but not publish

### Environment

![image](https://user-images.githubusercontent.com/43597843/167358089-5b739856-af38-4539-b4d5-c5688379ef5c.png)

![image](https://user-images.githubusercontent.com/43597843/167358186-b29346b9-7837-49e3-a6c7-d7c30e81cf97.png)

**Comment by tao12345666333** [comment]
Thanks for your report. 

In fact we are voting for the release of v1.4.1 
https://lists.apache.org/thread/yz0ttw2sw67o3ydcbqyr1ng5vt3yo5c7

After 1.4.1 is released, the corresponding container image will also be released.

The vote has now received enough votes, and the 1.4.1 release process is expected to be completed tomorrow at the latest

**Comment by tao12345666333** [comment]
https://lists.apache.org/thread/1qllm6szr7howz4jzv36bvzg9o5b2hmk

The vote is now closed and I will start the release process for v1.4.1. I will close this issue and thank you for your report!
