### ISSUE TITLE
request help: how to setup plugin ua-restriction

### ISSUE THREAD

**Issue by hxcGit** [apache/apisix-ingress-controller#1010]
### Issue description

I want to try ua-restriction plugin. I followed the guide(https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/minikube.md) and installed Ingress APISIX on Kind. And I followed ua-restriction's guide(https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/ua-restriction.md) to setup the plugin. But I got a "Connection refused" error.

### My steps
1. 
```
kubectl create ns ingress-apisix
helm install apisix apisix/apisix \
  --set gateway.type=NodePort \
  --set ingress-controller.enabled=true \
  --namespace ingress-apisix \
  --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix
```
2. 
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    },
    "plugins": {
        "ua-restriction": {
             "bypass_missing": true,
             "allowlist": [
                 "my-bot1",
                 "(Baiduspider)/(\\d+)\\.(\\d+)"
             ],
             "denylist": [
                 "my-bot2",
                 "(Twitterspider)/(\\d+)\\.(\\d+)"
             ]
        }
    }
}'
```

### other information
![image](https://user-images.githubusercontent.com/60642406/167402891-3b01b305-81be-4927-8d1e-b4e78709bcbc.png)
![image](https://user-images.githubusercontent.com/60642406/167402927-123ec7fe-8c23-4127-b831-a30af1bbb3a7.png)

### Environment

- APISIX version：apisix:2.13.1-alpine；apisix-ingress-controller ：apisix-ingress-controller:1.4.0
- Kubernetes version: v1.23.4
- OS version (uname -a): Linux ubuntu 5.15.0-27-generic amd64

**Comment by tao12345666333** [comment]
you should run `curl` command in Apache APISIX 's container
