### ISSUE TITLE
help request: failed to install CRD crds/customresourcedefinitions.yaml

### ISSUE THREAD

**Issue by zzq926083010** [apache/apisix-ingress-controller#1017]
### Description

执行：helm install apisix-ingress-controller apisix/apisix-ingress-controller --namespace apisix  --set config.apisix.serviceName=apisix-dashboard --set ingress-controller.enabled=true --set config.apisix.serviceNamespace=apisix --set config.apisix.servicePort=9080 --set config.logLevel=warn --set config.apisix.adminKey=edd1c9f034335f136f87ad84b625c8f1

报错：Error: INSTALLATION FAILED: failed to install CRD crds/customresourcedefinitions.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

### Environment

- APISIX version (run `2.11`):
- Operating system (run `Linux master 3.10.0-957.el7.x86_64 apache/apisix#1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `v3.5.4`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
For the latest Helm charts, we need Kubernetes v1.16+.

But you can modify the CRD api-version by yourself, or use the old version of Chart.

**Comment by tao12345666333** [comment]
I think the above replies have answered this question.
And this issue has not been updated for a long time, we can safely close it
