### ISSUE TITLE
Proposal:  Apisix-Ingress-Controller support integrating with service discovery registry

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix-ingress-controller#1019]
Currently, Apisix-Ingress-Controller only supports Kubernetes services as service discovery. However, Apisix supports multiple service discovery registry, such as Eureka and Nacos . Therefore, Apisix-Ingress-Controller is proposed to support more service discovery integration.
This will help users resolve legacy infrastructure issues and expand Apisix-Ingress-Controller usage scenarios.  ref #948 

One possible solution is to add `discovery_type` to `http[].backends` and `stream[].backend` of [`apisix_route_v2Beta3`](https://apisix.apache.org/zh/docs/ingress-controller/references/apisix_route_v2beta3). The default value is `kubernetes` and the behavior remains the same as now.

Consul_kv, DNS, NacOS, Eureka  are available based on [apisix's service integration configuration](https://apisix.apache.org/docs/apisix/discovery). If these are optional, these configurations will only be converted to apisix upstream configurations and will not be processed by parsing the endpoint through the kubernetes service.

**Comment by tokers** [comment]
@Gallardot Would you like to submit a proposal to dev@apisix.apache.org? Thanks!

**Comment by Gallardot** [comment]
> @Gallardot Would you like to submit a proposal to [dev@apisix.apache.org](mailto:dev@apisix.apache.org)? Thanks!

@tokers   I have sent an email to [dev@apisix.apache.org](mailto:dev@apisix.apache.org), please check again

**Comment by tao12345666333** [comment]
SGTM.

As I replied on the mailing list:

> For now, the APISIX Ingress controller is a control plane component that
does not handle static configuration of APISIX.
>
>I think the most initial support is:
>
>* Allow some Upstreams that are not part of Kubernetes
>
>We need to make some changes to the processing logic of Upstream

https://lists.apache.org/thread/fmdnssz9hm1n6yk2y7py2fs2k6mj3hcd

**Comment by tao12345666333** [comment]
The first method is too complicated, and currently we need to consider other requirements at the same time, such as supporting external name

**Comment by Gallardot** [comment]
> It's my idea that we have two ways:
> 
> 1. The service in the service registry has a corresponding Kubernetes Service object but without endpoints, and there is an annotation on the Kubernetes service with some details about the real service information in the registry. This way we don't have to update the ApisixRoute CRD;
> 2. We modify the ApisixRoute CRD so that we can allow users specify a field like `discovery_from`, when this field exists, APISIX Ingress Controller doesn't ask users to fill the `service` item. This way makes the ApisixRoute CRD more complicated. But the use is easier (without the dependency of annotations on Service).

> The first method is too complicated, and currently we need to consider other requirements at the same time, such as supporting external name #927 and split ApisixUpstream #864

Yes, I agree that the first method is too complicated and less usable. 

If we use the second method, the question becomes where to add fields? I suggest the following option


> One possible solution is to add `discovery_type` to `http[].backends` and `stream[].backend` of [`apisix_route_v2Beta3`](https://apisix.apache.org/zh/docs/ingress-controller/references/apisix_route_v2beta3). The default value is `kubernetes` and the behavior remains the same as now.
> 
> Consul_kv, DNS, NacOS, Eureka are available based on [apisix's service integration configuration](https://apisix.apache.org/docs/apisix/discovery). If these are optional, these configurations will only be converted to apisix upstream configurations and will not be processed by parsing the endpoint through the kubernetes service.

If we supporting external name service #927 , we can add a new `discovery_type ` named `external_Service`
