### ISSUE TITLE
doc: add the way of changing the admin key into FAQ

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix-ingress-controller#1021]
## issues description:

When I wanted to change the admin key for my Ingress, I found no documentation about this, but the fact that I needed to change two admin keys was hard to find for someone new to APISIX-Ingress. I want to add a message to the FAQ to improve the documentation.

Problem sources: https://the-asf.slack.com/archives/CUC5MN17A/p1652688280858689

## I will do:

add *how to change the admin key of APISIX-Ingress* into [FAQ](https://apisix.apache.org/docs/ingress-controller/FAQ)

**Comment by tao12345666333** [comment]
SGTM.

A description of this is included in the configuration file, but it's also good to put it in the FAQ separately, if you are interested please submit a PR, thanks
https://github.com/apache/apisix-ingress-controller/blob/3cccd5666e098f374c262eb443de194d69d6a55e/conf/config-default.yaml#L81-L89
