### ISSUE TITLE
request help: How to use APISIX on low memory devices

### ISSUE THREAD

**Issue by VineFiner** [apache/apisix-ingress-controller#1024]
### Issue description

I deploy apisix in 1C1G, always memory alarm.
traefik no problem.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version): k3s
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): Ubuntu:20.04

**Comment by tao12345666333** [comment]
> I deploy apisix in 1C1G, always memory alarm.

Do you mean APISIX or APISIX ingress controller?

**Comment by VineFiner** [comment]
> > I deploy apisix in 1C1G, always memory alarm.
> 
> Do you mean APISIX or APISIX ingress controller?

I use traefik and it works fine. Is it not recommended to install apisix with low memory?

**Comment by VineFiner** [comment]
> Please provide more details:
> 
> 1. APISIX Version, APISIX Ingress Controller Version
> 2. How did you find the memory problem, and what does it look like?

I just test it. Use Alibaba Cloud Lightweight Server.
can not work

**Comment by tao12345666333** [comment]
If you install using the above command, it will install the following:

* 1 APISIX pod
* 3 etcd pods
* 1 APISIX Ingress controller pod

If you are just for testing, you can set the number of replicas for etcd to 1

**Comment by VineFiner** [comment]
With 2 cores 2G works fine. I will close it.
