### ISSUE TITLE
infra: update golang version

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#1032]
Go 1.16 is end of support since 1.18 is released.

**Comment by tao12345666333** [comment]
SGTM

**Comment by tokers** [comment]
SGTM, let's update it to `1.17`.

**Comment by lingsamuel** [comment]
I'm also thinking using generics to reduce code duplication for multi-version support.

**Comment by tao12345666333** [comment]
How about we upgrade to 1.18?
