### ISSUE TITLE
help request:   apisix get upstreams 404

### ISSUE THREAD

**Issue by bubbyqi** [apache/apisix-ingress-controller#1042]
### Description

dear apisix specialist, i need support,  we config the apisix-ingress-controller to router the request to the backend svc in k8s ,but access ,404  error happen.  the backend svc with nginx-ingress-controller is ok.

ingress:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/20379897/170413545-ff24dd04-e6a2-4103-bd3d-aca5b5ccc58b.png">

router:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/20379897/170413211-35784de6-4325-447f-a064-90ca004c00f6.png">

apisix pod error log: 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/20379897/170413068-0b1cba15-a854-4e56-8b72-f1d3025731ab.png">

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
you can modify the configuration `pathType: Prefix`  and try again.

**Comment by tao12345666333** [comment]
For APISIX , if you want to proxy all paths, the config should be `/*` instead of `/`

**Comment by bubbyqi** [comment]
> For APISIX , if you want to proxy all paths, the config should be `/*` instead of `/`

@tao12345666333  thanks for reply,but still 404 error
<img width="599" alt="image" src="https://user-images.githubusercontent.com/20379897/170432242-3946791b-ae4f-4ee3-89b6-c8c52febb00e.png">

<img width="993" alt="image" src="https://user-images.githubusercontent.com/20379897/170432297-2238309f-dba0-4492-9871-ee33f7afe50c.png">

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/20379897/170432346-236e06eb-7bff-4e05-a6cf-27b55ca3a591.png">


<img width="996" alt="image" src="https://user-images.githubusercontent.com/20379897/170432560-8fd958f9-7ad7-4a2f-8b23-89ed0ff92e6c.png">

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/20379897/170432634-66099355-f3ac-42f5-b04c-eb405ff0b01f.png">

**Comment by tao12345666333** [comment]
What is the `default backend`  in your screenshot?
Looks like it has nothing to do with APISIX or APISIX Ingress

**Comment by bubbyqi** [comment]
@tao12345666333 
the apisix ingress  deployment:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/20379897/170433829-85378689-07af-4e56-8e53-853fc8ece86d.png">
the backend is the  sopexe-for-deployment svc  at the namespace dev
<img width="760" alt="image" src="https://user-images.githubusercontent.com/20379897/170433982-69bb3bf4-8ab2-4505-ac61-ca66288ed87e.png">
the nginx-ingress deploy
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/20379897/170434117-e4a0e641-0d7a-44e9-8853-1fae00d6a19b.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/20379897/170434206-8947c2aa-ed9e-42c4-9134-f033a87d264d.png">

from the nginx-ingress, can acess ok
<img width="958" alt="image" src="https://user-images.githubusercontent.com/20379897/170434244-506873ff-b5fa-4e2b-9bac-7d79ec1eb779.png">

**Comment by tao12345666333** [comment]
Obviously the status code in your screenshot above is also 404.

This requires you to check your upstream services.


You can refer to this document for functional verification.

https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/proxy-the-httpbin-service-with-ingress.md
