### ISSUE TITLE
request help: apisix wolf-rbac consumer config for multiple appIds

### ISSUE THREAD

**Issue by rjiang-ptm** [apache/apisix-ingress-controller#1043]
### Issue description

In the apisixConsumer config for wolf-rbac, the appId field can only be specified for one appid, or a list of appid? The use case is: usually for a given consumer/user, there could be multiple apps (appIds) associated with that user. 

Here is the typical consumer config for wolf-rbac:
```
{
  "username":"wolf_rbac",
  "plugins":{
    "wolf-rbac":{
      "server":"http://127.0.0.1:12180",
      "appid":"restful"
    }
  },
  "desc":"wolf-rbac"
}'
```

Notice the `appid` is just one string.

If the apisixConsumer wolf-rbac config can support multiple appid for a given consumer/user, how to specify it - in what format, can you show some examples? If it's not supported, what do you suggest to support the above user case?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.0
- your Kubernetes cluster version (output of kubectl version): 1.22
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Please refer to https://apisix.apache.org/docs/apisix/plugins/wolf-rbac/#attributes, it is consistent with APISIX

**Comment by rjiang-ptm** [comment]
Are you saying it is indeed true for apisixConsumer to only have ONE appid associated? That means one consumer can only access one app? In wolf-rbac, one user (corresponding to one consumer in apisix) can have a list of appIds, which means one user can access multiple apps (same as the use case I mentioned above).

Should the apisixConsumer config for `appid` field be expanded to a list?

**Comment by tao12345666333** [comment]
I mean it depends on the implementation in APISIX

**Comment by rjiang-ptm** [comment]
ah, right, should post this question on apisix then...

**Comment by tao12345666333** [comment]
Yes

**Comment by tao12345666333** [comment]
I will close this issue and open it for tracking after APISIX supports this behavior, thanks for the report
