### ISSUE TITLE
log: shouldn't log secret object

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#1045]
http://github.com/apache/apisix-ingress-controller/blob/3d0b9769894197ba3138cd3b96d775ba2163e0c8/pkg/ingress/secret.go#L376-L376

**Comment by tao12345666333** [comment]
the link is invalid.

**Comment by PGDream** [comment]
get

**Comment by tao12345666333** [comment]
@PGDream do you want to pick up this task?

**Comment by PGDream** [comment]
> @PGDream do you want to pick up this task?

y

**Comment by tao12345666333** [comment]
@PGDream Assigned, thanks

**Comment by zaunist** [comment]
[WeOpen Star]I would like to help
