### ISSUE TITLE
request help: Handling default Ingress resources (tested with Keycloak)

### ISSUE THREAD

**Issue by NMichas** [apache/apisix-ingress-controller#1049]
### Issue description

Hello, I'm trying to deploy Keycloak using the Bitnami chart (https://github.com/bitnami/charts/tree/master/bitnami/keycloak) and expose it using its built-in Ingress resources generation as:

```
helm upgrade --install keycloak bitnami/keycloak --version 9.0.5 \
  --set service.type=ClusterIP \
  --set ingress.enabled=true \
  --set ingress.pathType=Prefix \
  --set ingress.ingressClassName=apisix \
  --set ingress.selfSigned=true \
  --set ingress.hostname=idm.local.esthes.is \
  --set ingress.path="/" \
  --set "extraEnvVars[0].name"=KEYCLOAK_PROXY_ADDRESS_FORWARDING \
  --set-string "extraEnvVars[0].value"=true \
  --set "extraEnvVars[1].name"=KEYCLOAK_FRONTEND_URL \
  --set "extraEnvVars[1].value"="http://idm.local.esthes.is"
```

The above generates an Ingress such as:
![Lens](https://user-images.githubusercontent.com/2218296/170636095-2cda2fdd-cd16-4f98-9b37-f53c6078a67c.png)

When I open http://idm.local.esthes.is, the Keycloak welcome page is properly presented, however all generated links seem to be prefixed with `idm.local.esthes.is:9080` instead of just `idm.local.esthes.is`:
![Cursor_and_Welcome_to_Keycloak](https://user-images.githubusercontent.com/2218296/170636441-3ee61b16-fa9c-45a0-b39c-b83d5ad26e31.png)
Interestingly, 9080 is the http port of the APISIX pod:
![Cursor_and_Lens](https://user-images.githubusercontent.com/2218296/170636581-b96ca470-27b9-4ba5-a8d0-0c88918df574.png)

If I switch the `IngressClassName` above to `nginx` (so that nginx ingress handles the ingress creation), everything works fine.

Is my ingress definition missing something to allow APISIX ingress to work properly?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1 (with APISIX 2.14.1)
- your Kubernetes cluster version (output of kubectl version): v1.23.6+k3s1

**Comment by NMichas** [comment]
This issue seems to be solved by adding `--set proxy=none `. Not sure if it creates other problems further down the road (as Keycloak *is* reversed proxied via APISIX) but for now this issue can be closed.

**Comment by tao12345666333** [comment]
thanks for your share
