### ISSUE TITLE
request help: install apisix-ingress fail

### ISSUE THREAD

**Issue by vcqr** [apache/apisix-ingress-controller#1061]
### Issue description

helm install apisix apisix/apisix \
  --namespace ingress-apisix --create-namespace \
  --set gateway.type=LoadBalancer \
  --set ingress-controller.enabled=true \
  --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix \
  --set etcd.persistence.enabled=false

status

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/3401237/171379414-98b05a34-6d0f-41ba-8039-0af81e9b3ff2.png">

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version): 1.24.1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): 
 k8smaster:~# uname -a
Linux k8smaster 5.15.41-0-virt #1-Alpine SMP Fri, 20 May 2022 21:42:55 +0000 x86_64 Linux

**Comment by tokers** [comment]
This is normal. Your ETCD cluster is not ready, so your APISIX service won't be ready. Since APISIX Ingress Controller will detect the status of APISIX service, so it's also not ready (the init container is running).

**Comment by tao12345666333** [comment]
As @tokers said, you can check etcd's log to see why it failed
