### ISSUE TITLE
lint: add yamllint to format yaml files under samples/deploy/ directory

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1062]
> I suggest to support yamllint to format those yaml files.

Good idea. I will create new issue for track it.

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/pull/1051#discussion_r887441161_

**Comment by tao12345666333** [comment]
cc @mangoGoForward

**Comment by mangoGoForward** [comment]
Sure, I'd like to work on it.

**Comment by tao12345666333** [comment]
thanks! assigned.

**Comment by tao12345666333** [comment]
@sakulali assigned, thanks
