### ISSUE TITLE
docs: add v2 apiversion resource reference docs

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1063]
According to #707 we recently added resources for v2 version.

But we haven't added the corresponding reference documents.

It would be better to add a new api-version of the documentation.

In order to complete this issue, you can rename the files in this directory [1] to `*_v2beta3.md` , and copy these files to update the content to v2 api-version.

1: https://github.com/apache/apisix-ingress-controller/tree/master/docs/en/latest/references

**Comment by stillfox-lee** [comment]
Please assign it to me.

**Comment by tao12345666333** [comment]
@stillfox-lee Thanks! Assigned.

Feel free to ping me if you have any questions
