### ISSUE TITLE
request help: webhook-registration.yaml 

### ISSUE THREAD

**Issue by xxdyu** [apache/apisix-ingress-controller#1069]
### Issue description

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: apisix-validations
  labels:
    app: apisixroute-plugin-validator-webhook
    kind: validating
webhooks:
  - name: apisixroute.plugin.validator.webhook
    clientConfig:
      service:
        name: apisix-admission-server
        namespace: ingress-apisix
        port: 8443
        path: "/validation/apisixroutes/plugin"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apisix.apache.org"]
        apiVersions: ["*"]
        resources: ["apisixroutes"]
    timeoutSeconds: 30
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
----
kubectl  apply -f  webhook-registration.yaml 
---
Error from server (BadRequest): error when creating "webhook-registration.yaml": ValidatingWebhookConfiguration in version "v1" cannot be handled as a ValidatingWebhookConfiguration: v1.ValidatingWebhookConfiguration.Webhooks: []v1.ValidatingWebhook: v1.ValidatingWebhook.ClientConfig: v1.WebhookClientConfig.Service: CABundle: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|A_BUNDLE}","service"|..., bigger context ...|1beta1"],"clientConfig":{"caBundle":"${CA_BUNDLE}","service":{"name":"apisix-admission-server","name|...

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
You can refer to this file https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/testdata/webhook-create-signed-cert.sh

If you want to use `admissionregistration.k8s.io/v1`, please ensure your kubernetes  cluster is at least as new as v1.16

**Comment by tao12345666333** [comment]
In addition, please add a description when submitting an issue next time, so that it can be more clear

**Comment by wanghuashun** [comment]
thanks
