### ISSUE TITLE
request help:  在同一个k8s集群中如何分别给apisix内网、apisix外网集群创建upstream、route

### ISSUE THREAD

**Issue by jackey20200402** [apache/apisix-ingress-controller#1070]
### Issue description

我在k8s集群中部署了两套apisix，分别关联阿里云的内外网负载均衡。我在使用yaml创建upstream、route时遇到问题：我无法指定这个upstream 和 route 是属于哪套apisix，请问这种情况应该怎么解决呢？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.0
- your Kubernetes cluster version (output of kubectl version):  1.20.11-aliyun.1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
If you have multiple APISIX clusters, then you also need multiple APISIX Ingress controllers to connect to these clusters respectively.

In APISIX Ingress configuration, `namespace_selector` can be configured to control the namespace to be processed by APISIX Ingress controller.
https://github.com/apache/apisix-ingress-controller/blob/96dd07f847bff9d425b223e0bcac0eea2efe6316/conf/config-default.yaml#L58-L60

Or you can differentiate by `ingress_class`  https://github.com/apache/apisix-ingress-controller/blob/96dd07f847bff9d425b223e0bcac0eea2efe6316/conf/config-default.yaml#L64-L67

**Comment by jackey20200402** [comment]
那么如果我同一个ns下面的两个服务需要分别作为两套apisix集群的upstream，这个又该如何处理呢？

**Comment by tao12345666333** [comment]
you can differentiate by ingress_class

**Comment by jackey20200402** [comment]
ingress_class的配置有参考例子吗？我尝试两个apisix集群定义不同ingress_class后再通过metadata.annotations.kubernetes.io/ingress.class 配置upstream、route。发现还是两个apisix集群都同步了一样的upsream、route

**Comment by tao12345666333** [comment]
ingress_class can only be used for Ingress resources, not for custom resources

**Comment by jackey20200402** [comment]
好的，谢谢。我在官方文档找到了使用的例子：https://apisix.apache.org/zh/docs/ingress-controller/practices/proxy-the-httpbin-service-with-ingress

**Comment by jackey20200402** [comment]
使用ingress的方式如何配置apisix插件？

**Comment by tao12345666333** [comment]
you can use annotations to do this. ref:

https://github.com/apache/apisix-ingress-controller/blob/2af39c949883dc831aa64be075aa7cc0edd2dd8a/test/e2e/suite-annotations/redirect.go#L164-L166
