### ISSUE TITLE
request help: How to route the public traffic to the actual service via apisix ingress

### ISSUE THREAD

**Issue by haohello** [apache/apisix-ingress-controller#1074]
### Issue description

Sorry, this may sound silly to ask such kind of questions here. I'm just starting out to learn how to use apisix and kubernetes.
As per the example on this [page](https://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service) , once you create a route, you'll be able to proxy this route through apisix, obviously there is no clue here on how to route the public traffic to the actual service.

### Environment

- your apisix-ingress-controller version (the latest version): latest
- your Kubernetes cluster version (output of kubectl version): v1.23.6+k3s1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
If I understand correctly, you are asking how to access the actual service through APISIX outside the Kubernetes cluster.

First you need to get APISIX to route the proxy correctly, which is obviously already done in your screenshot.

Then, outside the Kubernetes cluster, you should access the address exposed by APISIX. 
You can check the address of the `apisix-gateway` service. It may be exposed through NodePort or LoadBalancer.

Then you can correctly route to your service by accessing the address and port.

**Comment by haohello** [comment]
I'm using the LoadBalancer IP address of the `apisix-gateway` service.  As you can see from the screenshot, it still shows the error of '404 Route Not Found'.

**Comment by tao12345666333** [comment]
Maybe you need to remove the `/` at the end of the url.

**Comment by tao12345666333** [comment]
Can you check APISIX's logs?
Or first check if your IP is correctly forwarded to APISIX

**Comment by haohello** [comment]
May I ask how I could check apisix' logs? Plz bear with me, I have no idea how to work this out.

**Comment by haohello** [comment]
![image](https://user-images.githubusercontent.com/134774/172445657-0fced551-dd77-48ac-9627-7b382c474acf.png)

**Comment by tao12345666333** [comment]
It's obvious from the logs that your host hader is not being passed. 
You can check the configuration of your load balancer

**Comment by haohello** [comment]
@tao12345666333 There is [also another issue in the k3s project issue list](https://github.com/k3s-io/k3s/issues/1652), looks like that might be the similar issue I encountered.

**Comment by tao12345666333** [comment]
So you are using klipper-lb (k3s servicelb) instead of public cloud LoadBalancer, right?

I would recommend you to try MetalLB.

**Comment by haohello** [comment]
I'm afraid that I couldn't be able to use MetalLB since it is not possible for me to get a layer 2 ip address. 
All of the servers are on the Hetzner Cloud, they only allow the users to bind the ip to a specific server.

After too many trials and errors, I finally get it working correctly after reinstall everything from scratch again.   I guess it might be a network firewall issue.

**Comment by haohello** [comment]
Now it turned out that the command `curl http://5.1xx.xx.108/headers -H 'Host: local.httpbin.org'` can't return correct result only on my local machine.
When I tried this command on the Hetzner Cloud servers and also on the website `https://reqbin.com/curl` , all return with the expected result.

**Comment by tao12345666333** [comment]
> After too many trials and errors, I finally get it working correctly after reinstall everything from scratch again.
:+1: 



> When I tried this command on the Hetzner Cloud servers and also on the website `https://reqbin.com/curl` , all return with the expected result.

In this case, can we consider this issue to be resolved?

**Comment by haohello** [comment]
Yes, thank you very much for helping resolve this issue.

**Comment by tao12345666333** [comment]
OK, I will close this issue, if you have any questions, feel free to open a new issue.
