### ISSUE TITLE
CI: add regression testing with apisix:dev

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1075]
Currently, we will use the latest version of APISIX for e2e testing to ensure the compatibility of APISIX Ingress and APISIX.

But we don't know about some of the latest changes in APISIX.
I suggest we add a scheduled job to use `apisix:dev` image for regression testing.

We used to use `apisix:dev` for e2e testing by default, but this way would affect our development experience, and sometimes we found that e2e failed, but it was actually just due to some changes in APISIX.

**Comment by tao12345666333** [comment]
https://hub.docker.com/layers/apache/apisix/dev/images/sha256-d56ffe4f1722cb6ee2d779360bc93837a6d2f0953af77588993e54978709943d?context=explore

**Comment by ps-19** [comment]
I wish to work on this issue. Kindly assign this to me.

**Comment by tao12345666333** [comment]
#1721 has been merged. I will close this one. Thanks
