### ISSUE TITLE
request help: Is there any way to create a ssl certificate automatically when creating an apisix route?

### ISSUE THREAD

**Issue by haohello** [apache/apisix-ingress-controller#1081]
### Issue description

Is there any way to create a ssl certificate automatically when creating an apisix route?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by haohello** [comment]
The [doc on this page](https://apisix.apache.org/docs/ingress-controller/practices/manage-certificates-with-cert-manager/) requires manually creating the SSL certificate.
I'm wondering if there is any way to create SSL certificate automatically with cert-manager http01 solvers similar to [the one on this page](https://k3s.rocks/https-cert-manager-letsencrypt/).

**Comment by tao12345666333** [comment]
Sure!

The document is an example, you can refer to the documentation of cert-manager for specific configuration. https://cert-manager.io/docs/

You can use a similar Ingress resource or ApisixRoute resource. I've verified this feature before, and it's also used by some users in production.
