### ISSUE TITLE
request help: Why does 'the enabling https redirect' redirect to the https scheme with the port 9443?

### ISSUE THREAD

**Issue by haohello** [apache/apisix-ingress-controller#1082]
### Issue description

I've deployed a whoami image and set up route with the https redirect enabled.
Now the browser will redirect `http://domain.com/foo` to `https://domain.com:9443/foo`
Any ideas how this happened?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by haohello** [comment]
This happened when you enable the https redirect on the admin dashboard UI.

**Comment by haohello** [comment]
Setting the `http_to_https` redirect plugin in the yaml config file also get the same result. Anybody who can look into how to resolve this issue?
![image](https://user-images.githubusercontent.com/134774/173258393-d7bf9ef4-ce6c-453e-b773-656cdf8cc15f.png)
![image](https://user-images.githubusercontent.com/134774/173258412-09cf2f52-4f23-4281-a1ac-12a145a7a629.png)

**Comment by tao12345666333** [comment]
duplicate https://github.com/apache/apisix/issues/7172

**Comment by haohello** [comment]
I'm using the latest version of APISIX, obviously this issue still hasn't been resolved yet.

**Comment by tao12345666333** [comment]
Please refer to this document to configure APISIX 

https://apisix.apache.org/docs/apisix/plugins/redirect/

> Only one of http_to_https, uri and regex_uri can be configured.
> 
> When enabling http_to_https, the ports in the redirect URL will pick a value in the following order (in descending order of priority)
> Read plugin_attr.redirect.https_port from the configuration file (conf/config.yaml).
> If apisix.ssl is enabled, read apisix.ssl.listen_port first, and if it does not exist, read apisix.ssl.listen and select a port randomly from it.
> Use 443 as the default https port.
>

**Comment by haohello** [comment]
Why can't you just make this plugin to work with the default 443 https port out of the box? It's too difficult for newcomers like me to figure out how to get it working correctly even if you just throw the documentation here. It still looks too complicated for me to figure out where the `conf/config.yaml` file really is in my kubernetes cluster.

**Comment by haohello** [comment]
I guess you can add a `Tip me` button in the issue section so that I'm willing to send a few hundred bucks as tips to help speed things up a little.

**Comment by haohello** [comment]
> Please refer to this document to configure APISIX
> 
> https://apisix.apache.org/docs/apisix/plugins/redirect/
> 
> > Only one of http_to_https, uri and regex_uri can be configured.
> > When enabling http_to_https, the ports in the redirect URL will pick a value in the following order (in descending order of priority)
> > Read plugin_attr.redirect.https_port from the configuration file (conf/config.yaml).
> > If apisix.ssl is enabled, read apisix.ssl.listen_port first, and if it does not exist, read apisix.ssl.listen and select a port randomly from it.
> > Use 443 as the default https port.

Technically speaking, https redirect only send a `301` or `302` response with a new url so that the browser will initiate a new https request with the new url, why is there a need to make it so complicated?

**Comment by haohello** [comment]
??

**Comment by tao12345666333** [comment]
In fact, the APISIX Ingress controller is a control plane component, it does not control how APISIX is deployed (or the APISIX configuration file).

So as described in the above documentation, you can avoid redirection to port 9443 by modifying the APISIX configuration file.



> Why can't you just make this plugin to work with the default 443 https port out of the box?

Also, the actual redirection port depends on how you are deploying.
If you directly let APISIX listen on ports 80 and 443, you won't have this problem.


For the APISIX Ingress controller project, we need to keep its behavior consistent with APISIX to avoid confusion for users.
So for this issue, we will not make any adjustments at this time.

**Comment by wofr** [comment]
I run into the same problem.  I deployed apisix by using helm-chart therefore I had to adapt the following paramter

```
      - name:  "gateway.tls.containerPort"
        value: "443"  
```
which changes the value apisix.ssl.listen_port to 443, just in case somebody runs into the same problem.  I suggest the documentation (https://apisix.apache.org/docs/apisix/plugins/redirect/) should be updated.

**Comment by ohayak** [comment]
> redirect.https_port

Indeed it changes the container port but it dosn't solve the problem, redirect still rewrite the port to 9443. The workaround that worked for me was to edit the redirect plugin attribute "https_port" to match containerPort on 443
I m using the heml chart so it's sometjing like:
```yaml
gateway:
  tls:
    enabled: true
    containerPort: 443
pluginAttrs:
  redirect:
    https_port: 443
```

**Comment by wofr** [comment]
Out of interest, I alsow used the helm-chart but the pluginsAttrs redirect was not part of the config created by helm, I guess thats why I needed to adapt the containerport.

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-helm-chart/blob/46d0096fd23fdcad58e8337d62c78550c0014b46/charts/apisix/values.yaml#L159

you can try to change this item to 443

**Comment by wofr** [comment]
For me adding the helm paramter `"gateway.tls.containerPort"  value: "443" `  did the trick!   First I tried to change ` "pluginAttrs.  redirect.https_port: 443'`  like @ohayak did but it did not work as ` "pluginAttrs.redirect.https_port'` was not part of the configuration.    Out of interest, I would like to know how he managed to add the prameter `"pluginAttrs.redirect.https_port"`  to the config.

**Comment by ch4dwick** [comment]
> Why can't you just make this plugin to work with the default 443 https port out of the box? It's too difficult for newcomers like me to figure out how to get it working correctly even if you just throw the documentation here. It still looks too complicated for me to figure out where the `conf/config.yaml` file really is in my kubernetes cluster.

Just want to share this.

I've been fumbling around with this all week. Apparently, the configs for apisix are store in the configmaps. So you do this:
> kubectl edit configmap -n <your apisix namespace> apisix-gateway
> kubectl edit configmap -n <your apisix namespace> apisix

I find that restarting the deployment is more reliable than just reloading as it needs to remount the files.
