### ISSUE TITLE
request help: http to https redirect

### ISSUE THREAD

**Issue by haohello** [apache/apisix-ingress-controller#1084]
### Issue description

Use the following code to enable the https redirect for the  path `/bar`, however the https version of this path can't work correctly after this operation.
```
kubectl exec -it -n ingress-apisix apisix-7584d75d9-lg522 -- curl http://127.0.0.1:9080/apisix/admin/routes/40f73b2a -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -d '
{
	"uri": "/bar",
	"host": "code.devtaoism.com",
	"vars": [
		[
			"scheme",
			"==",
			"http"
		]
	],
	"plugins": {
		"redirect": {
			"uri" : "https://$host$request_uri",
			"ret_code": 301
		}
	}
}'
```
The screenshot of the logs for the http to https redirect:

![image](https://user-images.githubusercontent.com/134774/173222672-e9e28e32-ad6a-4be2-9d6a-ec441d91b08c.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): latest version
- your Kubernetes cluster version (output of kubectl version):  v1.23.6+k3s1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): ubuntu 22.04

**Comment by tao12345666333** [comment]
The log shows that your certificate does not match the SNI

Maybe you should use your domain name to access instead of your IP

**Comment by haohello** [comment]
I'm using the domain name instead of IP address.

**Comment by haohello** [comment]
![image](https://user-images.githubusercontent.com/134774/173227319-edcb3613-c6b3-4b87-802c-93e1a4ae865a.png)

**Comment by haohello** [comment]
The path `/foo` hasn't been set any https redirect rules and is working correctly for the https. Once if you set the https redirect rule the same as above, https access will be the same as above.

The screenshot below is what it looks like when not setting any https redirect rules.
 
![image](https://user-images.githubusercontent.com/134774/173227473-33dafec3-4284-4e68-b9d4-0a0dc684aa99.png)

**Comment by haohello** [comment]
Any ideas how to resolve this issue?

**Comment by haohello** [comment]
??

**Comment by haohello** [comment]
@tokers There is already a working SSL certificate configured for the domain name `code.devtaoism.com` which is clearly shown in the screenshot for the path `/foo` , and [here is the link for your information](https://github.com/apache/apisix-ingress-controller/issues/1084#issuecomment-1153117069).

**Comment by haohello** [comment]
??

**Comment by tao12345666333** [comment]
Have you checked out this document?
https://apisix.apache.org/docs/apisix/FAQ/#how-do-i-redirect-http-traffic-to-https-with-apache-apisix
