### ISSUE TITLE
request help: DigitalOcean support

### ISSUE THREAD

**Issue by BFergerson** [apache/apisix-ingress-controller#1088]
### Issue description

I don't see a guide for installing this on DigitalOcean. Does that mean DigitalOcean is not supported? If not, is there anything that's blocking support, or is it just something that hasn't been tried?

I'm trying to install this on DigitalOcean but I'm not entirely sure what needs to be done. I'm successfully able to use NGINX Ingress Controller with DigitalOcean using this file https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.1/deploy/static/provider/do/deploy.yaml. What would be the equivalent file for this ingress controller?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): n/a
- your Kubernetes cluster version (output of kubectl version): 1.22.8-do.1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): n/a

**Comment by tao12345666333** [comment]
No, just because the documentation is not added. Since there are many public cloud vendors, adding a documentation for each vendor in the project will increase maintenance costs.

Of course, if anyone would like to contribute documentation then we would be more than welcome and accept.

I recommend that you install directly with Helm.
If you have problems installing the APISIX Ingress controller on DO, please submit an issue.

**Comment by BFergerson** [comment]
Thanks for the recommendation. I'm trying to follow [this guide](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/the-hard-way.md), but I'm running into this error:
```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
```

All the previous steps work fine:
```sh
b@b:~/Desktop/tester$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
b@b:~/Desktop/tester$ kubectl create ns apisix
namespace/apisix created

b@b:~/Desktop/tester$ kubectl apply -f config
config2.yaml  config.yaml   

b@b:~/Desktop/tester$ kubectl apply -f etcd.yaml 
service/etcd-headless created
statefulset.apps/etcd created

b@b:~/Desktop/tester$ kubectl -n apisix exec -it etcd-0 -- etcdctl endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 3.743602ms

b@b:~/Desktop/tester$ kubectl apply -f apisix.yaml 
deployment.apps/apisix created

b@b:~/Desktop/tester$ kubectl -n apisix create cm apisix-conf --from-file ./config.yaml
configmap/apisix-conf created
```

I see there is a note to ensure `etcd.host` matches the headless service. What command would I use to ensure that?

**Comment by tao12345666333** [comment]
If it is your first experience or trying it out, I really recommend that you install directly with Helm, it is the easiest and continuously maintained way to do it.


The-hard-way documentation in this project is there to guide users in understanding exactly what is needed and what is going on.  Of course, the user also needs some experience.  Also, the documentation only ensures that it is correct at the time, I have the impression that this documentation has not been updated for a long time... sorry, we don't have many people maintaining it together.

**Comment by tao12345666333** [comment]
Back to your question, you can run

`kubectl -n APISIX get service/etcd-headless `

**Comment by BFergerson** [comment]
@tao12345666333, I was able to get [this guide] working, thanks. I think I avoided starting with this guide because it installs etcd and apisix-admin. I'm using the standalone version of APISIX. Is there a guide that shows how to install the apisix-ingress-controller with the stand-alone version of APISIX?

I've tried doing it without etcd and I run into:
```
Defaulted container "ingress-controller" out of: ingress-controller, wait-apisix-admin (init)
Error from server (BadRequest): container "ingress-controller" in pod "apisix-ingress-controller-6c7c757f75-qn4cl" is waiting to start: PodInitializing
```

---

> Back to your question, you can run
> 
> `kubectl -n APISIX get service/etcd-headless `

That doesn't seem to help:
```
kubectl -n apisix get service/etcd-headless 
NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
etcd-headless   ClusterIP   None         <none>        2379/TCP,2380/TCP   5m19s
```

**Comment by tao12345666333** [comment]
> Is there a guide that shows how to install the apisix-ingress-controller with the stand-alone version of APISIX?

No. The stand-alone version of APISIX (without etcd) can't work with APISIX Ingress controller.

**Comment by anhbinhvodanh** [comment]
Hi @BFergerson,
Did you deploy apisix successfully to DigitalOcean?
Thanks.

**Comment by BFergerson** [comment]
Unfortunately, no. I'm still using NGINX ingress controller as apisix-ingress-controller doesn't support the standalone version of APISIX.

**Comment by anhbinhvodanh** [comment]
Hi @BFergerson Did you try this one. I can successfull deploy apisix to DigitalOcean https://apisix.apache.org/blog/2021/12/15/deploy-apisix-in-kubernetes/

**Comment by BFergerson** [comment]
@anhbinhvodanh, good to know it'll work but it looks like that guide uses etcd too. Currently, I do not need to dynamically configure APISIX. It's fully configured via the standalone file.
