### ISSUE TITLE
request help: How to let multiple APISIX Ingress process resources independently

### ISSUE THREAD

**Issue by guwenjiang85** [apache/apisix-ingress-controller#1089]
### Issue description

我目前使用apisix都是通过ApisixRoute，没有使用ingress资源；
如何在ApisixRoute中申明ingress-class来隔离内网和公网网关；
还有就是配置Ingress资源如何使用插件功能。

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
apisix-ingress-controller version 1.4.1-no-git-module-go1.16.15
/ingress-apisix # ./apisix-ingress-controller version --long
Version: 1.4.1
Git SHA: no-git-module
Go Version: go1.16.15
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

- your Kubernetes cluster version (output of kubectl version):
```
 Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-tke.17", GitCommit:"7410252b56a5896ded1b9b3bbc8ae8bcfa009707", GitTreeState:"clean", BuildDate:"2022-04-19T03:04:37Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tao12345666333** [comment]
> 如何在ApisixRoute中申明ingress-class来隔离内网和公网网关；

Unfortunately, this feature is not implemented yet. Ref #593

**Comment by tao12345666333** [comment]
> 还有就是配置Ingress资源如何使用插件功能。

For ingress resources, you can add annotations to use plugins

**Comment by tao12345666333** [comment]
In addition, you can modify the namespace that APISIX Ingress can handle through configuration
