### ISSUE TITLE
bug: ApisixRouteHTTPBackend don't support service port name

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1092]
### Issue description

error: error validating "jenkins-apisixroute.yaml": error validating data: ValidationError(ApisixRoute.spec.http[0].backends[0].servicePort): invalid type for org.apache.apisix.v2beta2.ApisixRoute.spec.http.backends.servicePort: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):1.20.4
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): centos-7

### Minimal test code / Steps to reproduce

```
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: jenkins
  namespace: ns-test
spec:
  http:
  - name: rule1
    match:
      hosts:
      - jenkins.td-test2.aaa.com
      paths:
      - /*
    backends:
       - serviceName: jenkins
         servicePort: http
```
kubectl apply -f apisixRoute.yaml -n ns-test

it will return error: error validating "jenkins-apisixroute.yaml": error validating data: ValidationError(ApisixRoute.spec.http[0].backends[0].servicePort): invalid type for org.apache.apisix.v2beta2.ApisixRoute.spec.http.backends.servicePort: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false

but in the types.go

```
type ApisixRouteHTTPBackend struct {
	// The name (short) of the service, note cross namespace is forbidden,
	// so be sure the ApisixRoute and Service are in the same namespace.
	ServiceName string `json:"serviceName" yaml:"serviceName"`
### 	// The service port, could be the name or the port number.
	ServicePort intstr.IntOrString `json:"servicePort" yaml:"servicePort"`
	// The resolve granularity, can be "endpoints" or "service",
	// when set to "endpoints", the pod ips will be used; other
	// wise, the service ClusterIP or ExternalIP will be used,
	// default is endpoints.
	ResolveGranularity string `json:"resolveGranularity,omitempty" yaml:"resolveGranularity,omitempty"`
	// Weight of this backend.
	Weight *int `json:"weight" yaml:"weight"`
	// Subset specifies a subset for the target Service. The subset should be pre-defined
	// in ApisixUpstream about this service.
	Subset string `json:"subset,omitempty" yaml:"subset,omitempty"`
}
```

is now ApisixRouteHTTPBackend ServicePort don't support service ports name ?

### Actual result

xxx create

### Error log

 error validating data: ValidationError(ApisixRoute.spec.http[0].backends[0].servicePort): invalid type for org.apache.apisix.v2beta2.ApisixRoute.spec.http.backends.servicePort: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by tao12345666333** [comment]
The CRD is here

https://github.com/apache/apisix-ingress-controller/blob/3214c698f9dd2dc7797fce837e16d15d60f64050/samples/deploy/crd/v1/ApisixRoute.yaml#L184-L187


the deal logic 

https://github.com/apache/apisix-ingress-controller/blob/3214c698f9dd2dc7797fce837e16d15d60f64050/pkg/kube/apisix/apis/config/v2/types.go#L78-L94

 we can change the CRD schema to accept service port name. 

thanks.
