### ISSUE TITLE
Umbrella: flaky test

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#1097]
- [ ] `service is referenced by two ApisixRoutes` 
<details>

https://github.com/apache/apisix-ingress-controller/runs/7001002614?check_suite_focus=true

`/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/resourcepushing.go:28`
</details>

- [x] #1015

**Comment by lingsamuel** [comment]
[apache/apisix-ingress-controller/runs/7001002614?check_suite_focus=true](https://github.com/apache/apisix-ingress-controller/runs/7001002614?check_suite_focus=true)

This run does not output in the summary which test was failed.

**Comment by lingsamuel** [comment]
`github.com/apache/apisix-ingress-controller/pkg/kube/translation	600.032s`

This unit test failed several times.

**Comment by lingsamuel** [comment]
```
• [FAILED] [32.329 seconds]
suite-ingress: leader election
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/sanity.go:138
  suite-ingress: scaffold v2
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/sanity.go:196
[It] leader failover
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/sanity.go:152

```

**Comment by lingsamuel** [comment]
```

suite-endpoints: port usage
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-endpoints/endpoints.go:121
  suite-endpoints: scaffold v2beta3
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-endpoints/endpoints.go:162
[It] service port != target port
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-endpoints/endpoints.go:123
```

**Comment by AlinsRan** [comment]
I'm fixing endpoints and resourcesync.

**Comment by AlinsRan** [comment]
> `github.com/apache/apisix-ingress-controller/pkg/kube/translation 600.032s`
> 
> This unit test failed several times.

We should use chan with buffer.
