### ISSUE TITLE
request help: how can I migrate existing apisix(bare-metal) route config to apisix-ingress-controller

### ISSUE THREAD

**Issue by 0x9be00ff1** [apache/apisix-ingress-controller#1105]
### Issue description

We're using apisix in production, with lots of route and upstream configs already, planning migrate our services to k8s, is there any way I can generate CRDs file from etcd or admin api? 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): v1.4.1
- your Kubernetes cluster version (output of kubectl version): v1.23.7
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
This is a very interesting use case.  
Can you describe more, or join Slack for a live chat with me ()
https://join.slack.com/t/the-asf/shared_invite/zt-1bjo8bo8k-kp5nk0DaEf28oBoDL07nlQ
