### ISSUE TITLE
request help: How to upgrade

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#1106]
### Issue description

Before upgrade  env：
apisix  2.11.0    , 
apisix-ingress-controller:  1.4.0, I  install it like this:  helm install apisix-ingress-controller apisix/apisix-ingress-controller --version=0.9.0 --namespace apisix   ......

Tobe   upgrade  env：
I want to use the  apisix 2.13.1  or 2.13.2.
apisix-ingress-controller:   I  find the newest is 1.4.1  ,  I want to know is it match the apisix 2.13.x ? 

by the way , [Milestones]1.5    Will it be released on time?

thanks.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
> apisix-ingress-controller: I find the newest is 1.4.1 , I want to know is it match the apisix 2.13.x ?

yes. They can work together
