### ISSUE TITLE
Improve: Keep verify-mdlint same between Makefile and github actions

### ISSUE THREAD

**Issue by stillfox-lee** [apache/apisix-ingress-controller#1110]
https://github.com/apache/apisix-ingress-controller/blob/0e1f8d4afdf4d90743ef238872d1e383cdfa93a4/Makefile#L187
https://github.com/apache/apisix-ingress-controller/blob/0e1f8d4afdf4d90743ef238872d1e383cdfa93a4/.github/workflows/lint-checker.yml#L93

Maybe we should add `--ignore CHANGELOG.md ` into Makefile. Otherwise, we will see error after run `make verify-mdlint`.
```
❯ make verify-mdlint
docker run -it --rm -v /Users/Developer/apisix/apisix-ingress-controller:/work tmknom/markdownlint '**/*.md' --ignore node_modules
CHANGELOG.md:63:1 MD034/no-bare-urls Bare URL used [Context: "https://github.com/apache/apis..."]
CHANGELOG.md:78 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Changes"]
CHANGELOG.md:105 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "* [`b7dd90a`](https://github.c..."]
make: *** [verify-mdlint] Error 1
```

**Comment by tao12345666333** [comment]
@stillfox-lee thanks for your report.
Could you send a PR to fix this?

**Comment by tao12345666333** [comment]
#1126 has been merged. I will close this one.

thanks
