### ISSUE TITLE
request help: Processing logic for the same ApisixRoute when multiple APISIX Ingresses are deployed in the same Kubernetes cluster

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1125]
### Issue description

1. 我同一个k8s集群里，部署了两套apisix-ingress-controller和apisix 集群，一个apisix-ingress-controller对应一个apisix集群，
我两个ingress-controller都watch所有namespace，我使用crd apisixroute定义路由，后来发现当我apisixroute变动的时候，有时候会出现配置只被一个apisix-ingress-controller处理，是否因为apisixroute上会回写状态，如果一个ingress-controller处理了，resourceversion更改了另外一个就不处理了？
2. 如果我想同一个apisixroute 能同步两个集群，有什么最佳实践吗。主要是想内外网隔离，要保证两个集群都有全量路由
3. apisixroute 支持的插件ingress都可以通过annotation配置吗？
### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):centos-7.6

**Comment by AlinsRan** [comment]
For the first question, I think that Ingress-Controller cannot cross clusters. You need to configure `ApisixRoute` in each clusters.

**Comment by wolgod** [comment]
> For the first question, I think that Ingress-Controller cannot cross clusters. You need to configure `ApisixRoute` in each clusters.

I only have one cluster

**Comment by AlinsRan** [comment]
> 



> > For the first question, I think that Ingress-Controller cannot cross clusters. You need to configure `ApisixRoute` in each clusters.
> 
> I only have one cluster

Well, I regard question 1 2 as one.
For the first question, Under what circumstances will it fail? Is there a high probability.

**Comment by wolgod** [comment]
> > 
> 
> > > For the first question, I think that Ingress-Controller cannot cross clusters. You need to configure `ApisixRoute` in each clusters.
> > 
> > 
> > I only have one cluster
> 
> Well, I regard question 1 2 as one. For the first question, Under what circumstances will it fail? Is there a high probability. For the third question, not all plug-ins support it. You can take a look at this [link](https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations). We plan to achieve #799, to support more apisix plugins.

非常感谢您的回答，就是说我们支持一个集群里多个ingress-controller同时监控一个ApisixRoute，并且可以正确推送到ingress-controller对应的apisix集群里是吧，我再测试一下，提供详细的测试步骤

**Comment by AlinsRan** [comment]
> > > 
> > 
> > 
> > > > For the first question, I think that Ingress-Controller cannot cross clusters. You need to configure `ApisixRoute` in each clusters.
> > > 
> > > 
> > > I only have one cluster
> > 
> > 
> > Well, I regard question 1 2 as one. For the first question, Under what circumstances will it fail? Is there a high probability. For the third question, not all plug-ins support it. You can take a look at this [link](https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations). We plan to achieve #799, to support more apisix plugins.
> 
> 非常感谢您的回答，就是说我们支持一个集群里多个ingress-controller同时监控一个ApisixRoute，并且可以正确推送到ingress-controller对应的apisix集群里是吧，我再测试一下，提供详细的测试步骤

Yes, can do this, but the ingress-controller cannot guarantee the consistency of the two environments.

**Comment by tao12345666333** [comment]
> 我们支持一个集群里多个ingress-controller同时监控一个ApisixRoute，并且可以正确推送到ingress-controller对应的apisix集群里是吧，我再测试一下，提供详细的测试步骤

OK, looking forward to your feedback after the test. Thanks
