### ISSUE TITLE
request help: How to debug e2e-test fail case efficiently

### ISSUE THREAD

**Issue by stillfox-lee** [apache/apisix-ingress-controller#1138]
### Issue description

Hi, guys. Currently, e2t-test still has a randomly fail problem. I tried to set the breakpoint to debug, but the error is not reproduced. Is there an efficient way to solve this problem? What's best practice?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
You can add `focus` to only run a specific test case

**Comment by tao12345666333** [comment]
https://onsi.github.io/ginkgo/

**Comment by stillfox-lee** [comment]
> You can add `focus` to only run a specific test case

Yes, `focus` can do that. But ginkgo will teardown after every test case. I wanted to keep env which setup by test case. So that I can debug and find out the reason cause test case to fail.

**Comment by tao12345666333** [comment]
Just add a sleep? 😜

**Comment by tao12345666333** [comment]
>我在想对于随机错误这种问题，我们是否需要一种通用的解决方案？一种可以加入到e2e-test代码里的方案。比如说，在测试用例执行失败的时候，向k8s集群进行采样，获取足够多的信息来辅助我们定位问题。这样就不需要我们测试失败之后，加入sleep再次重跑，然后再看集群里面的实际情况来确定问题。

Currently we have the relevant processing logic.  But maybe we can make some optimizations.

For example, we can add an environment variable. If it is run locally by the developer, when a failure occurs, the relevant resources will be kept and not deleted.

https://github.com/apache/apisix-ingress-controller/blob/f0217ae5b022d6086bab2155dd3053567b3fc3aa/test/e2e/scaffold/scaffold.go#L440-L475


> 然后，关于随机错误。我猜想主要有两种原因：一是客观的集群环境问题导致，对于这种情况也许只能再次执行测试。二是我们的测试用例构造不完善，有一些边界情况会导致错误发生。对于第二种情况，我认为还是需要去解决的。

You are right!

If there is a job failure, we usually create an issue to track until the problem goes away.

**Comment by stillfox-lee** [comment]
> For example, we can add an environment variable. If it is run locally by the developer, when a failure occurs, the relevant resources will be kept and not deleted.

That's a good idea. Maybe I can create PR for this?
