### ISSUE TITLE
question: please help to confirm the document description

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-ingress-controller#1142]
### Issue description

Hi, I followed the document to install APISIX Ingress Controller on GKE. However, when I tried this tutorial[1], it showed that "It's not allowed to refer to other namespace's service," but I could access other namespace's service successfully.

![image](https://user-images.githubusercontent.com/2106987/177912466-5b2d11ef-5319-42d0-ab3c-1c1694fd8613.png)

[1] https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): None
- your Kubernetes cluster version (output of kubectl version): None
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): None

### Minimal test code / Steps to reproduce

1. Install APISIX Ingress Controller via Helm on GKE, according to https://apisix.apache.org/docs/ingress-controller/deployments/gke/. Note: this is in the `ingress-apisix` namespace.
2. Follow this tutorial[1] to run a httpbin pod and apply the `httpbin-route.yaml` in the `default` namespace.
3. Access LoadBalancer's External IP, succeed in accessing the `default` namespace's service.

![image](https://user-images.githubusercontent.com/2106987/177913668-502c8ed6-3775-4c17-84a4-62ac52aec635.png)

[1] https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service

### Actual result

See Steps to reproduce.

![image](https://user-images.githubusercontent.com/2106987/177913214-cd320449-de84-42cc-af0b-198fdf6a4187.png)

### Error log

None

### Expected result

![image](https://user-images.githubusercontent.com/2106987/177913113-1a236f3f-1cef-4fa9-b8ee-2496936690e7.png)

**Comment by AlinsRan** [comment]
It means that the `ApisixRoute` resource reference `k8s service` needs to be in the same namespace.

**Comment by juzhiyuan** [comment]
> It means that the `ApisixRoute` resource reference `k8s service` needs to be in the same namespace.

![image](https://user-images.githubusercontent.com/2106987/177913881-8785ef32-a598-4df4-8a94-45b959b1f26b.png)

**Comment by AlinsRan** [comment]
> > It means that the `ApisixRoute` resource reference `k8s service` needs to be in the same namespace.
> 
> ![image](https://user-images.githubusercontent.com/2106987/177913881-8785ef32-a598-4df4-8a94-45b959b1f26b.png)

This is correct because `service: httpbin` and `ApisixRoute: httpserver-route` are in the same namespace `default`.

**Comment by tao12345666333** [comment]
As @AlinsRan  said, there is no ambiguity here.  ApisixRoute and  service are namespace scoped.
