### ISSUE TITLE
test: debug info should not be output for e2e-test case that pass the run

### ISSUE THREAD

**Issue by AlinsRan** [apache/apisix-ingress-controller#1148]
## background:

At present, our e2e-test cases will print relevant debug info whether they pass or fail, resulting in a long debug log. This is not conducive to positioning problems, and which greatly affects our debugging efficiency.  
Therefore, we should not print debug info for the passed e2e-test cases, because in most cases, it is not helpful for us.

## expect:
![image](https://user-images.githubusercontent.com/79972061/178449157-b623764d-fec9-486b-ac24-c6ae2f48c42c.png)

## actual:
![image](https://user-images.githubusercontent.com/79972061/178451374-d373652b-085c-4c54-aa49-11a889b5541d.png)

**Comment by Erhao** [comment]
Assign this to me, please
