### ISSUE TITLE
request help: How to coordinate work between multiple ingress-controller pods.

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix-ingress-controller#1159]
### Issue description

When we tested, a cluster deployed 2 apisix and 2 ingress pods, found that 1 ingress did not work, and stopped 1 ingress pod, the other ingress pod still did not work, the relationship between these 2 ingress pods is The master-slave relationship still works at the same time.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1
- your Kubernetes cluster version (output of kubectl version): 1.21
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Hi

Your description confuses me. Please describe more clearly, including steps to reproduce.

In addition, we have not released v1.14 version, please describe it accurately.
