### ISSUE TITLE
bug: when service port change,the ingress can't handle correctly

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1165]
### Issue description

I wrote the service port wrong at the beginning, and the service port in apisixroute is also wrong, but when I change the service port and the port of apisixroute to the right, it does not take effect, and the correct Upstream cannot be synchronized to apisix, only when apisixroute is deleted. Resync the correct port to Upstream, but the ingress controller still prints an error message

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):centos7

### Minimal test code / Steps to reproduce

1.I wrote the service port wrong at the beginning, and the service port in apisixroute is also wrong
2.when I change the service port and the port of apisixroute to the right, it does not take effect, and the correct Upstream cannot be synchronized to apisix
3.when apisixroute is deleted. Resync the correct port to Upstream, but the ingress controller still prints an error message

### Actual result

when apisixroute is deleted. ingress controller  can Resync the correct port to Upstream, and the ingress controller  don’t print error message 

### Error log

error   translation/util.go:66  ApisixRoute refers to non-existent Service port {"namespace": "ns-2424", "port": "8123"}
2022-07-18T10:13:12+08:00       error   ingress/apisix_route.go:217     failed to translate old ApisixRoute     {"version": "apisix.apache.org/v2beta3", "event": "update", "error": "service.spec.ports: port not defined", "ApisixRoute": {}}
2022-07-18T10:13:12+08:00       warn    ingress/apisix_route.go:305     sync ApisixRoute failed, will retry     {"object": {"Type":2,"Object":{"Key":"ns-2424/log-monitor-aggregate-test","OldObject":{},"GroupVersion":"apisix.apache.org/v2beta3"},"Tombstone":null}, "error": "service.spec.ports: port not defined"}

**Comment by tao12345666333** [comment]
Can you provide the corresponding YAML configuration directly in the reproduction step?

**Comment by wolgod** [comment]
1.kubectl run httpbin --image kennethreitz/httpbin --port 80
2.
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: ClusterIP
  clusterIP: None   # clusterIP = None
  selector:
    run: httpbin
  ports:
  - port: 80
    targetPort: 80
3.
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80


4. change the svc port 8080 and apisix-route 8080

**Comment by wolgod** [comment]
In the code, I see the logic is that when the apisixroute update event, it will check the old apisixroute. At this time, the port of my svc has changed, so the check will fail, and then it will always fail

```
oldCtx, err = c.controller.translator.TranslateRouteV2beta3(obj.OldObject.V2beta3())

```

**Comment by tao12345666333** [comment]
thanks

**Comment by AlinsRan** [comment]
I recurrent it. There is indeed this problem.
