### ISSUE TITLE
request help: how to get client real-ip

### ISSUE THREAD

**Issue by hotbaby** [apache/apisix-ingress-controller#1166]
### Issue description

要增加IP白名单限制，发现APISIX获取远程客户端的地址为本地网络设备CNI0的地址。

**Comment by tao12345666333** [comment]
This is actually a Kubernetes knowledge.
You can set `externalTrafficPolicy` for apisix-gateway service.

**Comment by hotbaby** [comment]
> This is actually a Kubernetes knowledge. You can set `externalTrafficPolicy` for apisix-gateway service.

谢谢大佬，修改externalTrafficPolicy为Local，解决了。
