### ISSUE TITLE
request help: use ingress annotation to support traffic split feature

### ISSUE THREAD

**Issue by cai200631** [apache/apisix-ingress-controller#1167]
### Issue description

I am trying to replace nginx-ingress by apisix-ingress, the traffic-split feature(like gray) in nginx-ingress is supported by ingress annotation like nginx.ingress.kubernetes.io/canary-by-header,  is there any chance that apisix-ingress can support or supply some annotation to support traffic-split ?  I prefer to use ingress than ApisixRoute,  ingress is in common use after all

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Yes! We can use the PluginConfig annotation on the Ingress resource to bind any APISIX plugin to the Ingress resource.

you can refer to https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/annotations.md#use-apisixpluginconfig

This feature will be introduced in this month's v1.5 release. Implemented in #1139

**Comment by cai200631** [comment]
> Yes! We can use the PluginConfig annotation on the Ingress resource to bind any APISIX plugin to the Ingress resource.
> 
> you can refer to https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/annotations.md#use-apisixpluginconfig
> 
> This feature will be introduced in this month's v1.5 release. Implemented in #1139

I am confused,  is apisixpluginconfig can bind traffic-split now?  or I can bind traffic-split plugin to apisixpluginconfig when V1.5 is released ? 


I have tried as follows:

1. declare  an ApisixPluginConfig: 

apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: traffic-split
  namespace: test-beijing
spec:
  plugins:
  - name: traffic-split
    enable: true
    config:
     rules:
      - match:
        - vars:
            - front-traffic-env
            - ==
            - test-beijing

2. declare an Ingress: 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: um-qingzhou-fe-70otk2cqeal71rq10wdyb1463
  namespace: test-beijing
  annotations:
    k8s.apisix.apache.org/plugin-conifg-name: "traffic-split"
  labels:
    deployment: um-qingzhou-fe
    env: test-beijing
    host: test.demo.com
spec:
  ingressClassName: apisix
  rules:
    - host: qingzhou.baijia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-arch-fe-general-test-service
                port:
                  number: 80



but when I curl add an header  'front-traffic-env:test-beijing' http:// test.demo.com/index.html,  it is not working;

**Comment by tao12345666333** [comment]
You need to use latest code from master branch or wait for v1.5 released

**Comment by cai200631** [comment]
> You need to use latest code from master branch or wait for v1.5 released

I finally figure out the trick,  you guys are too naughty. Why the documentation's version is NEXT,  and I cannot choose the current version....

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/9104913/179876150-0304e1dd-a67a-4090-84ea-b9e7c6ab092e.png">

**Comment by tao12345666333** [comment]
@juzhiyuan Can you help point out how to add versioned documentation? I didn't notice it

**Comment by juzhiyuan** [comment]
Hi @tao12345666333, please check https://github.com/apache/apisix-website/issues/201 and https://apisix.apache.org/docs/general/documentation-style-guide/#formatting-punctuation-and-organization.

For this repo, the only change we should take is **renaming the released branch from `vxxxx` to `release/xxxx`**, see https://github.com/apache/apisix

Just to make sure: will this change break some CI/3rd systems?

cc @SkyeYoung

**Comment by cai200631** [comment]
By the way, is there any exact date that v1.5 will be released ? 

> @juzhiyuan Can you help point out how to add versioned documentation? I didn't notice it

**Comment by tao12345666333** [comment]
end of the month

**Comment by SkyeYoung** [comment]
> For this repo, the only change we should take is **renaming the released branch from `vxxxx` to `release/xxxx`**, see [apache/apisix](https://github.com/apache/apisix)

@tao12345666333 Will we change the name of the release branch to keep it consistent with projects like apisix? Or do I have to do some extra processing in apisix-website?

**Comment by tao12345666333** [comment]
@SkyeYoung It is best if it can be adapted through the apisix-website project.  
Since we may have used that branch name in some mail or stuff in the history, I'm not sure what would break.
Thanks!

**Comment by SkyeYoung** [comment]
> @SkyeYoung It is best if it can be adapted through the apisix-website project. Since we may have used that branch name in some mail or stuff in the history, I'm not sure what would break. Thanks!

Okay, I will submit a PR in the apisix-website repository tomorrow and CC it to you.
