### ISSUE TITLE
request help:  How many settings resync_interval are appropriate？

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1171]
### Issue description

resync_interval default is 6h，There are about 3000 apisixroutes in my environment. If the default value of 6h is used, if some events are lost, the routing may be inaccurate, but if the setting is too small, the resync will be too frequent. Is there a more suitable experience value?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):centos7

**Comment by tao12345666333** [comment]
In fact, this is not a recommended value. I recommend you to do some testing in your environment
