### ISSUE TITLE
feat: Combine ApisixRoute, ApisixService, ApisixUpstream into one resource object

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#120]
During the development process, we maintained some additional complexity, because of splitting the CRD (custom resource object) to  `ApisixRoute` `ApisixService` and `ApisixUpstream`.
Controller need to handle broken links between resources and/or mismatched configuration.

I proposal combine `ApisixRoute`, `ApisixService`, `ApisixUpstream` into one resource object `ApisixRoute`. 

Benefits:
Using a single resource object to define routing rules will effectively reduce the maintenance cost of internal relationships. 

Downsides:
There will be more configuration items and the internal structure of `ApisixRoute` will become bloated.

There are two solutions for the processing of `ApisixRoute` and `ApisixService`:
1. Keep them
Continue to keep `ApisixService` and `ApisixUpstream` as supplementary configuration to `ApisixRoute`, but the routing configuration will not fail due to the failure of `ApisixService` and `ApisixUpstream`.

2. Ignore it, configuration no longer takes effect.

**Comment by tokers** [comment]
What about changing a name, people may confuse with the two versions of ApisixRoute.

**Comment by tokers** [comment]
> What about changing a name, people may confuse with the two versions of ApisixRoute.

What about APISIXTrafficPolicy or APISIXPolicy?

**Comment by gxthrj** [comment]
We can discuss about changing name.
* If we use a new name , such as `APISIXTrafficPolicy`, what is the relation between `APISIXTrafficPolicy` and others.
* If we use `ApisixRoute`, need to keep compatible.

**Comment by tao12345666333** [comment]
We have removed the ApisixService resource.

Using ApisixRoute and ApisixUpstream is closer to the concept of APISIX itself, and the learning cost for users is lower.
I recommend keeping the current ApisixRoute and ApisixUpstream

**Comment by gxthrj** [comment]
OK, let's close this stale discussion.
