### ISSUE TITLE
request help: make e2etest local error

### ISSUE THREAD

**Issue by xiangtianyu** [apache/apisix-ingress-controller#1205]
### Issue description

When i run make e2e-test-local, there are such errors output

```
<< End Captured StdOut/StdErr Output


  	Error Trace:	/Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/scaffold.go:391
  	            				/Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/suite.go:596
  	            				/Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/asm_arm64.s:1263
  	Error:      	Expected nil, but got: &errors.errorString{s:"timed out waiting for the condition"}
  	Test:       	suite-features: route match exprs suite-features: scaffold v2 operator is regex match in case insensitive mode
  	Messages:   	waiting for etcd ready

  In [BeforeEach] at: /Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/scaffold/scaffold.go:391

  Full Stack Trace
    github.com/apache/apisix-ingress-controller/test/e2e/scaffold.(*Scaffold).beforeEach(0x140001769c0)
    	/Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/scaffold/scaffold.go:391 +0x408
------------------------------
• [FAILED] [67.244 seconds]
suite-annotations: authorization annotations
/Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/suite-annotations/authorization.go:28
  suite-annotations: scaffold v2beta3 [BeforeEach]
  /Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/scaffold/scaffold.go:153
    enable keyAuth in ingress networking/v1
    /Users/xiangtianyu/workspace/code/github/contribute/apisix-ingress-controller/test/e2e/suite-annotations/authorization.go:32

  Begin Captured StdOut/StdErr Output >>
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
I used docker desktop and minikube to build container env

kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1

**Comment by AlinsRan** [comment]
Generally, it is a network problem. Does your docker registry have an etcd image? 
![image](https://user-images.githubusercontent.com/79972061/182508379-2d4d40e5-ce57-4598-b4b1-789218dc6a56.png)

**Comment by xiangtianyu** [comment]
![image](https://user-images.githubusercontent.com/10825900/182509087-475d184b-f452-43ca-be3f-d9508f5b60ba.png)
you mean this?

**Comment by AlinsRan** [comment]
> ![image](https://user-images.githubusercontent.com/10825900/182509087-475d184b-f452-43ca-be3f-d9508f5b60ba.png) you mean this?

Yeah. If not, you can load your image into the node. `make kind-load-images`

**Comment by AlinsRan** [comment]
You can check the etcd pod log first.

**Comment by xiangtianyu** [comment]
make failure

```
➜  apisix-ingress-controller git:(feature/log_rotate) ✗ make kind-load-images
kind load docker-image --name=apisix \
			127.0.0.1:5000/apache/apisix:dev \
            127.0.0.1:5000/bitnami/etcd:dev \
            127.0.0.1:5000/apache/apisix-ingress-controller:dev \
            127.0.0.1:5000/kennethreitz/httpbin:dev \
            127.0.0.1:5000/test-backend:dev \
            127.0.0.1:5000/jmalloc/echo-server:dev \
            127.0.0.1:5000/busybox:dev
Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-worker2", loading...
Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-control-plane", loading...
Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-worker", loading...
Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-worker2", loading...
ERROR: failed to load image: command "docker exec --privileged -i apisix-worker2 ctr --namespace=k8s.io images import --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: unpacking 127.0.0.1:5000/apache/apisix-ingress-controller:dev (sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580)...done
unpacking import-2022-08-03@sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580 (sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580)...done
unpacking 127.0.0.1:5000/kennethreitz/httpbin:dev (sha256:b75383b2157ff661d3a3ec151c12fe7f35aac423d9adb7200f5cbb77184e3ff0)...time="2022-08-03T02:25:09Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: failed to get reader from content store: content digest sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: not found" key="extract-727652504-Uyfz sha256:1aac3bd167decb7e1a7151df7e6cbc94ab81cd36239eba33b5278be32454ab01"
ctr: failed to extract layer sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: failed to get reader from content store: content digest sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: not found
make: *** [kind-load-images] Error 1
```

**Comment by xiangtianyu** [comment]
And there is no etcd pod,how can i check the log?

**Comment by AlinsRan** [comment]
> And there is no etcd pod,how can i check the log?

When running e2e.

**Comment by AlinsRan** [comment]
> make failure
> 
> ```
> ➜  apisix-ingress-controller git:(feature/log_rotate) ✗ make kind-load-images
> kind load docker-image --name=apisix \
> 			127.0.0.1:5000/apache/apisix:dev \
>             127.0.0.1:5000/bitnami/etcd:dev \
>             127.0.0.1:5000/apache/apisix-ingress-controller:dev \
>             127.0.0.1:5000/kennethreitz/httpbin:dev \
>             127.0.0.1:5000/test-backend:dev \
>             127.0.0.1:5000/jmalloc/echo-server:dev \
>             127.0.0.1:5000/busybox:dev
> Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/apache/apisix:dev" with ID "sha256:b29a7332b953f0e2a287db9a09ad174f00586b371335baa9c78d90f284bd5f2d" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/bitnami/etcd:dev" with ID "sha256:18e23f04cdf7dabb22da88364717756cb8d13770de73e109a578d859c5d7c688" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/apache/apisix-ingress-controller:dev" with ID "sha256:94428b4efc7e1fa4e451f08c2bca9a4eefbad370676bcd1099d62b0a195a3a84" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/kennethreitz/httpbin:dev" with ID "sha256:b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/test-backend:dev" with ID "sha256:148d6023435401f79a032c3730e6c4c5967cab16e5f84eeb1254d7e3b335b955" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/jmalloc/echo-server:dev" with ID "sha256:ce2d2cda2d858fdaea84129deb86d18e5dbf1c548f230b79fdca74cc91729d17" not yet present on node "apisix-worker2", loading...
> Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-control-plane", loading...
> Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-worker", loading...
> Image: "127.0.0.1:5000/busybox:dev" with ID "sha256:89a35e2ebb6b938201966889b5e8c85b931db6432c5643966116cd1c28bf45cd" not yet present on node "apisix-worker2", loading...
> ERROR: failed to load image: command "docker exec --privileged -i apisix-worker2 ctr --namespace=k8s.io images import --digests --snapshotter=overlayfs -" failed with error: exit status 1
> Command Output: unpacking 127.0.0.1:5000/apache/apisix-ingress-controller:dev (sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580)...done
> unpacking import-2022-08-03@sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580 (sha256:abe2cfde3e0901e8cd071ebb36baba5058f672a8b4358134b44e354e76153580)...done
> unpacking 127.0.0.1:5000/kennethreitz/httpbin:dev (sha256:b75383b2157ff661d3a3ec151c12fe7f35aac423d9adb7200f5cbb77184e3ff0)...time="2022-08-03T02:25:09Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: failed to get reader from content store: content digest sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: not found" key="extract-727652504-Uyfz sha256:1aac3bd167decb7e1a7151df7e6cbc94ab81cd36239eba33b5278be32454ab01"
> ctr: failed to extract layer sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: failed to get reader from content store: content digest sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: not found
> make: *** [kind-load-images] Error 1
> ```

Your computer will parse localhost into 127.0.0.1.

**Comment by AlinsRan** [comment]
> ![image](https://user-images.githubusercontent.com/10825900/182509087-475d184b-f452-43ca-be3f-d9508f5b60ba.png) you mean this?

![image](https://user-images.githubusercontent.com/79972061/182512010-d82bc00b-8978-49db-b836-10f96793003b.png)
Your computer will parse localhost into 127.0.0.1

**Comment by xiangtianyu** [comment]
My host is always bind  localhost to 127.0.0.1 in /etc/hosts

**Comment by AlinsRan** [comment]
Maybe we should not use localhost:5000 to represent the local warehouse image.

**Comment by xiangtianyu** [comment]
my etcd pod exports such error 

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  62s                default-scheduler  Successfully assigned ingress-apisix-e2e-tests-default-27891000/etcd-deployment-e2e-test-78f8c847b-p5lmn to apisix-worker2
  Normal   Pulling    24s (x3 over 62s)  kubelet            Pulling image "127.0.0.1:5000/bitnami/etcd:dev"
  Warning  Failed     24s (x3 over 62s)  kubelet            Failed to pull image "127.0.0.1:5000/bitnami/etcd:dev": rpc error: code = Unknown desc = failed to pull and unpack image "127.0.0.1:5000/bitnami/etcd:dev": failed to resolve reference "127.0.0.1:5000/bitnami/etcd:dev": failed to do request: Head "http://127.0.0.1:5000/v2/bitnami/etcd/manifests/dev": dial tcp 127.0.0.1:5000: connect: connection refused
  Warning  Failed     24s (x3 over 62s)  kubelet            Error: ErrImagePull
  Normal   BackOff    0s (x4 over 61s)   kubelet            Back-off pulling image "127.0.0.1:5000/bitnami/etcd:dev"
  Warning  Failed     0s (x4 over 61s)   kubelet            Error: ImagePullBackOff
```

it seems a network error?

**Comment by xiangtianyu** [comment]
It's a problem of something difference between "localhost" and "127.0.0.1" ?

**Comment by AlinsRan** [comment]
> It's a problem of something difference between "localhost" and "127.0.0.1" ?

Yeah.

**Comment by AlinsRan** [comment]
![image](https://user-images.githubusercontent.com/79972061/182513933-ac70c39a-93a3-4fe2-a8e1-4bc0375169cd.png)

**Comment by xiangtianyu** [comment]
I've tried 127.0.0.1 and localhost, they output different errors

**Comment by AlinsRan** [comment]
`kind-with-registry.sh` Maybe the localhost in this file has been replaced with 127.0.0.1. You need to have a look,

**Comment by xiangtianyu** [comment]
When i used localhost it will output

```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker tag test-backend:dev "localhost:5000"/test-backend:dev
docker tag apache/apisix-ingress-controller:dev "localhost:5000"/apache/apisix-ingress-controller:dev
docker pull jmalloc/echo-server:latest
latest: Pulling from jmalloc/echo-server
Digest: sha256:e43a10c9ecbd025df7ed6dac1e45551ce7bd676142600b0734fe7dcd10a47abe
Status: Image is up to date for jmalloc/echo-server:latest
docker.io/jmalloc/echo-server:latest
docker tag  jmalloc/echo-server:latest "localhost:5000"/jmalloc/echo-server:dev
docker pull busybox:1.28
1.28: Pulling from library/busybox
Digest: sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
Status: Image is up to date for busybox:1.28
docker.io/library/busybox:1.28
docker tag  busybox:1.28 "localhost:5000"/busybox:dev
docker push "localhost:5000"/apache/apisix:dev
The push refers to repository [localhost:5000/apache/apisix]
Get "http://localhost:5000/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
make: *** [push-images] Error 1
```

**Comment by xiangtianyu** [comment]
Thanks a lot! I changed all "locahost" to "127.0.0.1" in makefile and kind-with-registry.sh and the error disappears!
But its still confused to me what's the difference between them

**Comment by tao12345666333** [comment]
```

ctr: failed to extract layer sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: failed to get reader from content store: content digest sha256:e29f63869784e4e80a8d33f0589cc9da27f21f2f51c0058cd4ce6cd6879ed405: not found
make: *** [kind-load-images] Error 1

```

If you got this error, you can try it again.

**Comment by tao12345666333** [comment]
> Thanks a lot! I changed all "locahost" to "127.0.0.1" in makefile and kind-with-registry.sh and the error disappears!
> 
> But its still confused to me what's the difference between them

If you use `localhost`, DNS resolution will be performed here

**Comment by xiangtianyu** [comment]
> > Thanks a lot! I changed all "locahost" to "127.0.0.1" in makefile and kind-with-registry.sh and the error disappears!
> > But its still confused to me what's the difference between them
> 
> If you use `localhost`, DNS resolution will be performed here

But IMO when i bind localhost to 127.0.0.1, dns will transform localhost to 127.0.0.1. It seems the same

**Comment by tao12345666333** [comment]
sorry for delay. 

Actually it depends on your specific environment, maybe there are configuration differences, maybe there are proxies and so on.

The most intuitive way is to grab the packet for inspection. e.g. `tcpdump`
