### ISSUE TITLE
request help: How to setup on `kind`

### ISSUE THREAD

**Issue by caniko** [apache/apisix-ingress-controller#1209]
### Issue description

I am huge fan of Apache, and want to use their projects whenever possible. However, I also use `kind`, and I noticed there is no guide for [`kind`](https://kind.sigs.k8s.io/docs/user/ingress/).

Hope we can change that! Mentioning @BenTheElder

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
latest
- your Kubernetes cluster version (output of kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
```
Linux Stellate 5.18.15-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:41 +0000 x86_64 GNU/Linux
```

**Comment by BenTheElder** [comment]
I'm sorry I don't have time to figure this out, [my focus is moreso on ~kubernetes now](https://twitter.com/BenTheElder/status/1551670320423059456) but `@tao12345666333` is active in both projects and may be able to help, when they have time.

**Comment by tao12345666333** [comment]
Thanks! In this project, we have added the deployment guide about how to install APISIX Ingress controller on KIND. 

ref: https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/kind.md

**Comment by BenTheElder** [comment]
AHA, perhaps it should be added https://github.com/apache/apisix-ingress-controller/blob/master/install.md#installation

thanks @tao12345666333 🙏

**Comment by tao12345666333** [comment]
Thanks! let me add it.

**Comment by tao12345666333** [comment]
Opened PR to fix it. https://github.com/apache/apisix-ingress-controller/pull/1220
