### ISSUE TITLE
[DISCUSS] e2e test cases

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#121]
We have the following groups of e2e cases.

* Annotations

Test wether the Annotations in ApisixRoute are normal.

* Proxy

Test the proxy result to upstream.

* Plugins

Test each plugin, just like APISIX.

* TLS/SSL

Test TLS/SSL certificates.

* ingress

Test the behavior of ingress controller, like bad CRDs.

**Comment by tao12345666333** [comment]
Our current e2e test case has been basically covered, and I will close this issue. Feel free to reopen it, if you have any question.
