### ISSUE TITLE
request help: add ingress but always status Initializing

### ISSUE THREAD

**Issue by kozora** [apache/apisix-ingress-controller#1210]
### Issue description

set annotation:   `kubernetes.io/ingress.class: apisix`

in apisix dashboard I can see the auto-create route and upstream, but visiting the ingress domain can not success

### Environment

- apache/apisix-ingress-controller:1.4.1
- installed by apisix helm  v0.11.0

**Comment by tao12345666333** [comment]
you need to provide more information
