### ISSUE TITLE
request help: upstreamNode json解析异常

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#1218]
## 问题1：
1. admin api根据id获取upstream json数据如下：
![image](https://user-images.githubusercontent.com/7006014/182865884-04b00294-743f-4cf7-a00b-a70ba132f5c2.png)

2. apisix-ingress-controller定义的数据结构如下：
![image](https://user-images.githubusercontent.com/7006014/182844021-7ca224b3-87df-4624-a3a4-e36202d8d221.png)

3. 注释红框中的判断，否则解析报错
![image](https://user-images.githubusercontent.com/7006014/182866463-7d81a63b-8cb7-4efe-8a47-1cef40fa94fb.png)

3.1 不注释代码的情况下，报错：
```
2022-08-04 22:04:55.984	error	unexpected non-empty object
```

3.2 注释代码的情况下，upstreamNode解析为空：
```
&{Metadata:{ID:419230261889204925 Name:test Desc: Labels:map[]} Type:roundrobin HashOn: Key: Checks:<nil> Nodes:[] Scheme:http Retries:<nil> Timeout:0xc0000d80d8 TLS:<nil>}
```

4. 下面的json数据结构不注释代码的情况下也可以正常解析
![image](https://user-images.githubusercontent.com/7006014/182865682-4389ad9f-990c-4c3a-a43f-1cb465303888.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.5.0
- your Kubernetes cluster version (output of kubectl version): 1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): centos7.4

**Comment by AlinsRan** [comment]
Thank you very much. I am trying to reproduce this problem. This is indeed the case.

**Comment by AlinsRan** [comment]
Can you tell me the version of your apisix-dashboard？

**Comment by tao12345666333** [comment]
xref: #712

**Comment by marchlhw** [comment]
> Can you tell me the version of your apisix-dashboard？

apisix-dashboard 我用的最新的master分支，我看manager-api的源码有做数据结构转换
https://github.com/apache/apisix-dashboard/blob/master/api/internal/core/entity/format.go

**Comment by tao12345666333** [comment]
@bzp2010 Could you help confirm this if you have time?

**Comment by marchlhw** [comment]
apisix-ingress-controller调用的是admin-api，会有上面提到的数据解析问题；manager-api虽然有对upstreamNodes做数据结构转换，响应的json数据controller可以正常的解析，但是controller只支持api-key的验证，而manager-api是jwt的验证

**Comment by AlinsRan** [comment]
I'll fix it.
