### ISSUE TITLE
request help: K8s ingress extensions/v1beta1  GET /apisix/admin/upstreams/f968e567 HTTP/1.1" 404

### ISSUE THREAD

**Issue by dierbei** [apache/apisix-ingress-controller#1224]
### Issue description

apisix-admin.ingress-apisix.svc.cluster.local:9180 "GET /apisix/admin/upstreams/9e7bb51a HTTP/1.1" 404 39 0.002 "-" "Go-http-client/1.1" - - - "http://apisix-admin.ingress-apisix.svc.cluster.local:9180"
![Uploading image.png…]()

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by dierbei** [comment]
![image](https://user-images.githubusercontent.com/52097565/183034327-2412aab5-7109-47df-8853-e54eb337d9ff.png)

**Comment by tao12345666333** [comment]
Please provide more information and minimal steps to reproduce

**Comment by ahululu** [comment]
Has this issue been resolved? I also encountered this problem. 
Reproduction:
 `kubectl rollout restart deployment.apps/apisix-ingress-controller`
