### ISSUE TITLE
request help: Deployment failed   1.5

### ISSUE THREAD

**Issue by xxdyu** [apache/apisix-ingress-controller#1227]
### Issue description

![image](https://user-images.githubusercontent.com/32918557/183335659-fa4718f1-0ae6-45bc-94f2-65b18a76c46d.png)

### Environment

- your apisix-ingress-controller version 1.5
- your Kubernetes cluster version 1.24
- if you run apisix-ingress-controller  centos7

**Comment by tao12345666333** [comment]
we only support install by Helm chart. 

And v1.5 version helm chart hasn't been published 

Thanks

**Comment by xxdyu** [comment]
thanks
