### ISSUE TITLE
request help: Can grpc configured without SSL certificates in apisix ingress

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#1230]
### Issue description

![image](https://user-images.githubusercontent.com/32457473/183358253-cdb1a525-96fa-48f1-9e67-38b67905d6b8.png)

I see the grpc can use without ssl, as the doc show in the  apisix  . 

But  as the  apisix-ingress  way,  can I config  grpc  without ssl ?   ( the doc : proxy-grpc-service.md )

I have try it like this 
![image](https://user-images.githubusercontent.com/32457473/183359371-70d93c45-ab93-4a30-9c1a-843f2b65c095.png)

and  test  it： 
grpcurl  -servername grpc-proxy 172.16.11.61:30981 yages.Echo.Ping
Failed to dial target host "172.16.11.61:30981": tls: first record does not look like a TLS handshake

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4
- your Kubernetes cluster version (output of kubectl version): 1.21
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): in k8s

**Comment by xianshun163** [comment]
I config the upstream like this :
kubectl apply -f - <<EOF
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: yages
  namespace: ingress-apisix
spec:
  scheme: grpc
EOF
```

but,  in the dashboard  upstream， it  look like this , it is  scheme is http:

![image](https://user-images.githubusercontent.com/32457473/183383656-4d726946-5bc6-46d1-bf9d-f40bca1a8e54.png)

**Comment by wolgod** [comment]
apiVersion: apisix.apache.org/v1  maybe apiVersion: apisix.apache.org/v2beta3, try it

**Comment by wolgod** [comment]
> ### Issue description
> ![image](https://user-images.githubusercontent.com/32457473/183358253-cdb1a525-96fa-48f1-9e67-38b67905d6b8.png)
> 
> I see the grpc can use without ssl, as the doc show in the apisix .
> 
> But as the apisix-ingress way, can I config grpc without ssl ? ( the doc : proxy-grpc-service.md )
> 
> I have try it like this ![image](https://user-images.githubusercontent.com/32457473/183359371-70d93c45-ab93-4a30-9c1a-843f2b65c095.png)
> 
> and test it： grpcurl -servername grpc-proxy 172.16.11.61:30981 yages.Echo.Ping Failed to dial target host "172.16.11.61:30981": tls: first record does not look like a TLS handshake
> 
> ### Environment
> * your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4
> * your Kubernetes cluster version (output of kubectl version): 1.21
> * if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): in k8s

If you proxy the port 80 used by http, you must set a separate http port to proxy http2, so as to support clear text transmission, not ssl

**Comment by wolgod** [comment]
> namespace: ingress-apisix

namespace: ingress-apisix    ,Are you sure your application is under this namespace？

**Comment by xianshun163** [comment]
I use  another grpc server to  make a test and  it is ok  , thanks. 
/helloworld.Greeter/SayHello




here is my crd file,   defile the  ApisixUpstream  after the ApisixRoute,  or  it will make some mistake.


#apiVersion: apisix.apache.org/v2beta3
#kind: ApisixUpstream
#metadata:
#  name: xsgrpc-service
#spec:
#  scheme: grpc


apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: xsgrpc-proxy-route
spec:
  http:
    - name: xsgrpc-route
      match:
        paths:
          - "/helloworld.Greeter/SayHello"
      backends:
      - serviceName: xsgrpc-service
        servicePort: 50051
        weight: 10


apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: xsgrpc-service
spec:
  scheme: grpc

**Comment by xianshun163** [comment]
@tao12345666333 @wolgod 
I  find  sometimes, the ApisixUpstream  can  not set the scheme  to  grpc.  This situation will be found once after about ten operations.
This is the case. I put all CRDs in one file, as shown below, and then directly kubectl apply -f grpc2-route yaml。

I found that
1、create a  apisixroute
2、an upstream will be automatically generated when create  apisixroute  crd, and the scheme is http.
3、create the apisixupstream  crd , the scheme will be changed to grpc.
I thought, the time interval is very short, The order of the step 2 and 3  may be uncertain. 


```
[root@master app]# cat grpc2-route.yaml
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: xsgrpc-proxy-route
spec:
  http:
    - name: xsgrpc-route
      match:
        paths:
          - "/helloworld.Greeter/SayHello"
      backends:
      - serviceName: xsgrpc-service
        servicePort: 50051
        weight: 10
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: xsgrpc-service
spec:
  scheme: grpc
