### ISSUE TITLE
http[].match.exprs cannot matched one of the rules

### ISSUE THREAD

**Issue by cai200631** [apache/apisix-ingress-controller#1231]
Accordding to the documentation,  if I config multi http[].match.exprs,   results should be matched (oneof) to use this route rule.  but according to my test,  all rule should be matched , then the route effective;

my apisixroute spec is as follows: 

spec:
  http:
    - backends:
        - serviceName: svc-arch-fe-general-test-service
          servicePort: 80
      match:
        exprs:
          - op: Equal
            subject:
              name: qingzhou_gray_test
              scope: Cookie
            value: test-hangzhou
          - op: Equal
            subject:
              name: front-traffic-env
              scope: Header
            value: test-hangzhou
        hosts:
          - test-demo.baijia.com
        paths:
          - /*
      name: e153996aa8ea9af43841

test case as follows:
only add header and cookie, I can traffic to test-hangzhou;

![image](https://user-images.githubusercontent.com/9104913/183369878-a03cc4c8-85dd-4371-a2a0-00eed31196c8.png)

**Comment by tao12345666333** [comment]
Could you please format the ApisixRoute resource?

And provide a minimal complete reproduction steps, thanks!

**Comment by cai200631** [comment]
spec:
  http:
    - backends:
        - serviceName: svc-arch-fe-general-test-service
          servicePort: 80
      match:
        exprs:
          - op: Equal
            subject:
              name: qingzhou_gray_test
              scope: Cookie
            value: test-hangzhou
          - op: Equal
            subject:
              name: front-traffic-env
              scope: Header
            value: test-hangzhou
        hosts:
          - test-demo.baijia.com
        paths:
          - /*

**Comment by cai200631** [comment]
[apiSixRoute.md](https://github.com/apache/apisix-ingress-controller/files/9287669/apiSixRoute.md)
