### ISSUE TITLE
request help: apisix-ingress-controller控制台日志出现大量service not found

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#1234]
### Issue description

1. apisix-ingress-controller控制台日志有大量service not found

```
2022-08-09T15:24:19+08:00	info	ingress/controller.go:606	service kube-system/kube-scheduler not found
```

2. helm包value.yaml文件仅配置如下命名空间
![image](https://user-images.githubusercontent.com/7006014/183590010-ca8696d7-9a7c-4c59-b741-fb5b73a22711.png)

3. 通过分析源码有过滤命名空间的逻辑
![image](https://user-images.githubusercontent.com/7006014/183589479-2cc961cb-dd06-4900-a511-2e457d0bb74f.png)
![image](https://user-images.githubusercontent.com/7006014/183589117-244af1ce-efe7-4f36-9c0c-10438a3d1498.png)

问题：为什么会watch 其他的命名空间的资源，不解？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1
- your Kubernetes cluster version (output of kubectl version): 1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): centos 7.4

**Comment by tao12345666333** [comment]
Did you change your code to v1.4.1 tag?

**Comment by marchlhw** [comment]
> Did you change your code to v1.4.1 tag?

确定切换到1.4.1 tag了

**Comment by marchlhw** [comment]
![image](https://user-images.githubusercontent.com/7006014/183595026-4764e5b5-075d-48db-8d05-65582982306a.png)
k8s集群中service对象是不存在的，只存在endpoint对象

**Comment by marchlhw** [comment]
通过验证：
1. 使用appNamespaces配置，会出现以上问题
2. 使用namespaceSelector配置，目前正常

**Comment by tao12345666333** [comment]
Thanks for your report.

Please see #931 we plane remove the appNamespace configuration in v1.6 and it has been deprecated.

I'll take care to declare it when v1.5.0 is officially released

**Comment by marchlhw** [comment]
发现新的问题：原先通过namespaceSelector关联3个命名空间，一切都很正常，但是去掉其中一个命名空间的watching标签后，apisix-ingress-controller仍然会watching这个去掉标签的命名空间

**Comment by tao12345666333** [comment]
it has been fixed in https://github.com/apache/apisix-ingress-controller/pull/1130
