### ISSUE TITLE
request help: After removing apisix-ingress-controller it will not start

### ISSUE THREAD

**Issue by hyt05** [apache/apisix-ingress-controller#1242]
### Issue description

I deleted a route created by apisix-ingress-controller on the dashbord dashboard, executed ```kubectl delete pod apisix-ingress-controller``` and it doesn't start anymore

### Environment

- your apisix-ingress-controller version (1.4.1):
- your Kubernetes cluster version (v1.24.2+rke2r1):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version ( 5.15.0-43-generic Ubuntu):
- apisix version (2.13.1-alpine)
- apisix dashbord version (2.11-alpine)

**Comment by hyt05** [comment]
apisix-ingress-controller  error log
![image](https://user-images.githubusercontent.com/48778924/184267470-d8804251-9e37-487d-97fd-e3d59b20fdac.png)

In fact there are only two apisixroutes in the cluster
![image](https://user-images.githubusercontent.com/48778924/184267624-cec9da15-a229-4790-8422-61c754f3eb0b.png)

**Comment by tao12345666333** [comment]
please show me your `kubectl get pods apisix-ingress-controller` command's result. thanks.

**Comment by hyt05** [comment]
> please show me your `kubectl get pods apisix-ingress-controller` command's result. thanks.

![image](https://user-images.githubusercontent.com/48778924/184305409-32269ffc-416c-4b75-bd93-7cf25fc1e9e0.png)

**Comment by hyt05** [comment]
I did an uninstall and deleted the data in etcd and redeploy also couldn't get it to work

**Comment by tao12345666333** [comment]
I saw the pod status is CrashLoopBackOff, In this scenario, you need to view its log and debug it.

In addition, when using APISIX Ingress, it is not recommended that you use APISIX Dashboard for data manipulation.

**Comment by hyt05** [comment]
> 我看到pod状态是CrashLoopBackOff，在这种情况下，你需要查看它的日志并调试它。
> 
> 此外，在使用 APISIX Ingress 时，不建议您使用 APISIX Dashboard 进行数据操作。

![image](https://user-images.githubusercontent.com/48778924/184309465-46277520-5a70-465b-896e-b5699d593a1f.png)
Its log is as follows, I don't have upstreams appearing in the log, and it doesn't help after I redeploy, how can I fix it

**Comment by hyt05** [comment]
Solved, my k8s cluster node network is not connected, and the health check fails.
