### ISSUE TITLE
request help: unexpected status code 404

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#1248]
### Issue description

如果apisix是新集群且没有任何apisix对象，controller启动时list所有apisix的对象，会出现404报错，导致controller无法初始化完成
![image](https://user-images.githubusercontent.com/7006014/184871757-c05e1a4b-9178-46e9-9ab4-8c4cf1f44983.png)

![image](https://user-images.githubusercontent.com/7006014/184871798-76c543a7-5095-4721-8498-34f0a118d52f.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1
- your Kubernetes cluster version (output of kubectl version): 1.16
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): centos7.6

**Comment by marchlhw** [comment]
![image](https://user-images.githubusercontent.com/7006014/184878133-3f5833b7-fec4-4c38-8588-4d0844b48956.png)
加了这一行代码解决问题

**Comment by tao12345666333** [comment]
cc @lingsamuel PTAL, thanks

**Comment by marchlhw** [comment]
> 

控制器在启动的时候会list所有apisix对象，截图中仅是部分对象404，那是因为我人工录入了route、upstrem、ssl到集群中，剩下的，想尝试手动的方式解决

你们可以看下controller的run方法的逻辑，404也会导致HasSynced返回异常，会导致controller每次执行到这里就退出，然后反反复复

![image](https://user-images.githubusercontent.com/7006014/185305353-c2888283-4ea3-40ba-ae65-27f9c35a031f.png)

**Comment by AlinsRan** [comment]
Why 404? Can you open the debug log?

**Comment by marchlhw** [comment]
> 
default-apisix-cluster-base-url这个配置错了，就不是404的问题了

你们顺着这个调用链路排查下吧，这个链路就没有对错误进行区分，包括404在内
run --> HasSynced --> syncCacheOnce --> List --> listResource

**Comment by tao12345666333** [comment]
Please provide your minimum reproduce steps.

**Comment by AlinsRan** [comment]
> > 
> 
> default-apisix-cluster-base-url这个配置错了，就不是404的问题了
> 
> 你们顺着这个调用链路排查下吧，这个链路就没有对错误进行区分，包括404在内，底层抛出来的错误，到上游判断有错误的时候就直接退出了 run --> HasSynced --> syncCacheOnce --> List --> listResource

I have verified it. If the admin url is correct, it will not 404. If the URL is wrong, 404 will be generated. 
Can you open the debug log, and request the admin url yourself?

**Comment by marchlhw** [comment]
> 

现在环境我已经推到重建了没有复现，即使是全新的集群没有任何对象，list时也会响应200，可能我当时部署环境的有问题，但baseurl我可以保证是没有问题的，因为我没有修改过这个配置，我重建集群很快，通过ansible自动化部署
![image](https://user-images.githubusercontent.com/7006014/185533023-3d9965b0-ea7c-4c1d-b5f1-3c1b4b8bcdf0.png)
