### ISSUE TITLE
request help: support apisix timeout param at the ApisixRoute level

### ISSUE THREAD

**Issue by rjiang-ptm** [apache/apisix-ingress-controller#1253]
### Issue description

Does apisix ingress controller support timeout setting/config at the ApisixRoute level?

We have a need to upload large file, eg. 5G file but got 504 timeout error due to ingress controller limit. Would like to be able to extend the default `timeout` setting at the Route level.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): close to latest
- your Kubernetes cluster version (output of kubectl version): 1.22
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
you can set it by ApisixUpstream
