### ISSUE TITLE
request help:  默认集群名称始终为default

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#1264]
### Issue description

![image](https://user-images.githubusercontent.com/7006014/185877342-0720691a-ba7b-4d8b-8831-a4cc9819aa01.png)
这个地方缺少yaml标签，会导致默认集群名称始终为default
![image](https://user-images.githubusercontent.com/7006014/185877753-ebb8cf20-593e-4cdf-b5c3-d6384533c538.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
thanks for your report.

Do you want to open a PR to fix this?
