### ISSUE TITLE
request help: 控制器采集指标不一致问题

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#1271]
### Issue description

控制器源码中请求apisix的状态码指标名称为：apisix_ingress_controller_apisix_bad_status_codes

![image](https://user-images.githubusercontent.com/7006014/186620589-c6f81ff5-3fc3-47a8-b615-1f6d5fffe039.png)

grafana的dashboard的配置中却为：apisix_ingress_controller_apisix_status_codes
源码中dashboard配置文件路径为：docs/other/json/apisix-ingress-controller-grafana.json
![image](https://user-images.githubusercontent.com/7006014/186621037-95cce768-57ee-47b4-b749-6713629e8943.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by marchlhw** [comment]
使用apisix_ingress_controller_apisix_status_codes要合理些

**Comment by tao12345666333** [comment]
what's your code version? 

It has been changed. https://github.com/apache/apisix-ingress-controller/pull/1012

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-ingress-controller/issues/1005

**Comment by marchlhw** [comment]
> 

控制器的版本是1.4.1，看到已经修复了这个问题，计划什么时候出1.5正式版

**Comment by tao12345666333** [comment]
1.0.5-rc1 has been released 

V1.5.0 Scheduled to be released within two weeks
