### ISSUE TITLE
request help: ingress duplicate data

### ISSUE THREAD

**Issue by xiangtianyu** [apache/apisix-ingress-controller#1275]
There are both apisix ingress and other ingress controllers in our env(such as traefik and nginx). So when the apisix ingress controller get and analyze these datas, it may create duplicate routes. Is there any suggestions to avoid this ?

**Comment by tao12345666333** [comment]
Using ingress class to split them

**Comment by xiangtianyu** [comment]
> Using ingress class to split them

I got it,thanks
