### ISSUE TITLE
request help: route mode

### ISSUE THREAD

**Issue by cj2a7t** [apache/apisix-ingress-controller#1281]
### request description

- Can I write the routing information to the data plane directly through the admin API instead of through `apply apisixroute crd`？
- Only use RegexMatch method for parameter route matching with path?  Example `/users/{userId}/setting`

### Environment

in apisix-ingress-controller

**Comment by tao12345666333** [comment]
> * Can I write the routing information to the data plane directly through the admin API instead of through `apply apisixroute crd`？

NO, If you use the APISIX Ingress controller, the only way to configure it is through the declarative API






> * Only use RegexMatch method for parameter route matching with path?  Example `/users/{userId}/setting`

I didn't understand what you meant
