### ISSUE TITLE
request help: apisix ingress controller is support apisix 2.15？

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1292]
### Issue description

apisix ingress controller is support apisix 2.15？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):2.14.1
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):centos7.6

**Comment by tao12345666333** [comment]
yes. we use APISIX 2.15 as default e2e environment

**Comment by tao12345666333** [comment]
yes. we use APISIX 2.15 to run e2e test cases

**Comment by wolgod** [comment]
> yes. we use APISIX 2.15 to run e2e test cases

thanks
