### ISSUE TITLE
request help: Gateway Api configuration

### ISSUE THREAD

**Issue by MBoui** [apache/apisix-ingress-controller#1296]
### Issue description

Hi,

I try to setup a local environment with `kind` or `minikube` and use the k8s Gateway API.
I already enable the config `enableGatewayAPI` but it's look i need to setup also the `ingress_publish_service` value.
I am not sure about which service i need to use, can you help me?

ty,

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): standard installation with helm
- your Kubernetes cluster version (output of kubectl version): 1.24 (minikube)
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):  `Linux i-ubu 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 10:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by tao12345666333** [comment]
Typically, it is the APISIX Gateway service.

**Comment by tao12345666333** [comment]
refer to https://github.com/apache/apisix-ingress-controller/blob/31b3ef84be4e96dc663de883ef5730a03bfb962b/conf/config-default.yaml#L40-L49
