### ISSUE TITLE
request help: port not defined

### ISSUE THREAD

**Issue by jerrytaotz** [apache/apisix-ingress-controller#1301]
### Issue description

When we try to update APISIXRoute CRD，the ingress controller report the error like this:
![企业微信截图_20a983e2-1019-401e-a325-e3a92ab08ea4](https://user-images.githubusercontent.com/15017733/187448326-8c98aeee-eecc-4bc9-a568-774a0b02fe54.png)
It looks like this problem only appears when we try to update/delete ports, it works fine with adding new ports.
The steps as followed:
1. We first define two ports, 8080 and 8081
![企业微信截图_8d0bc18f-97e0-456e-984b-1e3092c21254](https://user-images.githubusercontent.com/15017733/187449188-abf8627f-cff8-48a0-b939-4f3e23206812.png)
The ingress controller create two upstreams correctly
![企业微信截图_ae9faabc-14cf-4bb3-b55b-fe88fbddf461](https://user-images.githubusercontent.com/15017733/187449478-1fd0ef27-8050-4b10-bbd8-54f669ec2441.png)

2. change port 8081 to 8083
![企业微信截图_2a14d4f5-bb8d-4643-b291-720c31da05aa](https://user-images.githubusercontent.com/15017733/187449639-c79d401b-af30-44d5-9f6b-75a85282e155.png)
The error appears:
service.spec.ports: port not defined

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1

**Comment by tao12345666333** [comment]
Please paste CR configuration YAML directly instead of images.

This makes it easier for others to reproduce the problem

**Comment by wolgod** [comment]
我也遇到过类似的问题，如果svc的port变化了，同步更新apisixroute的话就会出现这个问题，我这边的解决办法是如果port端口发生变化，我会删掉旧的apisixtroute 然后重新创建新的apisixroute,如果
