### ISSUE TITLE
Automatically reload ingress upon certificate renewal

### ISSUE THREAD

**Issue by TimVerbois** [apache/apisix-ingress-controller#1304]
### Issue description

I use cert-manager in combination with an ingress controller from APISIX.  Cert-manager replaces certificates in time and the secret containing the certificate always contains a valid certificate, but this is not picked up by the ingress controller.

I tried bumping the ingress by changing it slightly (like adding a label or an annotation), but it doesn't result in a solution.

Is there a solution for this problem, I can't imagine I'm the only one with this problem.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 
Version: 1.4.1
Git SHA: no-git-module
Go Version: go1.16.15
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64

- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a35ccc8395e8a5eaa83b7b8c981677893b651cba", GitTreeState:"clean", BuildDate:"2022-07-28T20:52:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

Cert-manager version:  v1.8.0

**Comment by tao12345666333** [comment]
Thanks for your report. 

Normally, cert-manager will update the secret resource, then ingress-controller can update it to APISIX.

How do you verify that the certificate is not valid? By checking the status? or log? Or some other way?

**Comment by TimVerbois** [comment]
I use 

```
$ openssl s_client -host <fqdn> -port 443 -servername <fqdn>
```

The result I get back is the old certificate.

I'm sure cert-manager updates the cert, because if I check the secret and use

```
$ openssl x509 -in <file with base64 decoded secret> -text
```
i get a valid certificate (the dates have been updated).

**Comment by tao12345666333** [comment]
You can try to get the ssl resource object through APISIX's admin API and check whether the content is correct
