### ISSUE TITLE
discuss: New feature in Apache APISIX Ingress controller v1.6

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1309]
Hi, folks

The Apache APISIX Ingress controller v1.5 version has been entered release window, and it is time to discuss the plans in the v1.6 version together.

I think the following features need to be included:

- [ ] Gateway API https://github.com/apache/apisix-ingress-controller/issues/644

    - [x]   * #1217 
    - [x]   * #1278 
    - [ ]   * #1418  HTTPRoute more complete support, such as filter

- [x] #927  
    - [x] #1306  

- [x] #547
    - [x] #1051 
  
- [x] #1372 Add suport for APISIX's plugin_metadata
    - [x] #1369 

- [x] #1019 and   #948 

- [x] #707 
    - [x] #1431 
- [x]  #1374 
    - [x] #1377 
- [x]  #1376 
- [x] #744 
- [x] #966

**Comment by MBoui** [comment]
- Knative support ? :)

**Comment by tao12345666333** [comment]
> * Knative support ? :)

thanks!  SGTM

This will help us expand the ecosystem

**Comment by machinly** [comment]
Support  multi cluster management should be helpful.
`ApisixClusterConfig` was designed for this, but not completed.

**Comment by tao12345666333** [comment]
> Support multi cluster management should be helpful. `ApisixClusterConfig` was designed for this, but not completed.

@machinly Are you referring to managing multiple APISIX clusters through one APISIX Ingress controller?

**Comment by tao12345666333** [comment]
In fact, we will achieve the goal of managing multiple APISIX instances through one Ingress controller.
This is necessary for a complete implementation of the Gateway API.

We can dynamically state the APISIX instance simply by creating a `Gateway` resource.

**Comment by machinly** [comment]
> > Support multi cluster management should be helpful. `ApisixClusterConfig` was designed for this, but not completed.
> 
> @machinly Are you referring to managing multiple APISIX clusters through one APISIX Ingress controller?

The field `parentRefs` in `HTTPRoute` is exactly what I needed. Gateway API is awesome.

**Comment by tao12345666333** [comment]
v1.6.0-rc1 has been released. #1536  I will close this one. Thanks all!!!
