### ISSUE TITLE
request help: 2个apisix-ingress-controller用同一个etcd时候无法隔离

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix-ingress-controller#1316]
### Issue description

当我在一个k8s环境的2个命名空间各自部署一套apisix（包括ingress和dashboard），但是2套apisix用的同一个etcd，但是是不同的prefix。每个命名空间有不同的apisix.ingress的label，并且ingress-controller的配置里也配置不同的  app_namespaces和 namespace-selector。但是当我在其中一个命名空间里创建apisixroute和apisixupstream时候，2个命名空间下的apisixdashboard有对方命名空间的apisixroute和apisixupstream。查看etcd时候，2个prefix下都有同样的route和upstream。
就是当2个apisix使用同一个etcd时候，互相会有冲突。

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):  1.4.1
- your Kubernetes cluster version (output of kubectl version): 1.20.10
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by AlinsRan** [comment]
In fact, the apisix-ingress-controller is not aware of etcd.
The `app_namespaces` has been deprecated. Maybe it was affected by this bug #1238 .

**Comment by AlinsRan** [comment]
The problem of `namespace-selector` invalid will be fixed in v1.5.0. 
You can use ingress resources, and then isolate resources through different [IngressClass](https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml#L69).

**Comment by tao12345666333** [comment]
Please refer to #592

**Comment by lihuawei321** [comment]
> The problem of `namespace-selector` invalid will be fixed in v1.5.0. You can use ingress resources, and then isolate resources through different [IngressClass](https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml#L69).

我用了ingressclass，也是2个命名空间下的apisixdashboard都会创建。
