### ISSUE TITLE
request help: Use certificates from AWS ACM service when deploying on Amazon EKS

### ISSUE THREAD

**Issue by lhmlihaomin** [apache/apisix-ingress-controller#1332]
### Issue description

Hello, 
Is it possible to tell apisix-ingress-gateway to read certificate files from ACM service?
Or if we set gateway.type to "LoadBalancer", is it possible to create the ELB listener with HTTPS:443 protocol instead of TCP:443?

### Environment

Ingress Controller Version:
Version: 1.4.1
Git SHA: no-git-module
Go Version: go1.16.15
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64

Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tao12345666333** [comment]
Normally they can work together. But it needs to be verified.

**Comment by lamoglia** [comment]
Reading the apisix_tls docs https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/apisix_tls.md, it suggests that the certificate itself must be stored in a kubernetes secrets. As far as I know, it is not possible to download an AWS ACM certificate private key
