### ISSUE TITLE
feat: Support Gateway API route attachment constraints

### ISSUE THREAD

**Issue by stillfox-lee** [apache/apisix-ingress-controller#1349]
Gateway API has some constraints about Route Attachment. 
Such as:

- Gateway [AllowedRoutes](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.AllowedRoutes) defines which Routes may be attached
- CommomRouteSpec [ParentReference](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.ParentReference) defines which Gateway it want to attachment.

This feature is not implemented in the project yet, and I can help to do that.

**Comment by tao12345666333** [comment]
cool! Thanks for your help!
