### ISSUE TITLE
How does the ingress controller work well with dashboard without relying on the Apache APISIX-Admin api?

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-ingress-controller#136]
The Apache APISIX-Admin api will be deprecated in the next 3.0 version. The current ingress controller relies on the Apache APISIX-Admin api, which does not seem like a good choice

**Comment by gxthrj** [comment]
I think whether we use `admin api` or not has nothing to do with the separation of apisix CP and DP.
But we can consider supporting both `admin api` way and `standalone` way.

**Comment by debu99** [comment]
I need standalone mode for apisix ingress controller, does it currently support?

**Comment by tokers** [comment]
@debu99 By using the term "standalone", what's your exact meaning? Does it mean do not rely on ETCD?

**Comment by debu99** [comment]
Yes, I would like to use git/yaml to update routing info, like Kong dbless

**Comment by tokers** [comment]
Currently we don't support it, we may do it in the future, it depends on a good standalone mode of APISIX, the current yaml based way is not so suitable in Ingress scanario.

**Comment by gxthrj** [comment]
we don't support it, 
If use the standalone mode, we need to develop an additional distribution system and ensure high availability.
BTW,Kong dbless is also not recommended for use in production.

**Comment by wgs111** [comment]
do we have a plan to support apisix stand-alone mode in the future?

**Comment by gxthrj** [comment]
We will indeed consider some new architectures so that APISIX will not rely on `etcd` when deploying. 
But this is different from the APISIX stand-alone mode. 
Our goal is to make `APISIX ingress` a stateless deployment.

**Comment by tao12345666333** [comment]
For stateless deployment mode, let's use #610 for tracking.

In a Kubernetes environment we recommend using declarative configuration, but APISIX Dashboard does not include this capability. This aspect is not in the roadmap of the APISIX Ingress project. I will close this issue, thanks
