### ISSUE TITLE
The ingress controller requires the reconcile loop

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-ingress-controller#137]
The reconcile loop is a basic feature of the controller model that guarantees the consistency of the Custom Resource Object with the actual business state or business rules

**Comment by gxthrj** [comment]
This is a important feature for keeping the controller more robust.

**Comment by gxthrj** [comment]
Let us make it done in milestone 0.2.0.

**Comment by gxthrj** [comment]
Close this Issue with #155
