### ISSUE TITLE
使用helm安装apisix-ingress-controller 没有生成对应的ingressclass

### ISSUE THREAD

**Issue by maristeslk** [apache/apisix-ingress-controller#1371]
### Issue description

我在集群当中想安装多个ingress controller并且开启了hostNetwork,通过nodeselecter来防止ingress冲突 集群中所有pod都能正常允许
我跟着官网文档 
https://apisix.apache.org/zh/docs/ingress-controller/tutorials/proxy-the-httpbin-service-with-ingress/
创建了ingress 也能查到route 但是访问域名一直是404
![image](https://user-images.githubusercontent.com/47805146/192991192-bc9f842e-fac2-49a7-ad0d-14965e826789.png)

![image](https://user-images.githubusercontent.com/47805146/192990810-f9c90054-ae0c-43e2-825a-9bced2b371ee.png)

ps: 域名是单独做了解析到ingress-controller的hostip上的
然后我注意到kubectl get ingressclass  看不到apisix的ingressclass 我不清楚这是不是符合预期的 会不会是导致我的ingress没有生效原因。
![image](https://user-images.githubusercontent.com/47805146/192990449-ffd74d25-b241-41f8-b0a3-21390bfbaf8a.png)

如果我需要手动创建一个ingressclass资源我要怎么做？

### Environment

apisix-ingress-controller-0.9.3  app verison 1.4.1
k8s verison v1.24.4 
ubuntu 2204  kernel 5.15.0-46

**Comment by tao12345666333** [comment]
please refer to this one https://github.com/apache/apisix-helm-chart/issues/343
