### ISSUE TITLE
The correspondence between ApisixService/ApisixRoute/ApisixUpstream CRD objects and APISIX Route and Upstream objects is a bit hard to understand

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-ingress-controller#138]
A route created is ApisixRoute->apisixService->ApisixUpstream instead of ApisixRoute->ApisixUpstream, which is a bit strange

**Comment by tokers** [comment]
We redesigned these CRDs, see http://apisix.apache.org/docs/ingress-controller/concepts/apisix_route for details.
