### ISSUE TITLE
bug: ingress extensions/v1beta1 seems like does not support tls

### ISSUE THREAD

**Issue by shareinto** [apache/apisix-ingress-controller#1387]
### Issue description

https://github.com/apache/apisix-ingress-controller/issues/586
now it support networking.k8s.io/v1 networking.k8s.io/v1beta1
i don't know why extensions/v1beta1 is not supported
it's a pity that I have a large number of extensions/v1beta1 that have not been upgraded

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
Version: 1.5.0
Git SHA: f23454f
Go Version: go1.19.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.19) exceeds the supported minor version skew of +/-1

### Minimal test code / Steps to reproduce

create a extensions/v1beta1 ingress with tls

### Actual result

no apisix tls was created

### Error log

no log

### Expected result

a apisix tls was created

**Comment by tao12345666333** [comment]
`extensions/v1beta1`  This version is too old.  

The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.


We don't want to continue adding support for such an old version.

Of course, we also accept PRs if anyone is interested in implementing it
