### ISSUE TITLE
bug: controller auth 403

### ISSUE THREAD

**Issue by misstick86** [apache/apisix-ingress-controller#1388]
### Issue description

Enter the following command. I get 403 error in controller. So, this is my operator problem.

```shell

make kind-up

helm install apisix apisix/apisix --create-namespace  --namespace apisix

helm install apisix-dashboard apisix/apisix-dashboard --create-namespace --namespace apisix

helm install apisix-ingress-controller apisix/apisix-ingress-controller --namespace apisix

```
and then. you should change **default_cluster_base_url** value in configmap name is `apisix-ingress-controller-configmap`. and change deployment yaml for init container settings. 

someboy can try do this again.  see if there will be this problem.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
/ingress-apisix # ./apisix-ingress-controller version --long
Version: 1.5.0
Git SHA: no-git-module
Go Version: go1.19.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
- your Kubernetes cluster version (output of kubectl version):
v1.21
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
```
/ingress-apisix # uname -a
Linux apisix-ingress-controller-f4f9974f8-k5ddt 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 Linux
```

### Minimal test code / Steps to reproduce

no

### Actual result

no

### Error log

controller log:

```
2022-10-14T23:46:30+08:00       error   apisix/plugin.go:46     failed to list plugins' names: unexpected status code 403; error message: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

2022-10-14T23:46:30+08:00       error   apisix/plugin.go:46     failed to list plugins' names: unexpected status code 403; error message: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

2022-10-14T23:46:30+08:00       error   apisix/cluster.go:394   failed to list plugin names in APISIX: unexpected status code 403; error message: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

2022-10-14T23:46:30+08:00       error   apisix/cluster.go:357   failed to sync schema: unexpected status code 403; error message: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

........
```

**Comment by misstick86** [comment]
I already know the reason. may be we should give a note in repo docs for [here](https://github.com/apache/apisix-helm-chart/blob/master/docs/en/latest/apisix.md). 

[reason](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/configmap.yaml#L247). apisix has some rule for access requests.

**Comment by tao12345666333** [comment]
you can see  https://github.com/apache/apisix-helm-chart/blob/0271a095d8294554319407c64dd60c525117e127/charts/apisix/templates/configmap.yaml#L255-L257


Our recommended installation is to install all components in one command.
```
 helm install apisix apisix/apisix    --set gateway.type=NodePort   --set ingress-controller.enabled=true   --set ingress-controller.config.apisix.serviceNamespace=apisix   --namespace apisix   --create-namespace   --set ingress-controller.config.apisix.serviceName=apisix-admin
```

**Comment by tao12345666333** [comment]
you can see  https://github.com/apache/apisix-helm-chart/blob/0271a095d8294554319407c64dd60c525117e127/charts/apisix/templates/configmap.yaml#L255-L257


Our recommended installation is to install all components in one command.
```
 helm install apisix apisix/apisix    --set gateway.type=NodePort   --set ingress-controller.enabled=true   --set ingress-controller.config.apisix.serviceNamespace=apisix   --namespace apisix   --create-namespace   --set ingress-controller.config.apisix.serviceName=apisix-admin
```

**Comment by misstick86** [comment]
yeap.
