### ISSUE TITLE
BUG: Route mybe no desc field. And code not go fmt

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#14]
![image](https://user-images.githubusercontent.com/10919124/76936927-bc7de200-692e-11ea-8c1a-2b92f3748b0c.png)
![image](https://user-images.githubusercontent.com/10919124/76936963-c99ad100-692e-11ea-92e2-996bba8e0992.png)

as below picture show, Route mybe no `desc` field
/apisix/admin/routes
![image](https://user-images.githubusercontent.com/10919124/76936566-1b8f2700-692e-11ea-868f-ecb3b2a965dc.png)

**Comment by gxthrj** [comment]
@chzhuo 
Yes, I will add a check here
However, it is recommended that when using `ingress-controller`, only define route through `CRD`, do not directly use `apisix dashboard` or `apisix admin api`, this will lead to inconsistent state between apisix and k8s, ingress-controller only does one-way synchronization `from k8s to apisix` , Two-way synchronization is more difficult.

Define route to use CRD (in this way, route will automatically generate name)
You can view it through the `apisix dashboard`.

**Comment by tokers** [comment]
Solved since #9 merged.
