### ISSUE TITLE
Ingress controller calls admin api need to support passing token

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-ingress-controller#140]
The current ingress controller calls api interface does not support token, so the deployment needs to apisix default off token authentication function, there is a security risk

**Comment by gxthrj** [comment]
Related to https://github.com/apache/apisix-ingress-controller/issues/50

**Comment by tokers** [comment]
The related PR is #147

**Comment by tokers** [comment]
Supoorted by #147.
