### ISSUE TITLE
feat: Allow use of config maps and secrets in plugin configs

### ISSUE THREAD

**Issue by jnystad** [apache/apisix-ingress-controller#1408]
Hi there,

Some plugins require secrets in their configs (e.g. openid-connect with client_secret and session.secret), but there is no way of injecting this from a Kubernetes secret that I can see. Likewise, obtaining some values from config maps could be very useful.

This makes it hard to automate deployments when using apisix-ingress-controller without writing custom scripts to inject secrets at deploy time (which is not always possible or desirable, e.g. when using a Kustomize based workflow with standard tooling like ArgoCD).

Is there a plan to add support for this? For instance, with a preprocessing step of plugin configs or adding the option to refer to a config map/value or secret/value in any of the config values?

**Comment by jnystad** [comment]
Yes, please. And if you include the option to set secret key name as well, that would probably solve the most common use cases.

**Comment by An-DJ** [comment]
I'd want to help to solve this. Could it be assigned to me? @tao12345666333

**Comment by tao12345666333** [comment]
@jnystad #1486 has been merged. It will be introduced in v1.6 version (this week)
