### ISSUE TITLE
Ingress controller container image tool packaging is not reasonable

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-ingress-controller#141]
1. The base image is not reasonable
2. Fewer tools, difficult to debug problems
3. Suggest adding curl, netstat, dlv and other common debugging tools

**Comment by tokers** [comment]
@Miss-you Do you have any recommended base images?

**Comment by tokers** [comment]
The Dockerfile in this repo can be armed with a rich base image, while the one in apisix-ingress-controller-docker can be concise.

**Comment by gxthrj** [comment]
> The Dockerfile in this repo can be armed with a rich base image, while the one in apisix-ingress-controller-docker can be concise.

Agree

**Comment by tokers** [comment]
Solved.
