### ISSUE TITLE
feat: allow to custom port when `make kind-up`

### ISSUE THREAD

**Issue by zou8944** [apache/apisix-ingress-controller#1416]
### Issue description

The default port of kind is 5000, and the script `make kind-up` does not support to custom port. In some case, 5000 is occupied by other process. 

I am using macbook pro, and macOS Monterey, the 5000 port is used by Control Panel. Although I can release this port in setting. But it's inconvenient.

If you agree to allow to custom it, I can do it.

### Environment

OS: Darwin zouguodongdeMBP.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### Minimal test code / Steps to reproduce

make kind-up

### Actual result

start fail

### Error log

```shell
./utils/kind-with-registry.sh
No kind clusters found.
16adaaa06c964635bdc6f014ad275f2cee9aaf90118f9f6490b2ff0fba4d0b83
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use.
make: *** [kind-up] Error 125
```

### Expected result

start success

**Comment by Shuimo03** [comment]
hi, i want this issues
