### ISSUE TITLE
dev-env: registry container should also be deleted when `make kind-reset`

### ISSUE THREAD

**Issue by zou8944** [apache/apisix-ingress-controller#1419]
### Issue description

`make kind-up` start registry and k8s cluster, while `make kind-reset` delete k8s cluster only and registry container is remaining, there are 2 disadvantages.

- Semantically, `make kind-reset` should be opposite to `make kind-up`, current script breaks this rule.
- If registry container start failed when `make kind-up` (may be port occupy conflict), to clean the environment, I have to delete registry container mannully besides run `make kind-reset`. This can be reproduced.

So, I suggest egistry container should also be deleted when `make kind-reset`

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.5.0

### Minimal test code / Steps to reproduce

1. Run any process that occupy this port 5000
2. Run `make kind-up`, the result should report
```shell
zouguodong@zouguodongdeMBP apisix-ingress-controller % make kind-up
./utils/kind-with-registry-up.sh
No kind clusters found.
33502d9bdb669d397a305a03c8cbccb717595f0e51441151ce4324293f1394fa
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use.
make: *** [kind-up] Error 125
```
3. Run `make kind-reset` to clean local environment, It should be success.
4. To avoid port conflict, Change registry port to 5001, and run `make kind-up` again. report another error
```shell
zouguodong@zouguodongdeMBP apisix-ingress-controller % make kind-up
./utils/kind-with-registry-up.sh
No kind clusters found.
docker: Error response from daemon: Conflict. The container name "/kind-registry" is already in use by container "33502d9bdb669d397a305a03c8cbccb717595f0e51441151ce4324293f1394fa". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
make: *** [kind-up] Error 125
```

### Actual result

refer to "Steps to reproduce"

### Error log

refer to "Steps to reproduce"

### Expected result

After change registry log, `make kind-up` should be success.

**Comment by tao12345666333** [comment]
This is a problem.

But I have some different ideas.

Since the registry can be used to store images, it is stateful. Users can use it to store some images.

I'm leaning towards us adding some logic, or some options.
Allow the user to have a registry, or allow the user to control whether to clean up the registry

WDYT @lingsamuel @AlinsRan

**Comment by zou8944** [comment]
It seems a good idea to allow user to control whether to clean up the registry.

On the other hand, the registry started in `make kind-up` is implicit. If user want to store images, they should run their own local registry, and this registry is only for kind. 🤔

**Comment by zou8944** [comment]
@tao12345666333 if no further discussion, this issue may be closed.

**Comment by tao12345666333** [comment]
Sure, if you want
