### ISSUE TITLE
discuss: ingress annotations supports the specified upstream protocol

### ISSUE THREAD

**Issue by dickens7** [apache/apisix-ingress-controller#1420]
### Issue description

# Describe

Use ingress to expose resources upstream of gRPC, gRPCs, or https

We can add Ingress annotations `k8s.apisix.apache.org/upstream-protocol`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8s.apisix.apache.org/upstream -protocol: "gRPC"
...
```
>  k8s.apisix.apache.org/upstream -protocol

- http
- https
- gRPC
- gRPCs

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
SGTM!
