### ISSUE TITLE
docs: file link in website is wrong

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#1430]
https://apisix.apache.org/docs/ingress-controller/tutorials/mtls/#protect-the-route-using-ssl

The generated link is `https://apisix.apache.org/assets/files/server-secret-b6e186f162ed247c320c42de1e1e43f4.yaml/`, which results a 404. The link has an extra slash, removing the trailing slash it will work.

@SkyeYoung PTAL

**Comment by SkyeYoung** [comment]
@lingsamuel Please use the original GitHub link instead of the relative path; the server rules provided by Apache don't handle non-web resources very well.

**Comment by SkyeYoung** [comment]
@lingsamuel Hi, I fixed this in #1434 and #1432. And the CI failure doesn't look like it has anything to do with my changes, so please Review.
