### ISSUE TITLE
request help: What's difference between Proxy the httpbin service with Ingress and not with Ingress ?

### ISSUE THREAD

**Issue by s-khaon** [apache/apisix-ingress-controller#1433]
### Issue description

https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service-with-ingress/
https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service/
I don't know what is the difference in the access path between the above two proxy modes.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- 2.15.0-alpine
- your Kubernetes cluster version (output of kubectl version):
- 1.21
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
- No

**Comment by tao12345666333** [comment]
Using CRD or using Ingress resource

**Comment by oyiadin** [comment]
The difference is that APISIX CRDs are more specific and compatible with the most of APISIX features, in the meanwhile, the Ingress way is more common within the Kubernetes world, but lack of some APISIX features.

For example, there are only three types of operators in the Ingress way: `Exact`, `Prefix` and `ImplementationSpecific` (see https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types). But, using APISIX CRD, you can control your route-matching rules with more expression operators (such as `RegexNotMatch`, `In` and `NotIn`, see https://apisix.apache.org/docs/ingress-controller/next/references/apisix_route_v2beta3/#expression-operators).

As for the two tutorials that you've mentioned, I don't think that there are any differences from the point of a developer in such a simple situation.
