### ISSUE TITLE
help request: apisix-ingress-controller 1.5 can't work with APISIX v3

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix-ingress-controller#1436]
### Description

apisix-ingress-controller 1.5 crashed without Admin API `/apisix/ssl`

### Environment

- APISIX version (run `apisix version`): 3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
@tao12345666333 
Which version of apisix-ingress-controller will support APISIX 3.0?

**Comment by tao12345666333** [comment]
maybe v1.7

v1.5 can work with APISIX v2.15

**Comment by tao12345666333** [comment]
we can use #1339 for track
