### ISSUE TITLE
e2e: add test case for SNI based TLS route

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1438]
But I think a more complete case can be added in e2e.
Create a certificate pair and use it for proxying.

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/pull/1051#pullrequestreview-1168112154_
      

cc @mangoGoForward

**Comment by cr7258** [comment]
I can try it.

**Comment by tao12345666333** [comment]
Thanks! Assigned
