### ISSUE TITLE
chore: remove `conf/config-default.json`, only keep `conf/config-default.yaml`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-ingress-controller#145]
the JSON format is not good for the user.

related comment: https://github.com/apache/apisix-ingress-controller/pull/131/files#r548930435

**Comment by tokers** [comment]
Yes, we can just remove the `conf/config-default.json` file.

**Comment by gxthrj** [comment]
Let's make it done in milestone 0.3.0.
