### ISSUE TITLE
request help: Block request method with Apisix Ingress Controller annotation

### ISSUE THREAD

**Issue by hndoss** [apache/apisix-ingress-controller#1463]
### Issue description

I need to block any request method DELETE using the Apisix ingress controller. I don't see any annotation in [this list](https://apisix.apache.org/docs/ingress-controller/concepts/annotations/) that can help me with my needs.

With the nginx ingress controller, I had to add the following annotation to an ingress.
```
nginx.ingress.kubernetes.io/server-snippet: |
      if ($request_method ~ DELETE){
        return 405;
      }
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
# /ingress-apisix/apisix-ingress-controller version --long
Version: 1.5.0
Git SHA: no-git-module
Go Version: go1.19.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
- your Kubernetes cluster version (output of kubectl version):
```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.21.14-gke.3000
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by incubator4** [comment]
> This feature is not yet implemented, but it's not hard.
> 
> Currently, it can be done by binding a pluginconfig of a serverless plugin

I'd love to have a try. Need I implement plugin (might called method-restriction) in both  apisix and ingress controller ?

**Comment by tao12345666333** [comment]
@incubator4 Thanks!

no, you don't need implement any new plugin, you can just use APISIX's response-rewrite plugin https://apisix.apache.org/docs/apisix/plugins/response-rewrite/

What you need to do is implement the new annotation   https://github.com/apache/apisix-ingress-controller/tree/master/pkg/providers/ingress/translation/annotations

And when translating, just add response-rewrite configuration to it

**Comment by tao12345666333** [comment]
#1471 has been merged. Thanks @incubator4 make this happen
