### ISSUE TITLE
bug:  ths request header append apisix upstream port 

### ISSUE THREAD

**Issue by jaikewhh166** [apache/apisix-ingress-controller#1468]
### Issue description

1.  get the request header  info，the Host header append apisix upstream port 
{
    "code": 0,
    "data": {
        "debug": "kkyy@123",
        "Accept": "*/*",
        "User-Agent": "PostmanRuntime/7.29.2",
        "X-Forwarded-Proto": "http",
        "X-Forwarded-Host": "hh.whatb.xyz",
        "Host": "hh.whatb.xyz:9080",
        "Accept-Encoding": "gzip, deflate, br",
        "X-Forwarded-Port": "9080",
        "X-real-client-ip": "133.11.99.156",
        "Cache-Control": "no-cache",
        "X-Forwarded-For": "133.11.99.156, 10.118.45.23",
        "Postman-Token": "7d184ad2-1bfe-4f77-b36d-5490fcf4f7cf",
        "Content-Length": "0",
        "X-Real-IP": "10.118.45.23",
        "X-Scheme": "http"
    },
    "message": "Execute successfull",
    "serverTime": "2022-11-18 06:33:32",
    "success": true
}

### Environment

1.  chart version apisix-0.11.0  app version 2.15.0
2.  kubernetes cluster version 1.24.1
3.  Linux 5.4.17-2136.307.3.1.el7uek.x86_64 #2 SMP Mon May 9 17:25:56 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Minimal test code / Steps to reproduce
![image](https://user-images.githubusercontent.com/39252581/202653042-d8969263-aaae-41bc-8b99-a4cb5f57f157.png)
![image](https://user-images.githubusercontent.com/39252581/202653153-49beaae4-993f-4cd1-8723-520b4c69abf8.png)

### Actual result

"Host": "hh.whatb.xyz:9080",

### Error log

"Host": "hh.whatb.xyz:9080",

### Expected result

"Host": "hh.whatb.xyz",

**Comment by AlinsRan** [comment]
Can you provide a steps to reproduce? Or more information.

**Comment by jaikewhh166** [comment]
1.  Just use helm install apisix and do nothing else ， kuberneter on  oracle cloud  ,  oke service
helm upgrade --create-namespace -install apisix apisix/apisix \
  --set gateway.type=LoadBalancer \
  --set gateway.loadBalancerIP="134.227.117.97" \
  --set gateway.externalTrafficPolicy=Local \
  --set etcd.enabled=false \
  --set etcd.host={http://10.118.6.244:2379\,http://10.118.6.149:2379\,http://10.118.15.22:2379} \
  --set ingress-controller.enabled=true \
  --set dashboard.enabled=true \
  --set dashboard.service.type=NodePort \
  --set dashboard.config.authentication.users[0].username="admin" \
  --set dashboard.config.authentication.users[0].password="apisix" \
  --set dashboard.config.authentication.users[1].username="viewer" \
  --set dashboard.config.authentication.users[1].password="viewer" \
  --set etcd.persistence.storageClass="oci-bv" \
  --set etcd.nodeSelector.name="common-np" \
  --set apisix.replicaCount=10 \
  --set allow.ipList="10.118.0.0/16" \
  --set nginx.workerRlimitNofile="655360" \
  --values apisix.nginx.conf.yaml \
  --set nginx.workerConnections="102400" \
  --namespace apisix \
  --set ingress-controller.config.apisix.adminKey=adminkey \
  --set admin.credentials.admin=adminkey \
  --set admin.credentials.viewer=viewerkey \
  --set admin.type=LoadBalancer \
  --set admin.annotations."oci\.oraclecloud\.com\/load-balancer-type"="nlb" \
  --set admin.annotations."oci-network-load-balancer\.oraclecloud\.com\/internal"="true" \
  --set admin.annotations."oci-network-load-balancer\.oraclecloud\.com\/oci-network-security-groups"="ocid1.networksecuritygroup.oc1.phx.aaaaaaaaulgcocvpolqiyggvazajmol2nzclark5hoa6ridehnwaultrl37a" \
  --set ingress-controller.config.apisix.serviceNamespace=apisix \
  --set ingress-controller.replicaCount=3 \
  --set ingress-controller.nodeSelector.name="common-np" \
  --set apisix.nodeSelector.name="common-np" \
  --set apisix.podAntiAffinity.enabled="true" \
  --set apisix.name="apisix" \
  --set serviceMonitor.enabled="true" \
  --set ingress-controller.serviceMonitor.enabled="true" \
  --set ingress-controller.serviceMonitor.namespace="apisix" \
  --set gateway.annotations."oci\.oraclecloud\.com\/load-balancer-type"="nlb" \
  --set gateway.annotations."oci-network-load-balancer\.oraclecloud\.com\/node-label-selector"="name=common-np" \
  --set gateway.annotations."oci-network-load-balancer\.oraclecloud\.com\/oci-network-security-groups"="ocid1.networksecuritygroup.oc1.phx.aaaaaaaaw5n6or3ksabwlsfgoxhxyuy5g6fmkydnelwinrmbplaatnex2htq"

**Comment by jaikewhh166** [comment]
> Can you provide a steps to reproduce? Or more information.

What information do I need to provide you?

**Comment by jaikewhh166** [comment]
1. apisixroute yaml 

apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: user-api-h5-whatb-xyz
  namespace: api
  labels:
    project: yowin
    service: user-api
spec:
  http:
  - name: intf-user-reg
    priority: 30
    match:
      hosts:
      - hh.whatb.xyz
      paths:
        - "/api/user/register*"
    backends:
    - serviceName: user-api-reg
      servicePort: 8080
  - name: intf-user
    priority: 20
    match:
      hosts:
      - hh.whatb.xyz
      paths:
        - "/api/user*"
    backends:
    - serviceName: user-api
      servicePort: 8080

**Comment by tao12345666333** [comment]
Can you format it please?

**Comment by jaikewhh166** [comment]
> Can you format it please?
This is a bug ?
