### ISSUE TITLE
request help: can use crd config apisix global rule

### ISSUE THREAD

**Issue by shijunLee** [apache/apisix-ingress-controller#1493]
### Issue description

I want use apisix global rule to process some problem，like route not found and the gateway 500 error etc. ,but I read the ingress source code not found hao to use crd to config this ,is this support?

**Comment by tao12345666333** [comment]
ApisixClusterConfig resource

**Comment by shijunLee** [comment]
> ApisixClusterConfig resource

this only support monitoring skywalking ,I want use custom plugins

**Comment by tokers** [comment]
Global rule cannot be used in apisix ingrees controller right now.

**Comment by shijunLee** [comment]
> Global rule cannot be used in apisix ingrees controller right now.

Whether there is plan support it

**Comment by tao12345666333** [comment]
If all goes well, it could be in v1.6, otherwise it will be in v1.7.

Also, I will close this issue, we can use https://github.com/apache/apisix-ingress-controller/issues/1104  for track
