### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by maqile** [apache/apisix-ingress-controller#1499]
### Issue description

请教个问题，如果apisix 部署在 k8s 集群外部， apisix ingress controller 监听 k8s api server, 给 apisix 生成的路由信息 是 pod+port? ，那apisix怎么访问 容器内部服务？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
I don't fully understand what you mean.
Please describe more clearly.

Maybe you want this one https://github.com/apache/apisix-ingress-controller/blob/de9f84fce92e9ad26d487ccafa4bb7e800176776/docs/en/latest/concepts/apisix_route.md?plain=1#L120

Also, please improve the title
