### ISSUE TITLE
Is ingress-controller be ready to use?

### ISSUE THREAD

**Issue by Iflengmo** [apache/apisix-ingress-controller#15]
I can't start this ingress follow the doc https://github.com/api7/ingress-controller/blob/master/doc/dev/develop.md
And it can be used now?

**Comment by moonming** [comment]
@gxthrj please take a look. Does the document need to be updated?

**Comment by dangfan** [comment]
In the deployment documentation, it is said that "并且补充APISIX image路径和版本号". Should this be the path of the image of APISIX ingress controller?

**Comment by gxthrj** [comment]
> I can't start this ingress follow the doc https://github.com/api7/ingress-controller/blob/master/doc/dev/develop.md
> And it can be used now?

Are there any more detailed error messages, or point out all unclear descriptions in the document "deploy.md", which I will add.

**Comment by gxthrj** [comment]
> In the deployment documentation, it is said that "并且补充APISIX image路径和版本号". Should this be the path of the image of APISIX ingress controller?

yes,that is a mistake, I have fixed it  now
thanks for report

**Comment by gxthrj** [comment]
close this issue now，reopen it  if have any problem
