### ISSUE TITLE
Trying to understand what these infos/warns mean

### ISSUE THREAD

**Issue by maths-lover** [apache/apisix-ingress-controller#1502]
![image](https://user-images.githubusercontent.com/25811797/206494182-cbd07f5d-47dd-46f0-a375-f513d4ec7f77.png)

I deployed it using helm chart with everything almost default. Is it possible to remove them?

**Comment by AlinsRan** [comment]
It looks like the crd of the v2.ApisixUpsteram resource is not installed.

**Comment by maths-lover** [comment]
@AlinsRan I believe it is installed. Check the output of the command you gave below,
```bash
$ kubectl get crd apisixupstreams.apisix.apache.org -o yaml | grep v2
  - name: v2beta3
  - v2beta3
```

**Comment by AlinsRan** [comment]
> @AlinsRan I believe it is installed. Check the output of the command you gave below,
> 
> ```shell
> $ kubectl get crd apisixupstreams.apisix.apache.org -o yaml | grep v2
>   - name: v2beta3
>   - v2beta3
> ```

Not installed v2 CRDs, you are currently v2beta3 CRDs.

**Comment by maths-lover** [comment]
So doing something like below be fine, right?
- Update `crds/customresourcedefinitions.yaml` with v2 instead of v2beta3
- Update values.yaml with value,
```
...
apisixRouteVersion: "apisix.apache.org/v2"
...
```

**Comment by maths-lover** [comment]
The helm version that I'm using doesn't support it.

**Comment by maths-lover** [comment]
> Just execute this command:
> 
> ```shell
> helm show crds apisix/apisix-ingress-controller | kubectl apply -f -
> ```

The helm version that I'm using doesn't support it, so this command fails.

**Comment by tao12345666333** [comment]
you can just apply this file 
https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml

**Comment by maths-lover** [comment]
@tao12345666333 I did apply this file, it didn't change anything, I still get those infos.
Thank you

**Comment by tao12345666333** [comment]
after you apply the new CRD, did you restart the apisix-ingress-controller?

**Comment by maths-lover** [comment]
> after you apply the new CRD, did you restart the apisix-ingress-controller?

Yes, I did restart the ingress-controller.
