### ISSUE TITLE
feat request: prometheus prefer_name param should be supported to set in apisixclusterconfig

### ISSUE THREAD

**Issue by fatpa** [apache/apisix-ingress-controller#1516]
### Issue description

Even if I set the `prefer_name: true` at apisix-helm-chart/values.yaml `pluginAttrs` or configmap `apisix` directly, it doesn't work. Because the default apisixclusterconfig will override the global_rules and make the change invalid. And the apisixclusterconfig can't support setting `prefer_name` param.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.5.0
- your Kubernetes cluster version (output of kubectl version): 1.19.6
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): 3.10

### Minimal test code / Steps to reproduce

Nothing

### Actual result

prefer_name: false

### Error log

Nothing

**Comment by fatpa** [comment]
I will add the `prefer_name` param into apisixclusterconfig `prometheusPluginConfig` soon.

Assign it to me plz.

**Comment by tao12345666333** [comment]
you want to add `perfer_name` to `prometheus.properties` ,right?

https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1/ApisixClusterConfig.yaml#L58-L62

**Comment by fatpa** [comment]
> you want to add `perfer_name` to `prometheus.properties` ,right?
> 
> https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1/ApisixClusterConfig.yaml#L58-L62

yes

**Comment by fatpa** [comment]
> https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1/ApisixClusterConfig.yaml#L58-L62

And I already finish it.

**Comment by tao12345666333** [comment]
Assigned!
