### ISSUE TITLE
request help: defind multiply ingress-apisix-controller in a k8s cluster

### ISSUE THREAD

**Issue by njustzsm** [apache/apisix-ingress-controller#1517]
### Issue description

hello，teams：
    I want to defind multiply ingress-apisix-controller in a k8s cluster, then create ApisixRoute in  the designated ingress-apisix-controller，Can I do that？ and please give me an example?

### Environment

apisix-ingress-controller 1.5
kubectl version:1.24

**Comment by tao12345666333** [comment]
please refer to #1070  and #592

**Comment by tao12345666333** [comment]
I will close this one, let using #592 for tracking. Thanks
