### ISSUE TITLE
fix: set the health check log level by gin to debug

### ISSUE THREAD

**Issue by huweihuang** [apache/apisix-ingress-controller#1546]
### Issue description

the health check log level is the info level and affected the business log.

```
info	gin@v1.8.1/context.go:173	path: /healthz
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

kubectl logs -f ingress-controller pod

### Actual result

```
debug	gin@v1.8.1/context.go:173	path: /healthz
```

### Error log

```
info	gin@v1.8.1/context.go:173	path: /healthz
```

**Comment by tao12345666333** [comment]
thanks for your report.

I think the following two steps are required:

* modify log level  (this can meet your basic needs)
* Replace the logger of this part with the same logger as other parts

**Comment by aynp** [comment]
I can take this one
