### ISSUE TITLE
request help: apisix send request to offline pod ip

### ISSUE THREAD

**Issue by start1943** [apache/apisix-ingress-controller#1563]
### Issue description

We updated deployment around 0:04 and check endpoints and apisix upstream iplist have been updated at 0:04, but check log , apisix sent the request to the offline pod ip cause http 504 at 01:00 until we reload apisix, then 504 disapper.
The possible reason is？thanks!

<img width="857" alt="image" src="https://user-images.githubusercontent.com/35452394/209625026-306afa5a-e46c-4117-84a2-97e8d1d93371.png">

### Environment

apisix-ingress-controller version:1.3.0
kubernetes cluster version 1.16.6
os-version :centos 7.4  3.10.0-1062.9.1.el7.x86_64

**Comment by tao12345666333** [comment]
Can you provide APISIX logs?

**Comment by start1943** [comment]
> Can you provide APISIX logs?

he apisix and Apisix-ingress-Controller logs don't have any error and  useful information,and this can't be repeated now...
