### ISSUE TITLE
request help: use apisixroute generate crd

### ISSUE THREAD

**Issue by wnz27** [apache/apisix-ingress-controller#1566]
### Issue description

use this plugin defination in crd yaml:

![截屏2022-12-28 19 08 30](https://user-images.githubusercontent.com/12094918/209803232-02ee1447-3eb0-4e8a-aedf-d15744a61f38.png)

crd yaml display this error：

<img width="672" alt="截屏2022-12-28 19 12 50" src="https://user-images.githubusercontent.com/12094918/209803563-45c9ab6c-ef2e-4277-a62f-7bc39531a730.png">

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by wnz27** [comment]
the format is error？ but i dont found some doc in official document

**Comment by AlinsRan** [comment]
Install using the helm? You need to enable forward-auth plugin.
https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L258-L304

**Comment by wnz27** [comment]
> Install using the helm? You need to enable forward-auth plugin. https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L258-L304

yes, i found the default configmap plugin list don't have this plugin, i resolve this problem, i add this plugin in configmap, and fix this

**Comment by wnz27** [comment]
> Install using the helm? You need to enable forward-auth plugin. https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L258-L304

thank u anyway~
