### ISSUE TITLE
request help: how to define ApisixPluginConfig and in apisixroute use some other param to overwrite some param

### ISSUE THREAD

**Issue by wnz27** [apache/apisix-ingress-controller#1568]
### Issue description

if i want to
1、define a ApisixPluginConfig use some plugin
2、define a apisixRoute and set same  plugin in ApisixPluginConfig with some different param
it‘s can work?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
You can actually try it out, they have different priorities

**Comment by tokers** [comment]
> ### Issue description
> if i want to 1、define a ApisixPluginConfig use some plugin 2、define a apisixRoute and set same plugin in ApisixPluginConfig with some different param it‘s can work?
> 
> ### Environment
> * your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
> * your Kubernetes cluster version (output of kubectl version):
> * if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

Yes they can. The relationship between them just likes the global rules and routes in Apache APISIX.

**Comment by wnz27** [comment]
> You can actually try it out, they have different priorities

i try it, but dont  take effect. the plugin config not auto merge

**Comment by wnz27** [comment]
> > ### Issue description
> > if i want to 1、define a ApisixPluginConfig use some plugin 2、define a apisixRoute and set same plugin in ApisixPluginConfig with some different param it‘s can work?
> > ### Environment
> > 
> > * your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
> > * your Kubernetes cluster version (output of kubectl version):
> > * if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
> 
> Yes they can. The relationship between them just likes the global rules and routes in Apache APISIX.

but it doesn't take effect
