### ISSUE TITLE
chore: Update GitHub Isssue templates

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1571]
Currently we have created two simple Issue templates

https://github.com/apache/apisix-ingress-controller/tree/master/.github/ISSUE_TEMPLATE

But they are relatively simple, and many times users need to create blank Issues to meet their needs.

I think we can do better by adding some other templates

for example:

* New feature requirements
* Documentation
* Performance issues
* question

**Comment by navendu-pottekkat** [comment]
I can update the issue templates. Will reference the apache/apisix repo: https://github.com/apache/apisix/issues/new/choose

**Comment by tao12345666333** [comment]
Great! But we don't need to link to https://github.com/apache/apisix/discussions
The rest are mostly consistent

**Comment by navendu-pottekkat** [comment]
@tao12345666333 What would a template for reporting performance issues look like? What data do we need from the user?

**Comment by tao12345666333** [comment]
@navendu-pottekkat maybe like this? https://github.com/aertslab/scenicplus/blob/main/.github/ISSUE_TEMPLATE/performance-optimization-request.md?plain=1
