### ISSUE TITLE
request help: call between services with apisix ingress?

### ISSUE THREAD

**Issue by rf-guo** [apache/apisix-ingress-controller#1573]
### Issue description

For example : Service A call domain of service B and flow :

Service A -> domain of service B -> ingress -> services B

Does this work ?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
I don't fully understand what you mean.

But if I understand correctly, it's ok

**Comment by rf-guo** [comment]
> I don't fully understand what you mean.
> 
> But if I understand correctly, it's ok

Thx feedback fist, 
In other words , east-west traffic is support ?

**Comment by tao12345666333** [comment]
yes
