### ISSUE TITLE
feat request: ApisixConsumer CRD add ldap-auth support

### ISSUE THREAD

**Issue by panditha** [apache/apisix-ingress-controller#1574]
### Issue description

Hi,

We are planning to use APISIX in kubernetees and managing all yaml (instead of dashboard) to promote  configuration as a code practice.  We have planned to use ldap authentication for majority of consumers but we realized that current CRD of ApisixConsumer doesn't support ldap-auth and also we don't see any work around other than switching back to dashboard or APIs.

Can you please let us know when it will be available or any workarounds. 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): we use helm charts from API7. (helm repo add apisix https://charts.apiseven.com)
- your Kubernetes cluster version (output of kubectl version): 1.22
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): Not Applicable.

### Minimal test code / Steps to reproduce

  Not Applicable

### Actual result

Not Applicable

### Error log

Not Applicable

### Expected result

ApisixConsumer CRD should support all authentication plugins.

**Comment by tao12345666333** [comment]
Thanks for your report.

We really didn't add that functionality yet.

This is a very simple feature, are you interested in adding it?

Here are some examples for reference:

* https://github.com/apache/apisix-ingress-controller/pull/1035
* https://github.com/apache/apisix-ingress-controller/pull/1009
* https://github.com/apache/apisix-ingress-controller/pull/1011

**Comment by machinly** [comment]
hi, I implemented this in the private version before, and I sorted it out  in the PR  #1588.

**Comment by tao12345666333** [comment]
thanks
