### ISSUE TITLE
docs: add documentation for using APISIX Ingress with Gateway API

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix-ingress-controller#1597]
APISIX Ingress controller supports using Kubernetes Gateway API for configuration. Currently, we don't have any documentation regarding it. We should add:

1. An additional step in the installation guides that mentions how you can install the Gateway API CRDs.
2. Add a similar example on the "Getting started" page.
3. Add tutorials on how you can use the Gateway API to configure APISIX Ingress. Maybe we can merge tutorials together and show three ways to configure APISIX (Ingress, Gateway, APISIX CRDs) in a single document.

**Comment by navendu-pottekkat** [comment]
I can work on this issue. Please update if need to add anymore than what is mention in the issue description.

**Comment by tao12345666333** [comment]
Thanks. SGTM

We also need to mention that APISIX Ingress' support for Gateway API is not yet stable and is currently in the beta stage.
