### ISSUE TITLE
bug: lots of recurring error logs on removal of helm release (deletion of multiple resources in short period of time)

### ISSUE THREAD

**Issue by goblain** [apache/apisix-ingress-controller#1625]
### Issue description

Whenever we perform a large scale removal of resources with removal of our helm releases, we see a significant amount of error logs due to ingress controller trying to configure an ingress which backing resources like services and endpoints no longer exist. On it's own it would be a minor inconvenience, but because of error wrapping as `TranslateError` this is no longer detected by `k8serrors.IsNotFound` in `handleSyncErr` and causes the sync to become rescheduled in the workqueue, causing error logs long after the whole namespace for the problematic ingress being removed.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
- your Kubernetes cluster version (output of kubectl version): 1.24.6

### Minimal test code / Steps to reproduce

test code will be provided in respective PR fixing this issue in a moment

### Actual result

n/a

### Error log

```2023-01-27T18:27:27+08:00	error	translation/translator.go:158	failed to translate ingress backend to upstream	{"error": "endpoints: endpoints \"myservice\" not found", "ingress": "&Ingress{ObjectMeta:{myservice  mynamespace  771a540d-fe9d-46f1-a9cf-40b895f02955 32852296 1 ```

### Expected result

no error logs on proper removal of all ingress related resources

**Comment by tao12345666333** [comment]
Thanks for your report

**Comment by Revolyssup** [comment]
Will be fixed here https://github.com/apache/apisix-ingress-controller/pull/2146
