### ISSUE TITLE
bug: exec failed, "curl" not found in $PATH

### ISSUE THREAD

**Issue by Baoyuantop** [apache/apisix-ingress-controller#1637]
### Issue description

I am using apisix ingress controller according to this document
https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service/

When I got to this point in the execution I found the error
```
kubectl exec -it -n ${namespace of Apache APISIX} ${Pod name of Apache APISIX} -- curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'
```

The errors are as follows:
```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
command terminated with exit code 126
```

After troubleshooting, we found that apisix changed the image to `debian`, which caused the `curl` command to be unavailable, so we may need to update the documentation.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service/

### Actual result

Following the documentation can be successfully executed.

### Error log

```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
command terminated with exit code 126
```

**Comment by tao12345666333** [comment]
We can modify all the examples to enter the Pod of apisix-ingress-controller to operate

**Comment by fengshunli** [comment]
Is the solution to this fix is to install curl command processing in the container? @tao12345666333

**Comment by fengshunli** [comment]
see https://github.com/apache/apisix-ingress-controller/pull/1648 @tao12345666333

**Comment by Baoyuantop** [comment]
Hi @fengshunli, we need to add `curl` in the APISIX docker image, you can refer to https://github.com/apache/apisix-docker, apisix-ingress-controller no need to change.

**Comment by fengshunli** [comment]
Do you need to modify the dockerfile in debian and centos? @Baoyuantop

**Comment by Baoyuantop** [comment]
Just modify the `debian`, cc @tao12345666333

**Comment by Baoyuantop** [comment]
fixed by https://github.com/apache/apisix-docker/pull/419
