### ISSUE TITLE
docs: How to add Basic Auth with Ingress annotations

### ISSUE THREAD

**Issue by hndoss** [apache/apisix-ingress-controller#1639]
### Issue description

We have a general ApisixPluginConfig that is used by all of our ingresses. A particular ingress needs to have basic auth and I think a very convenient way would be to use annotations as nginx allows. I don't see any annotation in [this list](https://apisix.apache.org/docs/ingress-controller/concepts/annotations/) that can help me with this.

```
nginx.ingress.kubernetes.io/auth-secret: my-secret
nginx.ingress.kubernetes.io/auth-type: basic
```

In this way, I can apply the configuration I need to this ingress that is different from all but needs the general ApisixPluginConfig that all ingresses use.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
/ingress-apisix # /ingress-apisix/apisix-ingress-controller version --long
Version: 1.6.0
Git SHA: no-git-module
Go Version: go1.19.4
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

- your Kubernetes cluster version (output of kubectl version):
```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.21.14-gke.3000
```

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
you can refer to this one https://github.com/apache/apisix-ingress-controller/blob/75030566f324af508febd1cfaa65320565c938ec/test/e2e/suite-annotations/authorization.go#L185-L186

**Comment by tao12345666333** [comment]
ref https://github.com/apache/apisix-ingress-controller/issues/782
