### ISSUE TITLE
How To Set Apisix Default IngressClass

### ISSUE THREAD

**Issue by liyongxian** [apache/apisix-ingress-controller#1647]
### Issue description

How to set apisix ingress to be default ingress class.Thanks.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
You can directly create a default IngressClass

ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class

**Comment by liyongxian** [comment]
@tao12345666333  What is  controller of APISIX in IngressClass ?Thanks.
![image](https://user-images.githubusercontent.com/18571576/216949376-9f24befc-cef6-40f3-89f2-beca7c21675b.png)
