### ISSUE TITLE
 default IngressClass Controller 

### ISSUE THREAD

**Issue by liyongxian** [apache/apisix-ingress-controller#1653]
You can directly create a default IngressClass

ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/issues/1647#issuecomment-1418796955_

**Comment by liyongxian** [comment]
![image](https://user-images.githubusercontent.com/18571576/216949796-58ac3f31-96b0-4c4e-b671-9c4e371cb4ba.png)

**Comment by tao12345666333** [comment]
apisix.apache.org/apisix-ingress

**Comment by liyongxian** [comment]
Thanks for your reply. But It does not work.
![image](https://user-images.githubusercontent.com/18571576/217143652-bc79a297-6b2c-4659-8886-8514d6d959bc.png)

**Comment by tao12345666333** [comment]
Please describe more clearly.

Do you mean Ingress controller or Ingress Object?
What are the specific steps

**Comment by wszgrcy** [comment]
终于把apisix搞上了....说下遇到的坑
首先是helm安装,遇到一些镜像拉不下来问题(国内通病...没啥可说的)
然后就是拉下来之后因为默认是NodePort所以要修改LoadBalancer...这个也还算比较明显
最后就是没有这个ingressclass.因为之前用nginx/traefik,他们默认部署成功后会添加一个Ingressclass然后直接切换就ok了.
但是apisix是通过注解`kubernetes.io/ingress.class:apisix`(不知道是不是常量),然后到dashboard中配置.
> 当然也可以直接手动加路由
> 刚开始打开dashboard的时候还以为只能手动输入.....
我第一次搞的时候,差点怀疑人生.怎么安装完死活没有`ingressclass`.还以为配置有问题,不断修改.(虽然我知道有dashboard,但是以为是配置完再看的)
后来看了n多文章,都没提到ingressclass问题,才觉得可能出现问题了,最后发现用的真是注解(虽然之前我也看到了注解),但是一看有`ingress.class`就下意识去找`IngressClass`资源,发现没有,就以为是这一步错了.....
