### ISSUE TITLE
Mutual TLS Authentication ， CN cannot be specified

### ISSUE THREAD

**Issue by wangyp0701** [apache/apisix-ingress-controller#1658]
After configuring the ca certificate, you can access it, but you cannot control the required CN. Now all the issued ca certificates can be authenticated successfully.

https://apisix.apache.org/docs/ingress-controller/references/apisix_tls_v2/     No parameter to set CN

![1675662392741](https://user-images.githubusercontent.com/33682005/216893169-b545918a-8c5f-4a1a-b68b-51ad241de134.png)

![1675662193240](https://user-images.githubusercontent.com/33682005/216892729-49dcad87-524f-474a-b84c-29c15d0f0d8c.png)
![1675662218650](https://user-images.githubusercontent.com/33682005/216892790-c479fb37-22c2-408c-8d2b-d39f75a86119.png)

What is the way to realize it? According to CN

_Originally posted by @wangyp0701 in https://github.com/apache/apisix/issues/8474#issuecomment-1418550432_

**Comment by tao12345666333** [comment]
The hosts filed.
