### ISSUE TITLE
feat: missing pass_host from ApisixUpstream CRD

### ISSUE THREAD

**Issue by ohayak** [apache/apisix-ingress-controller#1661]
### Description

Hello 
According to Upstream api docs https://apisix.apache.org/docs/apisix/2.15/admin-api/#request-body-parameters-3 we can edit the `pass_host` parameter, unfortunately this parameter is not defined in the CRD, is there any particular reason to not include it ?

Regards,

**Comment by tao12345666333** [comment]
Thanks for your suggestion, just because we haven't implemented it yet.

I have not received related feature requests or use cases before.

Can you describe your scenario? Or just want to align the functionality?

**Comment by oyiadin** [comment]
I need it too. Some of our upstreams need to recognize which "virtual host" is hitted by reading requests' hosts.

**Comment by Aaron199** [comment]
I need this functionality where, when going through an HTTPS proxy to retrieve data from other services such as OSS or OBS, it is not possible to retrieve the data without setting the host header.

**Comment by tao12345666333** [comment]
Since we are currently focusing on the v1.7 release, there is no bandwidth to handle this requirement. Welcome to submit PR

**Comment by adam-huganir** [comment]
This feature would also help with the use case of when apisix is the external gateway (as it is in our case) but has to go through another internal gateway, for instance with Knative services where it needs the internal hostname to be directed to the right endpoints. 

We have a workaround by setting them in the admin api, but i wanted to add a comment with another use case for when someone does have the bandwidth to take a stab at it.  The behavior we would want to recreate here is to have an upstream crd fields to replicate this patch request in the admin api: `'{"pass_host":"rewrite", "upstream_host":"<internal hostname here>"}'`

**Comment by ikatlinsky** [comment]
@tao12345666333 please, assign issue to me

**Comment by tao12345666333** [comment]
#1889 has been merged, I will close this one.
