### ISSUE TITLE
consummate docs

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#167]
Here is a basic docs plan

## Introduction (README)
* features
* project status
* links to other sections

## Architecture
* Overview with a picture(each components)
* Resource translation (diagram + paragraphs)

## Concepts of CRDs
* ApisixRoute
* ApisixUpstream
* ApisixService
* ApisixSSL

## Deployment
* ACK, GKE, AKS, minikube, kind, etc
* Install by Helm chart
* Install by Kustomize
* Install Dashboard (if any)
* Install Prometheus, Grafana to scrape ingress controller’s metrics

## Development
* Steps like build, build-image, run units and e2e tests in local env.

## Guides
* Authentication between controller (control plane) and apisix (data plane) with admin key or mTLS.
* Multiple tenants / clusters
* Scale controller pods for high availability.
* ...

## Reference
* Cli options
* Configueration files
* CRDs

**Comment by gxthrj** [comment]
Great! I will add some articles on architecture and design with more diagrams.

**Comment by gxthrj** [comment]
Close this issue, feel free to reopen.
