### ISSUE TITLE
request help: ApiSixRoute's backends can config outer network host?

### ISSUE THREAD

**Issue by wnz27** [apache/apisix-ingress-controller#1675]
### Issue description

in ： 
apiVersion: apisix.apache.org/v2
kind: ApisixRoute

set backends service name with outer service host
the crd created but route don‘t tack effect

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Fabriceli** [comment]
Maybe this tutorial [Using External Services In ApisixUpstream](https://apisix.apache.org/docs/ingress-controller/tutorials/external-service/) can help you

**Comment by tao12345666333** [comment]
As @Fabriceli  said, you can use the `externalNodes`

**Comment by wnz27** [comment]
> As @Fabriceli said, you can use the `externalNodes`

ok thanks, i try it next monday; and response u ~

**Comment by wnz27** [comment]
> Maybe this tutorial [Using External Services In ApisixUpstream](https://apisix.apache.org/docs/ingress-controller/tutorials/external-service/) can help you

ok thanks, i try it next monday; and response u ~

**Comment by wnz27** [comment]
have no chance  to attempt hhhhhh
