### ISSUE TITLE
docs: https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/tutorials/the-hard-way.md

### ISSUE THREAD

**Issue by ns-xlz** [apache/apisix-ingress-controller#1686]
### Current State

  there is some bugs in the tutorials of hard way. 
  A label is specified in the configuration file: apisix.ingress=watching，but in the section of 'Deploying httpbin', there is no this label for namespace demo.
  It took me an afternoon to troubleshoot this problem...

### Desired State

Please improve the document to avoid others stepping on the pit

**Comment by tao12345666333** [comment]
@lingsamuel  PTAL, Thanks
