### ISSUE TITLE
bug: the latest version of apisix-ingress-controller on pkg.go.dev is v1.4.1

### ISSUE THREAD

**Issue by machinly** [apache/apisix-ingress-controller#1697]
### Current Behavior

The latest version of apisix-ingress-controller on pkg.go.dev is v1.4.0, which is not newest version.

### Expected Behavior

I hope the version on pkg.go.dev is in sync with the source code on github so that the latest package can be imported.

### Steps to Reproduce

version list on pkg.go.dev

https://pkg.go.dev/github.com/apache/apisix-ingress-controller?tab=versions

### Environment

develop environment.

**Comment by tao12345666333** [comment]
Thanks! let me fix it.

**Comment by tao12345666333** [comment]
https://pkg.go.dev/github.com/apache/apisix-ingress-controller@v1.7.0

I have fixed this issue. The latest version is v1.7.0, thanks for your report.
