### ISSUE TITLE
request help: Configured route can't be deleted truely

### ISSUE THREAD

**Issue by GloryAndDream** [apache/apisix-ingress-controller#1699]
### Issue description

![image](https://user-images.githubusercontent.com/18462722/222326976-8dfdc120-0dbc-41fb-8091-55b9be962fe3.png)

I configured this route, but when I deleted it, in a few minites it shows up again! I tried to click offline first , then delete it , same issue happended!

I tried to reinstall apisix etcd, even use helm to reinstall apisix, same issue! what is the reason?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6
- your Kubernetes cluster version (output of kubectl version):  1.24

**Comment by GloryAndDream** [comment]
![image](https://user-images.githubusercontent.com/18462722/222327551-b1fd74c0-5495-4c19-94ef-8f3817122160.png)
the log of apisix-ingress-controller shows that keeps loadingg this route

**Comment by tao12345666333** [comment]
**If you are using the APISIX Ingress controller, please only use it to manage your routes.**
All configurations come from the declarative configuration in Kubernetes,
Modifications made by any other means will be corrected by the controller as the declarative configuration in Kubernetes.

**Comment by GloryAndDream** [comment]
> **If you are using the APISIX Ingress controller, please only use it to manage your routes.** All configurations come from the declarative configuration in Kubernetes, Modifications made by any other means will be corrected by the controller as the declarative configuration in Kubernetes.

OK, but how can I delete routes via APISIX Ingress controller?

**Comment by tao12345666333** [comment]
you can just delete ApisixRoute resource in Kubernetes.

**Comment by GloryAndDream** [comment]
final solution: 
`kubectl delete -f xxx.xml`
