### ISSUE TITLE
CI: Add test case using new default ingress-class value `apisix-and-all` for Ingress Resources.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1710]
This PR is good overall. 

I hope that some test cases using `apisix-and-all` can be added to the test cases of IngressClass to ensure that there will be no break change.

Of course, it can also be implemented in subsequent PRs, without blocking the merging of this PR

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/issues/1674#issuecomment-1453464349_

**Comment by afzal442** [comment]
Hi @tao12345666333 you can close it, I think.

**Comment by tao12345666333** [comment]
#1726 has been merged. I will close this one
