### ISSUE TITLE
bug: ingress-apisix dashboard The ssl obtained from APISIXTLS is incorrectly displayed

### ISSUE THREAD

**Issue by charles-liming** [apache/apisix-ingress-controller#1713]
### Current Behavior

I used apisixTLS + secret to manage my https certificate. Then I logged into the dashboard and found that the expiration time of my SNI showed invilad date.It doesn't affect my business, but I think it's an important function. It should be displayed correctly.

### Expected Behavior

The dashboard should normally display the expiration time of the SNI

### Steps to Reproduce

1、install repo and fetch localhost 
helm repo add apisix https://charts.apiseven.com
helm repo add bitnami https://charts.bitnami.com/bitnami
helm fetch apisix/apisix
tar -xvf apisix-0.7.2.tgz
mkdir -p apisix/ci

2、Define a value.yaml for helm chart as follows
# ci/prod.yaml
apisix:
  enabled: true
gateway:
  type: NodePort
  externalTrafficPolicy: Cluster
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: true  # 启用 tls
    servicePort: 443
    containerPort: 9443

etcd:
  enabled: true  
  replicaCount: 3  

dashboard:
  enabled: true

ingress-controller:
  enabled: true
  config:
    apisix:
      serviceName: apisix-admin
      serviceNamespace: ingress-apisix  
3、install chart
helm upgrade --install apisix ./apisix -f ./apisix/ci/prod.yaml -n apisix
4、 create tls secret and apisixTLS
5、Log in to the dashboard and check whether the sni display is normal

### Environment

- APISIX version (run `apisix version`): ingress-apisix 1.6 
- Operating system (run `uname -a`):  Linux shxt-test-cpu-public-gc-inside-02-1c2c 3.10.0-862.14.1.5.h520.eulerosv2r7.x86_64 apache/apisix#1 SMP Wed Nov 25 18:33:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  This version follows the ingress-apisix 1.6 version
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): This version follows the ingress-apisix 1.6 version
- APISIX Dashboard version, if relevant: This version follows the ingress-apisix 1.6 version
- Plugin runner version, for issues related to plugin runners: This version follows the ingress-apisix 1.6 version
- LuaRocks version, for installation issues (run `luarocks --version`): This version follows the ingress-apisix 1.6 version

**Comment by tao12345666333** [comment]
Please use APISIX's admin API to check the SSL resource and verify its information.

If the resource information you see through the Admin API is in line with your expectations, then there may be a problem with the dashboard display.

The APISIX Ingress controller does not modify any data in your ApisixTls resource.

**Comment by charles-liming** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/34326414/223403896-252eca31-75f8-40cd-b559-cf2239115d6a.png">

**Comment by charles-liming** [comment]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/34326414/223405782-4c9d6393-1ea0-4de4-8c53-e7270bce2d2b.png">

**Comment by charles-liming** [comment]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/34326414/223406398-4f9298ed-2dce-4ac3-b31d-c035781205dd.png">

**Comment by charles-liming** [comment]
> Please use APISIX's admin API to check the SSL resource and verify its information.
> 
> 请使用 APISIX 的管理 API 检查 SSL 资源并验证其信息。
> 
> If the resource information you see through the Admin API is in line with your expectations, then there may be a problem with the dashboard display.
> 
> 如果您通过管理 API 看到的资源信息与您的预期一致，那么仪表板显示可能有问题。
> 
> The APISIX Ingress controller does not modify any data in your ApisixTls resource.
> 
> APISIXInress 控制器不修改 ApisixTls 资源中的任何数据。

![image](https://user-images.githubusercontent.com/34326414/223406586-93c68135-b292-4be3-9237-7e1107810112.png)

**Comment by tao12345666333** [comment]
You should get the data of the certificate, read its content with a tool like openssl, and confirm its correctness.

**Comment by charles-liming** [comment]
kubectl -n ingress-apisix exec -it apisix-79d97b7fff-nfdql -- curl -H  'X-API-KEY:  xx 'http://127.0.0.1:9180/apisix/admin/ssls
Is the output data the certificate or encrypted data that needs to be decoded first

**Comment by charles-liming** [comment]
Since it is normal for me to get https, I judge it is normal for me to get ssl, so what is the logic for dashboard to get ssl information?

**Comment by tao12345666333** [comment]
I don't know.  
If you confirm that this has nothing to do with ingress-controller, then I think you can close this issue.  

Then submit an issue on the dashboard, or check its code.
