### ISSUE TITLE
docs: Add a spec for `prefer_name` field in ApisixClusterConfig/v2

### ISSUE THREAD

**Issue by yujinchoi-94** [apache/apisix-ingress-controller#1736]
### Current State

Spec for a `prefer_name` field is missing

### Desired State

Spec for a `prefer_name` field should be added.
The description would be like this:
> When set to true, prints Route/Service name instead of ID in Prometheus metric.

**Comment by yujinchoi-94** [comment]
related https://github.com/apache/apisix-ingress-controller/issues/1516

**Comment by tao12345666333** [comment]
Thanks for the report, would you mind submitting a PR to add it?

**Comment by Neilblaze** [comment]
@tao12345666333 can you please assign me this? 😄

**Comment by tao12345666333** [comment]
Sure! Assigned

**Comment by Neilblaze** [comment]
Sorry, I got caught up with school work & missed it. I'm unassigning myself. Apologies for any inconvenience caused.
