### ISSUE TITLE
docs: ApisixUpstream reference need to be updated

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1740]
@tao12345666333 
Hi,
`discovery` related fields seem missing in [ApisixUpstream reference](https://apisix.apache.org/docs/ingress-controller/references/apisix_upstream/)
It would be good if a spec for a `discovery` related fields are added.

__Originally posted by @yujinchoi-94 in https://github.com/apache/apisix-ingress-controller/issues/948#issuecomment-1478807186__

**Comment by Neilblaze** [comment]
@tao12345666333 is this up for grabs?

**Comment by tao12345666333** [comment]
no one pick up this.

**Comment by AuruTus** [comment]
@tao12345666333 hi, could assign this to me? Will fix it later.

**Comment by Neilblaze** [comment]
@AuruTus sure, go for it!

**Comment by tao12345666333** [comment]
assigned, thanks
