### ISSUE TITLE
request help:   How ApisixRoute implements redis clustering, proxy access

### ISSUE THREAD

**Issue by wwwzhouhui** [apache/apisix-ingress-controller#1749]
### Issue description

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: redis-cluster-route
  namespace: ingress-apisix
spec:
  stream:
    - name: redis-cluster-route20230327
      protocol: TCP
      match:
        ingressPort: 9101
      backend:
        serviceName: redis-test327
        servicePort: 6379

 
The above code can achieve a single redis access, how to achieve Redis cluster agent access

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
```
  ``` Please use the code block to format your configurations. ```
```

**Comment by tao12345666333** [comment]
APISIX Ingress controller uses APISIX as the data plane, and all requests are proxied by APISIX. Currently, when APISIX proxies Redis using stream, it is only a forwarding proxy. You need a smart client to automatically handle ask/moved.

**Comment by tao12345666333** [comment]
Also FYI: https://apisix.apache.org/docs/apisix/xrpc/  APISIX has the `xRPC` protocol support.

**Comment by wwwzhouhui** [comment]
我们用的是apache.apisix@apisix-ingress-controller 官方的https://apisix.apache.org/zh/docs/ingress-controller/references/apisix_route_v2/ 中提到
![image](https://user-images.githubusercontent.com/355799/228175325-85543fb1-e5be-4e14-90ab-ac969f7459e6.png) 支持tcp和 udp 没有提到protocol：redis，不知道是不是还没支持还是后续支持

**Comment by tao12345666333** [comment]
> it is only a forwarding proxy. You need a smart client to automatically handle ask/moved.
