### ISSUE TITLE
bug: apisix restarts, ingress controller unavailable

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#1760]
### Current Behavior

The following scenario:
1 * apisix gateway instance. 
2 * ingress controller instances.

Apisix gateway restart occurred,   the health check interface of leader ingress controller  throws 500 error code.
interface: /apisix/healthz
500 error msg: {"status":"timed out waiting for the condition"}
This interface keeps reporting errors, but another candidate ingress controller interface is normal.

### Expected Behavior

It should be able to recover automatically after reporting an error for a period of time.
At present, it can only be solved by restarting the ingress controller

### Error Logs

 curl http://10.227.55.111:8080/apisix/healthz
{"status":"timed out waiting for the condition"}

### Steps to Reproduce

resource preparation:
1 * apisix gateway instance. 
2 * ingress controller instances.

step1: restart apisix gateway.
step2: Observe the leader ingress controller status and logs.

### Environment

- APISIX Ingress controller version: v1.5.0
- Kubernetes cluster version (run `kubectl version`): v1.22

**Comment by basefas** [comment]
I want to work on this issue please assign this to me.

**Comment by tao12345666333** [comment]
Assigned, thanks
