### ISSUE TITLE
docs: describe how to generate secret from cert file

### ISSUE THREAD

**Issue by kingluo** [apache/apisix-ingress-controller#1767]
### Current State

https://apisix.apache.org/zh/docs/ingress-controller/tutorials/mtls/#protect-the-route-using-ssl

It lacks descriptions:
* what's the meaning and format of the secret
* how to generate a secret value from the cert file

### Desired State

The secret contains the base64 value and can be generated via the below commands:

```bash
base64 -w0 foo.crt # for cert
base64 -w0 foo.key # for priv key
```

**Comment by ps-19** [comment]
I wish to work on this issue please assign this to me.

**Comment by tao12345666333** [comment]
assigned

**Comment by ps-19** [comment]
https://github.com/ps-19/apisix-ingress-controller/blob/docs/docs/en/latest/tutorials/mtls.md#protecting-the-route-with-ssl

**Comment by ps-19** [comment]
any suggestions before PR.

**Comment by tao12345666333** [comment]
#1769 has been merged. I will close this one.
