### ISSUE TITLE
bug: malformed URL creation for schemaClient

### ISSUE THREAD

**Issue by Revolyssup** [apache/apisix-ingress-controller#1771]
### Current Behavior

The URL generated for schema here has `/` already in the suffix https://github.com/apache/apisix-ingress-controller/blob/97f9ef904b3e1e0d66e6fddae59712e7ec849fca/pkg/apisix/schema.go#L36. 

Another `/` gets added before making the GET request here: https://github.com/apache/apisix-ingress-controller/blob/97f9ef904b3e1e0d66e6fddae59712e7ec849fca/pkg/apisix/schema.go#L66

### Expected Behavior

The extra `/` suffixed to the URL in new function should be removed. 

### Error Logs

![Screenshot 2023-04-09 at 5 55 32 PM](https://user-images.githubusercontent.com/43276904/230772880-5bd82ff9-5d03-427e-b6ce-73ecfbd1ae5a.png)

### Steps to Reproduce

Run `make build` and run the controller locally.

### Environment

- APISIX Ingress controller version 
Version: 1.6.0
Git SHA: 97f9ef9
Go Version: go1.19.2
Building OS/Arch: darwin/arm64
Running OS/Arch: darwin/arm64
- Kubernetes cluster version v1.25.2
- OS version if running APISIX Ingress controller in a bare-metal environment 
Darwin Kernel Version 21.4.0

**Comment by Revolyssup** [comment]
Can I take this up, given that the issue is small and fix is straightforward?

**Comment by tao12345666333** [comment]
#1772 has been merged, I will close this one, Thanks
