### ISSUE TITLE
request help: native Kubernetes ingress  yaml  add  timeout config

### ISSUE THREAD

**Issue by wangjia5693** [apache/apisix-ingress-controller#1783]
### Issue description

![image](https://user-images.githubusercontent.com/8287270/231105562-b9dbe423-b63f-425e-aae4-cd7af6a2ae38.png)

how to change default  timeout and  retry config in native Kubernetes ingress  yaml 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Revolyssup** [comment]
@tao12345666333 Can we use annotation here to support this? Something like `<Prefix>.retry.<ServiceName>: 3` 
where `<ServiceName>` is the backend.service corresponding to an upstream.

**Comment by tao12345666333** [comment]
SGTM

But I think if we use `<Prefix>.time.read` or `<Prefix>.retry` would be better. 
Differentiating between different backends may be more flexible, but it is not intuitive.

**Comment by Revolyssup** [comment]
> SGTM
> 
> But I think if we use `<Prefix>.time.read` or `<Prefix>.retry` would be better. Differentiating between different backends may be more flexible, but it is not intuitive.

@tao12345666333 So the configuration will be applied to all backends in the ingress uniformly?

**Comment by tao12345666333** [comment]
Yes, this is more realistic scenario

**Comment by Revolyssup** [comment]
> Yes, this is more realistic scenario

Okay thanks, I will take this item.
