### ISSUE TITLE
chore: update Go tool chain to v1.20

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#1786]
Thanks for your contribution.

I think we should upgrade our Go tool chain to v1.20 first.

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/issues/1750#issuecomment-1491272173_

**Comment by WVenus** [comment]
could you assign to me?

**Comment by tao12345666333** [comment]
Sure! Assigned, thanks.
