### ISSUE TITLE
bug: ssl synchronization is pathlogical

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#179]
### Issue description

The logic for synchronizing ApisixSSL is pathlogical, we don't have a name/fullname field to index the SSL object in cache, so as to we cannot get its id in APISIX, the Update/Delete will failure.

### Environment

* your apisix-ingress-controller version: master branch
* your Kubernetes cluster version: have nothing to do with the Kubernetes cluster version
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### What's the actual result? (including assertion message & call stack if applicable)

The Update/Delete of SSL should be successful.

### What's the expected result?

The apisix-ingress-controller crashes since the ssl.ID is nil.

**Comment by gxthrj** [comment]
Thanks, It is a bug, I will fix it.
