### ISSUE TITLE
CI: Version mismatch between Ginkgo CLI and imported Ginkgo package in e2e test

### ISSUE THREAD

**Issue by ps-19** [apache/apisix-ingress-controller#1799]
### Current Behavior

Description:
When running e2e tests locally, Ginkgo has detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages. The Ginkgo CLI version is 2.9.0, but the imported Ginkgo package version is 2.9.2. This may result in errors, including flag parsing errors, and could cause issues during test execution.

### Expected Behavior

Ginkgo CLI and imported Ginkgo package versions should match to avoid any compatibility issues during test execution.

There is a version mismatch between the Ginkgo CLI and the imported Ginkgo package, which may cause errors during test execution.

### Error Logs

Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
  Ginkgo CLI Version:
    2.9.0
  Mismatched package versions found:
    2.9.2 used by e2e

  Ginkgo will continue to attempt to run but you may see errors (including flag
  parsing errors) and should either update your go.mod or your version of the
  Ginkgo CLI to match.

  To install the matching version of the CLI run
    go install github.com/onsi/ginkgo/v2/ginkgo
  from a path that contains a go.mod file.  Alternatively you can use
    go run github.com/onsi/ginkgo/v2/ginkgo
  from a path that contains a go.mod file to invoke the matching version of the
  Ginkgo CLI.

  If you are attempting to test multiple packages that each have a different
  version of the Ginkgo library with a single Ginkgo CLI that is currently
  unsupported.
  
Running Suite: ingress-apisix e2e test suites - /home/ubuntu/Api7/Runnning_purpose/apisix-ingress-controller/test/e2e
=====================================================================================================================
Random Seed: 1681794225 - will randomize all specs

### Steps to Reproduce

Steps to Reproduce:

1. Run e2e tests locally using Ginkgo.
2. Observe the output on the terminal.

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by WVenus** [comment]
could you assign to me?

**Comment by tao12345666333** [comment]
Assigned, thanks
