### ISSUE TITLE
request help: How to use multiple plugins configs

### ISSUE THREAD

**Issue by hndoss** [apache/apisix-ingress-controller#1811]
### Issue description

We have an ApisixPluginConfig with general configuration for all the ingress resources in our cluster, but some of them have specific configuration. Is it possible to use two or more plugin configs with `k8s.apisix.apache.org/plugin-config-name` annotation?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
/ingress-apisix # /ingress-apisix/apisix-ingress-controller version --long
Version: 1.6.0
Git SHA: no-git-module
Go Version: go1.19.4
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

- your Kubernetes cluster version (output of kubectl version):
```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.21.14-gke.3000
```

**Comment by acuteaura** [comment]
I think this is worth exploring, I can think of several use cases where reusing a chain of plugins provided by a platform team is desirable. For instance, we have a recurring need for a specific set of authz/authn plugins and would like to centrally manage and update this (maybe even outside the namespace the route is in, so we do not need to deduplicate and can prevent developers from editing via RBAC). But teams also need their own set of plugins for their specific use-cases.

maybe the ingress controller can compose those plugins into the apisix object per route, allowing inline plugins and (multiple) external CRD configs? Would need to figure out how to order when mixing and invalidation would be a pain...

**Comment by tao12345666333** [comment]
Can using ApisixPluginConfig meet this requirement?

**Comment by acuteaura** [comment]
I don't think so. Since you want developers to be able to extend the plugin chain, but still be able to update the "platform managed" part without reconciling forks. Maybe we could render a PluginConfig out of a list of other PluginConfigs via annotation within our stack, but that feels like a dirty hack.
