### ISSUE TITLE
bug:  failed to record status change for ApisixUpstream

### ISSUE THREAD

**Issue by liuwenzhi0318** [apache/apisix-ingress-controller#1815]
### Current Behavior

![image](https://user-images.githubusercontent.com/37536326/234527895-5bad09c7-1d63-4208-9ea1-522d4a2cf0e2.png)

### Steps to Reproduce

1、 uninstall service
2、 uninstall ApisixUpstream
3、etcd database not ApisixUpstream

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by tao12345666333** [comment]
Please provide version information.

**Comment by liuwenzhi0318** [comment]
apisix-ingress-controller:1.6.0         apisix:3.1.0-debian

**Comment by liuwenzhi0318** [comment]
、






















、

**Comment by tao12345666333** [comment]
Can you try building an image test using the master branch?
