### ISSUE TITLE
feat: As a user, I want to add unit tests for validation.go.

### ISSUE THREAD

**Issue by khareyash05** [apache/apisix-ingress-controller#1821]
### Description

Since the coverage report of `pkg/api/validation/apisix_plugin_config.go` gives 0% coverage [https://app.codecov.io/gh/apache/apisix-ingress-controller/tree/master/pkg/api/validation](https://app.codecov.io/gh/apache/apisix-ingress-controller/tree/master/pkg/api/validation) . I would like to add unit tests for the file

**Comment by Gallardot** [comment]
Thank you for your contribution and feel free to submit PR

**Comment by khareyash05** [comment]
@Gallardot kindly review
