### ISSUE TITLE
bug: Cron CI judgment logic problem

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix-ingress-controller#1849]
### Current Behavior

error code line [link](https://github.com/apache/apisix-ingress-controller/blob/e5db08a3fd16d0a56d218b5d054efbe53152c5b6/.github/workflows/e2e-test-ci-v2-cron-dev.yml#LL41C47-L41C49)

The cron CI should not use the logical OR condition, as it can cause the CI to run every time. Instead, it should use the logical AND condition.

### Expected Behavior

This is a timed CI and should not be run every CI.

### Steps to Reproduce

1. Run the CI And u will got this error.

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by tao12345666333** [comment]
Thanks!

**Comment by tao12345666333** [comment]
#1850 has been merged, I will close this one, thanks
