### ISSUE TITLE
The Ginkgo tool is used in the e2e test script, but the pre-installation check is not performed in the makefile script

### ISSUE THREAD

**Issue by liodo198592** [apache/apisix-ingress-controller#186]
### Issue description
The Ginkgo tool is used in the e2e test script, but the pre-installation check is not performed in the makefile script.

![image](https://user-images.githubusercontent.com/12790469/105144797-bbae7180-5b38-11eb-9557-2fe894db8a29.png)

**Comment by gxthrj** [comment]
Thanks @liodo198592 , There needs to be a check on the ginkgo command.

**Comment by gxthrj** [comment]
Is anyone interested in helping fix this issue?

**Comment by cao19881125** [comment]
let me have a try
