### ISSUE TITLE
feat: get white-list/black-list from configmap or a crd resource

### ISSUE THREAD

**Issue by wuzhuoquan** [apache/apisix-ingress-controller#1877]
### Description

I would like to use the ingressroute to define our service, but our service is only for some clients, and every client has many different public IPs, if I set the white-list in the annotations, it will be a disaster for maintain the ingress!

so, I think ingress-controller get the white-list from configmap or a crd resouce, and set in the annotation like 
```
k8s.apisix.apache.org/whitelist-source-range: configmap/white-list
```
that would be more friendly

**Comment by tao12345666333** [comment]
I think you can just use the `ip-restriction` plugin.

You can define it through the ApisixPluginConfig resource, and then refer to it in the Ingress resource through plugin-config-name.

**Comment by wuzhuoquan** [comment]
> I think you can just use the `ip-restriction` plugin.
> 
> You can define it through the ApisixPluginConfig resource, and then refer to it in the Ingress resource through plugin-config-name.

thank you，I will try it.
