### ISSUE TITLE
bug: ingress controller does not register ingressClass and also does not watch Ingress objects

### ISSUE THREAD

**Issue by sebschlue** [apache/apisix-ingress-controller#1880]
### Current Behavior

I have deployed apisix ingress controller from latest Helm chart 2.0.0 and am playing with it for a few days now. CR objects like apisixRoute work fine but Ingress objects don't work.

I noticed that "kubectl get ingressclass" does not list apisix as an ingress class.

I also noticed that Ingress objects with spec: ingressClassName: apisix do not work.

namespace_selector is set to "" so I believe it should work for all namespaces.

I have checked possible missing helm chart settings for both apisix/apisix chart as well as apisix/apisix-ingress-controller chart but did not find any setting that would relate specifically to the ability to support Ingress objects.

Also, the docs do not list any special requirements: https://apisix.apache.org/docs/ingress-controller/tutorials/proxy-the-httpbin-service-with-ingress/

I am sorry that I cannot offer any specific information as there are no error messages whatsover, it just does not work at all.

Some information regarding my environment: k8s is AWS EKS 1.24, helm is 3.10.3

### Expected Behavior

Ingress objects should be "watched" and acted upon by apisix ingress controller if they specify ingressClassName apisix

### Error Logs

```
error   ingress/ingress.go:472  failed to get APISIX gateway external IPs       {"error": "resource name may not be empty"}
```

### Steps to Reproduce

Install APISIX ingress controller via Helm chart.

Create Ingress object with ingressClassName apisix

### Environment

chart-version: apisix/apix 2.0.0 with app-version 3.3.0 installs deployment- and statefulset-objects using the following container images:

apache/apisix-ingress-controller:1.6.0
apache/apisix:3.3.0-debian
bitnami/etcd:3.5.7-debian-11-r14

helm chart is deployed at a AWS EKS 1.24 cluster.

**Comment by Revolyssup** [comment]
Assign this to me please

**Comment by Revolyssup** [comment]
@sebschlue APISIX ingress controller currently doesn't deploy the IngressClass CR so you won't see that in the output of `kubectl get ingress`. By default, Ingress doesn't work cross-namespace and it will forward traffic to services in the same namespace in which `Ingress` resource is deployed. For cross namespace, use the annotation `k8s.apisix.apache.org/svc-namespace:<namespace>`.

Can you provide the `Ingress` configuration as well as the output of `kubectl get all -A`

**Comment by sebschlue** [comment]
Now I get an error message when creating an Ingress object with spec: ingressClassName: apisix

```
error   ingress/ingress.go:472  failed to get APISIX gateway external IPs       {"error": "resource name may not be empty"}
```

**Comment by sebschlue** [comment]
But Ingress object does not work --> external address is empty.

```
$ kubectl get ingress -A
NAMESPACE      NAME       CLASS    HOSTS                                             ADDRESS                                                                      PORTS
foo      foo    nginx    foo.tld       xxx.eu-central-1.elb.amazonaws.com   80
bar      bar     apisix   bar.tld                                            80
```

**Comment by Revolyssup** [comment]
@sebschlue Can you provide the `Ingress` CR configuration once?

**Comment by sebschlue** [comment]
This is the ingress object:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bar
  namespace: bar
spec:
  ingressClassName: apisix
  rules:
  - host: bar.tld
    http:
      paths:
      - backend:
          service:
            name: bar-service
            port:
              number: 80
        path: /
        pathType: Prefix
```

**Comment by tao12345666333** [comment]
please refer to https://github.com/apache/apisix-ingress-controller/blob/e809cfbaaad6f6c3cbd23f5ec8e93bc1d87f543d/conf/config-default.yaml#L40
