### ISSUE TITLE
request help:  failed to list *v2.ApisixTls: the server could not find the requested resource （helm install）

### ISSUE THREAD

**Issue by wwwsky86** [apache/apisix-ingress-controller#1892]
### Issue description

![image](https://github.com/apache/apisix-ingress-controller/assets/10069198/be225b12-5a80-4d65-8ab8-f1424a746d45)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
what's your kubernetes version?

**Comment by wwwsky86** [comment]
> what's your kubernetes version?

v1.20.5

**Comment by DarkEngineer** [comment]
I have this problem too.
App Version apache/apisix-ingress-controller:1.6.0
Kubernetes Version v1.27.4
At kubernetes at Custom Resource Definitions panel if I want to choose my created dashboard-route ApisixRoute object it shows message: "the server could not find the requested resource (get apisixroutes.apisix.apache.org dashboard-route)"
ApisixRoute object was created with apiVersion: apisix.apache.org/v2
![obraz](https://github.com/apache/apisix-ingress-controller/assets/3199618/7e7cb37f-d9a1-465b-a264-dfd276f089e8)
