### ISSUE TITLE
request help: encounter problem in setting up a ingress controller

### ISSUE THREAD

**Issue by pkking** [apache/apisix-ingress-controller#1894]
### Issue description

Hi, i have setup a kubernetes cluster using `kind` and here's [my config](https://github.com/pkking/homelab/blob/main/kind/kind-config.yaml)

To test my kind cluster, i run: 
```
$ kubectl apply -f https://raw.githubusercontent.com/pkking/homelab/main/ingress/nginx-deploy.yaml
$ kubectl apply -f https://raw.githubusercontent.com/pkking/homelab/main/ingress/nginx.yaml
```
and then `curl -v localhost -H "Host: local.httpbin.org" ` will return the `httpbin` page:
```
$ kubectl get ingress
NAME                 CLASS    HOSTS               ADDRESS     PORTS   AGE                                                                                                                                                                  
httpserver-ingress   <none>   local.httpbin.org   localhost   80      63s    
```

But then i tried deploy a apisix controller, it seems not works:
```
$ kubectl apply -f https://raw.githubusercontent.com/pkking/homelab/main/ingress/apisix-apiroute.yaml
```
Then `curl -v localhost -H "Host: local.httpbin.org" ` will just return 404;
and have no idea why
```
$ kubectl get apisixroute   
NAME               HOSTS                   URIS     AGE                                                                                                                                                                                    
httpserver-route   ["local.httpbin.org"]   ["/*"]   27m   
```

Any suggestions appreciated!!

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 
```
$ helm list -A 
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION                                                                                                                
apisix  ingress-apisix  1               2023-07-18 17:15:09.356819359 +0800 CST deployed        apisix-2.1.0    3.4.0     
````
- your Kubernetes cluster version (output of kubectl version): K8s Rev: v1.27.3  
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):  5.15.0-58-generic 64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tao12345666333** [comment]
In fact, all e2e test cases of this project use Httpbin as the backend, which you can refer to.

https://github.com/apache/apisix-ingress-controller/blob/e809cfbaaad6f6c3cbd23f5ec8e93bc1d87f543d/test/e2e/suite-plugins/suite-plugins-general/echo.go#L34-L58

**Comment by pawankukreja01** [comment]
**Misconfigured ApisixRoute**: The ApisixRoute configuration might be incorrect. [You can check the configuration file to ensure that it is correct and that the `local.httpbin.org` host is correctly specified ](https://github.com/apache/apisix-ingress-controller/issues/729)[1](https://github.com/apache/apisix-ingress-controller/issues/729).

**Incorrect Apisix version**: The Apisix version you are using might be outdated or incompatible with your Kubernetes cluster. [You can try upgrading to the latest version of Apisix to see if that resolves the issue ](https://github.com/apache/apisix-ingress-controller/issues/729)[1](https://github.com/apache/apisix-ingress-controller/issues/729).

**Misconfigured Ingress**: The Ingress configuration might be incorrect. [You can check the configuration file to ensure that it is correct and that the `local.httpbin.org` host is correctly specified ](https://github.com/apache/apisix-ingress-controller/issues/729)[1](https://github.com/apache/apisix-ingress-controller/issues/729).
