### ISSUE TITLE
docs: Add Q&A section for ingress controller

### ISSUE THREAD

**Issue by Revolyssup** [apache/apisix-ingress-controller#1895]
### Current State

All the tutorials install Apisix with service type NodePort and access APISIX either by nodeport or by curl'ing into the Pod. Users might have questions like how can APISIX be exposed as service type LoadBalancer? and how can the Ingress resource be allocated Address?

### Desired State

Answer these questions in the Q&A section on installing APISIX with ingress.

**Comment by Revolyssup** [comment]
@tao12345666333 Can I add these qa to existing FAQ here ? https://apisix.apache.org/docs/ingress-controller/FAQ/

**Comment by tao12345666333** [comment]
Sure!

**Comment by Revolyssup** [comment]
Completed https://github.com/apache/apisix-ingress-controller/pull/1907
