### ISSUE TITLE
request help:   Do you have plan to remove etcd?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#1896]
### Issue description

Do you have plan to remove etcd ? And combine ingress controller with apisix ,so that we can reduce a  componet to maintenance ? If yes, what't the progress and timetime? Thanks in advance for your answer.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Please refer to https://github.com/apache/apisix-ingress-controller/issues/610

We are currently working on the implementation and there is already a pull request submitted.
#1803 

But to fully achieve that goal is a huge task, and I cannot commit to a specific timeframe for it.

I will close this one. If you have any technical discussions about this feature, let's use #610 as the tracking and unified discussion place. Thanks!
