### ISSUE TITLE
How to make apisix fetch the ssl through ingress-controller with kubernetes secrets rather than fetch from admin api?

### ISSUE THREAD

**Issue by chiliast123** [apache/apisix-ingress-controller#1902]
### Description

what should I configure the values.yaml? we got 2 certifictes want to pass to ingress-controller through secrets, by the way, should I set admin api into false?

**Comment by tao12345666333** [comment]
You can refer to these documents.

* [Using APISIX Ingress Controller With AWS ACM - API7.ai](https://api7.ai/blog/using-apisix-ingress-with-aws-acm)
* [How to Use cert-manager and HashiCorp Vault to Manage Certificates? - API7.ai](https://api7.ai/blog/how-to-use-cert-manager-and-vault-to-manage-certifications)
* [Manage Ingress Certificates With Cert Manager | Apache APISIX® -- Cloud-Native API Gateway](https://apisix.apache.org/docs/ingress-controller/tutorials/manage-ingress-certificates-with-cert-manager/)
* [HashiCorp Vault Secure Storage Backend in Apache APISIX Ecosystem | Apache APISIX® -- Cloud-Native API Gateway](https://apisix.apache.org/blog/2022/01/21/apisix-hashicorp-vault-integration/)
* [How to Use Vault to Manage Certificates in APISIX - API7.ai](https://api7.ai/blog/apisix-integrates-with-vault)

In addition, Apache APISIX Ingress use admin-api to communicate with APISIX. You shouldn't set it to false.

**Comment by Revolyssup** [comment]
@chiliast123 What are these certs for? You said you want to pass it to ingress controller. These certs are for APISIX gateway? Then you'd be configuring them while installing the APISIX helm chart and not ingress controller.

**Comment by chiliast123** [comment]
what should I do if I don't want apisix fetch the ssl from admin api in the helm chart way?

**Comment by tao12345666333** [comment]
You don't need to do any extra configuration. Just don't configure APISIX through the Admin API.
