### ISSUE TITLE
help request: only response if protocol is https

### ISSUE THREAD

**Issue by JoniJnm** [apache/apisix-ingress-controller#1903]
### Description

I'm using ingress-controller.

I have an API witch responds using HTTP and HTTPS. I use the redirect plugin with the config [http_to_https](https://apisix.apache.org/docs/apisix/FAQ/#how-do-i-redirect-http-traffic-to-https-with-apache-apisix).

I want to remove the redirect plugin and respond a 4XX code (maybe 403 Forbidden or [426 upgrade required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426)) when the request is using http? Is this possible?

ApisixRoute has the value exprs config ([example](https://apisix.apache.org/docs/ingress-controller/concepts/apisix_route/#advanced-routing), [docs](https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2/)), but seems like there is no way to match the port or "it's http".

### Environment

- [Helm apisix chart: 1.3.0](https://artifacthub.io/packages/helm/apisix/apisix/1.3.0) 
- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): `Linux apisix-594cbcf65-q5mf8 5.19.0-41-generic apache/apisix#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 GNU/Linux`
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1

**Comment by tao12345666333** [comment]
You can refer to this document and use the serverless plugin to complete it.

https://apisix.apache.org/docs/apisix/FAQ/#how-do-i-redirect-http-traffic-to-https-with-apache-apisix

**Comment by JoniJnm** [comment]
It works, ty

```yaml
      plugins:
        - name: serverless-pre-function
          enable: true
          config:
            phase: rewrite
            functions:
              - |
                return function()
                  if ngx.var.scheme == "http" then
                    ngx.status = ngx.HTTP_UPGRADE_REQUIRED
                    ngx.header["content-type"] = "application/json"
                    ngx.say('{"error": "Use HTTPs"}')
                    ngx.exit(ngx.HTTP_UPGRADE_REQUIRED)
                  end
                end
```

I tried to use [request-validation](https://apisix.apache.org/docs/apisix/plugins/request-validation/) using header: schema=https but seems like the header doesn't exists (tried with http_schema also)

I tried also ApisixRoute with `http[].match.exprs` but in the list of scopes (Header, Query, Cookie, Path) there isn't a "[special ngx context](http://nginx.org/en/docs/varindex.html)" to filter by schema as in the example code in your link:

```shell
curl -i http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "host": "foo.com",
    "vars": [
        [
            "scheme",
            "==",
            "http"
        ]
    ],
    "plugins": {
        "redirect": {
            "uri": "https://$host$request_uri",
            "ret_code": 301
        }
    }
}'
```

**Comment by tao12345666333** [comment]
This issue can be considered resolved, I will close it.

Thanks
