### ISSUE TITLE
apisix-ingress-controller Pod memory leak

### ISSUE THREAD

**Issue by liyongxian** [apache/apisix-ingress-controller#1925]
### Current Behavior

![image](https://github.com/apache/apisix-ingress-controller/assets/18571576/8d810f36-607c-4941-a22e-a83d80b0ae6d)

### Expected Behavior

low memory.

### Steps to Reproduce

helm install 

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- 
![image](https://github.com/apache/apisix-ingress-controller/assets/18571576/cb39c58b-7525-4447-acde-60c6dd645367)

- Kubernetes cluster version (run `kubectl version`)
-
![image](https://github.com/apache/apisix-ingress-controller/assets/18571576/27d93abf-3507-45c3-a721-f03d432d62e1)

- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)
![image](https://github.com/apache/apisix-ingress-controller/assets/18571576/5dc35b4e-ea77-4a14-8518-a8dbaae8d259)

**Comment by tao12345666333** [comment]
Can you provide more information? What are your resource configurations, Ingress or CRD, etc.?

**Comment by liyongxian** [comment]
Limit resource of Contaners Not Set,Using apisix ingressclass .
![image](https://github.com/apache/apisix-ingress-controller/assets/18571576/7007d69d-f80c-49a8-a533-fcf7e8c68bea)

**Comment by tao12345666333** [comment]
My meaning is the number of your Ingress resources.
Can the instability be reproduced after restarting? When did the memory increase occur and is there any log available? If you want us to help solve the problem, please provide more information in as much detail as possible.

**Comment by twotwo7** [comment]
@liyongxian 你好，我想问下这个问题最后是怎么解决的？我也遇到了类似的问题
