### ISSUE TITLE
bug: ingress controller logs default to UTC+8

### ISSUE THREAD

**Issue by acuteaura** [apache/apisix-ingress-controller#1934]
The Dockerfile currently explicitly sets the localtime to Hong Kong, which is a very opinionated default and should likely be configured via ConfigMap injected into the container if needed. Support could also be added to the Helm chart.

There is also mention of a seperate docker build with a slimmer base container in some commits relating to the Dockerfile. Does this exist, is it planned or did it exist in the past?

I'm happy to contribute an alpine/distroless/wolfi-based image if needed.

**Comment by tao12345666333** [comment]
You can pass TZ env to configure it.

**Comment by tao12345666333** [comment]
Welcome PR a distroless based image. Thanks

**Comment by shreemaan-abhishek** [comment]
@yuweizzz can we close this now?

**Comment by yuweizzz** [comment]
yes, it's already finished.
