### ISSUE TITLE
bug: controller doesn't remove routes for deleted ingresses

### ISSUE THREAD

**Issue by acuteaura** [apache/apisix-ingress-controller#1935]
### Current Behavior

Old routes are still visible in the apisix API.

### Expected Behavior

Routes are deleted as soon as the ingress is removed.

Note that delivery of deletion events is not guaranteed in Kubernetes, and a finalizer would be needed to guarantee backing objects are removed. The controller could also periodically check if all routes marked as managed by the controller are still referenced.

### Error Logs

N/A

### Steps to Reproduce

1. Stop the controller (to simulate missing the event; this can happen for various reasons, like intermittent network errors)
2. Delete an ingress
3. Restart the controller, wait for it to settle
4. Check http://apisix-admin:9180/apisix/admin/routes/

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`) v1.6.0
- Kubernetes cluster version (run `kubectl version`) v1.26.6

**Comment by tao12345666333** [comment]
For controllers, they usually process events based on what they receive. However, we also have a compensation mechanism that allows for full data synchronization according to the information configured in Kubernetes within a specific period of time.

FYI: https://github.com/apache/apisix-ingress-controller/blob/c3174d46fb2dfabd1472326688df873509d72ce2/conf/config-default.yaml#L58-L60

**Comment by acuteaura** [comment]
This seems sensible, though I'd like to note again that events from informers are not reliable, and finalizers exist for resources where missing a deletion event can cause severe errors in state. Usually the flow goes like this:

* The controller sets a unique key in metadata.finalizers (namespaces have "kubernetes" there, for instance)
* When at least one finalizer is present and apiserver receives a delete for an object, it is not deleted, by metadata.deletionTimestamp is set. In Kubectl output the resource now shows as "deleting".
* The controller runs the logic required to clean up resources in the background, and only then removed the finalizer with its unique key.
* As soon as all finalizers are removed, apiserver deletes the resource.

Bad things can happen if you force-delete resources (which ignores the finalizers) - we once had a case of your cloud provider having several tens of dead loadbalancers because developers force-deleted their associated service objects and the controller couldn't clean up.

For an ingress that is unambiguously created to be consumed by apisix (e.g. matching ingressClassName), a finalizer might be a good alternative, but you also need to consider that imo, those fields aren't locked like Service type, so an ingress may fall out of scope for different reasons and then not get removed.
