### ISSUE TITLE
request help: Can we remove the crds for v2beta3?

### ISSUE THREAD

**Issue by jiangfucheng** [apache/apisix-ingress-controller#1973]
### Issue description

The APISIX-related k8s resource that version is v2beta3 has been removed. However, I found that the 'crds' still exist in the 'samples/' folder. Should we remove them?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Sure.  #1976
