### ISSUE TITLE
bug: Log is spammed with unknown field "status.conditions[0].lastTransitionTime"

### ISSUE THREAD

**Issue by mfractal** [apache/apisix-ingress-controller#1974]
### Current Behavior

After [discussing it with Jintao Zhang](https://the-asf.slack.com/archives/CUC5MN17A/p1681755119223459) on slack i am creating this issue here : 

our logs are being spammed with 

`unknown field "status.conditions[0].lastTransitionTime"`

It's not a new issue, been happening for a while with various versions of APISIX.

I always make sure to upgrade the CRDs when upgrading apisix so i don't think that's the issue.

Currently we're running 3.4.1 and apisix-ingress-controller version 1.6.1-no-git-module-go1.19.8

before upgrading CRDs were upgraded via 

`helm show crds apisix/apisix-ingress-controller | kubectl apply -f -`

### Expected Behavior

not seeing this message.

### Error Logs

unknown field "status.conditions[0].lastTransitionTime"

### Steps to Reproduce

basically run apisix with ingress-controller, create some routes and watch the logs.

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)

```
/ingress-apisix # ./apisix-ingress-controller  version --long
Version: 1.6.1
Git SHA: no-git-module
Go Version: go1.19.8
Building OS/Arch: linux/aarch64
Running OS/Arch: linux/arm64
```

- Kubernetes cluster version (run `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tao12345666333** [comment]
could you please try to use https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1 ?
