### ISSUE TITLE
request help: How to update crds?

### ISSUE THREAD

**Issue by jiangfucheng** [apache/apisix-ingress-controller#1975]
### Issue description

Hi, I'm learning `apisix-ingress-controller` project, I have a question about how to generate the crds under `sapmles/` folder if we update the resource field like `ApisixRoute`.  Can we only manually update it?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
The current process is done manually. There is also a PR in progress to switch it to kubebuilder-based mode.
https://github.com/apache/apisix-ingress-controller/pull/1320

**Comment by jiangfucheng** [comment]
@tao12345666333 Understood, thank you for your answer.
