### ISSUE TITLE
feature request: namespace_selector support for having multiple values for the same label

### ISSUE THREAD

**Issue by vortegatorres** [apache/apisix-ingress-controller#1987]
### Current Behavior

In the `namespace_selector` configuration, when there are multiple values for the same label, only the last one is taken into account. This happens because the label key serves as the unique identifier [in this map](https://github.com/apache/apisix-ingress-controller/blob/bca0d1da5e0d721ff7c94555821db55dd2659504/pkg/providers/k8s/namespace/namespace_provider.go#L70), and the most recent value will replace any previous ones.

For instance, if you have the following values, only "app3" would be considered in the list of watched namespaces:
```
namespace_selector:
        - "kubernetes.io/metadata.name=app1"
        - "kubernetes.io/metadata.name=app2"
        - "kubernetes.io/metadata.name=app3" 
```

### Expected Behavior

Apply all the labels, even if the label key is the same.

### Steps to Reproduce

Configure several namespace labels with the same key:

```
namespace_selector:
        - "kubernetes.io/metadata.name=app1"
        - "kubernetes.io/metadata.name=app2"
        - "kubernetes.io/metadata.name=app3" 
```

### Environment

APISIX install with helm chart version: 1.3.1

**Comment by tao12345666333** [comment]
The current version indeed does not support this feature. You are welcome to submit a PR to improve it.

The earliest use case for it was to add tags like "should-apisix-watch=true" to namespaces that were waiting to be used.

**Comment by vortegatorres** [comment]
@tao12345666333 I've gone ahead and opened a pull request to introduce support for this feature. Please take a moment to review it and share your thoughts. Your feedback is much appreciated! https://github.com/apache/apisix-ingress-controller/pull/1994
