### ISSUE TITLE
why the apisix ingressClass CANNOT be found, by run "kubectl get ingressClass"

### ISSUE THREAD

**Issue by szhengli** [apache/apisix-ingress-controller#1988]
### Issue description

"ingressClassName: apisix "   can be used successfully, BUT, why the apisix ingressClass CANNOT be found, by run "kubectl get ingressClass"??

### Environment

apache/apisix-ingress-controller:1.6.1

**Comment by tao12345666333** [comment]
Because we didn't create it by default, you can manually create it yourself.

**Comment by szhengli** [comment]
> Because we didn't create it by default, you can manually create it yourself.

even apisix doestno appear in the output of   "kubectl get ingressClass",  it can still use it to create the ingress, as follow:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-route
spec:
  ingressClassName: apisix
  rules:
    - host: local.httpbin.org
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  number: 80
            path: /
            pathType: Prefix

WHY ?
