### ISSUE TITLE
Support for APISIX Standalone mode?

### ISSUE THREAD

**Issue by mlasevich** [apache/apisix-ingress-controller#1990]
### Description

As I user I would like to reduce complexity of APISIX and IngressController configuration by running APISIX in (["standalone mode"](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone)). In that mode APISIX is running of the YAML based static configuration, monitoring it and auto-reloading it as necessary. Ingress-Controller would, in this case, be simply responsible for updating that config file in ConfigMap as necessary based on CRDs/Ingress items

There was already a request for this here https://github.com/apache/apisix-ingress-controller/issues/610 but it resulted in a much more complicated (if I understand it correctly) setup ([described here](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/composite.md)) where ingress controller tries to  emulate etcd and is intertwined with ingress-controller. This _seems_ to be a bit more complicated and fragile than I would like it to be.

Is there any interest in simplifying it to actually use the "standalone" mode?

Thanks

**Comment by daroga0002** [comment]
This is Apisix subproject which in general is about feature which you dont want to have.

You can use standalone Apisix chart:
https://github.com/apache/apisix-helm-chart/tree/master/charts

just dont enable this project via values: `ingress-controller.enabled=false`

then you will have staticly controller apisix.

**Comment by tao12345666333** [comment]
As @daroga0002 said, this project doesn't support this feature and will not add it.

You can just deploy APISIX standalone mode

**Comment by mlasevich** [comment]
I suspect we are not understanding each other - I want the  ingress-controller functionality, but more like a traditional ingress controller sense - one that uses CRDs and ingress objects to configure APISIX. It does not seem that far off from what this is. Otherwise this project is very much misnamed

**Comment by mlasevich** [comment]
> You can just deploy APISIX standalone mode

*SMH* I don't think you understood what I was asking.
