### ISSUE TITLE
how to route traffic to external  (outside of kubernetes cluster) server  by native ingress object  ?

### ISSUE THREAD

**Issue by szhengli** [apache/apisix-ingress-controller#1991]
### Issue description

because, the target server is outside of kubernetes cluster, first I try to create ExternalName type service and refer it in ingress object,  it fails to sync with apsix.  then . try the below, it can sync successfully. but fail to access  http://local.httpbin.org/ui with  "503 Service Temporarily Unavailable" error.

apiVersion: v1
kind: Service
metadata:
  name: uidemo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

apiVersion: v1
kind: Endpoints
metadata:
  name: uidemo
  labels:
    endpointslice.kubernetes.io/managed-by: staff
subsets:
- addresses:
  - ip: 192.168.3.150
  ports:
  - name: web
    port: 80
    protocol: TCP

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-route
spec:
  ingressClassName: apisix
  rules:
    - host: local.httpbin.org
      http:
        paths:
          - backend:
              service:
                name: uidemo
                port:
                  number: 80
            path: /ui
            pathType: Prefix
          - backend:
              service:
                name: httpbin
                port:
                  number: 80
            path: /
            pathType: Prefix

### Environment

apache/apisix-ingress-controller:1.6.1

**Comment by tao12345666333** [comment]
Please format your contents first
