### ISSUE TITLE
request help: is it possible to user cert-manager annotation with the CRD of apisix such apisixRoute

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [apache/apisix-ingress-controller#1992]
### Issue description

i want to automated ssl http1 and dns1 challange certification with the apisix CRD apisixroute example: 
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: test-ssl
  namespace: thingsboard
  annotations:
    #"helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-weight": "1"
    cert-manager.io/issuer: "ca-issuer"                  # is this possible to be use 
spec:

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
No cert-manager does not support this feature

**Comment by MohamedKHALILRouissi** [comment]
is theres solution i can use this automation with apisixroute , a turn arround or something else ( right now am using the ingress and specifying ingressclassname: apisix )

**Comment by tao12345666333** [comment]
In fact, these actions are performed by cert-manager. If you wish to achieve this through other means, you can automatically update the ApisixTls resource when there is a TLS certificate update to complete this process (but this is not a feature provided by this project).
