### ISSUE TITLE
bug: Image version V1.7.0 is not multi arch

### ISSUE THREAD

**Issue by codifierr** [apache/apisix-ingress-controller#1997]
### Current Behavior

https://hub.docker.com/layers/apache/apisix-ingress-controller/1.7.0/images/sha256-6ea5f5e15f1e55dfd0a2103c051032250303c86bfd5897b2b6d5932c93b46c55?context=explore

The docker image is not multi-arch.
Earlier image version 1.6.0 was multi-arch.

### Expected Behavior

The image should be multi-arch so that it can be deployed in amd as well as arm. This was the earlier image behavior.

### Error Logs

exec /docker-entrypoint.sh: exec format error

### Steps to Reproduce

Install apisix ingress controller with image 1.7.0 on Arm system it won't start

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
 v 1.7.0
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by tao12345666333** [comment]
Thanks 

Let me update it

**Comment by codifierr** [comment]
@tao12345666333 Any update on this?

**Comment by tao12345666333** [comment]
Sorry for delay. Maybe @AlinsRan @lingsamuel can help with this

**Comment by codifierr** [comment]
@lingsamuel @AlinsRan Can you help here with multi-arch docker images?

**Comment by AlinsRan** [comment]
@codifierr Sorry for the delay, I will handle it later.

**Comment by AlinsRan** [comment]
https://hub.docker.com/layers/apache/apisix-ingress-controller/1.7.0/images/sha256-2c430915a0bad24db997f91943d7d5a80f69c612da80aeae5a7f6c7e1a6a2b5b?context=explore

**Comment by AlinsRan** [comment]
> https://hub.docker.com/layers/apache/apisix-ingress-controller/1.7.0/images/sha256-2c430915a0bad24db997f91943d7d5a80f69c612da80aeae5a7f6c7e1a6a2b5b?context=explore

@codifierr Updated.

**Comment by codifierr** [comment]
@AlinsRan Can you please update the same for 1.7.1?

**Comment by AlinsRan** [comment]
The image 1.7.0 has been updated, and I will close this issue.

For image 1.7.1, I will update it as soon as possible.

Thanks.

**Comment by codifierr** [comment]
@AlinsRan Any update on 1.7.1?
