### ISSUE TITLE
request help: 使用1.7.0的ingress-controller，修改admin-key不生效

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix-ingress-controller#2014]
### Issue description
![image](https://github.com/apache/apisix-ingress-controller/assets/31987918/5846cc42-cf5e-4711-835a-bce8b9f0daeb)

在deployment里修改key的值，通过api请求时候，仍然是默认的edd1c9f034335f136f87ad84b625c8f1值能请求，自定义的key值报错“failed to check token”

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by zll600** [comment]
@lihuawei321 Can you provide more detailed steps to reproduce?

1. What deployment method did you use?
2. How did you set `admin_key`?
3. What does your request look like?
