### ISSUE TITLE
bug: apisix standalone mode (without etcd) on kubernetes does not work

### ISSUE THREAD

**Issue by gigi206** [apache/apisix-ingress-controller#2036]
### Current Behavior

1) As explained [here](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone) it's impossible to set `config_provider: yaml` with the helm chart because it's hardcoded => see [this issue](https://github.com/apache/apisix-helm-chart/issues/472)
2) If I update manually the config map to defined `config_provider: yaml`, the ingress deployment loop with the init container with the message : **waiting for apisix-admin**

Of course, I set `apisix.admin.enabled=true` and `ingress-controller.enabled=true` with the helm chart but the connection is refused:
```shell
$ kubectl  get svc -n ingress-apisix ingress-apisix-admin
NAME                                TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
ingress-apisix-admin                ClusterIP      10.43.227.70   <none>           9180/TCP                     18m

$ nc 10.43.227.70 9180
(UNKNOWN) [10.43.227.70] 9180 (?) : Connection refused
```

### Expected Behavior

Chart must be fixed and the init container must accept the connection. Note that with etcd enabled (traditional mode) it works.

### Steps to Reproduce

Give the procedure to install apisix in a standalone mode on kubernetes because the [documentation](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone) is not well documented and I expect a bug

### Environment

```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.13+rke2r1
Kustomize Version: v4.5.7
Server Version: v1.25.13+rke2r1
```

**Comment by Revolyssup** [comment]
@gigi206 I think we can track this issue here https://github.com/apache/apisix-helm-chart/issues/472, so I am closing the one here. I think we should remove the hardcoding and allow for configuring standalone in apisix-helm-chart.
