### ISSUE TITLE
request help: Is there any quick way to generate k8s crd resources with client-go?

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2042]
### Issue description

When I used istio before, it had istio.io/client-go to quickly generate crd resources. Does apisix have a library similar to this?

The following is chatgpt's answer. Is there any official follow-up?

<img width="707" alt="图片" src="https://github.com/apache/apisix-ingress-controller/assets/62740231/3bac0610-fe21-4785-bc4a-5b08fb145d17">

**Comment by Revolyssup** [comment]
@DokiDoki1103 There is no separate client-go repo which contains the structs. But you can access structs inside pkg/kube/apisix/. This package contains the struct and clientset, informers for Apisix resources.
