### ISSUE TITLE
request help: How to use the Coraza waf plugin by configuring CRD？

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2043]
### Issue description

There are relatively few documents on Coraza on the official website, and even when using the admin API, I can hardly see any Coraza documents. I would like to use the generated CRD resources to configure and use Coraza WAF. How should I configure CRD?

I see these are some rules, but I don't know how to configure them to take effect either

https://github.com/coreruleset/coreruleset/tree/v4.0/dev/rules

**Comment by Revolyssup** [comment]
Have you looked at this doc? https://apisix.apache.org/blog/2023/09/08/APISIX-integrates-with-Coraza/

**Comment by DokiDoki1103** [comment]
I have seen it, but this only provides the simplest demo and we are not sure how to configure the complete rules

**Comment by DokiDoki1103** [comment]
Do you have any more detailed documents or examples?
