### ISSUE TITLE
request help: Installation questions

### ISSUE THREAD

**Issue by jzhao20230918** [apache/apisix-ingress-controller#2050]
### Issue description

Hello,

How can I install Apisix Ingress Controller if I already had Apisix installed? 

And install it without k8s?

Thanks a lot

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Revolyssup** [comment]
1. You can do `helm install apisix-ingress apisix/apisix-ingress-controller --set ingress-controller.config.apisix.adminAPIVersion=$ADMIN_API_VERSION` and set other apisix configuration according to your running apisix instance for eg: the name of the apisix admin service, service namespace etc. Look here for all the apisix related variables that you can set - https://github.com/apache/apisix-helm-chart/blob/57783ea813e5d90aa44d7f42788a24c99b29d40d/charts/apisix-ingress-controller/values.yaml#L143
2. Ingress controller is supposed to work with Kubernetes.
