### ISSUE TITLE
bug:  Host matching cannot carry ports 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2064]
### Current Behavior

The ApisixRoute "rbd-http-routes" is invalid: spec.http.match.hosts: Invalid value: "8.130.141.31:7070": spec.http.match.hosts in body should match '^\*?[0-9a-zA-Z-._]+$'

```js
/^\*?[0-9a-zA-Z-._]+$/.test('8.130.141.31:7070')
false 
```

```js
/^\*?[0-9a-zA-Z-._]+$/.test('8.130.141.31') 
true
```

Some users access their applications through IP and ports, and use the HTTP protocol, so they hope to increase support for the HTTP port

**Comment by DokiDoki1103** [comment]
cc @Revolyssup

**Comment by Revolyssup** [comment]
@DokiDoki1103 Thanks for catching this. The regex that APISIX accepts for this field doesn't match with the one accepted by ingress controller. I will create a fix for this. https://github.com/apache/apisix/blob/a2da5f156c433b373ba670ce9eecdfdcb4cf7268/apisix/schema_def.lua#L40C23-L40C51

**Comment by DokiDoki1103** [comment]
@Revolyssup  You're welcome, I'm using Apisix extensively. If I encounter any problems, I'll give you feedback promptly
