### ISSUE TITLE
feat: As a user, I want to add support for configuring Consumer group with Ingress

### ISSUE THREAD

**Issue by Revolyssup** [apache/apisix-ingress-controller#2070]
### Description

Add support for configuring Consumer Group with APISIX ingress CRDs

**Comment by pottekkat** [comment]
@Revolyssup This isn't done right? Do we still have plans to support this feature? Reopened, please close if it is appropriate.

**Comment by fsteccanella** [comment]
Hi, any news on this? Thanks

**Comment by RuiSMagalhaes** [comment]
any news on this?

**Comment by devshiva75** [comment]
Can someone please share any update on this. Is this feature going to be added in any future releases?
