### ISSUE TITLE
request help:  How to generate the apisix schema.json file 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2072]
### Issue description

Because I need to use a firewall plugin, which is a wasm plugin and is not defined in this file, it will generate an error message stating that the plugin cannot be found

ref: https://github.com/apache/apisix-ingress-controller/issues/2049

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
apisix 3.7

**Comment by donghuuhieu137** [comment]
you can manually generate a schema to /usr/local/apisix/conf/config.yaml for coraza

**Comment by donghuuhieu137** [comment]
you can manually create a schema.json and mount to /usr/local/apisix-dashboard/conf/schema.json in apisix-dashboard, here's what I'm using: 
```
"coraza-filter": {
    "schema": {
        "type": "object",
        "properties": {
            "conf": {
              "type": "object",
              "properties":{
                "directives_map": {
                  "type": "object",
                  "properties":{
                    "default": {
                      "type": "array"
                    }
                  }
                },
                "default_directives": {
                  "type": "string"
                }
              }
            }
        },
        "$comment": "this is a mark for our injected plugin schema"
    },
    "version": 0.1,
 ```

**Comment by DokiDoki1103** [comment]
thank you ,I can test it
