### ISSUE TITLE
How to integrate AWS NLB to Apisix Ingress controller in kubernetes?

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix-ingress-controller#2077]
### Issue description

I am trying to integrate the below components in my EKS Cluster. 

AWS Network Load balancer ---> Ingress Gateway(Kind: Gateway)  ---> Apisix Ingress Controller ----> ApisixRoute

But I am unable to hit my hello-world service. Getting '404' error. I do not any see any errors in logs. I suspect that gateway mapping to Ingress controller is missing. Please provide me any sample configuration for the same or any example for the above use case.

Thanks,
Hariharan.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
- your Kubernetes cluster version (output of kubectl version): 1.28.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
- etcd - docker.io/bitnami/etcd:3.5.7-debian-11-r14
- Apisix version - apache/apisix:3.6.0-alpine

**Comment by Revolyssup** [comment]
@nphariharan Can you share your related configuration? Like ApisixRoute CR configuration that you're using?
