### ISSUE TITLE
bug: Image version V1.7.1 is not multi arch

### ISSUE THREAD

**Issue by codifierr** [apache/apisix-ingress-controller#2080]
### Current Behavior

https://hub.docker.com/layers/apache/apisix-ingress-controller/1.7.1/images/sha256-65dda29c6f7b5acd3deadbb41b11e046fbe8f8af0203ca4d64b0e363b39eef77?context=explore

The docker image is not multi-arch.
Earlier image version 1.7.0 was multi-arch.

### Expected Behavior

The image should be multi-arch so that it can be deployed in amd as well as arm. This was the earlier image behavior.

### Error Logs

exec /docker-entrypoint.sh: exec format error

### Steps to Reproduce

Install apisix ingress controller with image 1.7.1 on Arm system it won't start

### Environment

APISIX Ingress controller version (run apisix-ingress-controller version --long)
v 1.7.1
Kubernetes cluster version (run kubectl version)
OS version if running APISIX Ingress controller in a bare-metal environment (run uname -a)

**Comment by Gallardot** [comment]
After checking, Docker Hub still does not have the version 1.7.1 ARM image.

https://hub.docker.com/layers/apache/apisix-ingress-controller/1.7.1/images/sha256-65dda29c6f7b5acd3deadbb41b11e046fbe8f8af0203ca4d64b0e363b39eef77?context=explore

**Comment by Revolyssup** [comment]
@Gallardot Please check now. ITs now available.
