### ISSUE TITLE
bug: ssls API object never deleted when created from ingress

### ISSUE THREAD

**Issue by acuteaura** [apache/apisix-ingress-controller#2083]
### Current Behavior

We have found a broken SSLs from an ingress object (not ApisixTls+ApisixRoute) that a developer misconfigured. The update time is about a month in the past, and as far as I can tell, the namespace hasn't existed in several weeks.

```
{
  "createdIndex": 90460,
  "modifiedIndex": 90460,
  "value": {
    "type": "server",
    "labels": {
      "meta_secret_namespace": "fun--f-feature-fte-b43a",
      "meta_secret_name": "environment-cert",
      "managed-by": "apisix-ingress-controller"
    },
    "snis": [
      "sni-that-collides-with-different-cert"
    ],
    "id": "14abff72",
    "create_time": 1699527199,
    "update_time": 1699527199,
    "status": 1,
    "key": "/apisix/ssls/14abff72"
}
```

### Expected Behavior

The ApisixTls is found as orphaned when evaluating Ingresses and deleted.

### Error Logs

N/A

### Steps to Reproduce

#1985 fixing multiple generated ApisixTls objects from Ingress might be related, we're running the fix from the associated PR.

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`) 1.7.0 ([this](https://github.com/handelsblattgroup/apisix-ingress-controller/commits/hmg) tree specifically)
- Kubernetes cluster version (run `kubectl version`) 1.26
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`) N/A

**Comment by Revolyssup** [comment]
[This has been fixed in https://github.com/apache/apisix-ingress-controller/issues/1985 ](https://github.com/apache/apisix-ingress-controller/issues/1985) @acuteaura will be available in the next release. The ETA on next release is 20 December.

**Comment by Revolyssup** [comment]
@acuteaura the issue of leftover ssl objects was solved later in the pr
