### ISSUE TITLE
request help: Migrating from ingress-nginx, can basicAuth be used with Ingress?

### ISSUE THREAD

**Issue by Routhinator** [apache/apisix-ingress-controller#2089]
### Issue description

I'm trying to see if I can adopt the apisix ingress controller without rewriting every upstream helm chart that requires basic-auth that we use.

Can BasicAuth be used with an ingress with annotations? I'm unable to work this out from the docs. All of the docs examples are for full blown ApiConsumer > ApiRoute setups - but in an Ingress controller the routes are part of the ingress definition. Furthermore, ingress definitions are not overridable in most helm charts. I expected there to be some way to specify basic auth and the secret or APIConsumer to leverage for all routes on an Ingress, but I don't see anyway to do this. Is there any documentation that covers migrating from ingress-nginx with regards to common use cases like the Prometheus helm chart (which ships with an ingress and requires basic auth)? 

I'm thinking we can get the APIConsumer into the Ingress definition by adding the `spec.http[*].authentication` property, however that will mean writing a custom ingress definition for every helm chart we use, which will quickly become unmaintainable for a small team - so  wondering why I don't see any annotation based examples to attach basic auth to an ingress. 

Am I missing something in the docs here? Can someone provide an example of basicAuth attached to an ingress?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):  APISIX Helm chart 1.6.2 (this was the latest version I could find that worked, helm charts 1.7.x > 2.x have numerous undocumented changes and unexpected bevhabiour) - Looks like that pulls apisix-ingress-controller helm chart version 0.12.2 which uses docker image 1.7.0 for apisix-ingress-controller
- your Kubernetes cluster version (output of kubectl version): 1.27
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): Ubuntu 22.04

**Comment by Routhinator** [comment]
Looking at the code in https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/suite-annotations/authorization.go I'm guessing there's no way to adopt APISIX for charts that require auth becuase there's no annotation that allows applying auth across all defined paths via an annotation, it's the path  specific `authentication` key or bust.

**Comment by Revolyssup** [comment]
@Routhinator Yes you're right, currently there is no way to apply a plugin uniformly across all routes via annotation.
