### ISSUE TITLE
request help: separated base chart or merge base chart

### ISSUE THREAD

**Issue by Junnplus** [apache/apisix-ingress-controller#209]
### Issue description

Hi, I see helm chart is now supported, but I have a confusion:
Why base is separated of controller?

It is possible to deploy multiple for ingress controller, but each controller may have a different serviceaccount/rbac, it is inconvenient to maintain multiple releases for separated base.

reference:
- [kong ingress controller](https://github.com/Kong/charts/tree/main/charts/kong)
- [traefik ingress controller](https://github.com/traefik/traefik-helm-chart/tree/master/traefik)

**Comment by gxthrj** [comment]
> It is possible to deploy multiple for ingress controller, but each controller may have a different serviceaccount/rbac, it is inconvenient to maintain multiple releases for separated base.

This is indeed a more convincing scenario. It is a better choice to merge base into ingress-apisix .

**Comment by tokers** [comment]
Well, now think back it's not a good design to separate them, i suggest to merge them.

**Comment by gxthrj** [comment]
OK, Let's wait to other people's thoughts.

**Comment by Junnplus** [comment]
It seems that not many people use this now. I'd like to refactoring this if nobody minds.

**Comment by tokers** [comment]
@Junnplus Feel free to ask any questions here.
