### ISSUE TITLE
feat: ssl_protocols support for apisixtls

### ISSUE THREAD

**Issue by womfoo** [apache/apisix-ingress-controller#2090]
### Description

As a user, I would like the apisixtls CRD include [dynamic `ssl_protocols`](https://apisix.apache.org/docs/apisix/next/ssl-protocol/#dynamic-configuration). This will enable configuring multiple SNIs with distinct TLS v1.3-only and TLS v1.2+1.3 setups, providing more flexibility and control in securing SNIs with legacy clients.

**Comment by zll600** [comment]
@womfoo Good point. Would you be interested to create a PR ?
