### ISSUE TITLE
request help: require traffic split and rewrite uri together

### ISSUE THREAD

**Issue by sunkara007** [apache/apisix-ingress-controller#2091]
### Issue description

i have a service where the traffic has to be forwarded equally to 2 upstreams (upstream A & upstream B) and for the upstream B alone i want to rewrite the uri by appending a query parameter

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.7.0
- your Kubernetes cluster version (output of kubectl version): 
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): macos

**Comment by basuotian** [comment]
refer to https://apisix.apache.org/docs/apisix/plugins/traffic-split/

**Comment by soulbird** [comment]
The current capabilities of apisix cannot realize this scenario.
You can achieve even distribution of traffic by specifying a weight for each upstream.
The load balancing algorithm selects an upstream after the proxy-rewrite plugin rewrites the uri, so this cannot be done using the proxy-rewrite plugin.
The traffic-split plugin also cannot rewrite the uri for a certain upstream address.
