### ISSUE TITLE
request help:  How does Apisix create and bind custom plugins for Consumer type? 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2101]
### Issue description

 CRD not defined it , but the admin API supports it. What should I do 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
3.7.0 
1.7.1

**Comment by Revolyssup** [comment]
@DokiDoki1103 
Currently only authentication plugins are supported with `ApisixConsumer` CRD.

**Comment by Revolyssup** [comment]
@DokiDoki1103 Btw this is already being tracked here https://github.com/apache/apisix-ingress-controller/issues/2069
