### ISSUE TITLE
bug:  Unable to update reserved routes using SDK 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2102]
### Current Behavior

After using SDK to update the route, I found that there was no departure watch mechanism and it did not take effect in a timely manner 

**But I can update using `kubectl edit`**

 May I ask why the use of SDK does not work ？

```go
	c := handler.GetAPIGatewayHandler().GetClient().ApisixV2()
	tenant := r.Context().Value(ctxutil.ContextKey("tenant")).(*dbmodel.Tenants)
	list, _ := c.ApisixRoutes(tenant.Namespace).List(r.Context(), v1.ListOptions{
		LabelSelector: "service_alias=" + r.URL.Query().Get("service_alias"),
	})
	for _, item := range list.Items {
		var plugins = item.Spec.HTTP[0].Plugins
		var newPlugins = make([]v2.ApisixRoutePlugin, 0)
		for _, plugin := range plugins {
			if plugin.Name != ResponseRewrite {
				newPlugins = append(newPlugins, plugin)
			}
		}

		if r.URL.Query().Get("act") == "close" {
			newPlugins = append(newPlugins, v2.ApisixRoutePlugin{
				Name:   ResponseRewrite,
				Enable: true,
				Config: map[string]interface{}{
					"status_code": 404,
					"body":        "请打开对外访问",
				},
			})
		}
		item.Spec.HTTP[0].Plugins = newPlugins
		c.ApisixRoutes(tenant.Namespace).Update(r.Context(), &item, v1.UpdateOptions{})
		c.ApisixRoutes(tenant.Namespace).UpdateStatus(r.Context(), &item, v1.UpdateOptions{})
	}
```

**Comment by DokiDoki1103** [comment]
cc @kayx23  @Revolyssup

**Comment by kayx23** [comment]
No knowledge of this sorry, let's wait for others to pitch in.

**Comment by Revolyssup** [comment]
I'll take a loot at it tomorrow. Currently I am busy with other tasks. Thanks for reporting.

**Comment by DokiDoki1103** [comment]
I need to add that this situation only occurs when two resources are updated simultaneously. If I only update one of the resources, it will work normally 
```
[root@iZ0jlcmvdsbq3e5h9ronw8Z ~]# kubectl get apisixroutes.apisix.apache.org -n admin 
NAME                                              HOSTS                                                     URIS     AGE
180.grff3d3f.w51izhca.8.130.98.199.nip.iop-ps-s   ["80.grff3d3f.w51izhca.8.130.98.199.nip.io","lyck6.cn"]   ["/*"]   3s
1lyck6.cnp-ps-s                                   ["lyck6.cn"]                                              ["/*"]   3s
```

**Comment by Revolyssup** [comment]
@DokiDoki1103 When you check the error and response of .Update(), what do you see?

**Comment by DokiDoki1103** [comment]
> @DokiDoki1103 When you check the error and response of .Update(), what do you see?

 No errors were reported  ，But I have pinpointed the problem, it's because the host field is too long

**Comment by DokiDoki1103** [comment]
@Revolyssup  You can try using a very long host field, it will not take effect

**Comment by Revolyssup** [comment]
@DokiDoki1103 I need to be able to reproduce the issue. Can you paste the full route configuration which I can use to reproduce, for both cases when it works and when it doesnt?

**Comment by Revolyssup** [comment]
I used the SDK to update URI field where the Host was long as you suggested and it was updated successfully. 
<img width="1104" alt="Screenshot 2023-12-20 at 12 21 25 PM" src="https://github.com/apache/apisix-ingress-controller/assets/43276904/59128e5f-84a2-43db-ab14-341233e2f557">

**Comment by Revolyssup** [comment]
Are you sure there are no reported errors from Update(), please show the logs where you log the returned response and error. Also show the complete configuration that you used.

**Comment by DokiDoki1103** [comment]
I know he can successfully generate it, but he cannot work, and I am not sure if it is a bug in Apisix

**Comment by Revolyssup** [comment]
> I know he can successfully generate it, but he cannot work, and I am not sure if it is a bug in Apisix

Can you clarify what you said? What do you mean by "cannot work" and do you mean that update is successful in ingress but the configuration doesn't take effect in APISIX?

**Comment by Revolyssup** [comment]
@DokiDoki1103 Any updates?
