### ISSUE TITLE
request help: apisixroute support externalname

### ISSUE THREAD

**Issue by Mararesliu** [apache/apisix-ingress-controller#2103]
### Issue description

Is apisix ingress can support externalname to proxy to other namespace?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 3.7
- your Kubernetes cluster version (output of kubectl version): 1.27
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): 

1.

**Comment by Revolyssup** [comment]
You can specify FQDN of the service like `abcService.abcNamespace.svc.cluster.local`
