### ISSUE TITLE
docs:  Is there any plan for Chinese documentation?

### ISSUE THREAD

**Issue by smileby** [apache/apisix-ingress-controller#2116]
### Current State

There is no Chinese documentation related to ingress on the official website

### Desired State

Support Chinese documents

**Comment by smileby** [comment]
If  not in a hurry, you can assign it to me.  I plan to submit multiple docs PR

**Comment by Ayush9026** [comment]
I also try to contribute in documentation.

**Comment by smileby** [comment]
> I also try to contribute in documentation.

@Ayush9026 I plan to submit an issue for each document. Do you have any good suggestions?
