### ISSUE TITLE
help request: The remoteAddrs field in ApisixRoute does not work or malfunctioning？

### ISSUE THREAD

**Issue by Gitttttttt** [apache/apisix-ingress-controller#2117]
### Description

When I add the remoteAddrs field, the route responds 404, but correct without the field! Like the pic show:

It goes right like this:
![image](https://github.com/apache/apisix/assets/38375081/01e5f074-07da-45b3-90a7-e8c97fe3aa29)
![image](https://github.com/apache/apisix/assets/38375081/41c999d2-7769-4e82-bc43-c4c0238fad35)

but goes wrong while this（The IP address for initiating the request is **100.70）:
![image](https://github.com/apache/apisix/assets/38375081/abb429eb-7973-4169-abfc-a04031c2603f)
or this:
![image](https://github.com/apache/apisix/assets/38375081/d2ae89bc-8bfc-4827-aacd-0d5215bd1c9c)
It will show me 404 error:
![image](https://github.com/apache/apisix/assets/38375081/9321d1a8-4c05-493c-bdb2-2785ee16222d)

Is it a bug? or anything wrong?

### Environment

- APISIX version (run `apisix version`): 3.5.0-centos
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
> @Revolyssup any idea k8s wizard?

I'll take a look here by the end of the day. I have transferred the issue to ingress controller repo.

**Comment by Gitttttttt** [comment]
> > > the ip of k8s cluster master node is end with 100.70... So I request by 'xx.xx.100.70:32722'
> > 
> > 
> > `remote addrs` is used to restrict which client IP can access the route. But you mentioned it was the k8s master node address. Is that also the IP your request originates from?
> 
> yes, but It responds different result in different situation: ①.Without the remoteAddrs field: It responds correctly by requesting from xx.xx.100.70, but responds 404 error by requesting from browser. ②.With the remoteAddrs field: It responds 404 error wherever I request from.

@Revolyssup Hi, How is this problem going?

**Comment by Revolyssup** [comment]
> > > > the ip of k8s cluster master node is end with 100.70... So I request by 'xx.xx.100.70:32722'
> > > 
> > > 
> > > `remote addrs` is used to restrict which client IP can access the route. But you mentioned it was the k8s master node address. Is that also the IP your request originates from?
> > 
> > 
> > yes, but It responds different result in different situation: ①.Without the remoteAddrs field: It responds correctly by requesting from xx.xx.100.70, but responds 404 error by requesting from browser. ②.With the remoteAddrs field: It responds 404 error wherever I request from.
> 
> @Revolyssup Hi, How is this problem going?

I was on afk for the weekend. I am processing it today. I'll reply in a while

**Comment by Revolyssup** [comment]
@Gitttttttt Can you share APISIX pod logs?

**Comment by Revolyssup** [comment]
@Gitttttttt 
If you want to match all IPs, you need to use CIDR format `0.0.0.0/0` and not `0.0.0.0`

**Comment by Revolyssup** [comment]
@Gitttttttt 
1. 

> > > the ip of k8s cluster master node is end with 100.70... So I request by 'xx.xx.100.70:32722'
> > 
> > 
> > `remote addrs` is used to restrict which client IP can access the route. But you mentioned it was the k8s master node address. Is that also the IP your request originates from?
> 
> yes, but It responds different result in different situation: ①.Without the remoteAddrs field: It responds correctly by requesting from xx.xx.100.70, but responds 404 error by requesting from browser. ②.With the remoteAddrs field: It responds 404 error wherever I request from.

1. Without remote_addr field, it should be matched from everywhere. The curl request succeeds means everything is fine. Can you use something like wireshark to look at the http request when you send it via postman or whichever client when it doesn't match and gives you 404?

2. With remote_addr field:
  a. 0.0.0.0 won't work. If you want to match all. Use the CIDR 0.0.0.0/0 which matches all IP addresses
  b. When you send a request from Machine Port A to the same machine's Port B, the client IP address as seen by NGINX will 
  be the loopback address, which is usually 127.0.0.1 for IPv4 or ::1 for IPv6. This is because the communication is happening 
  within the same machine. So the remote_addr as host IP is not working as well.

**Comment by Gitttttttt** [comment]
@Revolyssup Sorry, I was careless for the problems, all the issues above have been resolved. 
But I found backend service must be the same namespace with the apisix, or it will response '502 Bad gateway', and I see the document clearly states this point. 
But this is not in line with practical application scenarios, as more often than not, apisix  is not in the same namespace with backend. Is that so? I'm not sure.

**Comment by Gitttttttt** [comment]
> If you're using `Ingress` resource then you can use the annotation `k8s.apisix.apache.org/svc-namespace: <service namespace>` to support cross namespace backend service, @Gitttttttt

@Revolyssup Oh! I am using ApisixRoute, is there any solution？

**Comment by Revolyssup** [comment]
> > If you're using `Ingress` resource then you can use the annotation `k8s.apisix.apache.org/svc-namespace: <service namespace>` to support cross namespace backend service, @Gitttttttt
> 
> @Revolyssup Oh! I am using ApisixRoute, is there any solution？

You can use FQDN for service name. So for eg if your svc in demo namespace: svc.demo.cluster.local
