### ISSUE TITLE
request help: How to solve the problem when the backend service is not in the same namespace with the apisix?

### ISSUE THREAD

**Issue by Gitttttttt** [apache/apisix-ingress-controller#2120]
### Issue description

For example:
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/c6480093-3914-4c7c-938e-1e364f0d816c)

I want to access the httpbin service through ApisixRoute, but failed while they are in the different ns.
Is there any solution for different ns between backend and apisix?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.7.1-latest
- your Kubernetes cluster version (output of kubectl version): 1.22.15
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Revolyssup** [comment]
As mentioned here[1], The name (short) of the service, note cross namespace is forbidden, so be sure the ApisixRoute and Service are in the same namespace.

1. https://apisix.apache.org/docs/ingress-controller/next/references/v2/#apisix.apache.org/v2.ApisixRouteHTTPBackend

**Comment by karl-chanel** [comment]
![Screenshot_2024-01-04-07-53-23-175_mark.via.gp.jpg](https://github.com/apache/apisix-ingress-controller/assets/78248702/b444e9eb-d647-46e8-8736-2127926eb7a9)

**Comment by karl-chanel** [comment]
I think we can do this by the docs above

**Comment by Gitttttttt** [comment]
> As mentioned here[1], The name (short) of the service, note cross namespace is forbidden, so be sure the ApisixRoute and Service are in the same namespace.
> 
> 1. https://apisix.apache.org/docs/ingress-controller/next/references/v2/#apisix.apache.org/v2.ApisixRouteHTTPBackend

@Revolyssup @karl-chanel  I have reviewed this document. Does it mean that the backend must be consistent with the namespace where Apisix is installed? Otherwise, we can only use Ingress, right?

**Comment by Revolyssup** [comment]
> ![Screenshot_2024-01-04-07-53-23-175_mark.via.gp.jpg](https://private-user-images.githubusercontent.com/78248702/294054909-b444e9eb-d647-46e8-8736-2127926eb7a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzkzMDgsIm5iZiI6MTcwNDMzOTAwOCwicGF0aCI6Ii83ODI0ODcwMi8yOTQwNTQ5MDktYjQ0NGU5ZWItZDY0Ny00NmU4LTg3MzYtMjEyNzkyNmViN2E5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYzAyMWFjZTIxMzAyYWQ1MWMwMTdhN2ExM2YwOTkzYmQ2OWRhOTFkMTFlYWRmNDgzNzRmZDU1ZjhhMTFlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hai6NrBaepi8Xuhd9ckMyEKCdQKmo_GK2HVwQTsGfNM)

Yes but the reporter said they are using ApisixRoute and not Ingress resource

**Comment by Revolyssup** [comment]
> > As mentioned here[1], The name (short) of the service, note cross namespace is forbidden, so be sure the ApisixRoute and Service are in the same namespace.
> > 
> > 1. https://apisix.apache.org/docs/ingress-controller/next/references/v2/#apisix.apache.org/v2.ApisixRouteHTTPBackend
> 
> @Revolyssup @karl-chanel I have reviewed this document. Does it mean that the backend of ApisixRoute must be consistent with the namespace where Apisix is installed? Otherwise, we can only use Ingress, right?

No. It means the namespace of `ApisixRoute` resource and `Service` should be same. Apisix can be installed anywhere.
