### ISSUE TITLE
release of 1.8

### ISSUE THREAD

**Issue by karl-chanel** [apache/apisix-ingress-controller#2122]

**Comment by karl-chanel** [comment]
Hey, the latest docs of apisix ingress controller is 1.8 , But it seems that  it is not released in github, Is the version of 1.8 available.

**Comment by Revolyssup** [comment]
> Hey, the latest docs of apisix ingress controller is 1.8 , But it seems that it is not released in github, Is the version of 1.8 available.

The voting mail is out. We are waiting for votes and then we will push appropriate images

**Comment by Revolyssup** [comment]
@karl-chanel release has been made
