### ISSUE TITLE
request help: 502 Bad Gateway while requesting an Ingress resource

### ISSUE THREAD

**Issue by Gitttttttt** [apache/apisix-ingress-controller#2123]
### Issue description

services like this:
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/c0d7847a-00c7-4e96-9504-a49227e62feb)

ingress like this:
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/06fd7fb9-fc0d-4787-b410-18f616eb7f7f)

After applying the above Ingress, I send a request like this(10.18.100.70 is master node):
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/27456563-f02f-4b72-991a-45058e7b8f92)

The apisix pod showed me error logs:
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/bb4ea5a5-9633-449e-9adc-f84ecd7be007)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.7.0
- your Kubernetes cluster version (output of kubectl version): 1.22.15
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Gitttttttt** [comment]
I get this solution:

![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/e7bcb021-0977-4c00-8105-37c8b8b37086)


but does it not seem to be effective

![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/a160a591-fe5a-44a5-989c-2b2620557f1d)

**Comment by Revolyssup** [comment]
@Gitttttttt I see you are trying to send the request to port 8081 on the `httpbin` service but the port configured is `80`

**Comment by Gitttttttt** [comment]
@Revolyssup yes, there are two `httpbin` services, another with 8081 port is in `test` namespace, But I found the port of httpbin pod must be 80,  if I run with `kubectl expose pod httpbin --port 8081`, it can not be accessed.

**Comment by Gitttttttt** [comment]
Now I have redeployed `httpbin` service and `apisix`, and I created an `Ingress`, but how should I access the `httpbin` service?
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/f180940e-895b-46e7-8beb-a0051d6d43d6)

**Comment by Revolyssup** [comment]
> `pbin` serv

Hear your `Host` is wrong. Set it the same as you have set in Ingress

**Comment by Gitttttttt** [comment]
@Revolyssup Another question, If I need to access a backend from another namespace, I can use the `Ingress` resource and add a `k8s.apisix.apache.org/svc-namespace` annotation, but does this way only apply to L7 gateways (route)？If I want to access a backend(stream_route) from another namespace, what should I do? Is `Ingress` still in effect?

**Comment by Gitttttttt** [comment]
@Revolyssup One more question, If I modify the path as follows, it response `404 Not Found`:
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/29f352dd-139b-47be-90a0-f90fcecd8a2a)

![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/be346ceb-50e6-46b2-bccc-151fce404152)


But if I set path to `/`, it goes right, I'm confused, so is there any document for the pathType? thanks!
![image](https://github.com/apache/apisix-ingress-controller/assets/38375081/64c0f639-02a5-48b5-a0fd-47bb6ce63d24)

**Comment by Revolyssup** [comment]
> @Revolyssup One more question, If I modify the path as follows, it response `404 Not Found`: ![image](https://private-user-images.githubusercontent.com/38375081/294142259-29f352dd-139b-47be-90a0-f90fcecd8a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzA5NTksIm5iZiI6MTcwNDQzMDY1OSwicGF0aCI6Ii8zODM3NTA4MS8yOTQxNDIyNTktMjlmMzUyZGQtMTM5Yi00N2JlLTkwYTAtZjkwZmNlY2Q4YTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODQyY2NmYTFkNTNlM2EwY2U4N2FiY2M4NjEwMjkyZGQ1ZmExNGIxZDRkYTVkNTA2YjQ5ZGJkMTgwNzYwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3u1RXIkY0OXrx38SfsjYOP6NAwDD-wh1HXeVSWhKZaw)
> 
> ![image](https://private-user-images.githubusercontent.com/38375081/294142154-be346ceb-50e6-46b2-bccc-151fce404152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzA5NTksIm5iZiI6MTcwNDQzMDY1OSwicGF0aCI6Ii8zODM3NTA4MS8yOTQxNDIxNTQtYmUzNDZjZWItNTBlNi00NmIyLWJjY2MtMTUxZmNlNDA0MTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMTY2NmNlY2QxMGNjNWYxMTY2ZWRmZjJmYTZiNGM5OTk0Zjc2NDI5ZGYwZjdiZDVlM2QzZTY0MDdlOTc2N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xbKvuQzs5r8HxbOn2CVRK0_PPc1Jxk7Cwys9pjGgxXU)
> 
> But if I set path to `/`, it goes right, I'm confused, so is there any document for the pathType? thanks! ![image](https://private-user-images.githubusercontent.com/38375081/294140572-64c0f639-02a5-48b5-a0fd-47bb6ce63d24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzA5NTksIm5iZiI6MTcwNDQzMDY1OSwicGF0aCI6Ii8zODM3NTA4MS8yOTQxNDA1NzItNjRjMGY2MzktMDJhNS00OGI1LWEwZmQtNDdiYjZjZTYzZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNjc1NzlkMGNmZGFmMTg5ZWRhOTNjNTA5YzJmMzA3ODE5MDdhYjA5YjhmNzA2NzRlYjQxZjE5MTQ0Mjg0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6b_F1byOfjestcW48J-wrFDwjOFeJQC_u5H73VDm7s) ![image](https://private-user-images.githubusercontent.com/38375081/294143512-6dd0a044-66d8-43b3-a13a-932c4a26042e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzA5NTksIm5iZiI6MTcwNDQzMDY1OSwicGF0aCI6Ii8zODM3NTA4MS8yOTQxNDM1MTItNmRkMGEwNDQtNjZkOC00M2IzLWExM2EtOTMyYzRhMjYwNDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MzIxZmZmNjM3ZDZkMWU0YmY5NWViOTIyNzAyMTE1MjE1YmMzMDU2ZGRkMDE2ZjUzNGM4MjczZWZhMDIzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPyFAnGjrTJAMauH3KNoXACMqMtzXmw54Iu-pt8tUyY)

The routing is fine. `httpbin` service doesn't have a route `/namespace/test/cookies`. The 404 is from httpbin service and not APISIX

**Comment by Gitttttttt** [comment]
ok, thanks very much
