### ISSUE TITLE
request help: Need help on installing Apisix 3.6.0 in kubernetes through yaml files.

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix-ingress-controller#2128]
### Issue description

The below link explains the steps for installing  Apisix i.e. - 2.15.0 in kubernetes through yaml files.
https://apisix.apache.org/docs/ingress-controller/tutorials/the-hard-way/

I want to install Apisix 3.6.0 in AWS EKS Cluster(Version - 1.28) in standalone mode i.e. without etcd server through yaml files.

Please provide me the complete steps with yaml files.

Environment
APISIX version (run apisix version): 3.6.0
AWS EKS Cluster version - 1.28
APISIX Dashboard version, if relevant: NA
Plugin runner version, for issues related to plugin runners: NA
LuaRocks version, for installation issues (run luarocks --version): NA
I could not get detailed example for installing the same. Please provide any useful link for the same.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Vacant2333** [comment]
pls check these:
https://apisix.apache.org/docs/apisix/2.15/stand-alone/
https://apisix.apache.org/blog/2023/02/09/secure-apisix-admin/#standalone-mode

**Comment by nphariharan** [comment]
The above link describes installation of apisix outside kubernetes. But I want to install Apisix in kubernetes. Do you have any guide for the same? At least give me the complete Apisix-config map and Apisix deployment yaml file.

**Comment by zll600** [comment]
@nphariharan Can you check this doc to change `config.yaml`  for apisix: https://apisix.apache.org/docs/apisix/deployment-modes/#standalone
