### ISSUE TITLE
request help: Not able to hit kubernetes local service using ApisixRoute and ApisixUpstream

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix-ingress-controller#2131]
### Issue description

Issue description
Not able to hit kubernetes local service using ApisixRoute and ApisixUpstream. Getting the below error.

Error message in Apisix logs : **http_access_phase(): failed to set upstream: discovery dns is uninitialized, client: 127.0.0.1**

I am installing the apisix using the below link(through manifest files)
https://apisix.apache.org/docs/ingress-controller/tutorials/the-hard-way/

I added below extra configuration for service discovery in apisix-conf.yaml file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-conf
  namespace: apisix
data:
  config.yaml: |-
    apisix:
      discovery:
        enabled: true
        registry:
          dns:
            servers:
              - "172.20.0.10:53"

Thanks,
Hariharan.

### Environment

Environment
your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
your Kubernetes cluster version (output of kubectl version): 1.28.3
if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
etcd - docker.io/bitnami/etcd:3.4.14-debian-10-r0
Apisix version - apache/apisix:2.15.0-alpine

**Comment by lakshya8066** [comment]
Are there any other logs? 
You can change the log level to `debug` in the config.yaml to get more logs
```
nginx_config:           
      error_log_level: "debug"   
```

**Comment by Revolyssup** [comment]
This was answered here https://github.com/apache/apisix-ingress-controller/issues/2097#issuecomment-1876453987
