### ISSUE TITLE
feat: Add a "namespace" parameter to the "plugin_config" of apisixRoute, to share the same apisixPluginConfig between all namespaces of apisixRoutes

### ISSUE THREAD

**Issue by seethedoor** [apache/apisix-ingress-controller#2132]
### Description

We are using apisixRoutes, and now we need to add a common plugin_config to all of the routes. But I found that apisixRoute `spec` params only support `plugin_config_name`, and it will only search apisixPluginConfig in the same namespace of the apisixRoute. 
This will require to create the same apisixPluginConfigs for all namespaces and maintain these apisixPluginConfigs as namespaces change. If we can add a `plugin_config_namespace` parameter under the apisixRoute `spec`, combined with the `plugin_config_name`, we can solve the above problem with just one apisixPluginConfig.

**Comment by Gallardot** [comment]
Good idea. I believe this will help to reduce maintenance costs.

**Comment by Revolyssup** [comment]
@seethedoor Thanks for reporting. I'll take this up
