### ISSUE TITLE
request help: Need help in installing Apisix 3.1 with yaml files in kubernetes cluster

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix-ingress-controller#2136]
### Issue description

https://apisix.apache.org/docs/ingress-controller/tutorials/the-hard-way/
The above link provides the steps to install Apisix 2.15.0 using yaml file.

Similarly, I need the steps to install Apisix latest version - 3.0 or 3.1 using yaml files in kubernetes cluster. The yaml should have the configuration of DNS Service discovery and without etcd server.

Thanks,
Hariharan.

### Environment

your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
your Kubernetes cluster version (output of kubectl version): 1.28.3
if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
etcd - docker.io/bitnami/etcd:3.5.7-debian-11-r14
Apisix version - Apisix 3

**Comment by Revolyssup** [comment]
@nphariharan By without etcd server, do you mean you are looking for the composite architecture where ingress controller and apisix run in the same pod without any etcd server?

**Comment by nphariharan** [comment]
https://apisix.apache.org/blog/2023/10/18/ingress-apisix/

As per the above link, I need to install apisix with mock etcd server using yaml files.

**Comment by zll600** [comment]
Looks like https://github.com/apache/apisix-ingress-controller/issues/2128
