### ISSUE TITLE
bug:  library etcd-adapter fixed a concurrent issue, need upgrade dependency mod version 

### ISSUE THREAD

**Issue by liushv0** [apache/apisix-ingress-controller#2157]
### Current Behavior

apisix ingress controller  will push many events to Etcd，
such as EventAdd、EventUpdate、EventDelete，
etcd-adapter  watch and handler those events，
there is an issue  ([#28](https://github.com/api7/etcd-adapter/issues/28))   in this process flow，
which could cause panic  because send data to closed channel，

etcd-adapter has fixed this issue，
need  upgrade  version of etcd-adapter in go.mod

### Expected Behavior

no panic

### Error Logs

<img width="1468" alt="截屏2024-02-05 14 56 06" src="https://github.com/apache/apisix-ingress-controller/assets/19424192/89add05d-bf6c-4e00-b043-de081cd877bf">

### Steps to Reproduce

concurrent exception,  could not reproduce stability；

take a pressure test，with huge crd-resources  created/updated/deleted，may reproduce this issue

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by Revolyssup** [comment]
this is completed
