### ISSUE TITLE
bug:  plugin config "concurrent map writes" 

### ISSUE THREAD

**Issue by liushv0** [apache/apisix-ingress-controller#2167]
### Current Behavior

controller processor occasionally crash during running,
cause by "fatal error: concurrent map writes"

### Expected Behavior

no panic

### Error Logs

<img width="1443" alt="image" src="https://github.com/apache/apisix-ingress-controller/assets/19424192/1d8b851e-6f55-4fed-8496-8c689faf3782">

### Steps to Reproduce

function call stack like this:
<img width="2700" alt="apisix-ingress-controller start" src="https://github.com/apache/apisix-ingress-controller/assets/19424192/741d36c0-db0c-4a0f-ae7e-a4a84d7848d8">

so function   Plugins.DeepCopyInto(pkg/types/apisix/v1/types.go:187)  could be called by multiple goroutine at same time,
type  Plugins  is alias name  to map， 
it is not concurrent safe，this will cause  ”concurrent map writes“  error

### Environment

- APISIX Ingress controller version  1.7.1

**Comment by Revolyssup** [comment]
The struct on which unmarshal is being performed is created with new() everytime when DeepCopy is called. Which means the data which is being written is not shared between function calls, so how can there be concurrent writes? I am trying to understand that right now.

**Comment by lkad** [comment]
"I also encountered the same bug; the ingress can restart about three times a week."
