### ISSUE TITLE
feat: As a user, I want to configure ApisixRoute with the multi-auth plugin, so that my service can support multiple authentication methods per route

### ISSUE THREAD

**Issue by greenbird-chr** [apache/apisix-ingress-controller#2169]
### Description

Hi.

APISIX 3.8 [added support](https://github.com/apache/apisix/issues/10196) for defining multiple authentication methods per route by adding the multi-auth authentication plugin.
Our use case mandates the ability for our customers to choose between multiple authentication methods on the same route.
Therefore I am requesting that support for the multi-auth plugin is added to the [plugin types](https://github.com/apache/apisix-ingress-controller/blob/v1.8.0/samples/deploy/crd/v1/ApisixRoute.yaml#L249) supported by the ApisixRoute CRD. 

Regards
Christian

**Comment by joshdcu** [comment]
@Baoyuantop, I believe this is still not supported in v2 of the ingress controller. I can only see these authentication types...

https://github.com/apache/apisix-ingress-controller/blob/v2.0.0/api/v2/apisixroute_types.go#L211-L222

Can we please reopen this and label it as an enhancement? Or if there is a workaround, could you please let us know what it is?
