### ISSUE TITLE
feat: can apisix-ingress-controller use plugin without apisix

### ISSUE THREAD

**Issue by CPAltair** [apache/apisix-ingress-controller#2173]
### Description

Currently apisix-ingress already supports running without etcd. Can it use the plug-in function without apisix ?

**Comment by Revolyssup** [comment]
@CPAltair No, it requires APISIX. Though you can deploy APISIX in the ingress pod using composite mode. Please refer: https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/composite.md
