### ISSUE TITLE
feat: Add support for multiple plugins with a single ApisixConsumer 

### ISSUE THREAD

**Issue by nilimaomni** [apache/apisix-ingress-controller#2215]
### Description

I want to use multiple auth mechanism in a single route which requires to create consumer with multiple auth plugin. This is possible via apisix admin api. Example:
```
curl http://localhost:9180/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "xyz",
    "plugins": {
        "hmac-auth": {
            "access_key": "ejncd934fie",
            "secret_key": "whrbkjndc239o",
            "validate_request_body": true
        },
        "key-auth": {
            "key": "auth-one"
        }
    }
}'

```
But for convenience I want to keep it in config file and want to create consumer via ApisixConsumer CRD. I want something like this:
```apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  name: jack
spec:
  authParameter:
      hmacAuth:
        value:
          access_key: "ejncd934fie"
          secret_key: "whrbkjndc239o"
          validate_request_body: true
      keyAuth:
        value:
          key: "auth-one"

```

It works for single plugin consumer But more than one schema (plugin config) is not supported, hence throwing error : 

> The ApisixConsumer "jack" is invalid: <nil>: Invalid value: "": "spec.authParameter" must validate one and only one schema (oneOf). Found 2 valid alternatives

Kindly add support for the above mentioned feature.

**Comment by jmorenoc-o** [comment]
I also think this feature would be very useful. If I am not mistaken, I think it is possible to do this using the dashboard.
