### ISSUE TITLE
request help: How do I use radixtree_uri_with_parameter router?

### ISSUE THREAD

**Issue by pckhoi** [apache/apisix-ingress-controller#2237]
### Issue description

I couldn't find any documentation on how to set `apisix.router.http` with apisix ingress controller. I assume that it isn't possible at this point?

### Environment

- your apisix-ingress-controller version: 1.8.0 (latest at the moment)
- your Kubernetes cluster version: not relevant, I'm just scanning documentation rn

**Comment by pottekkat** [comment]
@pckhoi You can configure it in your values.yaml file while deploying APISIX: https://github.com/apache/apisix-helm-chart/blob/693acfad2ee9371645bb4b758949aa15a4f8c683/charts/apisix/values.yaml#L281

Does that help?

**Comment by pckhoi** [comment]
Thanks! Is that chart the official way to install apisix ingress controller? What is the status of the [apisix-ingress-controller](https://github.com/apache/apisix-helm-chart/blob/693acfad2ee9371645bb4b758949aa15a4f8c683/charts/apisix-ingress-controller/README.md) chart?

**Comment by pottekkat** [comment]
Yes, charts are the easier/more straightforward way. They are continuously updated with newer releases of the ingress controller.
