### ISSUE TITLE
request help: Multiple Cluster

### ISSUE THREAD

**Issue by JorgeAraujo123** [apache/apisix-ingress-controller#2253]
### Issue description

Is it possible to have multiple Apisix Clusters on the same kubernetes cluster?
If so, it needs another ingress controller installation?
And can I have CRDs for each?

### Environment

- your apisix-ingress-controller version: v1.8.2
- your Kubernetes cluster version (output of kubectl version): v1.30.0

**Comment by Kamaradeivanov** [comment]
Same question, 
Can I have one api gateway expose on a private load-balancer, and another one on a public load balancer ? And if so, how to create a ApisixRoute CustomResource only for the private one ? Maybe by using labels or annotations ?

**Comment by kworkbee** [comment]
I'm having the same concern. I have multiple purpose gateways in the same cluster, and the default `ingressClassName` is `apisix`, so even if `ApisixRoute` and `ApisixUpstream` are deployed for separate purposes, each ingress controller is dealing with them all.
Therefore, each gateway deployment must be completely isolated with a separate `ingressClassName`, or it will have unexpected consequences. (I'm actually the one who overlooked this and caused the failure.)
