### ISSUE TITLE
Support latest `gateway.networking.k8s.io/v1`

### ISSUE THREAD

**Issue by olexiyb** [apache/apisix-ingress-controller#2266]
### Description

In [documentation](https://apisix.apache.org/docs/ingress-controller/getting-started/) require to use very old Kubernetes Gateway API `gateway.networking.k8s.io/v1alpha2`
Do you have any plans to support released version `gateway.networking.k8s.io/v1`?

**Comment by kayx23** [comment]
Relevant issue: https://github.com/apache/apisix-ingress-controller/issues/2255

**Comment by pottekkat** [comment]
@olexiyb We plan to support v1 and keep up with the Gateway API as it is adopted more widely.
