### ISSUE TITLE
Question about the ingress part 

### ISSUE THREAD

**Issue by jp-gouin** [apache/apisix-ingress-controller#227]
Hello i have a few questions regarding apisix ingress controller, 

Is it really an Ingress Controller , as does the solution watch k8s resources type ingress and route traffic to the service ?
And is it planned to use annotations on the ingress to setup the plugin list to apply on the resource ? (Same for service ?)
This way we can use common helm charts and operators and override the ingress/service definition.

thanks

**Comment by tokers** [comment]
@jp-gouin 

> Is it really an Ingress Controller , as does the solution watch k8s resources type ingress and route traffic to the service ?

Currently we don't support the Kubernetes Ingress resource, but it's in the TODO list, i believe it'll be supported in the near future.

> And is it planned to use annotations on the ingress to setup the plugin list to apply on the resource ? (Same for service ?)

Sure, we'll use the annotations capabilities to leverage the rich plugins set in Apache APISIX :).

**Comment by jp-gouin** [comment]
Awesome ! thanks for the confirmation
look forward to test this release !
