### ISSUE TITLE
Version information should be shown when the program started

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#228]
Currently, the version information can be shown by running:

```shell
apisix-ingress-controller version --long
```

While in containerized environment, people have to login to the container and execute the above command. So it's more convenient to show these information when the program started. Just like the configuration information.

![image](https://user-images.githubusercontent.com/10428333/106687650-82313800-6607-11eb-9150-7ed2c19ee9a3.png)

**Comment by huahu0213** [comment]
Seems not that hard , assigned to me  : )

**Comment by tokers** [comment]
@huahu0213 Assigned, feel free to post any questions in this thread.

**Comment by tokers** [comment]
Solved by #238 .
