### ISSUE TITLE
bug: how to skip basic resources installation by helm chart

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#229]
### Issue description

Use helm charts to install apisix-ingress-controller in multiple namespaces.

```
helm install apisix-ingress-controller -n <namespace> ./charts/apisix-ingress-controller
```

### What's the actual result? (including assertion message & call stack if applicable)

The first installation is successful, while the second one failed since some cluster-scoped resources already exists.

![image](https://user-images.githubusercontent.com/10428333/106704938-e82db780-6627-11eb-94e7-704101fddb5b.png)

### What's the expected result?

The second installation should be also successful.

**Comment by tokers** [comment]
@Junnplus Please take a look when you have time.

**Comment by Junnplus** [comment]
We use ClusterRole now, ClusterRole is a non-namespaced resource, but helm release is namespaced resource and auto set annotation `meta.helm.sh/release-namespace` cause this problem.

Use different release name of helm can avoid this problem.

**Comment by tokers** [comment]
@Junnplus But users like me might not know this.

**Comment by tokers** [comment]
@Junnplus Could we add a switch to control the installation of RBAC related resources?

**Comment by Junnplus** [comment]
> Could we add a switch to control the installation of RBAC related resources?

`rbac.create` and `serviceAccount.create` can control create of rbac/serviceAccount resource.
But need manual bind serviceAccount to old clusterRole.

**Comment by tokers** [comment]
@Junnplus Would you like to add these best practices to the document, I think it's better to record them.

**Comment by Junnplus** [comment]
Sure, it may take some time.

**Comment by tokers** [comment]
@Junnplus I'll assign this issue for you and feel free to post your questions here :)

**Comment by tokers** [comment]
Currently, we add a FAQ to mention users.https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/FAQ.md
