### ISSUE TITLE
request help: Failed connect to 127.0.0.1:9180; 拒绝连接

### ISSUE THREAD

**Issue by zhangxiaohui123456** [apache/apisix-ingress-controller#231]
### Issue description
My apisix-admin type is NodePort  accessible from the outside  but  can access the container
### Environment

* your apisix-ingress-controller version (now master);
* your Kubernetes cluster version (v1.16.0);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
@zhangxiaohui123456 I'm afraid that I didn't get your mean. Is your apisix-ingress-controller cannot access the apisix-admin?

**Comment by zhangxiaohui123456** [comment]
> @zhangxiaohui123456 I'm afraid that I didn't get your mean. Is your apisix-ingress-controller cannot access the apisix-admin? If so, please tell us how you install them, and what's the apisix-ingress-controller configuration.

Sorry,Didn't make it clear . First  My   apisix-admin type is NodePort . when I   outside the container  send command :curl -XPUT http://127.0.0.1:9080/apisix/admin/upstreams/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -d '
{
    "nodes": {
        "10.244.143.48:8080": 100,
        "10.244.102.43:8080": 100,
        "10.244.102.63:8080": 100
    },
    "desc": "foo-upstream",
    "type": "roundrobin"
}
'  the response is failed connect to 127.0.0.1:9180 but When I go into the container Re-execute it success .

**Comment by tokers** [comment]
@zhangxiaohui123456 NodePort service doesn't mean you can access it by localhost, you have to change the IP to one of your Kubernetes worker nodes IP. This has nothing with Ingress APISIX.
