### ISSUE TITLE
request help: where can see "X-Amzn-Trace-Id"

### ISSUE THREAD

**Issue by logonmy** [apache/apisix-ingress-controller#233]
### where can see "X-Amzn-Trace-Id"

 In the offical demo 

```
https://github.com/apache/apisix-ingress-controller/blob/master/docs/samples/proxy-the-httpbin-service.md

```

here has : X-Amzn-Trace-Id

```

{
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.64.1",
    "X-Amzn-Trace-Id": "Root=1-5ffc3273-2928e0844e19c9810d1bbd8a"
  }
}
```

and  in my practice：
 kubectl exec -it -n demo-project apisix-f868c968d-qx4wl -- curl http://127.0.0.1:9080/headers -H 'Host: httpbin.apisix.com'

Get this result，there have not X-Amzn-Trace-Id？what's wrong with me?

```
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.apisix.com", 
    "User-Agent": "curl/7.67.0", 
    "X-Forwarded-Host": "httpbin.apisix.com"
  }
}
```

**Comment by tokers** [comment]
@logonmy This is because I ran the Ingress APISIX on Amazon EKS, and through its Load Balancer.
