### ISSUE TITLE
request help: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#246]
### Issue description
When apisixUpstream is configured, what is the reason for the error reported by the ingress-controller
logs:
2021-02-07T11:03:46+08:00 error apisix/upstream.go:89 failed to list upstreams: Get http://apisix-admin:9180/apisix/admin/upstreams: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
ERROR: logging before flag.Parse: E0207 11:03:46.725956 1 upstream.go:38] list upstreams in etcd failed, group: , err: Get http://apisix-admin:9180/apisix/admin/upstreams: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2021-02-07T11:03:46+08:00 error state/builder.go:207 solver upstream failed, find upstream from APISIX failed, upstream: &{ID: FullName:0xc00041ef40 Group:0xc00041eeb0 ResourceVersion:0xc00041eec0 Name:0xc00041eed0 Type:0xc00041ef50 HashOn:0xc00041ef60 Key:0xc00041ef70 Nodes:[0xc00000fae0 0xc00000fb00] FromKind:0xc00041ef30}, err: list upstreams failed, err: Get http://apisix-admin:9180/apisix/admin/upstreams: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0207 11:03:46.726001 1 apisix_upstream.go:113] error syncing 'default/web': list upstreams failed, err: Get http://apisix-admin:9180/apisix/admin/upstreams: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
### Environment
This is my installation procedure:
helm install apisix ./chart/apisix  -n default\  
    --set etcd.enabled=false \
    --set etcd.host={http://192.168.17.15:22379} \
    --set allow.ipList=""
and this  my ectd configuration:
name: etcd0
data-dir: /root/etcd-v3.4.3-linux-amd64/data
listen-peer-urls: http://192.168.17.15:22380
listen-client-urls: http://192.168.17.15:22379,http://127.0.0.1:22379
initial-advertise-peer-urls: http://192.168.17.15:22380
advertise-client-urls: http://192.168.17.15:22379
initial-cluster: etcd0=http://192.168.17.15:22380
initial-cluster-state: new
initial-cluster-token: miosisp
enable-grpc-gateway: true

**Comment by tokers** [comment]
@zhangxiaohui123456 Could you try to log in to the apisix ingress controller container and connect to the apisix-admin service?

**Comment by zhangxiaohui123456** [comment]
> @zhangxiaohui123456 Could you try to log in to the apisix ingress controller container and connect to the apisix-admin service?

I use curl http://127.0.0.1:9180/apisix/admin/upstreams in pod of apisix-ingress-controller 
This is error info :
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty</center>
</body>
</html>
Is there a problem with my secret key? But I haven't changed the configuration

**Comment by zhangxiaohui123456** [comment]
> > @zhangxiaohui123456 Could you try to log in to the apisix ingress controller container and connect to the apisix-admin service?
> 
> I use curl http://127.0.0.1:9180/apisix/admin/upstreams in pod of apisix-ingress-controller
> This is error info :
> 
> <title>401 Authorization Required</title>
> # 401 Authorization Required
> openresty Is there a problem with my secret key? But I haven't changed the configuration

this is add info ----------------------------------------------
I went into Apisix's POD and looked at the Admin Key , It is exactly the same as the ADMIN_KEY in config.yaml in apisix-ingress-controller pod

**Comment by tokers** [comment]
> > @zhangxiaohui123456 Could you try to log in to the apisix ingress controller container and connect to the apisix-admin service?
> 
> I use curl http://127.0.0.1:9180/apisix/admin/upstreams in pod of apisix-ingress-controller
> This is error info :
> 
> <title>401 Authorization Required</title>
> # 401 Authorization Required
> openresty Is there a problem with my secret key? But I haven't changed the configuration

It's weird, the apisix isn't deployed with the apisix ingress controller in the same pod, so how did you access it from the `127.0.0.1` ...
