### ISSUE TITLE
Migrate charts to repo apisix-helm-charts

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#256]
### Issue description

The repo [apisix-helm-chart](https://github.com/apache/apisix-helm-chart) contains the charts of APISIX, APISIX Dashboard, we consider to put the chart for apisix-ingress-controller there for the unified maintain.

We should, create a new directory apisix-ingress-controller in apisix-helm-chart's charts directory. Add some documents in this repo to guide people link to [apisix-helm-chart](https://github.com/apache/apisix-helm-chart).

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by Junnplus** [comment]
I can do this.

**Comment by tokers** [comment]
@Junnplus Thanks for your contribution. Now it's time to close it.
