### ISSUE TITLE
Change the location of install.md

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#257]
### Issue description

Currently the [install.md](https://github.com/apache/apisix-ingress-controller/blob/master/docs/install.md) is in `doc/`, we can put it in the top level directory so people can see it easier.

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by stu01509** [comment]
Can I pick this issue?

**Comment by tokers** [comment]
@stu01509 Sure, assigned for you.
