### ISSUE TITLE
request help: ingress-ui

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#261]
### Issue description
The current version does not support interface operations,I wonder if you can provide an API or other form of direct interface control of the configuration of these Ingress.
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
@zhangxiaohui123456 Could you describe your demands more detailed?

**Comment by gxthrj** [comment]
@zhangxiaohui123456  We mainly support declarative configuration in this version. What kind of interface do you want? Can you give me an example?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long. If you want to use a GUI for control, you can use KUI, K9S, KubeSphere or Rancher, etc. I will close this issue. Feel free to reopen it, if you have any question.
