### ISSUE TITLE
docs: update the architecture diagram

### ISSUE THREAD

**Issue by membphis** [apache/apisix-ingress-controller#274]
![image](https://user-images.githubusercontent.com/6814606/109374178-521b4300-78ee-11eb-8315-4da896383f53.png)

**Comment by membphis** [comment]
@gxthrj if you need the source file, please let me know. I can provide it.

**Comment by iamayushdas** [comment]
Can you please be elaborative? What exactly to do.

**Comment by membphis** [comment]
We can submit a PR to replace the image of  `README.md`:

![image](https://user-images.githubusercontent.com/6814606/109386761-e6f65e80-7937-11eb-9a39-546ebe9e638f.png)

Update the image file `docs/assets/images/module-0.png`.

**Comment by gxthrj** [comment]
Great~ but we need some clarification about the different colored arrows in the picture.

**Comment by tokers** [comment]
Consider it to be resolved.
