### ISSUE TITLE
docs: add chinese version  of ducument

### ISSUE THREAD

**Issue by soulsoul** [apache/apisix-ingress-controller#278]
add  chinese version  of ducument

**Comment by gxthrj** [comment]
Thanks, but we don’t want us to maintain Chinese documents all the time, This will increase a lot of maintenance costs.
What other peoples think?

**Comment by tao12345666333** [comment]
> Thanks, but we don’t want us to maintain Chinese documents all the time, This will increase a lot of maintenance costs. What other peoples think?

+1

This issue has not been updated for too long, I will close it
