### ISSUE TITLE
architecture diagram 

### ISSUE THREAD

**Issue by membphis** [apache/apisix-ingress-controller#294]
how about change to this one?

![image](https://user-images.githubusercontent.com/6814606/110804201-e60be800-82ba-11eb-89dc-a18547d4d27e.png)

**Comment by soulsoul** [comment]
nice！

**Comment by tokers** [comment]
@soulsoul Would you like to submit a PR to change the diagram in README to this one? Thanks!

**Comment by soulsoul** [comment]
@tokers  ok

**Comment by membphis** [comment]
fixed already by #301
