### ISSUE TITLE
request help: Both v1 and v1beta of ingress are supported 

### ISSUE THREAD

**Issue by Junnplus** [apache/apisix-ingress-controller#295]
### Issue description

`IngressVersion` limits the support of only one version of ingress, why not both v1 and v1beta of ingress are supported

**Comment by tokers** [comment]
@Junnplus Kubernetes will create `v1` incarnation replica when you create a `v1beta1` version Ingress and vice versa. What the `--ingress-version` does is tell the controller use which version's informer and lister to serve.

**Comment by tokers** [comment]
@Junnplus Any problems?
