### ISSUE TITLE
I execute the yaml file in k8s and report such an error in the log on the controller

### ISSUE THREAD

**Issue by maxluo1992** [apache/apisix-ingress-controller#33]
I execute the yaml file in k8s and report such an error in the log on the controller.
ingress-controller error log:
E0917 16:16:11.276293       1 builder.go:154] solver upstream failed, find upstream from etcd failed, upstream: &{ID:<nil> FullName:0xc0004a4100 Group:0xc0004a4070 ResourceVersion:0xc0004a4080 Name:0xc0004a40d0 Type:0xc0004a4110 HashOn:<nil> Key:<nil> Nodes:[0xc00000f1a0] FromKind:<nil>}, err: list upstreams failed, err: http get failed, url: http://192.168.63.185:9180/apisix/admin/upstreams, err: status: 401, body: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty</center>
</body>
</html>

my yaml file:
``` yaml
apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  name: httpserver-route
  namespace: default
spec:
  rules:
  - host: test.apisix.apache.org
    http:
      paths:
      - backend:
          serviceName: nginx-web
          servicePort: 80
        path: /

**Comment by membphis** [comment]
please confirm if you have set the right admin key.

**Comment by maxluo1992** [comment]
I tried to find api7/ingress-controller to access the admin-key of APISIX, but I did not find the corresponding option in the config.json file, may I ask where to configure the admin-key

**Comment by membphis** [comment]
@gxthrj do you have time to take a look at this issue?

**Comment by gxthrj** [comment]
@maxluo1992 Now we do not support a way to config admin-key, I am not sure how to configure them when we use multi-APISIX cluster with `ingress.class` annotation. There should be many `admin-keys`. 

For now , I suggest you to remove the `admin-key` and use `allow_admin` to keep `Admin API` safe.

**Comment by gxthrj** [comment]
@maxluo1992  For now, apisix-ingress-controller do not support the config admin_key from Apache APISIX.
When using apisix-ingress-controller with APISIX, it is recommended to remove the admin_key setting. You can use allow_admin to restrict the access scope of the APISIX control plane to ensure security.

**Comment by gxthrj** [comment]
I will organize this description into the document.

**Comment by Bhanuji95** [comment]
Hi, I removed admin_key and used allow_admin settings as you suggested, but then the log message says **admin_key is missing**.

**Comment by moonming** [comment]
ping @gxthrj

**Comment by tokers** [comment]
Admin key should be stored in Kubernetes Secret, we should add secret informers to fetch them and use them when communicating with APISIX. @gxthrj @moonming @membphis

**Comment by gxthrj** [comment]
> Hi, I removed admin_key and used allow_admin settings as you suggested, but then the log message says **admin_key is missing**. Can you please suggest anything for my issue.

It is strange.
Please tell us what version of APISIX you are using. 
And show the `admin_key` section in `config.yaml` and `config-default.yaml`.

**Comment by gxthrj** [comment]
> Admin key should be stored in Kubernetes Secret, we should add secret informers to fetch them and use them when communicating with APISIX. @gxthrj @moonming @membphis

Yes, it is a way, but APISIX should know this secret, too. We can discuss this in #50 .

**Comment by Bhanuji95** [comment]
> It is strange.
> Please tell us what version of APISIX you are using.
> And show the `admin_key` section in `config.yaml` and `config-default.yaml`.

Hello, we used **apache/apisix:latest** image from docker hub and we completely commented out the admin_key part as below.

config-default.conf:
![tmp_1607439753475](https://user-images.githubusercontent.com/38535547/101500727-e1225a00-3994-11eb-88c1-354d4462b496.jpg)

config.yaml:
![tmp_1607439965466](https://user-images.githubusercontent.com/38535547/101500912-17f87000-3995-11eb-8244-beb4afd579b8.jpg)

**Comment by gxthrj** [comment]
I will try to reproduce with the latest version of APISIX

**Comment by membphis** [comment]
any news?

**Comment by gxthrj** [comment]
will update today

**Comment by tokers** [comment]
@maxluo1992 This is due to the lack of admin_key support, we will add some documents to tell users how to close APISIX's admin_key.

**Comment by tokers** [comment]
@maxluo1992 See the point 4 in https://github.com/apache/apisix-ingress-controller/blob/master/docs/FAQ.md.
