### ISSUE TITLE
chore: use PUT instead of PATCH when update resources in APISIX

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#339]
### Issue description
Now we use `PATCH` method to update resources in APISIX, but some behaviors are inconsistent with expectations.
For example, the key in SSL will not be encrypted when use `PATCH`.

**Comment by tokers** [comment]
@gxthrj Does this the bug in Apache APISIX?

**Comment by gxthrj** [comment]
> @gxthrj Does this the bug in Apache APISIX?

I think so, This leads to inconsistent admin API behavior. 
cc @spacewander

**Comment by tokers** [comment]
@gxthrj You may create an issue in APISIX repo and describe the details there.
