### ISSUE TITLE
getting  Error: apiVersion 'v2' is not valid. The value must be "v1" During installation 

### ISSUE THREAD

**Issue by mootezbessifi** [apache/apisix-ingress-controller#346]
Hi 
Am using helm 2.17.0 on top of k8s 1.17.4 and once performing the installation described here https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/kubesphere.md
I got `Error: apiVersion 'v2' is not valid. The value must be "v1"`

Could anyone help

**Comment by tokers** [comment]
@mootezbessifi In which step you met this problem?

**Comment by mootezbessifi** [comment]
@tokers once running the helm install command

**Comment by tokers** [comment]
> @tokers once running the helm install command

Which step? Installing APISIX or the ingress controller? Could you paste some screenshots here?

**Comment by tokers** [comment]
Well, the `apiVersion` in `Chart.yaml` is set to `v2` so you have to use helm version 3. Please try to upgrade your version. By the way, the helm v2 was deprecated.

**Comment by mootezbessifi** [comment]
anyway to run it using helm 2. since am not able to upgrade helm now ??
