### ISSUE TITLE
There is not a official docker image， someone can help build one？

### ISSUE THREAD

**Issue by zyxtomcat** [apache/apisix-ingress-controller#35]
I cann't find the official docker image anywhere, someone can help build one? Thanks

**Comment by gxthrj** [comment]
yes, It is best to upload to dockerhub.
and then replace the image [here](https://github.com/api7/ingress-controller/blob/1ec0f6c8ef7c412d8fc57d635eec8134317b64d3/samples/deploy/deployment/ingress-controller.yaml#L30)

**Comment by gxthrj** [comment]
@zyxtomcat I will donating api7/ingress-controller as a sub-project of Apache APISIX, the [discuss](donating api7/ingress-controller as a sub-project of Apache APISIX) is here. 

If all goes well, we will publish the image under the apache organization of dockerhub.

**Comment by tokers** [comment]
@zyxtomcat I have committed this PR to change the image.

https://github.com/apache/apisix-ingress-controller/pull/94

We use a temporary image (it works well) until we have the first apache release.
