### ISSUE TITLE
[DISCUSS] About donating api7/ingress-controller as a sub-project of Apache APISIX

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#36]
Hello everyone,

I am the founder of `api7/ingress-controller`.

Recently, more and more friends have paid attention to this project, and it has also been used by some companies in the production environment. But we know that `api7/ingress-controller` still has a lot of room for improvement. In order to make `api7/ingress-controller` more useful, I want to start discussing donating `api7/ingress-controller` as a sub-project of [Apache APISIX](https://github.com/apache/apisix).

the benefit are:

Embracing closely with the Apache community, attracting more people's attention and participation in contributing ingress-controller, we can continue to develop more features of ingress-controller.

and, I hope that any decision will be based on discussions with us, not a personal decision. Ensure that the direction of `ingress-controller` is correct.

If you have no objection, I will start writing a proposal.

Welcome to give me some feedback, thank you very much.

**Comment by moonming** [comment]
+1

**Comment by membphis** [comment]
agree +1

**Comment by tao12345666333** [comment]
It looks like it is now a sub-project of Apache APISIX.

**Comment by jxhsjxhs** [comment]
+1

**Comment by gxthrj** [comment]
OK， we can close this issue now.
