### ISSUE TITLE
bug: cannot set backend's weight to 0

### ISSUE THREAD

**Issue by ryan4yin** [apache/apisix-ingress-controller#368]
### Issue description

cannot set backend's weight to 0, ingress-controller will use `_defaultWeight` if `weight` is `0`.

maybe we should use `-1` to indicate the `_defaultWeight`? or just use `_defaultWeight` itself.

related codes:
- https://github.com/apache/apisix-ingress-controller/blob/master/pkg/kube/translation/apisix_route.go#L200
- https://github.com/apache/apisix-ingress-controller/blob/master/pkg/kube/translation/plugin.go#L41

### Environment

* apisix-ingress-controller: 0.5.0

**Comment by tokers** [comment]
@ryan4yin Thanks for your report, I think we should distinguish the zero weight and `nil` weight, it will be good if we use a pointer to point the `Weight` field.
