### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-ingress-controller#376]
### Issue description
My service were all deploy on k8s, This client address cannot be automatically resolved to upstream by apisix-ingress-conroller. It needs to be configured manually. You can configure the service name of k8s. But the name of the configuration service will report an error
![image](https://user-images.githubusercontent.com/52538259/114815165-41fceb80-9de8-11eb-8d57-a414cd4a5910.png)

I also tried node of upstream,but it said that apisix can only resolve the domain name from "/etc/resolv.conf"
![image](https://user-images.githubusercontent.com/52538259/114815223-5e008d00-9de8-11eb-8362-95d553a04972.png)

Now i have a little confusing is the specific interaction between apisix, apisix-ingress-controller, and k8s, The apisix-ingress-controller will automatically fetch all clients in K8 and automatically resolve to Apisix's upstream(each upstream is bound to a unique k8s service name and may have specific service tags, such as version, etc.). We can then route to the service directly by binding the resolved upstream ID to the route.

But it doesn't look like that at the moment, but it's not very clear on the doc。

**Comment by tokers** [comment]
Duplicated with #377 .
