### ISSUE TITLE
 client address cannot be automatically resolved to upstream by apisix-ingress-conroller

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-ingress-controller#377]
### Issue description
My service were all deploy on k8s, This client address cannot be automatically resolved to upstream by apisix-ingress-conroller. It needs to be configured manually. You can configure the service name of k8s. But the name of the configuration service will report an error
![image](https://user-images.githubusercontent.com/52538259/114815165-41fceb80-9de8-11eb-8d57-a414cd4a5910.png)

I also tried node of upstream,but it said that apisix can only resolve the domain name from "/etc/resolv.conf"
![image](https://user-images.githubusercontent.com/52538259/114815223-5e008d00-9de8-11eb-8362-95d553a04972.png)

Now i have a little confusing is the specific interaction between apisix, apisix-ingress-controller, and k8s, The apisix-ingress-controller will automatically fetch all clients in K8 and automatically resolve to Apisix's upstream(each upstream is bound to a unique k8s service name and may have specific service tags, such as version, etc.). We can then route to the service directly by binding the resolved upstream ID to the route.

But it doesn't look like that at the moment, but it's not very clear on the doc。

**Comment by tokers** [comment]
> Now i have a little confusing is the specific interaction between apisix, apisix-ingress-controller, and k8s, The apisix-ingress-controller will automatically fetch all clients in K8 and automatically resolve to Apisix's upstream(each upstream is bound to a unique k8s service name and may have specific service tags, such as version, etc.). We can then route to the service directly by binding the resolved upstream ID to the route.

What apisix-ingress-controller resolves is the Kubernetes Service Name/FQDN, not client address.

Client address is the remote IP address where the requests sent from. It can be configured as IPv4/IPv6/CIDR.

**Comment by Marco-Zheng** [comment]
> > Now i have a little confusing is the specific interaction between apisix, apisix-ingress-controller, and k8s, The apisix-ingress-controller will automatically fetch all clients in K8 and automatically resolve to Apisix's upstream(each upstream is bound to a unique k8s service name and may have specific service tags, such as version, etc.). We can then route to the service directly by binding the resolved upstream ID to the route.
> 
> What apisix-ingress-controller resolves is the Kubernetes Service Name/FQDN, not client address.
> 
> Client address is the remote IP address where the requests sent from. It can be configured as IPv4/IPv6/CIDR.

Here has a problem, i configure the route /patient/patient/* as below , but it also said that 404 Route Not Found
`curl -i -X GET http://ip:host/patient/patient/id -H "Host: httpbin.org" -H 'apikey: superSecretAPIKey'`
![image](https://user-images.githubusercontent.com/52538259/114843934-e6912480-9e0c-11eb-8fad-b5cf1930a488.png)

It was amazing that there had no route of `/get` which i was update to`/patient/patient/*` can get the reseult..
`curl -i -X GET http://ip:host/get -H "Host: httpbin.org" -H 'apikey: superSecretAPIKey'`
![Uploading image.png…]()

**Comment by tokers** [comment]
@Marco-Zheng How did you use your APISIX? If you use it by configuring objects in apisix-dashboard, you should submit issue to apisix repo.

If you're using apisix-ingress-controller, please paste related information like apisix-ingress-controller version, how you create this route (ApisixRoute or Ingress).

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng How did you use your APISIX? If you use it by configuring objects in apisix-dashboard, you should submit issue to apisix repo.
> 
> If you're using apisix-ingress-controller, please paste related information like apisix-ingress-controller version, how you create this route (ApisixRoute or Ingress).

Actually, i create the route on dashboard, but i tried to deploy the apisix and apisix dashboard only on aliyun server, it worked well, but i tried to use apisix-helm-chart and deploy all service, then meet that problem.

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng How did you use your APISIX? If you use it by configuring objects in apisix-dashboard, you should submit issue to apisix repo.
> 
> If you're using apisix-ingress-controller, please paste related information like apisix-ingress-controller version, how you create this route (ApisixRoute or Ingress).

I'm no sure which part cause this problem. i'll also submit issue to apisix repo

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng How did you use your APISIX? If you use it by configuring objects in apisix-dashboard, you should submit issue to apisix repo.
> 
> If you're using apisix-ingress-controller, please paste related information like apisix-ingress-controller version, how you create this route (ApisixRoute or Ingress).

There has an another question, may i know if can config the node domain/IP as below 
`medcloud-dev.dental-practice-patient`
![image](https://user-images.githubusercontent.com/52538259/114889641-dee97400-9e3c-11eb-96cd-831226ae8be1.png)
medcloud-dev is namespace of service 
dental-practice-patient is name of service
