### ISSUE TITLE
Add test cases to verify CRD schemas

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#387]
We may need some test cases to verify the CRD schemas.

**Comment by tao12345666333** [comment]
What do you mean specifically? What scenarios should we check the CRD schema?

**Comment by tokers** [comment]
Check whether the schema definition is correct or not.

**Comment by tao12345666333** [comment]
At present, we have upgraded the CRD version to v1 API, which uses openAPIV3Schema mandatory verification.

**Comment by tokers** [comment]
> At present, we have upgraded the CRD version to v1 API, which uses openAPIV3Schema mandatory verification.

I mean, we need some test cases to cover whether the definition of the schema itself are correct, say, we have a constraint on field `path`, it has to be started with "/", we may add some cases to cover the rule is correct.
