### ISSUE TITLE
request help: how to configure nginx param

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-ingress-controller#389]
### Issue description

May i know how to configure nginx param like `proxy-read-timeout` `proxy-body-size` ... in apisix ingress
![image](https://user-images.githubusercontent.com/52538259/115191119-96230b00-a11b-11eb-86c6-e6cc52a230d2.png)

**Comment by tokers** [comment]
@Marco-Zheng Currently we don't support so much annotations in `Ingress`, we have identical features in our own ApisixRoute resources but with the first-class support.

**Comment by tokers** [comment]
We also have plans to rich the Ingress resources by creating more and more annotations, these annotations will be similar to the one in Ingress Nginx but nor portable.

**Comment by Marco-Zheng** [comment]
> We also have plans to rich the Ingress resources by creating more and more annotations, these annotations will be similar to the one in Ingress Nginx but nor portable.

if there any similar config or plugin like `proxy-read-timeout` `proxy-body-size` in apisix?

**Comment by tokers** [comment]
> > We also have plans to rich the Ingress resources by creating more and more annotations, these annotations will be similar to the one in Ingress Nginx but nor portable.
> 
> if there any similar config or plugin like `proxy-read-timeout` `proxy-body-size` in apisix?

You can see this [document](http://apisix.apache.org/docs/ingress-controller/references/apisix_upstream) for more details.

**Comment by suninuni** [comment]
> > > We also have plans to rich the Ingress resources by creating more and more annotations, these annotations will be similar to the one in Ingress Nginx but nor portable.
> > 
> > 
> > if there any similar config or plugin like `proxy-read-timeout` `proxy-body-size` in apisix?
> 
> You can see this [document](http://apisix.apache.org/docs/ingress-controller/references/apisix_upstream) for more details.

@tokers I can't find any fields about nginx configs in CRD or plugins, but I find the global nginx configs in [Apisix](https://github.com/apache/apisix/blob/9c5ba9184ad000ee97afe808ade029f4bebc1771/docs/zh/latest/customize-nginx-configuration.md#L28), so is there anyway to config these in ApisixRoute?

![image](https://user-images.githubusercontent.com/7345529/129325635-ebdb02f9-69cd-4b77-8975-a0bf9bebbfca.png)

**Comment by tokers** [comment]
Currently we don't support configure Nginx Params in ApisixRoute @suninuni .
