### ISSUE TITLE
request help:  apply -f upstrem.yaml cannot find the service

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#403]
### Issue description
ingress-controller cannot discover services outside the default namespace
This is my upstream.yam configuration
``` yaml
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: web2
  namespace: gray-ns
spec:
  loadbalancer:
    type: chash
    hashOn: header
    key: "user-agent"
```
This is my env info
```
[root@host-172-21-9-35 CRD]# kubectl get service -n gray-ns
NAME   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
web2   NodePort   10.97.252.18     <none>        81:31261/TCP   95m
web3   NodePort   10.107.130.219   <none>        81:31877/TCP   64m
```
This is error log
···
2021-04-23T10:33:14+08:00       warn    controller/apisix_upstream.go:182       sync ApisixUpstream failed, will retry  {"object": {"Type":3,"Object":"default/web2","Tombstone":{"metadata":{"name":"web2","namespace":"default","selfLink":"/apis/apisix.apache.org/v1/namespaces/default/apisixupstreams/web2","uid":"e1fd33bf-5b04-4460-b9b6-dfb2db6183b3","resourceVersion":"38021690","generation":1,"creationTimestamp":"2021-04-23T02:31:51Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apisix.apache.org/v1\",\"kind\":\"ApisixUpstream\",\"metadata\":{\"annotations\":{},\"name\":\"web2\",\"namespace\":\"default\"},\"spec\":{\"loadbalancer\":{\"hashOn\":\"header\",\"key\":\"user-agent\",\"type\":\"chash\"}}}\n"}},"spec":{"loadbalancer":{"type":"chash","hashOn":"header","key":"user-agent"}}}}, "error": "service \"web2\" not found"}
···
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
As per the error log, your ApisixUpstream object was created in the **default** namespace, while the `web2` service is in `gray-ns` namespace.

> 2021-04-23T10:33:14+08:00 warn controller/apisix_upstream.go:182 sync ApisixUpstream failed, will retry {"object": {"Type":3,"Object":"default/web2","Tombstone":{"metadata":{"name":"web2","namespace":"**default**","selfLink":"/apis/apisix.apache.org/v1/namespaces/default/apisixupstreams/web2","uid":"e1fd33bf-5b04-4460-b9b6-dfb2db6183b3","resourceVersion":"38021690","generation":1,"creationTimestamp":"2021-04-23T02:31:51Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apisix.apache.org/v1","kind":"ApisixUpstream","metadata":{"annotations":{},"name":"web2","namespace":"default"},"spec":{"loadbalancer":{"hashOn":"header","key":"user-agent","type":"chash"}}}\n"}},"spec":{"loadbalancer":{"type":"chash","hashOn":"header","key":"user-agent"}}}}, "error": "service "web2" not found"}

**Comment by pioneer-hash** [comment]
> As per the error log, your ApisixUpstream object was created in the **default** namespace, while the `web2` service is in `gray-ns` namespace.
> 
> > 2021-04-23T10:33:14+08:00 warn controller/apisix_upstream.go:182 sync ApisixUpstream failed, will retry {"object": {"Type":3,"Object":"default/web2","Tombstone":{"metadata":{"name":"web2","namespace":"**default**","selfLink":"/apis/apisix.apache.org/v1/namespaces/default/apisixupstreams/web2","uid":"e1fd33bf-5b04-4460-b9b6-dfb2db6183b3","resourceVersion":"38021690","generation":1,"creationTimestamp":"2021-04-23T02:31:51Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apisix.apache.org/v1","kind":"ApisixUpstream","metadata":{"annotations":{},"name":"web2","namespace":"default"},"spec":{"loadbalancer":{"hashOn":"header","key":"user-agent","type":"chash"}}}\n"}},"spec":{"loadbalancer":{"type":"chash","hashOn":"header","key":"user-agent"}}}}, "error": "service "web2" not found"}

But my configuration specifies that the namespace is  gray-ns. 
```
[root@host-172-21-9-35 ~]# kubectl get au -n gray-ns
NAME   AGE
web2   30m
[root@host-172-21-9-35 ~]# kubectl describe  au web2  -n gray-ns
Name:         web2
Namespace:    gray-ns
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apisix.apache.org/v1","kind":"ApisixUpstream","metadata":{"annotations":{},"name":"web2","namespace":"gray-ns"},"spec":{"lo...
API Version:  apisix.apache.org/v1
Kind:         ApisixUpstream
Metadata:
  Creation Timestamp:  2021-04-23T02:35:11Z
  Generation:          1
  Resource Version:    38022730
  Self Link:           /apis/apisix.apache.org/v1/namespaces/gray-ns/apisixupstreams/web2
  UID:                 39436281-c440-42a3-b87d-26e7362268a1
Spec:
  Loadbalancer:
    Hash On:  header
    Key:      user-agent
    Type:     chash
Events:       <none>

```

**Comment by tokers** [comment]
@pioneer-hash Is there a `ApisixRoute` object named as `web2` in the default namespace, the error log might be occurred due to that resource.

**Comment by pioneer-hash** [comment]
> @pioneer-hash Is there an `ApisixRoute` object named as `web2` in the default namespace, the error log might be occurred due to that resource.

No, That's not the name , route name is  test-cookie-222
```
[root@host-172-21-9-35 CRD]# kubectl get ar -n gray-ns
NAME              AGE
test-cookie-222   144m
```
This is route.yaml
``` yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie-222
 namespace: gray-ns
spec:
 http:
 - name: rule1
   priority: 1
   match:
     paths:
       - /*
   backends:
     - serviceName: web3
       servicePort: 81
       weight: 70
     - serviceName: web2
       servicePort: 81
       weight: 30
 - name: rule2
   priority: 0
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: Equal
       value: zhangsan
     - subject:
         scope: Header
         name: name
       op: NotEqual
       value: lisi

   backend:
     serviceName: web2
     servicePort: 81

```

**Comment by tokers** [comment]
> > @pioneer-hash Is there an `ApisixRoute` object named as `web2` in the default namespace, the error log might be occurred due to that resource.
> 
> No, That's not the name , route name is test-cookie-222
> 
> ```
> [root@host-172-21-9-35 CRD]# kubectl get ar -n gray-ns
> NAME              AGE
> test-cookie-222   144m
> ```
> 
> This is route.yaml
> 
> ```yaml
> apiVersion: apisix.apache.org/v2alpha1
> kind: ApisixRoute
> metadata:
>  name: test-cookie-222
>  namespace: gray-ns
> spec:
>  http:
>  - name: rule1
>    priority: 1
>    match:
>      paths:
>        - /*
>    backends:
>      - serviceName: web3
>        servicePort: 81
>        weight: 70
>      - serviceName: web2
>        servicePort: 81
>        weight: 30
>  - name: rule2
>    priority: 0
>    match:
>      paths:
>        - /*
>      exprs:
>      - subject:
>          scope: Cookie
>          name: name
>        op: Equal
>        value: zhangsan
>      - subject:
>          scope: Header
>          name: name
>        op: NotEqual
>        value: lisi
> 
>    backend:
>      serviceName: web2
>      servicePort: 81
> ```

Sorry, my bad, I mean the `ApisixUpstream`.

**Comment by pioneer-hash** [comment]
> > > @pioneer-hash Is there an `ApisixRoute` object named as `web2` in the default namespace, the error log might be occurred due to that resource.
> > 
> > 
> > No, That's not the name , route name is test-cookie-222
> > ```
> > [root@host-172-21-9-35 CRD]# kubectl get ar -n gray-ns
> > NAME              AGE
> > test-cookie-222   144m
> > ```
> > 
> > 
> > This is route.yaml
> > ```yaml
> > apiVersion: apisix.apache.org/v2alpha1
> > kind: ApisixRoute
> > metadata:
> >  name: test-cookie-222
> >  namespace: gray-ns
> > spec:
> >  http:
> >  - name: rule1
> >    priority: 1
> >    match:
> >      paths:
> >        - /*
> >    backends:
> >      - serviceName: web3
> >        servicePort: 81
> >        weight: 70
> >      - serviceName: web2
> >        servicePort: 81
> >        weight: 30
> >  - name: rule2
> >    priority: 0
> >    match:
> >      paths:
> >        - /*
> >      exprs:
> >      - subject:
> >          scope: Cookie
> >          name: name
> >        op: Equal
> >        value: zhangsan
> >      - subject:
> >          scope: Header
> >          name: name
> >        op: NotEqual
> >        value: lisi
> > 
> >    backend:
> >      serviceName: web2
> >      servicePort: 81
> > ```
> 
> Sorry, my bad, I mean the `ApisixUpstream`.

I found that the upstream of Web2 was referenced first in the route.yaml configuration and then execute  apply -f upstream.yaml
Its success.
Is it because you have to do it in order？

**Comment by tokers** [comment]
No, it's not related with the order to create these to objects.

The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.

**Comment by pioneer-hash** [comment]
> No, it's not related with the order to create these to objects.
> 
> The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.

I'm sure not. The puzzle is that a reference to ApisixRoute will succeed in ApisixUpstream

**Comment by tokers** [comment]
> > No, it's not related with the order to create these to objects.
> 
> > 
> 
> > The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.
> 
> 
> 
> I'm sure not. The puzzle is that a reference to ApisixRoute will succeed in ApisixUpstream

So here we have two problems. Let's solve them one by one.

The first problem the apisix upstream is ineffective is because the corresponding service doesn't exist, this is a conclusion from your error log. I'm not sure whether this apisixupstream object was deleted so you said you are sure it doesn't exist.

**Comment by pioneer-hash** [comment]
> > > No, it's not related with the order to create these to objects.
> > 
> > 
> > > 
> > 
> > 
> > > The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.
> > 
> > 
> > I'm sure not. The puzzle is that a reference to ApisixRoute will succeed in ApisixUpstream
> 
> So here we have two problems. Let's solve them one by one.
> 
> The first problem the apisix upstream is ineffective is because the corresponding service doesn't exist, this is a conclusion from your error log. I'm not sure whether this apisixupstream object was deleted so you said you are sure it doesn't exist.

Previously, I set up this service called web2 in the default namespace ，Maybe I set up an ApisixUpstrem called web2. This has now been removed, and later apisixUpstreams have been created to specify the gray-ns namespace

**Comment by pioneer-hash** [comment]
> > > No, it's not related with the order to create these to objects.
> > 
> > 
> > > 
> > 
> > 
> > > The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.
> > 
> > 
> > I'm sure not. The puzzle is that a reference to ApisixRoute will succeed in ApisixUpstream
> 
> So here we have two problems. Let's solve them one by one.
> 
> The first problem the apisix upstream is ineffective is because the corresponding service doesn't exist, this is a conclusion from your error log. I'm not sure whether this apisixupstream object was deleted so you said you are sure it doesn't exist.

I recreated ApisixUpstream ，This is my configuration . Creating upstream that is not introduced by route will still report an error. As long as I reference to ApisixRoute about new serviename , I can synchronize successfully
```
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: web3
  namespace: gray-ns
spec:
  loadbalancer:
    type: chash
    hashOn: header
    key: "user-agent"
```
This is error.log
```
[root@host-172-21-9-35 ~]# kubectl logs  sitech-gray-ingress-controller-7779b6bd88-chpnm -n gray-publish | grep web3
2021-04-24T12:17:38+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"38550935","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-24T12:17:33+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"38550933"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
2021-04-24T12:17:56+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"38550935","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-24T12:17:33+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"38550933"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
2021-04-25T12:17:12+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"39043427","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-25T12:17:09+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"39043425"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
2021-04-25T12:17:30+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"39043427","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-25T12:17:09+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"39043425"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
2021-04-25T15:17:17+08:00       warn    apisix/upstream.go:114  upstream not found      {"fullname": "gray-ns_web3_81", "url": "http://sitech-gray-admin:9180/apisix/admin/upstreams/f95eb843", "cluster": ""}

```

**Comment by tokers** [comment]
> > > > No, it's not related with the order to create these to objects.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > The error log prompts that there is an `ApisixUpstream` object in the `default` namespace which named as `web2`. You should check it.
> > > 
> > > 
> > > I'm sure not. The puzzle is that a reference to ApisixRoute will succeed in ApisixUpstream
> > 
> > 
> > So here we have two problems. Let's solve them one by one.
> > The first problem the apisix upstream is ineffective is because the corresponding service doesn't exist, this is a conclusion from your error log. I'm not sure whether this apisixupstream object was deleted so you said you are sure it doesn't exist.
> 
> I recreated ApisixUpstream ，This is my configuration . Creating upstream that is not introduced by route will still report an error. As long as I reference to ApisixRoute about new serviename , I can synchronize successfully
> 
> ```
> apiVersion: apisix.apache.org/v1
> kind: ApisixUpstream
> metadata:
>   name: web3
>   namespace: gray-ns
> spec:
>   loadbalancer:
>     type: chash
>     hashOn: header
>     key: "user-agent"
> ```
> 
> This is error.log
> 
> ```
> [root@host-172-21-9-35 ~]# kubectl logs  sitech-gray-ingress-controller-7779b6bd88-chpnm -n gray-publish | grep web3
> 2021-04-24T12:17:38+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"38550935","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-24T12:17:33+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"38550933"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
> 2021-04-24T12:17:56+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"38550935","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-24T12:17:33+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"38550933"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
> 2021-04-25T12:17:12+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"39043427","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-25T12:17:09+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"39043425"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
> 2021-04-25T12:17:30+08:00       warn    controller/endpoint.go:169      sync endpoints failed, will retry       {"object": {"Type":2,"Object":{"metadata":{"name":"web3","namespace":"gray-ns","selfLink":"/api/v1/namespaces/gray-ns/endpoints/web3","uid":"fb474eea-e6da-485e-a1da-327017d9a92d","resourceVersion":"39043427","creationTimestamp":"2021-04-23T01:43:26Z","labels":{"app":"web3"},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2021-04-25T12:17:09+08:00"}},"subsets":[{"notReadyAddresses":[{"ip":"100.86.116.139","nodeName":"host-172-21-9-40","targetRef":{"kind":"Pod","namespace":"gray-ns","name":"web3-98c44d479-7ndh5","uid":"aa221851-49ce-49a4-9a0e-5cd335eb94bb","resourceVersion":"39043425"}}],"ports":[{"port":80,"protocol":"TCP"}]}]},"Tombstone":null}}
> 2021-04-25T15:17:17+08:00       warn    apisix/upstream.go:114  upstream not found      {"fullname": "gray-ns_web3_81", "url": "http://sitech-gray-admin:9180/apisix/admin/upstreams/f95eb843", "cluster": ""}
> ```

So the web3 service exists?

**Comment by tokers** [comment]
@pioneer-hash The newest logs pasted lost some vital contexts, please paste more logs so we can know why the synchronization of `endpoints` failed.

**Comment by tao12345666333** [comment]
This issue has not been updated for too long. Please try to update to the latest version to verify if there are still problems.

I will close this issue. Feel free to reopen it, if you have any question.
