### ISSUE TITLE
bug: Missing related consumer

### ISSUE THREAD

**Issue by kingGang** [apache/apisix-ingress-controller#404]
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
    # ./apisix-ingress-controller version --long
Version: 0.5.0
Git SHA: 
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
/ingress-apisix # ersion: 0.5.0
Git SHA: 
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
* your Kubernetes cluster version (output of `kubectl version`);
  ~# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
 uname -a
Linux apisix-apisix-ingress-controller-5bd45b5c5d-bx272 5.4.0-1043-azure #45~18.04.1-Ubuntu SMP Sat Mar 20 16:16:05 UTC 2021 x86_64 Linux
### Minimal test code / Steps to reproduce the issue

1.gui add cosumer config as follows:
{
  "username": "admin",
  "plugins": {
    "jwt-auth": {
      "disable": false,
      "exp": 86400,
      "key": "admin",
      "secret": "*******"
    }
  }
}
2. crd add route yaml file as follows:
  apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: syscode-route
  namespace: prod
spec:
  http:
    - name: syscode
      match:
        hosts:
        - syscode.lingo8.cn
        paths:
        - "/syscode/public/*"
      backends:
        - serviceName: syscode
          servicePort: 8009
          resolveGranularity: service
          weight: 1
      plugins:
          - name: jwt-auth
            enable: true
3. in cluster test pod request info:
   wget -S --header 'Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9vdCIsIm9pZCI6IjVhYzgyYzIyNDI0OTQ2Mjg3Y2IzYTcwMiIsInVpZCI6InJvb3QiLCJyb2xlX2lkIjpudWxsLCJub25jZV9zdHIiOiIiLCJrZXkiOiJhZG1
pbiIsImV4cCI6MTYxOTM4NTQ5NywiaXNzIjoiY2FyZWRhaWx5In0.rr_ZD3iSwrgyaP5zpWTDKTYXIM6MhOaPLoSMiLQOsQQ' -q -O - http://syscode.lingo8.cn/syscode/public/code?update_at=0
  HTTP/1.1 401 Unauthorized
wget: server returned error: HTTP/1.1 401 Unauthorized
4、postman request return:
{"message":"Missing related consumer"}

### What's the expected result?
The request can pass the verification

**Comment by tokers** [comment]
It seems that the consumer data are not synchronized to APISIX, could you paste the error.log in the APISIX container? It's in `/usr/local/apisix/logs/error.log`. You can execute the following like command to fetch it:

```
kubectl exec -n {namespace} {apisix pod name} -- cat /usr/local/apisix/logs/error.log
```

**Comment by kingGang** [comment]
> It seems that the consumer data are not synchronized to APISIX, could you paste the error.log in the APISIX container? It's in `/usr/local/apisix/logs/error.log`. You can execute the following like command to fetch it:
> 
> ```
> kubectl exec -n {namespace} {apisix pod name} -- cat /usr/local/apisix/logs/error.log
> ```

**No error logs**
kubectl exec -n ingress-apisix apisix-57bd6d8969-85rsn -- cat /usr/local/apisix/logs/error.log
Defaulted container "apisix" out of: apisix, wait-etcd (init)

**Comment by tokers** [comment]
> > It seems that the consumer data are not synchronized to APISIX, could you paste the error.log in the APISIX container? It's in `/usr/local/apisix/logs/error.log`. You can execute the following like command to fetch it:
> 
> > 
> 
> > ```
> 
> > kubectl exec -n {namespace} {apisix pod name} -- cat /usr/local/apisix/logs/error.log
> 
> > ```
> 
> 
> 
> **No error logs**
> 
> kubectl exec -n ingress-apisix apisix-57bd6d8969-85rsn -- cat /usr/local/apisix/logs/error.log
> 
> Defaulted container "apisix" out of: apisix, wait-etcd (init)
> 
> 
> 
> 
> 
> 

Your pod is still in initial, the init container is running.

**Comment by tokers** [comment]
@kingGang By the way, could you supplement the issue title, so that people can easily find this issue when they searching similar problems in search engines.

**Comment by tokers** [comment]
> 我检查了apisxi etcd host配置，并没有发现错误，我现在需要怎么去排查问题？
> 
> # cat config.yaml |grep etcd
> 
>   config_center: etcd             # etcd: use etcd to store the config value
> 
> etcd:
> 
>   host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
> 
>     - "http://apisix-etcd.ingress-apisix.svc.cluster.local:2379"
> 
>    

We need the error.log contents in apisix container.

**Comment by kingGang** [comment]
> > 我检查了apisxi etcd host配置，并没有发现错误，我现在需要怎么去排查问题？
> > # cat config.yaml |grep etcd
> > config_center: etcd             # etcd: use etcd to store the config value
> > etcd:
> > host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
> > ```
> > - "http://apisix-etcd.ingress-apisix.svc.cluster.local:2379"
> > ```
> 
> We need the error.log contents in apisix container.

因为我之前删掉过apisix的 pod， 后面在进去到容器内，看查询的日志内容只有一条“Defaulted container "apisix" out of: apisix, wait-etcd (init)”

**Comment by kingGang** [comment]
我重新添加consumer apisix报错，错误信息如下
 *191165894 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/consumers] err:additional properties forbidden, found id,  etcd key: /apisix/consumers, context: ngx.timer

**Comment by tokers** [comment]
> 我重新添加consumer apisix报错，错误信息如下
> *191165894 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/consumers] err:additional properties forbidden, found id, etcd key: /apisix/consumers, context: ngx.timer

What's the version of apisix-dashboard and apisix?

**Comment by kingGang** [comment]
> > 我重新添加consumer apisix报错，错误信息如下
> > *191165894 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/consumers] err:additional properties forbidden, found id, etcd key: /apisix/consumers, context: ngx.timer
> 
> What's the version of apisix-dashboard and apisix?

# apisix version
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.5
/manager-api --version
Version : 2.5
GitHash : 448e980
/usr/local/apisix-dashboard # ersion
Version : 2.5
GitHash : 448e980

**Comment by tokers** [comment]
> > > 我重新添加consumer apisix报错，错误信息如下
> > > *191165894 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/consumers] err:additional properties forbidden, found id, etcd key: /apisix/consumers, context: ngx.timer
> > 
> > 
> > What's the version of apisix-dashboard and apisix?
> 
> # apisix version
> /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
> 2.5
> /manager-api --version
> Version : 2.5
> GitHash : 448e980
> /usr/local/apisix-dashboard # ersion
> Version : 2.5
> GitHash : 448e980

Well, actually if you're using apisix/2.5, you should use the apisix-dashboard `2.6`. Have you ever seen error message like "mismatched version of apisix and apisix-dashboard" when you open apisix-dashboard.

**Comment by iamayushdas** [comment]
@kingGang if the your issue is resolved , kindly close the issue
