### ISSUE TITLE
request help:  Multi-tenancy scenario solution

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#405]
### Issue description
Here's a scenario ：I need two sets of environment, mobile and PC, and I want to keep them apart ,Similar to the previous Apisix, two gateways were deployed.If I  install  a  apisix-ingress-controller ， can't differentiate by context. If I install two Apisix-Ingress-Controllers, which Apisix-Ingress-Controller will handle it when I create a CRD resource? I hope we can discuss it
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
You can set up namespace isolation for different customers, and configuring different watching namespaces for apisix-ingress-controller.

**Comment by iamayushdas** [comment]
@pioneer-hash can you close the issue if that its resolved?
Thank you

**Comment by tao12345666333** [comment]
This issue has not been updated for too long. As mentioned above, you can deploy them in different namespaces, and you can isolate them by setting their watch namespace.

I will close this issue. Feel free to reopen it, if you have any question.
