### ISSUE TITLE
bug: The upstream associated with other routes cannot be deleted, and the delete event keeps retrying

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#421]
### Issue description
controller log as below:
![image](https://user-images.githubusercontent.com/7134928/117293086-8b9a9c80-aea3-11eb-9177-601820ac6e95.png)

upstream delete failed, The delete event is added to the queue again.

### Environment

* apisix-ingress-controller version:  v0.5.0
* Kubernetes cluster version: v1.16.9

### Minimal test code / Steps to reproduce the issue
1.  create apisix route,  service field references an existing k8s service.
2. delete apisix route resouce 

### What's the actual result? (including assertion message & call stack if applicable)
the delete event keeps retrying....

### What's the expected result?
ignore related upstream

![image](https://user-images.githubusercontent.com/7134928/117294155-e8e31d80-aea4-11eb-9913-2d82ca71a865.png)
add resp.StatusCode != 400  condition  ?

**Comment by tokers** [comment]
We may need to handle the given error from the caching operation.

**Comment by tokers** [comment]
> We may need to handle the given error from the caching operation.

Ignore this please.

**Comment by tokers** [comment]
@Donghui0 Thanks for your report, I have captured the root reason about this bug, I will fix it.
