### ISSUE TITLE
bug: ingress routing resource manifest file does not take effect 路由的资源清单文件不生效

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-ingress-controller#423]
### Issue description
添加路由的资源清单文件如下：
![image](https://user-images.githubusercontent.com/52538259/117444743-750c4800-af6c-11eb-9767-f4249b423e57.png)
apisix-gateway使用nodeport形式访问关联到slb的出口上
然后test1.laoganma.fun解析到slb的公网出口地址
浏览器访问域名服务
![image](https://user-images.githubusercontent.com/52538259/117444757-7b022900-af6c-11eb-88c0-422c98653a78.png)

**Comment by tokers** [comment]
@Marco-Zheng By default apisix-ingress-controller watches ingress in networking/v1, you should adjust the command line option `--ingress-version`, see https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml#L50 for details.

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng Much information is required to troubleshoot this problem.
> 
> * apisix-ingress-controller and apisix verison
> * command options to launch apisix-ingress-controller
> * error log of apisix-ingress-controller

apisix-ingress-controller：0.5.0
apisix：2.4-alpine
让资源路由规则生效的命令：kubectl apply -f route.yaml
日志：

> @Marco-Zheng By default apisix-ingress-controller watches ingress in networking/v1, you should adjust the command line option `--ingress-version`, see https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml#L50 for details.

Thanks, i'll try it, our company's k8s version is v1beta1, so you means the `config-default.yaml` must configure with `v1beta1`,but here comes a problem, we install ingress by helm-chart, and there has no file named `config-default.yaml`

below is the dictionary file tree for apisix-ingress-comtroller

![image](https://user-images.githubusercontent.com/52538259/117530820-d0444600-b011-11eb-8624-c5a614b2e8de.png)

**Comment by tokers** [comment]
@Marco-Zheng You can pass options to helm.

```
helm install apisix-ingress-controller ....
--set config.kubernetes.ingressVersion=networking/v1beta1
```

**Comment by Marco-Zheng** [comment]
> helm install apisix-ingress-controller ....
> --set config.kubernetes.ingressVersion=networking/v1beta1

I tried above option, but still didn't work, then i searched `ingressVersion` in all files, but not found, i also checked the

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng You can pass options to helm.
> 
> ```
> helm install apisix-ingress-controller ....
> --set config.kubernetes.ingressVersion=networking/v1beta1
> ```

Here is the full k8s resource file 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 6e32bfa01c440f5d4d34f1094abc6e7fbcd1984f2deca1a877a90cba9e15c96d
    tke.cloud.tencent.com/networks-status: |-
      [{
          "name": "tke-bridge",
          "ips": [
              "172.20.9.196"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2021-05-08T08:09:34Z"
  generateName: apisix-ingress-controller-7fd57594c7-
  labels:
    app.kubernetes.io/instance: apisix-ingress-controller
    app.kubernetes.io/name: apisix-ingress-controller
    pod-template-hash: 7fd57594c7
  name: apisix-ingress-controller-7fd57594c7-4jkld
  namespace: ingress-apisix
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apisix-ingress-controller-7fd57594c7
    uid: 0881ce5e-843a-474b-bb2b-d526200c5056
  resourceVersion: "7545642640"
  selfLink: /api/v1/namespaces/ingress-apisix/pods/apisix-ingress-controller-7fd57594c7-4jkld
  uid: ae110355-7b70-48e0-ba6e-f976559c6666
spec:
  containers:
  - command:
    - /ingress-apisix/apisix-ingress-controller
    - ingress
    - --config-path
    - /ingress-apisix/conf/config.yaml
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: apache/apisix-ingress-controller:0.5.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: apisix-ingress-controller
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /ingress-apisix/conf
      name: configuration
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: apisix-ingress-controller-token-lflw7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 192.168.52.10
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: apisix-ingress-controller
  serviceAccountName: apisix-ingress-controller
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: config.yaml
        path: config.yaml
      name: apisix-ingress-controller-configmap
    name: configuration
  - name: apisix-ingress-controller-token-lflw7
    secret:
      defaultMode: 420
      secretName: apisix-ingress-controller-token-lflw7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-08T08:09:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-08T08:09:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-08T08:09:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-08T08:09:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ec5f5d9ad5957943214485c3f2405e2825c417ae35d8e25b1e056b9b04cbbd03
    image: apache/apisix-ingress-controller:0.5.0
    imageID: docker-pullable://apache/apisix-ingress-controller@sha256:f67259591782661714444c85150b59db534de908312d4f4ededd922557451602
    lastState: {}
    name: apisix-ingress-controller
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-08T08:09:40Z"
  hostIP: 192.168.52.10
  phase: Running
  podIP: 172.20.9.196
  podIPs:
  - ip: 172.20.9.196
  qosClass: BestEffort
  startTime: "2021-05-08T08:09:34Z"
```

**Comment by tokers** [comment]
@Marco-Zheng Configurations are in configmap. Please check it out. Also, please tell us what's the version of apisix-ingress-controller.

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng Configurations are in configmap. Please check it out. Also, please tell us what's the version of apisix-ingress-controller.

Our version is 
```
apisix-ingress-controller：0.5.0
apisix：2.4-alpine
```

Here is the comfigmap
```
apiVersion: v1
data:
  config.yaml: |
    # log options
    log_level: "info"
    log_output: "stderr"
    http_listen: ":8080"
    enable_profiling: true
    kubernetes:
      kubeconfig: ""
      resync_interval: "60s"
      app_namespaces:
      - "*"
    apisix:
      base_url: "http://xxxxxx:9180/apisix/admin"
      admin_key: "edd1c9f034335f136f87ad84b625c8f1"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: apisix-ingress-controller
    meta.helm.sh/release-namespace: ingress-apisix
  creationTimestamp: "2021-05-08T08:09:34Z"
  labels:
    app.kubernetes.io/instance: apisix-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: apisix-ingress-controller-0.3.0
  name: apisix-ingress-controller-configmap
  namespace: ingress-apisix
  resourceVersion: "7545638850"
  selfLink: /api/v1/namespaces/ingress-apisix/configmaps/apisix-ingress-controller-configmap
  uid: 74524651-7a57-4d6d-a894-2f0b4715e11a
```

**Comment by tokers** [comment]
> ```
> apiVersion: v1
> data:
>   config.yaml: |
>     # log options
>     log_level: "info"
>     log_output: "stderr"
>     http_listen: ":8080"
>     enable_profiling: true
>     kubernetes:
>       kubeconfig: ""
>       resync_interval: "60s"
>       app_namespaces:
>       - "*"
>     apisix:
>       base_url: "http://xxxxxx:9180/apisix/admin"
>       admin_key: "edd1c9f034335f136f87ad84b625c8f1"
> kind: ConfigMap
> metadata:
>   annotations:
>     meta.helm.sh/release-name: apisix-ingress-controller
>     meta.helm.sh/release-namespace: ingress-apisix
>   creationTimestamp: "2021-05-08T08:09:34Z"
>   labels:
>     app.kubernetes.io/instance: apisix-ingress-controller
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: apisix-ingress-controller
>     app.kubernetes.io/version: 0.4.0
>     helm.sh/chart: apisix-ingress-controller-0.3.0
>   name: apisix-ingress-controller-configmap
>   namespace: ingress-apisix
>   resourceVersion: "7545638850"
>   selfLink: /api/v1/namespaces/ingress-apisix/configmaps/apisix-ingress-controller-configmap
>   uid: 74524651-7a57-4d6d-a894-2f0b4715e11a
> ```

```
apiVersion: v1
data:
  config.yaml: |
    # log options
    log_level: "info"
    log_output: "stderr"
    http_listen: ":8080"
    enable_profiling: true
    kubernetes:
      kubeconfig: ""
      resync_interval: "60s"
      **ingressVersion: networking/v1beta1**
      app_namespaces:
      - "*"
    apisix:
      base_url: "http://xxxxxx:9180/apisix/admin"
      admin_key: "edd1c9f034335f136f87ad84b625c8f1"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: apisix-ingress-controller
    meta.helm.sh/release-namespace: ingress-apisix
  creationTimestamp: "2021-05-08T08:09:34Z"
  labels:
    app.kubernetes.io/instance: apisix-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: apisix-ingress-controller-0.3.0
  name: apisix-ingress-controller-configmap
  namespace: ingress-apisix
  resourceVersion: "7545638850"
  selfLink: /api/v1/namespaces/ingress-apisix/configmaps/apisix-ingress-controller-configmap
  uid: 74524651-7a57-4d6d-a894-2f0b4715e11a
```

**Comment by tokers** [comment]
@Marco-Zheng Any suspicious error logs?

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng Any suspicious error logs?

Here is apisix log 
![image](https://user-images.githubusercontent.com/52538259/117753983-02d98300-b24c-11eb-85c8-bb5a96745041.png)
and here is apisix-ingress-controller log
![image](https://user-images.githubusercontent.com/52538259/117754009-108f0880-b24c-11eb-828c-54ae93981621.png)
no error was found, but I found a strange thing per the first log , i send request to 
![image](https://user-images.githubusercontent.com/52538259/117754150-577cfe00-b24c-11eb-877d-1524709b34ad.png)
but it seems to visit another place
![image](https://user-images.githubusercontent.com/52538259/117754187-7085af00-b24c-11eb-943a-ca9dca30dd71.png)

**Comment by Marco-Zheng** [comment]
> > > > > @Marco-Zheng Any suspicious error logs?
> > > > 
> > > > 
> > > > How does ingress work? If ingress parsing route yaml and store the route in etcd? how can we know the route.yaml is efficient
> > > 
> > > 
> > > In newest version (0.6), we record events and status for each ApisixRoute and ApisixUpstream, and error reason will be enrolled there.
> > 
> > 
> > so i need change a version to 0.6.0? if these version can match the apisix2.4?
> 
> 0.6.0 is in the progress of vote, it will be released in few days. We should use `2.5` or later APISIX to match it.

Do you have any idea or advise for that case? I had reviewed my configuration by checking your configure doc, but i still have no idea about it.

![image](https://user-images.githubusercontent.com/52538259/117909889-9c1c9e00-b30d-11eb-804b-6014f477c9a1.png)

**Comment by tokers** [comment]
@Marco-Zheng The `0.5.0` apisix-ingress-controller release doesn't contain the event and status feedback, Is it convenient for you to change the log level of apisix-ingress-controller to debug, we may get some clues from these debug logs.

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng The `0.5.0` apisix-ingress-controller release doesn't contain the event and status feedback, Is it convenient for you to change the log level of apisix-ingress-controller to debug, we may get some clues from these debug logs.

I change the log to debug and the logs as below 
![image](https://user-images.githubusercontent.com/52538259/117934361-304e2b80-b335-11eb-860b-86392eeaa5ec.png)

**Comment by tokers** [comment]
![image](https://user-images.githubusercontent.com/10428333/117937212-51644b80-b338-11eb-82bc-76d9f66cfb22.png)
It seems your apisix-ingress-controller still tries to watch the Ingress in networking/v1.

**Comment by Marco-Zheng** [comment]
> ![image](https://user-images.githubusercontent.com/10428333/117937212-51644b80-b338-11eb-82bc-76d9f66cfb22.png)
> It seems your apisix-ingress-controller still tries to watch the Ingress in networking/v1.

I have reconfirmed my config and follow below file
![image](https://user-images.githubusercontent.com/52538259/117946937-53330c80-b342-11eb-97d7-611f03a4ce6d.png)
change my file to 
![image](https://user-images.githubusercontent.com/52538259/117947307-a7d68780-b342-11eb-8f9d-e0b608133d11.png)
coud you please help me to check again, i try to change `apisix.apache.org/v1` to `apisix.apache.org/v1beta1`
but failed,  here is config map,  i don't know why it's still inoperative


![image](https://user-images.githubusercontent.com/52538259/117948183-7611f080-b343-11eb-8b5a-5fcdd79b13fa.png)

**Comment by tokers** [comment]
@tokers This is the version for [Kubernetes Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/).

**Comment by Marco-Zheng** [comment]
> @tokers This is the version for [Kubernetes Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/).

Yes, as you can see the config map version is `v1beta1` now, and apisix route.yaml as above, and i try all methods to let it works, but failed, i add the route in apisix dashboard, it can work well..

**Comment by tokers** [comment]
> > @tokers This is the version for [Kubernetes Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/).
> 
> 
> 
> Yes, as you can see the config map version is `v1beta1` now, and apisix route.yaml as above, and i try all methods to let it works, but failed, i add the route in apisix dashboard, it can work well..

What you configured is not ingress but the apisix route.

**Comment by Marco-Zheng** [comment]
> > > @tokers This is the version for [Kubernetes Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/).
> > 
> > 
> > Yes, as you can see the config map version is `v1beta1` now, and apisix route.yaml as above, and i try all methods to let it works, but failed, i add the route in apisix dashboard, it can work well..
> 
> What you configured is not ingress but the apisix route.

below configure also failed to send request, as you mentioned before, the log still print networking/v1, but the configmap actually is v1beta1, does any other config will influence it  
![image](https://user-images.githubusercontent.com/52538259/117980851-f72eaf00-b366-11eb-90f5-3ac175a48441.png)

**Comment by tokers** [comment]
> > > > @tokers This is the version for [Kubernetes Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/).
> 
> > > 
> 
> > > 
> 
> > > Yes, as you can see the config map version is `v1beta1` now, and apisix route.yaml as above, and i try all methods to let it works, but failed, i add the route in apisix dashboard, it can work well..
> 
> > 
> 
> > What you configured is not ingress but the apisix route.
> 
> 
> 
> below configure also failed to send request, as you mentioned before, the log still print networking/v1, but the configmap actually is v1beta1, does any other config will influence it  
> 
> ![image](https://user-images.githubusercontent.com/52538259/117980851-f72eaf00-b366-11eb-90f5-3ac175a48441.png)
> 
> 
> 
> 

OK, let me try to reproduce it.

**Comment by Marco-Zheng** [comment]
> OK, let me try to reproduce it.

Thanks a lot

**Comment by tao12345666333** [comment]
@Marco-Zheng any update?

**Comment by tokers** [comment]
@Marco-Zheng Sorry for the long delay. I have tried to reproduce this problem on my side with apisix-ingress-controller/1.0, but I cannot reproduce this scenario, could you please try to use the apisix-ingress-controller/1.0 again and see whether this problem still exists.

**Comment by Marco-Zheng** [comment]
@tao12345666333 not yet

**Comment by Marco-Zheng** [comment]
@tokers i add a `httpserver-route` in namespace `ingress-apisix`
![image](https://user-images.githubusercontent.com/52538259/123765173-132ae780-d8f8-11eb-9b26-b4637898f508.png)
```
apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  namespace: ingress-apisix
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backend:
        serviceName: httpbin
        servicePort: 80
```
then use `kubectl exec -it -n ingress-apisix apisix-6b6cfdd678-j24hx -- curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'`, no route was found 
![image](https://user-images.githubusercontent.com/52538259/123765360-40779580-d8f8-11eb-8607-d3fb10eab0f3.png)

could you please explain to it , any problem with my yml?

**Comment by Marco-Zheng** [comment]
My expect result is route create by my yml, and i can search route in apisix-dashboard, but nothing was found.

**Comment by tokers** [comment]
@Marco-Zheng Please use the `ApisixRoute/v2alpha1`, the v1 version was deprecated and obsolete.

**Comment by Marco-Zheng** [comment]
@tokers kubernate create -f xxx.yml was failed when i use ApisixRoute/v2alpha1, the version of my ingress-controller is 0.6.0
and apisix version is 2.7, doesn't this problem belongs to version?

**Comment by Marco-Zheng** [comment]
@tokers kubernate create -f xxx.yml was failed when i use ApisixRoute/v2alpha1, the version of my ingress-controller is 0.6.0
and apisix version is 2.7, perhaps this problem belongs to version?

**Comment by tokers** [comment]
> @tokers kubernate create -f xxx.yml was failed when i use ApisixRoute/v2alpha1, the version of my ingress-controller is 0.6.0
> and apisix version is 2.7, perhaps this problem belongs to version?

Oh, these two versions are not a good pair. You may try to update APISIX Ingress Controller.

BTW, what is the error reported by kubectl.

**Comment by Marco-Zheng** [comment]
@tokers It's shown as below 
```
error: unable to recognize "httpbin-route.yaml": no matches for kind "ApisixRoute/v2alpha1" in version "apisix.apache.org/v1"
```

**Comment by Marco-Zheng** [comment]
@tokers Is 1.0.0 the right version

**Comment by tokers** [comment]
You should apply all the CRDs provided in this repo before you create resources.

**Comment by Marco-Zheng** [comment]
@tokers do you means i need create apisix crds although we have apisix server in k8s? any example for this?

**Comment by tao12345666333** [comment]
@Marco-Zheng  Please try to execute the following command `kubectl apply -k samples/deploy/crd/v1beta1/`

```
➜  apisix-ingress-controller git:(master) ✗ kubectl apply -k samples/deploy/crd/v1beta1/
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/apisixclusterconfigs.apisix.apache.org created
customresourcedefinition.apiextensions.k8s.io/apisixconsumers.apisix.apache.org created
customresourcedefinition.apiextensions.k8s.io/apisixroutes.apisix.apache.org created
customresourcedefinition.apiextensions.k8s.io/apisixtlses.apisix.apache.org created
customresourcedefinition.apiextensions.k8s.io/apisixupstreams.apisix.apache.org created
```

**Comment by Marco-Zheng** [comment]
@tao12345666333 thx for your reply, i have executed this command
![image](https://user-images.githubusercontent.com/52538259/123894723-3a81c300-d991-11eb-8f28-19f3e83d28fb.png)
@tokers Hi, i apply all the CRDs, then execute `kubectl apply -f httpbin-route.yaml` again, it was successed, but when i 
use `kubectl exec -it -n ingress-apisix apisix-6b6cfdd678-gqrsx -- curl`, it shown below info
```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
curl: try 'curl --help' or 'curl --manual' for more information
command terminated with exit code 2
```
![image](https://user-images.githubusercontent.com/52538259/123894982-aebc6680-d991-11eb-873c-0ef1845f968b.png)

**Comment by Marco-Zheng** [comment]
it is success to register route , thx all
![image](https://user-images.githubusercontent.com/52538259/123897809-aca8d680-d996-11eb-8945-7fd81005e777.png)

**Comment by tokers** [comment]
@Marco-Zheng You're welcome.
