### ISSUE TITLE
bug: status update is failed

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#434]
### Issue description

Error log was reported when I run e2e test cases:

> 2021-05-11T14:52:56+08:00       error   ingress/status.go:91    failed to record status change for ApisixRoute  {"error": "apisixroutes.apisix.apache.org \"httpbin\" is forbidden: User \"system:serviceaccount:ingress-apisix-e2e-tests-default-300957000:ingress-apisix-e2e-test-service-account\" cannot update resource \"apisixroutes/status\" in API group \"apisix.apache.org\" in the namespace \"ingress-apisix-e2e-tests-default-300957000\"", "name": "httpbin", "namespace": "ingress-apisix-e2e-tests-default-300957000"}

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`); 0.6.0
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### What's the actual result? (including assertion message & call stack if applicable)

Error log was reported, status update is failed, so we cannot see them when using `kubectl describe`.

### What's the expected result?

No error log was shown and status can be seen normally.

**Comment by gxthrj** [comment]
I will check it.

**Comment by tokers** [comment]
@gxthrj Please describe the error reason here after you capture this bug.

**Comment by tokers** [comment]
Fixed.
