### ISSUE TITLE
request help: annotations, k8s.apisix.apache.org/whitelist-source-range not work

### ISSUE THREAD

**Issue by shuoshadow** [apache/apisix-ingress-controller#436]
### Issue description
![image](https://user-images.githubusercontent.com/10016360/117916459-c70cef00-b319-11eb-8e9b-dcdfe95a4bbe.png)

![image](https://user-images.githubusercontent.com/10016360/117916555-f91e5100-b319-11eb-8459-cdbcbeb4f3b2.png)

i set the whitelist annotation, but i can still access the domain.
### Environment

Version: 0.5.0
Git SHA:
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64

Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"d2f5a0f", GitTreeState:"", BuildDate:"2020-11-17T03:28:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"5959bcb", GitTreeState:"", BuildDate:"2021-03-11T11:16:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tokers** [comment]
@shuoshadow That's a known bug, will fix it as soon as possible.

**Comment by shuoshadow** [comment]
> remoteAddrs

**Comment by shuoshadow** [comment]
> ### Issue description
> ![image](https://user-images.githubusercontent.com/10016360/117916459-c70cef00-b319-11eb-8e9b-dcdfe95a4bbe.png)
> 
> ![image](https://user-images.githubusercontent.com/10016360/117916555-f91e5100-b319-11eb-8459-cdbcbeb4f3b2.png)
> 
> i set the whitelist annotation, but i can still access the domain.
> 
> ### Environment
> Version: 0.5.0
> Git SHA:
> Go Version: go1.13.8
> Building OS/Arch: linux/amd64
> Running OS/Arch: linux/amd64
> 
> Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"d2f5a0f", GitTreeState:"", BuildDate:"2020-11-17T03:28:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"5959bcb", GitTreeState:"", BuildDate:"2021-03-11T11:16:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}



> @shuoshadow That's a known bug, we will add it to the ingress resource, for the ApisixRoute, you can just configure the `remoteAddrs` field, see http://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2alpha1 (there is a typo that `remoteAddrs` was written as `remote_addrs`).

I configure the field, but the return code is 404, is that right?
![image](https://user-images.githubusercontent.com/10016360/117926216-ff68f900-b32a-11eb-8ba5-708175904b87.png)
![image](https://user-images.githubusercontent.com/10016360/117926139-dea0a380-b32a-11eb-9c50-73bca38f97f6.png)

**Comment by tokers** [comment]
@shuoshadow Yes, the `remoteAddrs` is set as the route match condition.

If this is not what you desired, may be you can set up the ip-restriction plugin, you can see this [test](https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/plugins/ip-restriction.go#L36) as the guide.

**Comment by tao12345666333** [comment]
any update?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I will close it. If your issue is not resolved, feel free to reopen it, or create a new issue
