### ISSUE TITLE
request help: how to configure ssl 

### ISSUE THREAD

**Issue by shuoshadow** [apache/apisix-ingress-controller#440]
### Issue description
I set redirect plugin: http-to-https. and create apisixtls resource

![image](https://user-images.githubusercontent.com/10016360/117944868-4ca39580-b340-11eb-8f93-6efa6009e3c6.png)
![image](https://user-images.githubusercontent.com/10016360/117944638-10703500-b340-11eb-8a46-a7c57b408a49.png)

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by shuoshadow** [comment]
apisix-ingress-controller  error log

![image](https://user-images.githubusercontent.com/10016360/117953518-a90ab300-b348-11eb-927a-b2df50691308.png)

**Comment by gxthrj** [comment]
@shuoshadow  The secret referenced in ApisixTls needs to be defined. In your environment, it is the `xxx-secret` under the `ingress-apisix` namespace.

The secret need to contains `cert` and `key`, There is a template in https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/scaffold/ssl.go#L26-L33.

We will add this piece of documentation soon.

**Comment by shuoshadow** [comment]
> @shuoshadow The secret referenced in ApisixTls needs to be defined. In your environment, it is the `xxx-secret` under the `ingress-apisix` namespace.
> 
> The secret need to contains `cert` and `key`, There is a template in https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/scaffold/ssl.go#L26-L33.
> 
> We will add this piece of documentation soon.

ok, i created the secret contains cert and key。The apisixtls configure has update to etcd. but i still can not access domain with https。

the apisix pod log is
![image](https://user-images.githubusercontent.com/10016360/118067112-81f8c380-b3d2-11eb-8b27-448e23467254.png)

the etcd ssl data
![image](https://user-images.githubusercontent.com/10016360/118067242-bf5d5100-b3d2-11eb-8914-c9b14210f0cb.png)


![image](https://user-images.githubusercontent.com/10016360/118067144-91780c80-b3d2-11eb-880a-4af2bd01bf53.png)

**Comment by tokers** [comment]
@shuoshadow Seems that you send HTTPS to HTTP port.

**Comment by shuoshadow** [comment]
> @shuoshadow Seems that you send HTTPS to HTTP port.

I install apisix and apisix-ingress-controller with helm.  --set gateway.type=LoadBalancer

this is svc in namespace ingress-apisix, just one port
apisix-gateway              LoadBalancer   172.18.192.111   121.41.xx.xx 80:32755/TCP        41h
![image](https://user-images.githubusercontent.com/10016360/118068550-23811480-b3d5-11eb-946d-7802175da502.png)

the port in apisix pod
![image](https://user-images.githubusercontent.com/10016360/118068642-49a6b480-b3d5-11eb-9213-a09f7abf69ce.png)

which one is https port?

**Comment by tokers** [comment]
@shuaijinchao You should set `tls.enabled` to `true` when you install apisix by helm chart.

**Comment by shuoshadow** [comment]
> @shuaijinchao You should set `tls.enabled` to `true` when you install apisix by helm chart.

Thanks very much! I reinstall apisix and https access ok. 
Mybe tls.enabled should be set true default, i think.
