### ISSUE TITLE
bug: fatal error reported when run `make build` in release src

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-ingress-controller#447]
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);

  Version: 0.5.0
  Git SHA: 
  Go Version: go1.14.6
  Building OS/Arch: linux/amd64
  Running OS/Arch: linux/amd64

* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
  fc32.x86_64

### Minimal test code / Steps to reproduce the issue

1. download release src https://github.com/apache/apisix-ingress-controller/archive/refs/tags/0.5.0.zip
2. unzip, run `make build` under the `apisix-ingress-controller-0.5.0` folder

### What's the actual result? (including assertion message & call stack if applicable)

An error message appears

![2021-05-13 16-40-50屏幕截图](https://user-images.githubusercontent.com/2561857/118101351-1894a700-b40a-11eb-8591-14d03e72dd2e.png)

### What's the expected result?

No error message appears would be better.

ps: It seems that the variable `GITSHA` is the key point, for there is no `.git` in release src folder.

![2021-05-13 16-47-14屏幕截图](https://user-images.githubusercontent.com/2561857/118102636-a0c77c00-b40b-11eb-967c-770b6dbf1e14.png)

**Comment by tokers** [comment]
Thanks for your report!

@gxthrj I think we can record the gitsha into a file when publish a new release.

**Comment by gxthrj** [comment]
I think GITSHA can be turned into an option. 
When users usually use `make build` to package, they can easily record the dist ID, 
but when we release the release, the src is under a specific tag,  In this case, GITSHA is not needed.

**Comment by tokers** [comment]
@gxthrj Yep, then we can optimize this Makefile.
