### ISSUE TITLE
doc: add User Stories

### ISSUE THREAD

**Issue by membphis** [apache/apisix-ingress-controller#46]
we can add `User Stories` in README.md.  
same as: https://github.com/apache/apisix/tree/master#user-stories

aispeech: Why we create a new k8s ingress controller?(Chinese)
https://mp.weixin.qq.com/s/bmm2ibk2V7-XYneLo9XAPQ

Tencent Cloud: Why choose Apache APISIX to implement the k8s ingress controller?(Chinese)
https://www.upyun.com/opentalk/448.html

if need, we can add more

**Comment by gxthrj** [comment]
That`s a good idea. I will add them to README.

**Comment by gxthrj** [comment]
close this issue now.
