### ISSUE TITLE
request help: Does it have native deployment yaml? i don't want to use helm to deployment apisix

### ISSUE THREAD

**Issue by Cassuis** [apache/apisix-ingress-controller#461]
### Issue description
 Does it have native deployment yaml? i don't want to use helm to deployment apisix

**Comment by tokers** [comment]
@Cassuis Try Kustomize: https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/deployment/kustomization.yaml.

**Comment by Cassuis** [comment]
> @Cassuis Try Kustomize: https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/deployment/kustomization.yaml.

thx !
