### ISSUE TITLE
bug: endpoint controller sync changes failed

### ISSUE THREAD

**Issue by flying1pig** [apache/apisix-ingress-controller#464]
### Issue description
endpoint controller will not sync changes when endpoints change from something to nothing

### Environment
apisix-ingress-controller: v0.4.0
k8s: 1.17.4

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue
1. deploy an app in k8s and make sure the endpoints sync to apisix correctly
2. change the replicas from something to nothing
3. view if the endpoints sync to apisix correctly

### What's the actual result? (including assertion message & call stack if applicable)
the pod of this app is already zero, but the nodes of apisixupstream reamain unchange.
### What's the expected result?
the nodes of apisixupstream change to zero

**Comment by tao12345666333** [comment]
We have released v1.0 version, can you try again?

**Comment by tokers** [comment]
@flying1pig Please provide a reproducible minimal case.

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I will close it. If your issue is not resolved, feel free to reopen it, or create a new issue. Thanks!
