### ISSUE TITLE
request help:  ingress event translate route is problematic

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#476]
### Issue description
ingress PathType column  on Kubernetes 1.18+ support.   After the translate, the routes can only match exactly. 
I expected  /    ->   /*     translate result.

only remove this judgment from the code ?

    `if pathRule.PathType != nil && *pathRule.PathType == extensionsv1beta1.PathTypePrefix`

### Environment

* your apisix-ingress-controller version: 0.6
* your Kubernetes cluster version: 1.16

**Comment by tokers** [comment]
@Donghui0 See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#httpingresspath-v1beta1-extensions

`PathType` is a valid field.

**Comment by tokers** [comment]
@Donghui0 I think we cannot remove this for users using ingress in the extensions group on Kubernetes 1.18+.

Does `/*` at `path` work for you?

**Comment by Donghui0** [comment]
> @Donghui0 I think we cannot remove this for users using ingress in the extensions group on Kubernetes 1.18+.
> 
> Does `/*` at `path` work for you?

We are migrating traefik in the test environment to apisix ingress controller.   If i modify the / of path to /*, it is not sure whether traefik can be compatible.  I can try it .

**Comment by gxthrj** [comment]
In traefik use `Path` and `PathPrefix` rule for the route match, which can be used to decide how to set Paths in ApisixRoute resource.

**Comment by tokers** [comment]
@Donghui0 Any new updates?

**Comment by Donghui0** [comment]
> @Donghui0 Any new updates?

no problem.   
I temporarily modified part of this code. this feature may not be used by most people, so won’t submit a pull request.
