### ISSUE TITLE
request help: run e2e test in existed cluster

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#481]
### Issue description
Run e2e in existed cluster. Current e2e requires docker registry at `localhost:5000`.

**Comment by tokers** [comment]
I am wondering whether this is really necessary as it's trivial to create a kind cluster.

cc @tao12345666333

**Comment by tao12345666333** [comment]
I agree with @tokers 

But if you don't want to do this, we can simply modify our script.

By load image instead of downloading from a local registry.

**Comment by tokers** [comment]
> I agree with @tokers
> 
> But if you don't want to do this, we can simply modify our script.
> 
> By load image instead of downloading from a local registry.

Maybe add some makefile directives like "push-images-to-kind", "push-images-to-minikube" and blah blah blah.

**Comment by tao12345666333** [comment]
ref: #880

**Comment by lingsamuel** [comment]
Resolved by #896
