### ISSUE TITLE
Do not run CI for draft PRs

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#493]
https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/6

**Comment by guoqqqi** [comment]
Hi, @tokers I created a Draft PR to test if the deployment was successful, please review it for me, I am not sure if it is correct.

**Comment by tokers** [comment]
@guoqqqi OK I have checked it out, it works well now I think you can mark it ready so we can review it.
