### ISSUE TITLE
request help: websocket reqeust failed

### ISSUE THREAD

**Issue by shuoshadow** [apache/apisix-ingress-controller#495]
### Issue description
![image](https://user-images.githubusercontent.com/10016360/119598950-913a3100-be16-11eb-8817-8684da9c4213.png)

![image](https://user-images.githubusercontent.com/10016360/119599041-c777b080-be16-11eb-8326-1cff851e1823.png)

![image](https://user-images.githubusercontent.com/10016360/119599143-fe4dc680-be16-11eb-8625-eba340068b87.png)

etcd :
,{"modifiedIndex":95,"value":{"update_time":1621999279,"uris":["\/*"],"priority":0,"id":"8da7575a","plugins":{"redirect":{"http_to_https":true,"ret_code":302}},"status":1,"desc":"ops_kas_kas","upstream_id":"fa143a0a","hosts":["xxx.xxx.vip"],"name":"ops_kas_kas","create_time":1621999279},"createdIndex":95,"key":"\/apisix\/routes\/8da7575a"}
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
@shuoshadow How did you send requests? Please give us a minimal reproducible case.

**Comment by shuoshadow** [comment]
> @shuoshadow How did you send requests? Please give us a minimal reproducible case.

frontend
const initSocket = () => {
    const socketURI = `${WEBSOCKET_URL_OBJ[props.namespace]}/api/v1/pod/exec/${props.namespace}/${props.podName}`

    socketRef.current = new WebSocket(socketURI)
    socketOnClose()
    socketOnOpen()
    socketOnError()
  }

  const socketOnClose = () => {
    socketRef.current.onclose = () => {
      socketRef.current.close()
      termRef.current.write('connet is closed!!!')
      console.log('close socket')
    }
  }

  const socketOnOpen = () => {
    socketRef.current.onopen = () => {
      initTerm()
    }
  }

backend:

	logger.Debug("in ExecPod")
	if !ctx.IsWebsocket() {
		ctx.JSON(http.StatusUnsupportedMediaType, hr.ErrResponse{hr.ErrorData{hr.ErrorCodePodExecError, "===not websocket request==="}})
		return
	}

it works right by nginx-ingress

**Comment by shuoshadow** [comment]
![image](https://user-images.githubusercontent.com/10016360/119615812-6a89f380-be32-11eb-9c99-91992d571f1a.png)

**Comment by shuoshadow** [comment]
apisix pod logs
```shell
2021/05/26 09:06:29 [error] 43#43: *11 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to validate the 'vars' expression: rule too short,  etcd key: /apisix/routes, context: ngx.timer
2021/05/26 09:06:29 [error] 47#47: *97 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to validate the 'vars' expression: rule too short,  etcd key: /apisix/routes, context: ngx.timer
2021/05/26 09:06:29 [error] 41#41: *45 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to validate the 'vars' expression: rule too short,  etcd key: /apisix/routes, context: ngx.timer
2021/05/26 09:06:29 [error] 44#44: *76 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to validate the 'vars' expression: rule too short,  etcd key: /apisix/routes, context: ngx.timer
2021/05/26 09:06:29 [error] 42#42: *32 [lua] config_etcd.lua:550: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to validate the 'vars' expression: rule too short,  etcd key: /apisix/routes, context: ngx.timer
```

when i set websocket true by dashboard

**Comment by shuoshadow** [comment]
> What are your apisix-ingress-controller and apisix version?

```shell
bash-5.0# /usr/bin/apisix version
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.5
```

```shell
/ingress-apisix # ./apisix-ingress-controller --version
apisix-ingress-controller version 0.5.0--go1.13.8
```

**Comment by tokers** [comment]
@lingsamuel Please take a look when you have time.

**Comment by Chever-John** [comment]
# HI, This issue has been solved in the latest version

My env:

```sh
kubectl version: Client Version: v1.23.5   Server Version: v1.23.4
kind version: kind v0.12.0 go1.17.8 linux/amd64
helm version: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
ingress version: 
```


I will describe my successful recurrence process as follows.


## Install APISIX Ingress

### Config APISIX Cluster

Commands as follows:

```sh
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
EOF
```

### Install APISIX Ingress

commands as follows:

```sh
helm repo add apisix https://charts.apiseven.com
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
kubectl create ns ingress-apisix
helm install apisix apisix/apisix \
  --set gateway.type=NodePort \
  --set ingress-controller.enabled=true \
  --namespace ingress-apisix \
  --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix
kubectl get service --namespace ingress-apisix
```


## Enable web-socket backend service

```sh
// pull image jmalloc/echo-server
kubectl run websocket-server --image jmalloc/echo-server --port 8080

// expose pod
kubectl expose pod websocket-server --port 8080

// check the service
kubectl get service websocket-server
```

## Create a resource

create a `websocket.yaml`

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: ws-route
spec:
  http:
  - name: websocket
    match:
      hosts:
      - ws.foo.org
      paths:
      - /*
    websocket: true
    backends:
       - serviceName: websocket-server
         servicePort: 8080
```

```sh
kubectl apply -f websock.yaml
```

## Test

```sh
kubectl exec -it -n ingress-apisix apisix-cfcdc4999-7jq8l -- curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'

kubectl exec -it -n ingress-apisix apisix-cfcdc4999-7jq8l -- curl http://127.0.0.1:9080/headers -H 'Host: ws.foo.org'
```

Then you will see:

```sh
chever@cloud-native-01:~/api7/cloud_native/websock$ kubectl exec -it -n ingress-apisix apisix-cfcdc4999-7jq8l -- curl http://127.0.0.1:9080/headers -H 'Host: ws.foo.org'
Defaulted container "apisix" out of: apisix, wait-etcd (init)
Request served by websocket-server
 
HTTP/1.1 GET /headers

Host: ws.foo.org
X-Forwarded-Host: ws.foo.org
X-Forwarded-Port: 9080
User-Agent: curl/7.79.1
Accept: */*
X-Real-Ip: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
```

**Comment by tao12345666333** [comment]
@Chever-John Thanks for your contribution.

In fact, we have an e2e test case to cover such scenarios.
Please try updating to the latest version.

I will close this issue.
If your problem is not resolved, please feel free to reopen it.
