### ISSUE TITLE
Discuss: use terratest for testing with Kubernetes

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#51]
I proposal use [terratest](https://github.com/gruntwork-io/terratest) for testing with Kubernetes. It can test the logic of Kubernetes with code(APIs).

But `ingress-controller` has CRDs, and the `terratest`  do not CRDs testing. 

Anybody has some good ideas? 

I found an [issue](https://github.com/gruntwork-io/terratest/issues/491) to discuss the feature, need time to digest.

**Comment by membphis** [comment]
Why we choose [terratest](https://github.com/gruntwork-io/terratest)?  Any reason?

**Comment by gxthrj** [comment]
Ref to kuma, I saw a [feat](https://github.com/kumahq/kuma/pull/784) about terratest.

**Comment by gxthrj** [comment]
Will add terratest in #101
