### ISSUE TITLE
docs: update mTLS support in ApisixTls reference 

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#521]
https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/references/apisix_tls.md

**Comment by tao12345666333** [comment]
@gxthrj Please set milestone for this issue.

/milestone v1.1

**Comment by tokers** [comment]
> @gxthrj Please set milestone for this issue.
> 
> 
> 
> /milestone v1.1

Done.
