### ISSUE TITLE
The default namespace `cloud` is not declared in documents

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#53]
As per the configurations in sample/deploy, we have an implicit install namespace `cloud` for those API objects, we'd better to add some hints to create this namespace firstly, otherwise errors will occur while users are installing these resources.

```
kubectl create namespace cloud
```

What's more, i think the `cloud` namespace is not so specialized, i recommend to use `ingress-apisix` as the namespace.

**Comment by gxthrj** [comment]
Yes, maybe `default` namespace is better :)

**Comment by tokers** [comment]
Yeah, `default` is good.

**Comment by gxthrj** [comment]
I will update it in PR #48 .

**Comment by gxthrj** [comment]
close this issue now
