### ISSUE TITLE
Be compatible with the broken change of resource count field from APISIX

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#536]
PR https://github.com/apache/apisix/pull/4385 changes `count` field from `string` to `number`. We use `count` field in some places such as e2e suites, we may make the code base compatible with this change.

@lingsamuel @gxthrj @tao12345666333

**Comment by tokers** [comment]
@lingsamuel Please take a look when you have time.

**Comment by lingsamuel** [comment]
Please assign me.

**Comment by gxthrj** [comment]
I think we can close this issue now, as #544 has been merged.
