### ISSUE TITLE
bug:  remove apisixroute resource failed, resulting in duplicate routes in apisix controller

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#540]
### Issue description
Delete the service  resource first, then delete the apisixroute, and the apisix controller will throw an exception:
![image](https://user-images.githubusercontent.com/7134928/121335331-106a5180-c94d-11eb-8197-e80a3fa3b6ef.png)

When creating a new apisixroute resource, the name of spec.http.name will change again, which will result in a lot of historical routes remaining.

![image](https://user-images.githubusercontent.com/7134928/121335848-8a023f80-c94d-11eb-9925-ecbbbbc02e81.png)

### Environment

* your apisix-ingress-controller version: v0.6
* your Kubernetes cluster version (output of `kubectl version`): v1.16.9

### Minimal test code / Steps to reproduce the issue
1.  delete service resource
2.  delete apisix route resource
3.  observe the controller log...

### What's the actual result? (including assertion message & call stack if applicable)
apisixroute resource failed to delete.

### What's the expected result?
apisixroute delete success.

PS:
If I reverse the order of deletion, can it solve the problem?

**Comment by gxthrj** [comment]
Let us discuss, if the k8s service has been deleted, what should be the behavior when deleting ApisixRoute ?

**Comment by tokers** [comment]
I'd like to set a retry max times for all controllers' loop, after exceeding the threshold, just dropping the event, you can see this behavior in Kubernetes Controller Manager, just like:

* https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L61
* https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L60

**Comment by Donghui0** [comment]
> Let us discuss, if the k8s service has been deleted, what should be the right behavior when deleting ApisixRoute ?

I think there should be a correspondence between resources, such as:
service  -> upstream
apisixroute ->  route

so,  the correct behavior for deleting ApisixRoute should only be to monitor whether the apisixroute resource is deleted.

**Comment by tokers** [comment]
> > Let us discuss, if the k8s service has been deleted, what should be the right behavior when deleting ApisixRoute ?
> 
> I think there should be a correspondence between resources, such as:
> Service -> upstream
> ApisixRoute -> route
> 
> so, the correct behavior for deleting ApisixRoute should only be to monitor whether the apisixroute resource is deleted.

I'm afraid I didn't capture your mean.

**Comment by Donghui0** [comment]
> > > Let us discuss, if the k8s service has been deleted, what should be the right behavior when deleting ApisixRoute ?
> > 
> > 
> > I think there should be a correspondence between resources, such as:
> > Service -> upstream
> > ApisixRoute -> route
> > so, the correct behavior for deleting ApisixRoute should only be to monitor whether the apisixroute resource is deleted.
> 
> I'm afraid I didn't capture your mean.

I hope that deleting the Service resource will not affect the resource deletion of ApiSixRoute.

**Comment by gxthrj** [comment]
I think it can be divided into two scenarios to look at this problem:
1. When creating or updating ApisixRoute resources, if there is no service, an error will be reported and a retry will be triggered.
2. When deleting ApisixRoute resources, don't need to do too strict verification during object conversion. Just make sure that the APISIX route object can be deleted normally to avoid object conversion errors due to the absence of k8s service.

**Comment by tokers** [comment]
> I think it can be divided into two scenarios to look at this problem:
> 
> 1. When creating or updating ApisixRoute resources, if there is no service, an error will be reported and a retry will be triggered.
> 2. When deleting ApisixRoute resources, don't need to do too strict verification during object conversion. Just make sure that the APISIX route object can be deleted normally to avoid object conversion errors due to the absence of k8s service.

For the first case, we may add more logics in admission server in the future, so that the ApisixRoute won't be created if some dependencies are missing.

For the second one, we may just fetch ids of all routes in this ApisixRoute resource, and delete them?

**Comment by gxthrj** [comment]
> > I think it can be divided into two scenarios to look at this problem:
> > 
> > 1. When creating or updating ApisixRoute resources, if there is no service, an error will be reported and a retry will be triggered.
> > 2. When deleting ApisixRoute resources, don't need to do too strict verification during object conversion. Just make sure that the APISIX route object can be deleted normally to avoid object conversion errors due to the absence of k8s service.
> 
> For the first case, we may add more logics in admission server in the future, so that the ApisixRoute won't be created if some dependencies are missing.
> 
> For the second one, we may just fetch ids of all routes in this ApisixRoute resource, and delete them?

That sounds good.

**Comment by tokers** [comment]
@Donghui0 Let's do the second case now, would you like to submit a PR to help this project to fix this? Thanks!

**Comment by gxthrj** [comment]
Close this issue now as the PR has been merged.
