### ISSUE TITLE
unexpected characters in the definition of image in the pod template declarement

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#55]
See https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/deployment/ingress-controller.yaml#L30 for the details.

![image](https://user-images.githubusercontent.com/10428333/101324738-abeb0e80-38a5-11eb-97fb-382d5e61f3c3.png)

Users cannot really deploy apisix-ingress-controller.

**Comment by gxthrj** [comment]
related to #35

**Comment by gxthrj** [comment]
We can build an official image under the Apache after the 0.1.0 milestone

**Comment by tokers** [comment]
@juzhiyuan @nic-chen @membphis We may also use it in Dashboard.

**Comment by tokers** [comment]
Solved.
