### ISSUE TITLE
request help: get unknown output before apisix-admin response

### ISSUE THREAD

**Issue by fhuzero** [apache/apisix-ingress-controller#551]
### Issue description
I run k8s cluster on either Minikue or KinD, and install apisix-ingress-controller by either Helm Chart or run on bare-metal. In all cases the apisix-admin service will return an unknown response before expected one.

For example. when I follow this [example](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/proxy-the-httpbin-service.md#test) and input `kubectl exec -it -n ingress-apisix apisix-6fc895b8d5-x2v49 -- curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'`
```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
{"count":"2","node":{"dir":true,"key":"\/apisix\/routes","nodes":[{"modifiedIndex":15,"key":"\/apisix\/routes\/add8e28c","createdIndex":15,"value":{"hosts":["local.httpbin.org"],"create_time":1624261538,"status":1,"desc":"Created by apisix-ingress-controller, DO NOT modify it manually","upstream_id":"5ce57b8e","id":"add8e28c","priority":0,"name":"default_httpserver-route_rule1","uris":["\/*"],"update_time":1624261538,"labels":{"managed-by":"apisix-ingress-controller"}}}]},"action":"get"}
```
and `kubectl exec -it -n ingress-apisix apisix-6fc895b8d5-x2v49 -- curl http://127.0.0.1:9080/headers -H 'Host: local.httpbin.org'`
```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
{
  "headers": {
    "Accept": "*/*",
    "Host": "local.httpbin.org",
    "User-Agent": "curl/7.76.1",
    "X-Forwarded-Host": "local.httpbin.org"
  }
}
```

**My question is** : why `Defaulted container "apisix" out of: apisix, wait-etcd (init)` keep popping out before expected response? Thanks for helping me out!

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
```
Version: 0.6.0
Git SHA: f5cc76e
Go Version: go1.15.13
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

The code I used is the up-to-date version (cloned on June 21).

* your Kubernetes cluster version (output of `kubectl version`);
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
```
Linux mylinux 5.4.0-1045-generic #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tokers** [comment]
@fhuzero This is because we have two containers in the pod spec (the `initContainer` `wait-etcd` and the normal container `apisix`), and you don't run it in quiet mode. So kubectl selects the first container to run your command.

![image](https://user-images.githubusercontent.com/10428333/122851193-23aff080-d341-11eb-8f8a-8b5c686019a9.png)

**Comment by fhuzero** [comment]
@tokers Thanks for your clear explanation with code! Now I know the meaning of the output and where it comes from. It really helps.
