### ISSUE TITLE
discuss: apisix-ingress-controller version update in Makefile

### ISSUE THREAD

**Issue by fhuzero** [apache/apisix-ingress-controller#553]
Now apisix-ingress-controller has released its first GA version `1.0.x`, but the default version in Makefile is still `0.6.0` ([here](https://github.com/apache/apisix-ingress-controller/blob/f5cc76ec6ac671772063d38a09f508db71ac2e48/Makefile#L19)). Should we update it to `1.0.x`? If so, I can open a PR to keep it up-to-date.

**Comment by tao12345666333** [comment]
yes, please!

**Comment by fhuzero** [comment]
> yes, please!

Thanks! I have created a PR.

**Comment by fhuzero** [comment]
The related PR #556 has been merged so I'll close this issue.
