### ISSUE TITLE
request help: How to configure Ingress to make browser requests reach the backend through Ingress

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-ingress-controller#561]
### Issue description

I created an Ingress resource based on the example in the document. [Proxy the httpbin service with Ingress](https://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service-with-ingress)

```
➜  [/srv/yaml] kubectl get ingress -n apisix-ws                                                                                      
NAME                   CLASS    HOSTS               ADDRESS   PORTS   AGE
httpserver-ingress     <none>   local.httpbin.org             80      2d22h
nginx-apisix-ingress   <none>   local.nginx.org               80      12m
```
And the test cases of the examples in the document can also be returned normally. and I want to know how to configure this ingress so that this request can be accessed through a browser?

I found that when I execute `kubectl apply -f nginx-apisix-ingress.yaml -n apisix-ws`, I can see this ingress on the application routing interface of kubesphere.
![image](https://user-images.githubusercontent.com/12752710/123507883-be406480-d69e-11eb-8a8b-d8fd2a8f3c79.png)
![image](https://user-images.githubusercontent.com/12752710/123507908-d87a4280-d69e-11eb-816d-98ec8094ea04.png)

But when I open it through the browser, it will return a 404 error, and the error message returned does not seem to be given by apisix-ingress-controller, and there is no similar 404 error in the log.

![image](https://user-images.githubusercontent.com/12752710/123507966-3c9d0680-d69f-11eb-9e43-7615ad61561d.png)

```
➜  [/srv/yaml] kubectl exec -it -n apisix-ws apisix-7b9bc99d4b-d2v4b -- curl http://127.0.0.1:9080/headers -H 'Host: local.nginx.org'
Server address: 179.10.62.215:16666
Server name: nginx-plain-v1-884978c4-6mgk2
Date: 26/Jun/2021:09:05:24 +0000
URI: /headers
Request length: 220
Scheme: http
Remote user: 
Request ID: ebffbc885308e31266ac5694956c4b5b
```

```
[/srv/yaml] cat nginx-apisix-ingress.yaml 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-apisix-ingress
  # Note for ingress.networking.k8s.io/v1beta1,
  # you have to carry annotation kubernetes.io/ingress.class,
  # and its value must be matched with the one configured in
  # apisix-ingress-controller, in our case, it's apisix.
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  rules:
    - host: local.nginx.org
      http:
        paths:
          - backend:
              serviceName: nginx-plain
              servicePort: 16666
            path: /
            pathType: Prefix

```

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
```
Version: 1.0.0
Git SHA: no-git-module
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
* your Kubernetes cluster version (output of `kubectl version`);
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
```
Kubesphere 3.0
```

**Comment by Caelebs** [comment]
I tried to create an application route on the kubesphere webpage, this ingress should be the nginx-ingress-controller used by default
![image](https://user-images.githubusercontent.com/12752710/123508135-1cba1280-d6a0-11eb-9cd8-49c4aa733795.png)

But this ingress can be forwarded to the backend if requested through the browser.
![image](https://user-images.githubusercontent.com/12752710/123508155-3d826800-d6a0-11eb-80d3-02a2250b8a05.png)

This is the yaml file of this ingress

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nginx-nginx-ingress
  namespace: apisix-ws
  annotations:
    kubesphere.io/creator: admin
spec:
  rules:
    - host: nginx-plain.apisix-ws.10.10.17.119.nip.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: nginx-plain
              servicePort: 16666
```

**Comment by Caelebs** [comment]
The description may be a bit confusing, I mean, how should this ingress be configured so that it can achieve the same effect as nginx-ingress-controller through apisix-ingress-controller

**Comment by tao12345666333** [comment]
You can try in the APISIX pod to see if the routing rules have taken effect.

Or see the log of apisix-ingress pod.

**Comment by tokers** [comment]
@Caelebs The `404` page doesn't look like an artifact of Apache APISIX, even if the route rules are not in effective, what we should see is a J string with contents like "404 Route Not Found".

I saw you execute the `curl` command in the apisix pod, have you ever tried to execute this command on your local environment?

**Comment by Caelebs** [comment]
I checked the log of apisix-ingress-controller, nothing seems to be relevant, it seems that the request did not enter the apisix-ingress-controller? But I found that in the apisix logs, there are always prompting some logs that the upstream service can't find. @tao12345666333 

```
[GIN] 2021/06/28 - 16:08:39 | 200 |     157.244µs |       10.0.2.15 | GET      "/healthz"
2021-06-28T16:08:40+08:00       info    ingress/endpoint.go:94  service kube-system/kube-controller-manager not found
2021-06-28T16:08:40+08:00       info    ingress/endpoint.go:94  service kube-system/kube-scheduler not found
2021-06-28T16:08:42+08:00       info    ingress/endpoint.go:94  service kube-system/kube-controller-manager not found
2021-06-28T16:08:42+08:00       info    ingress/endpoint.go:94  service kube-system/kube-scheduler not found
E0628 16:08:43.423466       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2alpha1.ApisixConsumer: failed to list *v2alpha1.ApisixConsumer: apisixconsumers.apisix.apache.org is forbidden: User "system:serviceaccount:apisix-ws:apisix-ingress-controller" cannot list resource "apisixconsumers" in API group "apisix.apache.org" at the cluster scope
2021-06-28T16:08:44+08:00       info    ingress/endpoint.go:94  service kube-system/kube-controller-manager not found
2021-06-28T16:08:44+08:00       info    ingress/endpoint.go:94  service kube-system/kube-scheduler not found
[GIN] 2021/06/28 - 16:08:44 | 200 |      71.466µs |       10.0.2.15 | GET      "/healthz"
E0628 16:08:45.926526       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2alpha1.ApisixClusterConfig: failed to list *v2alpha1.ApisixClusterConfig: apisixclusterconfigs.apisix.apache.org is forbidden: User "system:serviceaccount:apisix-ws:apisix-ingress-controller" cannot list resource "apisixclusterconfigs" in API group "apisix.apache.org" at the cluster scope
2021-06-28T16:08:46+08:00       info    ingress/endpoint.go:94  service kube-system/kube-scheduler not found
2021-06-28T16:08:46+08:00       info    ingress/endpoint.go:94  service kube-system/kube-controller-manager not found
```
```
179.10.154.11 - - [28/Jun/2021:16:07:00 +0800] apisix-admin:9180 "GET /apisix/admin/upstreams/492780d HTTP/1.1" 404 39 0.001 "-" "Go-http-client/1.1" - - - "http://apisix-admin:9180"
179.10.154.11 - - [28/Jun/2021:16:07:00 +0800] apisix-admin:9180 "GET /apisix/admin/upstreams/74f88c82 HTTP/1.1" 404 39 0.001 "-" "Go-http-client/1.1" - - - "http://apisix-admin:9180"
179.10.154.11 - - [28/Jun/2021:16:10:00 +0800] apisix-admin:9180 "GET /apisix/admin/upstreams/e4db1bcd HTTP/1.1" 404 39 0.015 "-" "Go-http-client/1.1" - - - "http://apisix-admin:9180"
179.10.154.11 - - [28/Jun/2021:16:10:00 +0800] apisix-admin:9180 "GET /apisix/admin/upstreams/492780d HTTP/1.1" 404 39 0.004 "-" "Go-http-client/1.1" - - - "http://apisix-admin:9180"
179.10.154.11 - - [28/Jun/2021:16:10:00 +0800] apisix-admin:9180 "GET /apisix/admin/upstreams/74f88c82 HTTP/1.1" 404 39 0.008 "-" "Go-http-client/1.1" - - - "http://apisix-admin:9180"
```

**Comment by Caelebs** [comment]
In the dashboard, I can already see that apisix-ingress-controller has created related routes. It seems that everything is okay, but it is true that the browser request will prompt a 404 error.
![image](https://user-images.githubusercontent.com/12752710/123603065-0e006680-d82c-11eb-88c2-557e572b3b4d.png)
![image](https://user-images.githubusercontent.com/12752710/123603052-093bb280-d82c-11eb-85ae-b03e618a2c94.png)

**Comment by Caelebs** [comment]
> @Caelebs The `404` page doesn't look like an artifact of Apache APISIX, even if the route rules are not in effective, what we should see is a J string with contents like "404 Route Not Found".
> 
> I saw you execute the `curl` command in the apisix pod, have you ever tried to execute this command on your local environment?

I tried it, but there seems to be no response because it says connection refused. I don't know how to do it next...
@tokers 

```
-> curl http://local.nginx.org/aaa
curl: (7) Failed connect to local.nginx.org:80; Connection refused
```

**Comment by tokers** [comment]
What is the type of apisix service? Your apisix service must be addressable from your own environment, for instance, you can set the apisix service type to `NodePort` or `LoadBalancer`.

**Comment by Caelebs** [comment]
> What is the type of apisix service? Your apisix service must be addressable from your own environment, for instance, you can set the apisix service type to `NodePort` or `LoadBalancer`.

The service type of apisix has always been NodePort. 
```
➜  [/srv/yaml] curl http://10.10.17.120:30155/abc -H 'Host: local.nginx.org' 
Server address: 179.10.62.206:16666
Server name: nginx-plain-v1-884978c4-6mgk2
Date: 29/Jun/2021:02:30:08 +0000
URI: /abc
Request length: 216
Scheme: http
Remote user: 
Request ID: a34d46d672d936409370a0fd5855a55d
```
```
➜  [/srv/yaml] kubectl get service -n apisix-ws | grep apisix           
apisix-admin                ClusterIP   179.20.3.90      <none>        9180/TCP            23h
apisix-dashboard            NodePort    179.20.194.232   <none>        9000:30340/TCP      23h
apisix-etcd                 ClusterIP   179.20.84.185    <none>        2379/TCP,2380/TCP   23h
apisix-etcd-headless        ClusterIP   None             <none>        2379/TCP,2380/TCP   23h
apisix-gateway              NodePort    179.20.171.132   <none>        80:30155/TCP        23h
apisix-ingress-controller   ClusterIP   179.20.151.245   <none>        80/TCP              23h
```
Does the service type of apisix-ingress-controller also need to be set to NodePort?
@tokers

**Comment by Caelebs** [comment]
I tried to set the service type of apisix-ingress-controller to NodePort, it seems to be useless.

```
➜  [/srv/yaml] kubectl get service -n apisix-ws | grep apisix        
apisix-admin                ClusterIP   179.20.3.90      <none>        9180/TCP            23h
apisix-dashboard            NodePort    179.20.194.232   <none>        9000:30340/TCP      23h
apisix-etcd                 ClusterIP   179.20.84.185    <none>        2379/TCP,2380/TCP   23h
apisix-etcd-headless        ClusterIP   None             <none>        2379/TCP,2380/TCP   23h
apisix-gateway              NodePort    179.20.171.132   <none>        80:30155/TCP        23h
apisix-ingress-controller   NodePort    179.20.151.245   <none>        80:32393/TCP        23h
```

**Comment by tokers** [comment]
> Does the service type of apisix-ingress-controller also need to be set to NodePort?

Nope, Controller doesn't handle traffic, it doesn't have to be a NodePort service.

It mean for the case that accessing from the your own environment is failed:

```
-> curl http://local.nginx.org/aaa
curl: (7) Failed connect to local.nginx.org:80; Connection refused
```

It seems that you just sent requests to port `80`, you should send it to the port of your apisix service.

**Comment by tokers** [comment]
> 30155

It seems the response of apisix is expected?

**Comment by tokers** [comment]
> > What is the type of apisix service? Your apisix service must be addressable from your own environment, for instance, you can set the apisix service type to `NodePort` or `LoadBalancer`.
> 
> The service type of apisix has always been NodePort.
> 
> ```
> ➜  [/srv/yaml] curl http://10.10.17.120:30155/abc -H 'Host: local.nginx.org' 
> Server address: 179.10.62.206:16666
> Server name: nginx-plain-v1-884978c4-6mgk2
> Date: 29/Jun/2021:02:30:08 +0000
> URI: /abc
> Request length: 216
> Scheme: http
> Remote user: 
> Request ID: a34d46d672d936409370a0fd5855a55d
> ```
> 
> ```
> ➜  [/srv/yaml] kubectl get service -n apisix-ws | grep apisix           
> apisix-admin                ClusterIP   179.20.3.90      <none>        9180/TCP            23h
> apisix-dashboard            NodePort    179.20.194.232   <none>        9000:30340/TCP      23h
> apisix-etcd                 ClusterIP   179.20.84.185    <none>        2379/TCP,2380/TCP   23h
> apisix-etcd-headless        ClusterIP   None             <none>        2379/TCP,2380/TCP   23h
> apisix-gateway              NodePort    179.20.171.132   <none>        80:30155/TCP        23h
> apisix-ingress-controller   ClusterIP   179.20.151.245   <none>        80/TCP              23h
> ```
> 
> Does the service type of apisix-ingress-controller also need to be set to NodePort?
> @tokers

It seems that the response returned by APISIX is expected?

**Comment by Caelebs** [comment]
understood. I once thought that only the host address specified in ingress is needed. so I directly requested `local.nginx.org`, now I tested `http://local.nginx.org:30155/aaa` and it can respond normally.
```
[root@120 ~] -> curl http://local.nginx.org:30155/aaa
Server address: 179.10.62.206:16666
Server name: nginx-plain-v1-884978c4-6mgk2
Date: 29/Jun/2021:05:47:31 +0000
URI: /aaa
Request length: 228
Scheme: http
Remote user: 
Request ID: 5f1d2ece1a3b50b3ede44436b5ea13ff
```
![image](https://user-images.githubusercontent.com/12752710/123744977-29c64400-d8e2-11eb-829e-b65fac58fcb9.png)

It seems that there is no problem. It's my misunderstanding
Thanks Reply @tokers

**Comment by tokers** [comment]
OK, considering it as solved.
