### ISSUE TITLE
discuss: support for APISIXRoute/v2alpha1 type in pkg/type/apisix

### ISSUE THREAD

**Issue by fhuzero** [apache/apisix-ingress-controller#562]
ApisixRoute/v1 is obsolete and will be unsupported in the future, and ApisixRoute/v2alpha1 is recommended. However, only type `Route` in pkg/type/apisix/**v1**/types.go is supported now. Should we add type `Route` definition in pkg/type/apisix/**v2alpha1**/types.go to support ApisixRoute/v2alpha1?

**Comment by tokers** [comment]
@fhuzero The ApisixRoute/v2alpha1 definition is in pkg/kube/apisix/apis/config/v2alpha1. The Apisix Route prototype is not changed.

**Comment by fhuzero** [comment]
@tokers Thanks for your explanation! Maybe I didn't explain my question clearly, my bad. From my understanding, the Apisix Route prototype refers to struct `Route` in _pkg/type/apisix/v1/types.go_. I want to implement traffic-split feature in my code when translating Ingress. Then I find that field `http[].backends.weight` suits my need. But I cannot find a field in `Route`  which represents `http[].backends` field in ApisixRoute/v2alpha1. What should I do if I want to access `backends` field in ApisixRoute/v2alpha1 spec?

**Comment by fhuzero** [comment]
@tokers  Could this issue be reopened to continue the discussion? Or I have to open another one.
