### ISSUE TITLE
feat: implement apisix healthz check

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#567]
https://github.com/apache/apisix-ingress-controller/blob/70d010092b626c9c6959bd026e669dbb60153608/pkg/api/router/router.go#L28-L35

The current `/apisix/healthz` interface does not implement the check logic for Apache APISIX.

**Comment by tokers** [comment]
@tao12345666333 Is this for the brand new arch in the future?

**Comment by tao12345666333** [comment]
Not all, even in the current architecture, if we implement this interface, it will be beneficial.

**Comment by tokers** [comment]
> Not at all, even in the current architecture, if we implement this interface, it will be beneficial.

OK, fail enough. BTW, it can be combined with the logic that the controller tries to campaign the leadership.

**Comment by sober-wang** [comment]
> 
> 
> https://github.com/apache/apisix-ingress-controller/blob/70d010092b626c9c6959bd026e669dbb60153608/pkg/api/router/router.go#L28-L35
> 
> The current `/apisix/healthz` interface does not implement the check logic for Apache APISIX.

This code is not check anything. Can I help you?

**Comment by suninuni** [comment]
![image](https://user-images.githubusercontent.com/7345529/133216130-1412197c-b62c-44ed-8ffa-b9cc5cad78e7.png)

The access log for this request should be able to be closed. It's useless.

**Comment by tokers** [comment]
> ![image](https://user-images.githubusercontent.com/7345529/133216130-1412197c-b62c-44ed-8ffa-b9cc5cad78e7.png)
> 
> 
> 
> The access log for this request should be able to be closed. It's useless.

We can disable the logging middleware in the gin engine. PR is welcome to do this!

**Comment by tao12345666333** [comment]
> This code is not check anything. Can I help you?

@sober-wang  If you are interested in this, welcome to implement its logic.
