### ISSUE TITLE
request help: apisix ingress controller with Dapr

### ISSUE THREAD

**Issue by geffzhang** [apache/apisix-ingress-controller#569]
I want to use apisix with dapr, how to configure？ I found a ngnix ingress with dapr https://dev.to/stevenjdh/create-a-kubernetes-nginx-controller-with-dapr-support-3e8n  , apisix should be configured to achieve the same functionality

**Comment by juzhiyuan** [comment]
Hi @tokers, would you please take a look at this issue 😄

**Comment by tokers** [comment]
@geffzhang The idea should similar, what you need to do is try to let Dapr inject the APISIX Pod, and create a series ApisixRoute and ApisixUpstream resources let the APISIX proxy traffic to the local Dapr sidecar.

**Comment by geffzhang** [comment]
@tokers  I can't inject  dapr  APISIX pod ,

<html>
<body>


/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
--
Tue, Sep 28 2021 6:16:14 pm |  
Tue, Sep 28 2021 6:16:14 pm | WARNING: using fixed Admin API token has security risk.
Tue, Sep 28 2021 6:16:14 pm | Please modify "admin_key" in conf/config.yaml .
Tue, Sep 28 2021 6:16:14 pm |  
Tue, Sep 28 2021 6:16:14 pm |  
Tue, Sep 28 2021 6:16:14 pm | /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
Tue, Sep 28 2021 6:16:15 pm | 2021/09/28 10:16:15 [warn] 1#1: low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:211
Tue, Sep 28 2021 6:16:15 pm | nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:211
Tue, Sep 28 2021 6:16:15 pm | 2021/09/28 10:16:15 [emerg] 1#1: bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:15 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:15 pm | 2021/09/28 10:16:15 [emerg] 1#1: bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:15 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:16 pm | 2021/09/28 10:16:15 [emerg] 1#1: bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:16 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:16 pm | 2021/09/28 10:16:15 [emerg] 1#1: bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:16 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:17 pm | 2021/09/28 10:16:15 [emerg] 1#1: bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:17 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)
Tue, Sep 28 2021 6:16:17 pm | 2021/09/28 10:16:15 [emerg] 1#1: still could not bind()
Tue, Sep 28 2021 6:16:17 pm | nginx: [emerg] still could not bind()


</body>
</html>

**Comment by tokers** [comment]
@geffzhang Could you try to figure out which program is listing on the `9090` port? It occupies it so Apache APISIX cannot be launched.

**Comment by gxthrj** [comment]
From the logs 'Tue, Sep 28 2021 6:16:17 pm | nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address in use)', should check the configurations about port both in apisix and dapr.

**Comment by geffzhang** [comment]
bash-5.1# netstat -an | grep 90
tcp        0      0 0.0.0.0:9080            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:9080            0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:9091          0.0.0.0:*               LISTEN      
tcp        0      0 10.244.0.16:9080        10.240.0.4:38288        ESTABLISHED 
tcp        0      0 10.244.0.16:9080        10.240.0.6:54711        ESTABLISHED 
tcp        0      0 10.244.0.16:9080        10.240.0.5:12667        ESTABLISHED 
tcp        0      0 :::9080                 :::*                    LISTEN      
tcp        0      0 :::9080                 :::*                    LISTEN      
unix  3      [ ]         STREAM     CONNECTED     1365790

**Comment by tao12345666333** [comment]
https://apisix.apache.org/zh/blog/2021/11/17/dapr-with-apisix/#%E5%9F%BA%E6%9C%AC%E9%A1%B9%E7%9B%AE%E6%A6%82%E8%A7%88

We have a blog post for this one.
