### ISSUE TITLE
feat: add response-rewrite for Ingress resource

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#575]
I think this is useful.

xref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/response-rewrite.md

**Comment by Chever-John** [comment]
Sure, I want to try this.

Please assign this to me, Thanks~

**Comment by stillfox-lee** [comment]
Hi, I got a little confused about this issue. Didn't we already support this feature by ApisixRoute HTTP plugin?

**Comment by tao12345666333** [comment]
@stillfox-lee We can indeed do this already by using a plugin in the ApisixRoute resource.

The purpose of this issue is to add annotations to the Ingress resource to extend its functionality.  Similar to the example here https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations

**Comment by stillfox-lee** [comment]
> @stillfox-lee We can indeed do this already by using a plugin in the ApisixRoute resource.
> 
> The purpose of this issue is to add annotations to the Ingress resource to extend its functionality. Similar to the example here https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations

Ok, I got it. Thanks!

**Comment by Chever-John** [comment]
Continue to work on this week~
