### ISSUE TITLE
feat:  Can it support independent use of ApisixUpstream CRD  in controller ?

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#578]
### Issue description
Use ApisixUpstream CRD directly and independently, instead of relying on ApisixRoute crd ?

**Comment by gxthrj** [comment]
By now, as an enhancement of ApisixRoute, ApisixUpstream resources must be created when the upstream is referenced by at least one rule in ApisixRoute, and when ApisixUpstream is deleted, it will also be judged whether it is referenced by ApisixRoute, and the corresponding upstream object will be deleted if there is no reference.

This really simplifies a lot of work, and from the point of view of APISIX, the upstream alone has no effect, and it must be used in conjunction with the route.

@Donghui0 Can you describe your scenario?

**Comment by Donghui0** [comment]
I need to use Apisix to handle east-west and north-south traffic separately, so in this scenario I need multiple Apisix clusters. I hope that the routing in each cluster is isolated, does not affect each other, and is clear at a glance.

I know that you definitely want me to use ingress_class annotation to distinguish. But I have a lot of routing, and I don't want to write an ingress resource for processing, and each route will introduce different plugins.

**Or, is it possible to add a route_class annotation in ApisixRoute CRD**?  In this way, I can let multiple controllers handle different ApisixRoute CRDs.

**Comment by Donghui0** [comment]
My initial idea was to let the controller only listen to Apisix Upstream CRD, and then use apisix admin api for routing management. On the other hand, Because ApisixRoute CRD attributes are incomplete, such as missing the timeout attribute (read/connect/write) of the route.

**Comment by gxthrj** [comment]
@Donghui0 
> Or, is it possible to add a route_class annotation in ApisixRoute CRD? In this way, I can let multiple controllers handle different ApisixRoute CRDs.

IMO, ingress.class annotation is doing the same things, make multiple controllers handle different ApisixRoute CRDs.

**Comment by gxthrj** [comment]
> ApisixRoute CRD attributes are incomplete, such as missing the timeout attribute (read/connect/write) of the route. 
This is a feature, now we use the default timeout in APISIX. 
We can support the timeout fields in CRD, too. 
PR is welcome ~ 
But I don't recommend you to mix yaml and admin api, this is uncontrollable.

**Comment by Donghui0** [comment]
> @Donghui0
> 
> > Or, is it possible to add a route_class annotation in ApisixRoute CRD? In this way, I can let multiple controllers handle different ApisixRoute CRDs.
> 
> IMO, ingress.class annotation is doing the same things, make multiple controllers handle different ApisixRoute CRDs.

You are right.   But you can’t use native or custom apisix plugins in ingress resource, There are only a few basic plugins.

So can only use ApisixRoute CRDs.  the crd has http[].plugins property.

**Comment by Donghui0** [comment]
After all, the configuration properties of ApisixRoute CRD are much more than ingress.  This is one of the reasons why I want to give up using Ingress Resource  and use ApisixRoute CRD directly.

**Comment by gxthrj** [comment]
Yes， I see， I mean we can support `ingress.class` in ApisixRoute, which is what you want.
This feature will get a proposal soon.

**Comment by tokers** [comment]
> Yes， I see， I mean we can support `ingress.class` in ApisixRoute, which is what you want.
> 
> This feature will get a proposal soon.

That won't be suitable that we use the same name in ApisixRoute.

**Comment by tao12345666333** [comment]
Thanks, we can use #592  for tracking, I will close this one.
