### ISSUE TITLE
The APISIX series Resources should be maintained in a separate repository

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#58]
So far both apisix-ingress-controller and apisix-dashboard maintain their own definitions for each APISIX resource, like Route, Upstream, Consumers and so on.

I propose to keep the definitions for those resources in a separate repository, and versioning them according to the release of data plane.

Protobuf 3 is a good choice to definition them.

**Comment by gxthrj** [comment]
Agree 

We can ref to https://github.com/kubernetes/code-generator/cmd/go-to-protobuf 

the submodule [apisix-types](https://github.com/api7/types)  in `apisix-ingress-controller` also use the code-generator.

**Comment by tokers** [comment]
No plan to support it yet.
