### ISSUE TITLE
request help: Failed to list *v1.ApisixService: apisixservices.apisix.apache.org is forbidden: User "system:serviceaccount:apisix:apisix-view-serviceaccount" cannot list resource "apisixservices" in API group "apisix.apache.org" at the cluster scope

### ISSUE THREAD

**Issue by ArmitageW** [apache/apisix-ingress-controller#581]
### Issue description
According to the official website, use kustomization to deploy, report an error, there is no CRD of apisixservices：

pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.ApisixService: apisixservices.apisix.apache.org is forbidden: User "system:serviceaccount:apisix:apisix-view-serviceaccount" cannot list resource "apisixservices" in API group "apisix.apache.org" at the cluster scope

### Environment
apisix-ingress-controller-1.0.0
apisix version: 2.7

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
ApisixService has been removed in #230  #566

Can you run `kubectl get apisixservices -A`  command ?

**Comment by gxthrj** [comment]
Yes, you may keep the CRD defination the same as [deploy](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy).

By the way, have you installed an old version of apisix-ingress before?

**Comment by ArmitageW** [comment]
@tao12345666333 

[root@scq03-VMWARE0050568fcbb0-test-app-66-34-msxf ~]# kubectl get apisixservices -A
error: the server doesn't have a resource type "apisixservices"

**Comment by ArmitageW** [comment]
@gxthrj 
No previous version installed

**Comment by ArmitageW** [comment]
ok，default version is 0.1.0

./deployment/ingress-controller.yaml:44:      - image: apache/apisix-ingress-controller:0.1.0

The image version needs to be modified

**Comment by tao12345666333** [comment]
yep, can you open a PR to modify it？ @ArmitageW

**Comment by ArmitageW** [comment]
OK
