### ISSUE TITLE
feat: Need to fully compare CRD and  internal objects in APISIX

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#587]
### Issue description
The current Ingress controller is highly available through elections, but when all controller instances are shut down, some events of deleting or modifying resources will be lost, which will cause inconsistencies between the declared configuration and the APISIX state, so we need a full comparison mechanism when apisix ingress starting up.

Discussing in https://lists.apache.org/thread.html/r2c73eca7b61200ffd132d2397d01cf20fa41955c781c34f39d915b83%40%3Cdev.apisix.apache.org%3E

**Comment by fatalc** [comment]
Consider migrating to <https://github.com/kubernetes-sigs/controller-runtime> 😊

**Comment by tao12345666333** [comment]
#680 has been merged. Should we close this one? @gxthrj

**Comment by gxthrj** [comment]
Yes, close it now.
