### ISSUE TITLE
bug: Install ValidationError(CustomResourceDefinition.spec.versions[0])

### ISSUE THREAD

**Issue by f1soft** [apache/apisix-ingress-controller#588]
### Issue description
ingress Installation failure
 
### Environment
* kubectl version
* Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", Git
TreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.11", GitCommit:"2093e9ec8db4fd321acac1e8b78ba28792ff63
95", GitTreeState:"clean", BuildDate:"2021-06-04T14:12:37Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

Tencent TKE
### Minimal test code / Steps to reproduce the issue

1.kubectl create namespace ingress-apisix
2.kubectl kustomize .\samples\deploy\ | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/apisixconsumers.apisix.apache.org created
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "
deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionVersion; if you choose to igno
re these errors, turn validation off with --validate=false

**Comment by gxthrj** [comment]
I'm afraid this error is because [this field](https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1beta1/ApisixRoute.yaml#L47) cannot be recognized，You can try to delete this field and try again.

But it is strange that e2e is ok, which is also use this CustomResourceDefinition.

**Comment by f1soft** [comment]
delete 'deprecated' filed get succeeded，Tks！@gxthrj
