### ISSUE TITLE
We may need debounce mechanism to collapse Kubernetes events

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#60]

**Comment by gxthrj** [comment]
Is it related to #59 ?

**Comment by tokers** [comment]
> Is it related to #59 ?

No.

**Comment by gxthrj** [comment]
Or Is this issue meaning : Need a mechanism to ensure that the resources in k8s and apisix are consistent ?

**Comment by tokers** [comment]
@gxthrj The debounce mechanism is used to prevent ingress-apisix/apisix overwhelming from too many resource change events arriving in.

**Comment by gxthrj** [comment]
This will be an extreme scenario, we can simulate and test the current limiting capability of `workqueue`.

**Comment by gxthrj** [comment]
stale issue, feel free to reopen .
