### ISSUE TITLE
request help:  failed to record status change for ApisixRoute

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#611]
### Issue description
When creating a new ApisixRoute resource, the error is reported as follows:
`ingress/status.go:91	failed to record status change for ApisixRoute	{"error": "Operation cannot be fulfilled on apisixroutes.apisix.apache.org \"api-product-v1\": the object has been modified; please apply your changes to the latest version and try again", "name": "api-product-v1", "namespace": "app"}`

Use the latest version of CRD, but with some modifications.  diff file:
![image](https://user-images.githubusercontent.com/7134928/127820756-451e832c-3d7c-43c3-b731-9e6671600686.png)

### Environment

* your apisix-ingress-controller: v1.1.0
* your Kubernetes cluster version: v1.16.9

**Comment by gxthrj** [comment]
@Donghui0 Is this issue related to https://github.com/apache/apisix-ingress-controller/pull/609?

**Comment by Donghui0** [comment]
> @Donghui0 Is this issue related to #609?

yep~

**Comment by gxthrj** [comment]
I found a scenario that can reproduce your problem. 
When two controllers in the cluster change the status of the `ApisixRoute` resource at the same time, this error will be reported. 

Please check if there are more than two controllers in your test environment.

**Comment by Donghui0** [comment]
> I found a scenario that can reproduce your problem.
> When two controllers in the cluster change the status of the `ApisixRoute` resource at the same time, this error will be reported.
> 
> Please check if there are more than two controllers in your test environment.

Yes. There are indeed multiple controllers in the same cluster. It seems that there are still some problems with running multiple controllers in the same cluster.

**Comment by gxthrj** [comment]
> > I found a scenario that can reproduce your problem.
> > When two controllers in the cluster change the status of the `ApisixRoute` resource at the same time, this error will be reported.
> > Please check if there are more than two controllers in your test environment.
> 
> Yes. There are indeed multiple controllers in the same cluster. It seems that there are still some problems with running multiple controllers in the same cluster.

The Ingress controller uses the election mechanism to determine which controller is effective. When configuring, ensure that only one controller handles one resource.

**Comment by Donghui0** [comment]
is my problem.
The other controller is fully watched.

**Comment by diaosj** [comment]
> 

I've read this commit. I don't understand why this issue is related to that commit.

**Comment by diaosj** [comment]
> > @Donghui0 Is this issue related to #609?
> 
> yep~

Hi, I've read this commit. But I don't understand why this issue is related to that commit.
