### ISSUE TITLE
bug: Wrong events keep circulating in the workqueue.

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#612]
### Issue description
In the following scenario:
1: Create ApisixRoute resource, but spec.http.backends.serverName does not exist in the current namespace.
2: Modify the ApisixRoute metadata.namespace attribute; make it in the same namespace as spec.http.backends.serverName.

the resource can be successfully created in apisix.  
However, the events in step 1 will continue to flow and cannot be deleted.  
These exceptions `sync ApisixRoute failed, will retry....` are thrown in the log.
### Environment

* your apisix-ingress-controller version: v1.1
* your Kubernetes cluster version: v1.16.9

### Minimal test code / Steps to reproduce the issue
Refer to the above 👆

### What's the actual result? (including assertion message & call stack if applicable)
Wrong events keep circulating in the workqueue.
### What's the expected result?
Wrong events can be terminated in time.

**Comment by tokers** [comment]
We may try to avoid this problem by setting up the admission server, so we can reject these invalid ApisixRoute configurations.

**Comment by gxthrj** [comment]
I'm afraid this is related to your behavior. `ApisixRoute` resources are namespace-sensitive. The `namespace` and `name` of 
 `ApisixRoute` are not allowed to be changed at will. 
If you need to modify the namespace, you can delete the original `ApisixRoute` first, and then create a new `ApisixRoute` resource with the correct namespace.

**Comment by Donghui0** [comment]
> I'm afraid this is related to your behavior. `ApisixRoute` resources are namespace-sensitive. The `namespace` and `name` of
> `ApisixRoute` are not allowed to be changed at will.
> If you need to modify the namespace, you can delete the original `ApisixRoute` first, and then create a new `ApisixRoute` resource with the correct namespace.

Yes. The correct way is as you said. 
But, When creating ApisixRoute CRD, I remembered the corresponding namespace of the service incorrectly. So I created the wrong CRD.

**Comment by tao12345666333** [comment]
you can remove the old CRD.
