### ISSUE TITLE
Feature Suggest support hot reload when configmap changed

### ISSUE THREAD

**Issue by zhaojizhuang** [apache/apisix-ingress-controller#618]
### Issue description
Feature Suggest:
 Support hot reload when configmap `ingress-apisix/apisix-ingress-controller-configmap`changed

**Comment by gxthrj** [comment]
Good proposal, but there are fewer use cases for this feature.

The apisix-ingress-controller is the control plane, which can be restarted at any time without affecting business traffic. Moreover, the modification of configmap is a very low-frequency operation, and doesn’t really need hot reload. 

Can you describe the business scenario?

**Comment by zhaojizhuang** [comment]
> Can you describe the business scenario?

Such as : change `log level`, `enable profile`.Just hope it will take effect immediately like ingress nginx

**Comment by tokers** [comment]
> > Can you describe the business scenario?
> 
> Such as : change `log level`, `enable profile`.Just hope it will take effect immediately like ingress nginx

ingress-nginx watches on files like nginx template, geoip files, but it doesn't watch on its own (the control plane) configuration file.

**Comment by zhaojizhuang** [comment]
@tokers configmap `ingress-nginx/ingress-nginx-controller`

**Comment by zhaojizhuang** [comment]
@tokers ingress-nginx's control plane configuration (such as `profiling` )is define in command args. So update deploy will update the Pod。What I mean is that it is best to support hot reload if the configurations is defined in configmap，otherwise，why not defined in container command args？

**Comment by tokers** [comment]
> @tokers ingress-nginx's control plane configuration (such as `profiling` )is define in command args. So the updation of deploy will update the Pod。What I mean is that it is best to support hot reload if the configurations is defined in configmap，otherwise，why not defined in container command args？

Settings in configmap (actually is the configuration file for apisix-ingress-controller) are the same as command line args.

Anyway, PR is welcome to support this feature.
