### ISSUE TITLE
bug:   sync to APISIX failed when remove ApisixRoute (v2beta1)

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#619]
### Issue description
Sync to APISIX failed when remove ApisixRoute (v2beta1)
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`); v1.1

### What's the expected result?
Can sync successfully when remove ApisixRoute (v2beta1)

**Comment by tokers** [comment]
@gxthrj You may describe the issue more elaborately.
