### ISSUE TITLE
request help: Ingress迁移

### ISSUE THREAD

**Issue by zou8944** [apache/apisix-ingress-controller#629]
### Issue description

通过查看apisix-ingress-controller手册，apisix的路由声明都在ApiRoute这一CRD上，如果我想将之前的nginx-ingress-controller更换为apisix，岂不是需要修改之前所有的ingress声明吗？

还有一个版本问题，目前有两个版本，v1和v2alpha1，但文档中出现的却是v2beta1，请问是什么原因导致文档和实际的版本不一致？v2alpha1会提供多久的支持？会不会我用到一半就又升级了。

**Comment by zou8944** [comment]
But there is no v2beta1 CRD after installing apisix-ingress-controller in my ACK.
![企业微信截图_617acbbe-029d-45d4-af24-d129535d6057](https://user-images.githubusercontent.com/18495995/129664457-14173d83-117d-4f00-ab2b-48ac04db9a4a.png)

**Comment by tokers** [comment]
@zou8944 Please try to use the newest charts.

```
helm search repo apisix
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
apisix/apisix                           0.3.5           2.7.0           A Helm chart for Apache APISIX
apisix/apisix-dashboard                 0.1.5           2.7.0           A Helm chart for Apache APISIX Dashboard
apisix/apisix-ingress-controller        0.6.0           1.1.0           Apache APISIX Ingress Controller for Kubernetes
```

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-helm-chart/blob/ba0b70d5cc4e43d04b20cc86c3e8b2f60af1b3db/charts/apisix-ingress-controller/values.yaml#L96

I have upgraded the default configuration to v2beta1

**Comment by Iced-Sun** [comment]
> 
> The APISIX ingress controller also supports the native ingress resource.
> 
> Also, now you should use the version v2beta1 when you use apisix-ingress-controller.

A slightly off-topic question: does the native Ingress support the apisix-specific configurations (e.g., stream/plugin/healthcheck configurations)?

**Comment by tokers** [comment]
> > The APISIX ingress controller also supports the native ingress resource.
> > Also, now you should use the version v2beta1 when you use apisix-ingress-controller.
> 
> A slightly off-topic question: does the native Ingress support the apisix-specific configurations (e.g., stream/plugin/healthcheck configurations)?

Features like stream proxy and plugins are not supported in Ingress yet, while `healthcheck` is a feature related to backend or upstream, it's supported in the CRD `ApisixUpstream`.
