### ISSUE TITLE
request help: 有关于grpc相关的apisixroute

### ISSUE THREAD

**Issue by lgy1027** [apache/apisix-ingress-controller#631]
你好，我现在想用apisix做http和grpc的代理，现在只会创建http的，请问grpc的该怎么做，因为配置grpc还需要配置TLS证书，这些都不知道用apisix怎么完成，目前用kong已经实现

**Comment by tokers** [comment]
@lgy1027 Please read http://apisix.apache.org/ for more details., for instance: http://apisix.apache.org/docs/apisix/grpc-proxy/.

**Comment by lgy1027** [comment]
> @lgy1027请阅读http://apisix.apache.org/了解更多详情，例如：[http](http://apisix.apache.org/docs/apisix/grpc-proxy/) : //apisix.apache.org/docs/apisix/grpc-proxy/。

感谢回复，但是看着文档更多的是http直接请求设置参数，我现在需要的是通过k8s完成交互，目前我想测试的是一个svc暴漏两个端口，一个是http端口，还有个是grpc端口，然后针对grpc需要单独创建upstream，但是我看官网说grpc需要设置证书，请问证书在哪里设置，是创建ApisixTls设置吗，然后证书如何和grpc关联，针对这个场景有很多疑问，主要是官网对ingress controller的文档不太友好，示例很少，还有就是helm安装apisix，crd没有betal版本，以下是我创建的实例。
````
func Test_Client(t *testing.T)  {
	BuildCons()
	BuildRoute()
	BuildApiSixUpStream()
}

func BuildApiSixUpStream()  {
	http := &apisixv1.ApisixUpstream{
		ObjectMeta:metav1.ObjectMeta{
			Name: "httpbin-http",
			Namespace: "lgy",
		},
		Spec: &apisixv1.ApisixUpstreamSpec{
			PortLevelSettings:[]apisixv1.PortLevelSettings{
				apisixv1.PortLevelSettings{
					Port: 80,
					ApisixUpstreamConfig:apisixv1.ApisixUpstreamConfig{
						Scheme:"http",
					},
				},
			},

		},
	}
	grpc := &apisixv1.ApisixUpstream{
		ObjectMeta:metav1.ObjectMeta{
			Name: "httpbin-grpc",
			Namespace: "lgy",
		},
		Spec: &apisixv1.ApisixUpstreamSpec{
			PortLevelSettings:[]apisixv1.PortLevelSettings{
				apisixv1.PortLevelSettings{
					Port: 81,
					ApisixUpstreamConfig:apisixv1.ApisixUpstreamConfig{
						Scheme:"grpc",
					},
				},
			},

		},
	}
	result, err := client.ApisixV1().ApisixUpstreams("lgy").Create(context.TODO(),http,v1.CreateOptions{})
	fmt.Println(err)
	fmt.Println(result)
	result, err = client.ApisixV1().ApisixUpstreams("lgy").Create(context.TODO(),grpc,v1.CreateOptions{})
	fmt.Println(err)
	fmt.Println(result)
	apisixv1.ApisixTls{}
}

func BuildCons()  {
	cons := &v2alpha1.ApisixConsumer{
		ObjectMeta:metav1.ObjectMeta{
			Name: "test",
			Namespace: "lgy",
		},
		Spec:v2alpha1.ApisixConsumerSpec{
			AuthParameter:v2alpha1.ApisixConsumerAuthParameter{
				KeyAuth:&v2alpha1.ApisixConsumerKeyAuth{
					//Value: &v2alpha1.ApisixConsumerKeyAuthValue{
					//	Key: "lgy",
					//},
					SecretRef:&corev1.LocalObjectReference{
						Name: "mysecret",
					},
				},
			},
		},
	}
	result, err := client.ApisixV2alpha1().ApisixConsumers("lgy").Create(context.TODO(),cons,v1.CreateOptions{})
	fmt.Println(err)
	fmt.Println(result)
}

func BuildRoute()  {
	w := int(100)
	http := &v2alpha1.ApisixRoute{
		ObjectMeta:metav1.ObjectMeta{
			Name: "test-lgy-http",
			Namespace: "lgy",
		},
		Spec:&v2alpha1.ApisixRouteSpec{
			HTTP: []*v2alpha1.ApisixRouteHTTP{
				&v2alpha1.ApisixRouteHTTP{
					Name: "http",
					Match: &v2alpha1.ApisixRouteHTTPMatch{
						Hosts: []string{"local.httpbin.org"},
						Paths: []string{"/*"},
					},
					Backends: []*v2alpha1.ApisixRouteHTTPBackend{
						&v2alpha1.ApisixRouteHTTPBackend{
							ServiceName: "httpbin-http",
							ServicePort: intstr.IntOrString{
								Type: intstr.Int,
								IntVal: 80,
							},
							Weight:&w,
						},
					},
					Authentication: &v2alpha1.ApisixRouteAuthentication{
						Enable: true,
						Type: "keyAuth",
					},
					Plugins: []*v2alpha1.ApisixRouteHTTPPlugin{
						&v2alpha1.ApisixRouteHTTPPlugin{
							Config:v2alpha1.ApisixRouteHTTPPluginConfig{
								"whitelist":[]string{"lgy_test"},
							},
							Enable:true,
							Name: "consumer-restriction",
						},
					},
				},
			},
		},
	}

	grpc := &v2alpha1.ApisixRoute{
		ObjectMeta:metav1.ObjectMeta{
			Name: "test-lgy-grpc",
			Namespace: "lgy",
		},
		Spec:&v2alpha1.ApisixRouteSpec{
			HTTP: []*v2alpha1.ApisixRouteHTTP{
				&v2alpha1.ApisixRouteHTTP{
					Name: "grpc",
					Match: &v2alpha1.ApisixRouteHTTPMatch{
						Hosts: []string{"local.httpbin.org"},
						Paths: []string{"/*"},
					},
					Backends: []*v2alpha1.ApisixRouteHTTPBackend{
						&v2alpha1.ApisixRouteHTTPBackend{
							ServiceName: "httpbin-grpc",
							ServicePort: intstr.IntOrString{
								Type: intstr.Int,
								IntVal: 81,
							},
							Weight:&w,
						},
					},
					Authentication: &v2alpha1.ApisixRouteAuthentication{
						Enable: true,
						Type: "keyAuth",
					},
					Plugins: []*v2alpha1.ApisixRouteHTTPPlugin{
						&v2alpha1.ApisixRouteHTTPPlugin{
							Config:v2alpha1.ApisixRouteHTTPPluginConfig{
								"whitelist":[]string{"lgy_test"},
							},
							Enable:true,
							Name: "consumer-restriction",
						},
					},
				},
			},
		},
	}
	result, err := client.ApisixV2alpha1().ApisixRoutes("lgy").Create(context.TODO(),http,v1.CreateOptions{})
	fmt.Println(err)
	fmt.Println(result)
	result, err = client.ApisixV2alpha1().ApisixRoutes("lgy").Create(context.TODO(),grpc,v1.CreateOptions{})
	fmt.Println(err)
	fmt.Println(result)
}
````

![image](https://user-images.githubusercontent.com/38779388/129825351-d2bfab6e-ea6b-4600-8dce-d3a0eb49e2df.png)

**Comment by lgy1027** [comment]
> @lgy1027请阅读http://apisix.apache.org/了解更多详情，例如：[http](http://apisix.apache.org/docs/apisix/grpc-proxy/) : //apisix.apache.org/docs/apisix/grpc-proxy/。

比如如果我使用ingress配置参数Spec.TLS来实现grpc的请求证书验证，在apisixroute中需要这么做吗，还是说我直接配置个apisxiTLS，然后在hosts指定地址，在Secret中指定secret就可以实现相同功能？

**Comment by tokers** [comment]
> > @lgy1027请阅读[http://apisix.apache.org/了解更多详情，例如：[http](http://apisix.apache.org/docs/apisix/grpc-proxy/)](http://apisix.apache.org/%E4%BA%86%E8%A7%A3%E6%9B%B4%E5%A4%9A%E8%AF%A6%E6%83%85%EF%BC%8C%E4%BE%8B%E5%A6%82%EF%BC%9A%5Bhttp%5D(http://apisix.apache.org/docs/apisix/grpc-proxy/)) : //apisix.apache.org/docs/apisix/grpc-proxy/。
> 
> 比如如果我使用ingress配置参数Spec.TLS来实现grpc的请求证书验证，在apisixroute中需要这么做吗，还是说我直接配置个apisxiTLS，然后在hosts指定地址，在Secret中指定secret就可以实现相同功能？

Yes, you can use ApisixTls to configure certificates, and certificate matching is done automatically by their SANs.

**Comment by lgy1027** [comment]
> > > @lgy1027请阅读[http://apisix.apache.org/了解更多详情，例如：[http](http://apisix.apache.org/docs/apisix/grpc-proxy/)](http://apisix.apache.org/%E4%BA%86%E8%A7%A3%E6%9B%B4%E5%A4%9A%E8%AF%A6%E6%83%85%EF%BC%8C%E4%BE%8B%E5%A6%82%EF%BC%9A%5Bhttp%5D(http://apisix.apache.org/docs/apisix/grpc-proxy/)) : //apisix.apache.org/docs/apisix/grpc-proxy/。
> > 
> > 
> > 比如如果我使用ingress配置参数Spec.TLS来实现grpc的请求证书验证，在apisixroute中需要这么做吗，还是说我直接配置个apisxiTLS，然后在hosts指定地址，在Secret中指定secret就可以实现相同功能？
> 
> Yes, you can use ApisixTls to configure certificates, and certificate matching is done automatically by their SANs.

http://apisix.apache.org/zh/docs/apisix/grpc-proxy/我是 参考这个做的代理，现在无法测试grpc，
![image](https://user-images.githubusercontent.com/38779388/129994575-8e7f1803-58be-41cb-b79c-7ab84d35b5ed.png)
这个是我起的服务，
![image](https://user-images.githubusercontent.com/38779388/129994639-d2b1db45-5b39-4630-924d-117cee91d30a.png)
![image](https://user-images.githubusercontent.com/38779388/129994692-d19c9721-0065-4190-bc0c-5a94dc258c63.png)
![image](https://user-images.githubusercontent.com/38779388/129994732-6495a085-6db5-477d-bd29-258c466825b8.png)
请问我该怎么测试

**Comment by nic-chen** [comment]
@tokers @gxthrj @tao12345666333  please have a look.

**Comment by tokers** [comment]
@lgy1027 How did you test the gRPC service? You should send HTTP requests with correct URI path and payload according to the gRPC IDL.

**Comment by lgy1027** [comment]
> @lgy1027 How did you test the gRPC service? You should send HTTP requests with correct URI path and payload according to the gRPC IDL.

所以这块不清楚要怎么测试，后面我把gateway的https设置打开了，
![image](https://user-images.githubusercontent.com/38779388/130066792-4df88de0-920f-4ffa-8e6f-31eef600ecfb.png)
然后发送请求
我发送的命令是grpcurl -insecure -import-path /  -proto helloworld.proto  \
    -d '{"name":"apisix"}' 10.233.22.220:443 helloworld.Greeter.SayHello，但是报错Failed to dial target host "10.233.22.220:443": remote error: tls: internal error

**Comment by lgy1027** [comment]
> @lgy1027 How did you test the gRPC service? You should send HTTP requests with correct URI path and payload according to the gRPC IDL.

这块不是这么好懂对于新手来说，有没有详细的文档，还有个问题，当我配置upstream里面设置了三个PortLevelSettings，在apisix中会全部覆盖成一个Scheme，如下
![image](https://user-images.githubusercontent.com/38779388/130067251-e6c9ea29-c9bd-4a7c-8c5b-d257906d6bf1.png)
````
{"node":{"dir":true,"nodes":[{"modifiedIndex":445,"key":"\/apisix\/upstreams\/1e604899","createdIndex":438,"value":{"pass_host":"pass","nodes":[{"host":"10.233.99.151","port":50051,"priority":0,"weight":100}],"labels":{"managed-by":"apisix-ingress-controller"},"update_time":1629374757,"create_time":1629374756,"scheme":"grpc","type":"roundrobin","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","hash_on":"vars","name":"lgy_grpc_50051","id":"1e604899"}},{"modifiedIndex":446,"key":"\/apisix\/upstreams\/87691923","createdIndex":439,"value":{"pass_host":"pass","nodes":[{"host":"10.233.99.151","port":50052,"priority":0,"weight":100}],"labels":{"managed-by":"apisix-ingress-controller"},"update_time":1629374757,"create_time":1629374756,"scheme":"grpc","type":"roundrobin","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","hash_on":"vars","name":"lgy_grpc_50052","id":"87691923"}},{"modifiedIndex":444,"key":"\/apisix\/upstreams\/ca0746f3","createdIndex":440,"value":{"pass_host":"pass","nodes":[{"host":"10.233.99.151","port":8082,"priority":0,"weight":100}],"labels":{"managed-by":"apisix-ingress-controller"},"update_time":1629374757,"create_time":1629374756,"scheme":"grpc","type":"roundrobin","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","hash_on":"vars","name":"lgy_grpc_8082","id":"ca0746f3"}}],"key":"\/apisix\/upstreams"},"count":3,"action":"get"}
````

**Comment by tao12345666333** [comment]
The grpc document has been added in #699 , now I will close this issue, we can track it through #699 

Please feel free to reopen it if you have any other questions.
