### ISSUE TITLE
request help: How about change field retries to value from pointer.

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#643]
[apisix admin upstream api](https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-3) describe field `retries`: 
*  If not set the retry mechanism is enabled by default
* 0 means disable retry mechanism.  
   
     
     
I wanna disable retry meechanism, but `0` not pass to the `admin upstream api` because the `omitempty`

https://github.com/apache/apisix-ingress-controller/blob/master/pkg/kube/apisix/apis/config/v1/types.go#L115
![image](https://user-images.githubusercontent.com/10919124/130190848-8812f8bc-7b32-46f9-81aa-434871c9df76.png)

https://github.com/apache/apisix-ingress-controller/blob/master/pkg/types/apisix/v1/types.go#L184
![image](https://user-images.githubusercontent.com/10919124/130190810-dca0680a-c618-48f1-a085-8cd76e3cfec9.png)

`Retries *int` that ok

**Comment by tokers** [comment]
@chzhuo Good, `*int` works well, PR's welcome!

**Comment by tao12345666333** [comment]
#647 has been merged.  I will close this issue. Feel free to reopen it, if you have any question.
