### ISSUE TITLE
I want custom a plugin for Ingress controller

### ISSUE THREAD

**Issue by geekgao** [apache/apisix-ingress-controller#656]
I want custom a plugin for Ingress controller. It seems that the documentation description is missing?
Does anyone know how or best practice articles?

**Comment by geekgao** [comment]
> you can see our e2e test case about how to using plugin https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/plugins

In actually, I meant to write a plugin. But Go is not my skill stack.

**Comment by tao12345666333** [comment]
Under the current architecture, APISIX is the actual data plane, and all actual traffic functions are implemented in APISIX.

**Comment by tao12345666333** [comment]
So you can use lua to develop plug-ins in APISIX, of course now we also support the use of Python development

**Comment by geekgao** [comment]
> So you can use lua to develop plug-ins in APISIX, of course now we also support the use of Python development

From [document](https://apisix.apache.org/docs/apisix/plugin-develop)   , I feel couldn't understand about how to write plugin for APISIX Ingress Controller  :-(  
Did you give me some other hints, such as the relationship between Ingress and conf/config.yaml file ? 
Thanks !

**Comment by tokers** [comment]
> > So you can use lua to develop plug-ins in APISIX, of course now we also support the use of Python development
> 
> 
> 
> From [document](https://apisix.apache.org/docs/apisix/plugin-develop)   , I feel couldn't understand about how to write plugin for APISIX Ingress Controller  :-(  
> 
> Did you give me some other hints, such as the relationship between Ingress and conf/config.yaml file ? 
> 
> Thanks !

After you developed your own plugin and distributed it with the apisix, you can configure your plugin in the apisixroute cr.

**Comment by gxthrj** [comment]
@geekgao You can configure plug-ins directly under `ApisixRoute` resources like [this](https://apisix.apache.org/docs/ingress-controller/concepts/apisix_route#plugins), but custom plug-ins are not what ingress-controller does.
So you need to learn how to customize the plug-in first from the [documentation](https://apisix.apache.org/docs/apisix/plugin-develop/), and then you can configure it in the ApisixRoute resource according to the plug-in's schema.

**Comment by geekgao** [comment]
thanks for your tips @gxthrj
