### ISSUE TITLE
test:  There are some false positives in e2e-test ,Need to be fixed.

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#658]
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by tao12345666333** [comment]
Currently our e2e test case seems to run pretty well.
I will close this issue. Feel free to reopen it, if you have any question.
