### ISSUE TITLE
apisix-ingress-controller日志一直报错

### ISSUE THREAD

**Issue by RunYuannn** [apache/apisix-ingress-controller#659]
### Issue description

按照文档 [Install Ingress APISIX on K3S and Rancher RKE](https://apisix.apache.org/docs/ingress-controller/deployments/k3s-rke)安装，但是apisix-ingress-controller pod一直刷error日志，并按照文档 [Proxy the httpbin service with Ingress](https://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service-with-ingress) 配置ingress无效

![image](https://user-images.githubusercontent.com/71421689/131793616-76e7952c-b6e4-44e7-a8b9-33efb022f9a4.png)

![image](https://user-images.githubusercontent.com/71421689/131794742-800ab57c-fa6a-4847-b657-c7bc8ed97969.png)

apisix-ingress-controller 日志报错：

![image](https://user-images.githubusercontent.com/71421689/131793674-c87135c0-12cc-4259-9b64-bbc894daf4c5.png)

404：

![image](https://user-images.githubusercontent.com/71421689/131795380-d144af84-8462-4e72-9e96-897b2fe1be6f.png)

yaml：

![image](https://user-images.githubusercontent.com/71421689/131794589-c877c8eb-9d72-42a1-ad63-f1aa2b85b515.png)

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);

![1630564440(1)](https://user-images.githubusercontent.com/71421689/131794665-49a39734-d5fa-4a8f-9a6a-b7edcb810246.png)

* your Kubernetes cluster version (output of `kubectl version`);

![1630564473(1)](https://user-images.githubusercontent.com/71421689/131794643-13a6f801-e0e7-49a7-b58a-e14022851d0d.png)

**Comment by tao12345666333** [comment]
can you try to delete apisix pod?

**Comment by tao12345666333** [comment]
can you please delete your ingress resource and re-apply it ?

**Comment by RunYuannn** [comment]
helm delete apisix -n ingress-apisix ？

**Comment by tao12345666333** [comment]
no, only need kubectl delete ingress resource

**Comment by RunYuannn** [comment]
is that right？

![8bfda9bc0bbe274f366c7fc238bd729](https://user-images.githubusercontent.com/71421689/131826114-5674fe92-d16e-4edc-b7e8-bbe124b002ee.png)

![fe06cc5ce7b3a77c1e4c5deac3f4ddd](https://user-images.githubusercontent.com/71421689/131826138-e7315e4e-b088-472f-bf85-d442718e3915.png)


![image](https://user-images.githubusercontent.com/71421689/131825911-1be85b3c-f787-4a9f-adca-c8477f00c65d.png)

**Comment by tokers** [comment]
@RunYuannn Where is the namespace of the ingress resource?

**Comment by RunYuannn** [comment]
@tokers ingress-apisix. same namespace as apisix

**Comment by drrrMikado** [comment]
Same issue.
Ref docs: [Install Ingress APISIX on Minikube](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/minikube.md) and [Proxy httpbin service](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/proxy-the-httpbin-service.md).

![24SPFT1B4{1F3R%37BENRKN](https://user-images.githubusercontent.com/11224565/140715949-67959bf7-9fd2-4500-b63b-1ed272c89766.png)

I also try out: `kubectl run httpbin --image kennethreitz/httpbin --port 80 -n ingress-apisix`.

**Comment by marchlhw** [comment]
我也遇到了一些类似的问题，如下：
![图片](https://user-images.githubusercontent.com/7006014/150284429-d4b39cb5-a027-4a9b-aef6-84323c5445ec.png)
![图片](https://user-images.githubusercontent.com/7006014/150284531-39f77694-4db5-47a1-9ef5-33877303f4cc.png)

**Comment by tao12345666333** [comment]
@marchlhw  what's your apisix-ingress version? 

It looks like the APISIX Ingress controller is not connected to the APISIX cluster.

**Comment by marchlhw** [comment]
> 

![图片](https://user-images.githubusercontent.com/7006014/150485491-54e72cf8-58d6-4a07-b06f-49e03685ee55.png)

**Comment by tokers** [comment]
@tao12345666333 If I remember correctly, we don't merge the #774 in 1.3.0?

**Comment by tao12345666333** [comment]
@tokers right! #774 was merged into v1.4.

**Comment by tao12345666333** [comment]
@marchlhw Please try to restart APISIX Ingress controller.
Or check if the connection information of APISIX is correct.

**Comment by marchlhw** [comment]
> @marchlhw Please try to restart APISIX Ingress controller. Or check if the connection information of APISIX is correct.

![图片](https://user-images.githubusercontent.com/7006014/151118484-1321640f-672b-444f-9375-9b8c67f78a60.png)
![图片](https://user-images.githubusercontent.com/7006014/151118530-2b120fdf-6d90-4a64-b375-af8202e87374.png)
在apisix ingress controller容器里调用管理API是正常的

**Comment by marchlhw** [comment]
重建了ingress-controller，现在报：022-01-26T17:41:05+08:00       error   ingress/pod.go:131      failed to delete pod from cache

**Comment by tao12345666333** [comment]
@marchlhw please refer to https://github.com/apache/apisix-ingress-controller/issues/851#issuecomment-1026306420

I will fix the Helm chat today.

**Comment by tao12345666333** [comment]
@marchlhw @RunYuannn Do you still have problems if you use the latest version?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, and based on current testing and some feedback, the issue has been fixed. I will close it.  If you still have this problem, please feel free to reply or reopen it.
