### ISSUE TITLE
http[].match.exprs - ability to refer to the internal nginx variables

### ISSUE THREAD

**Issue by Iced-Sun** [apache/apisix-ingress-controller#661]
### Issue description

I need use the `$proxy_protocol_server_port` variable in the match rules of ApisixRoute to do the http-to-https redirection. 

We decided to terminate TLS at the load balancer, hence the annotation of `k8s.apisix.apache.org/http-to-https` won't work because it depends on `$scheme` which is always `http`. The proxy protocol could help with the `$proxy_protocol_server_port` variable but it demands the ability to be referred.

As a workaround, I created a redirection ApisixRoute and then added the `vars` match rules manually, for now.

Is there any plan to enable ApisixRoute to refer to arbitary nginx variables? Or better, to support even in native Ingress (e.g. as annotations)?

Regards.

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`):  1.2.0
* your Kubernetes cluster version (output of `kubectl version`): 1.21.2-eks-0389ca3
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`):  N/A

**Comment by vicaya** [comment]
It'd be great if ApisixRoute can support `vars` option for route matching, as it's already supported by the `radixtree_uri_with_parameters` router, which I think is going to be the default anyway?

**Comment by tokers** [comment]
Previously the "easy to use" was the first thing we considered when we designed this feature. So some specific settings like `Query`, `Header` and etc were introduced.

We may add another setting like `NginxVar` to let People extend this feature, but apparently, it's not so friendly for users. @tao12345666333 What's your idea?

**Comment by tao12345666333** [comment]
> Previously the "easy to use" was the first thing we considered when we designed this feature. So some specific settings like `Query`, `Header` and etc were introduced.
> 
> We may add another setting like `NginxVar` to let People extend this feature, but apparently, it's not so friendly for users. @tao12345666333 What's your idea?

Sorry, I have too many reminders, I missed this one.

I think we should add this capability so that users can better utilize the capabilities of APISIX.

**Comment by Belyenochi** [comment]
> > Previously the "easy to use" was the first thing we considered when we designed this feature. So some specific settings like `Query`, `Header` and etc were introduced.
> > We may add another setting like `NginxVar` to let People extend this feature, but apparently, it's not so friendly for users. @tao12345666333 What's your idea?
> 
> Sorry, I have too many reminders, I missed this one.
> 
> I think we should add this capability so that users can better utilize the capabilities of APISIX.

If no one else, please assign to me

**Comment by tao12345666333** [comment]
👌

**Comment by Belyenochi** [comment]
> 👌
I'm a little confused, exprs can support some NginxVars, should we expand the fields based on ApisixRouteHTTPMatchExpr?

**Comment by Belyenochi** [comment]
> 👌

I'm a little confused, exprs can support some NginxVars, should we expand the fields based on ApisixRouteHTTPMatchExpr?

**Comment by Erhao** [comment]
Let me try it, too.
