### ISSUE TITLE
request help: Why using apisix admin api but not modify the data in etcd?

### ISSUE THREAD

**Issue by fregie** [apache/apisix-ingress-controller#669]
### Issue description
Why using apisix admin api but not modify the data in etcd to manage apisix config?
I think compare and modify the config data in etcd is simpler and more direct,and there is no coupling to apisix

**Comment by tao12345666333** [comment]
APISIX's admin api can help us do some schema verification

**Comment by fregie** [comment]
I think use apisix admin api to do schema things has becoming a problem.It has led to some unnecessary coupling.
In apisix-dashboard,some schema feature must depend on apisix admin api too, this is really not good.
How about separating those functions from apisix, make data panel more pure, only communicate with etcd(include register schema information to etcd).Then we offer a common sdk or service to get or verify schema infomation for other service like ingress-controll or dashboard.

**Comment by tokers** [comment]
> I think use apisix admin api to do schema things has becoming a problem.It has led to some unnecessary coupling.
> In apisix-dashboard,some schema feature must depend on apisix admin api too, this is really not good.
> How about separating those functions from apisix, make data panel more pure, only communicate with etcd(include register schema information to etcd).Then we offer a common sdk or service to get or verify schema infomation for other service like ingress-controll or dashboard.

We cannot fetch the first feedback from the config users, i.e. APISIX cluster, if we just write data to ETCD, we won't know any incompatible problems or bugs, instead, Admin APIs do this so we can record the kinds of errors to CRD status or error log, and, the bad config will not be persistent.

**Comment by fregie** [comment]
@tokers 
I got it.Using admin api is a correct choice
