### ISSUE TITLE
Chore: change the module from `github.com/api7/ingress-controller` to `github.com/apache/apisix-ingress-controller`

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#67]

**Comment by Firstsawyou** [comment]
This looks very interesting, let me try it. ^ _ ^

**Comment by Firstsawyou** [comment]
@gxthrj  I need to change all `github.com/api7/ingress-controller` to `github.com/apache/apisix-ingress-controller` right?

**Comment by tokers** [comment]
@Firstsawyou Yes, you have to.

**Comment by tokers** [comment]
Change module name is different from change dependencies, so we cannot use replace.

**Comment by Firstsawyou** [comment]
> Change module name is different from change dependencies, so we cannot use replace.

Got it.
