### ISSUE TITLE
bug:  recordStatus status is overwritten  

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#671]
### Issue description
Create an incorrect Route CRD, such as a parameter error in the plugin. recordStatus will be updated to **_resourceSyncAborted**.  But in the handleSyncErr method, it is covered as **_resourceSynced**.

![image](https://user-images.githubusercontent.com/7134928/132323755-f17de79b-5564-48b3-9446-f2ee9986e434.png)

https://github.com/apache/apisix-ingress-controller/blob/6a8658db1788c687c70c9f235601cc8224e0b38c/pkg/ingress/apisix_route.go#L246-L257

### Environment

* your apisix-ingress-controller version: 1.2

### Minimal test code / Steps to reproduce the issue

1. create incorrect Route CRD.
2. kubectl get apisixroute xxx -n namespace -o json 

### What's the actual result? (including assertion message & call stack if applicable)
status.conditions[0].message is "Sync Successfully"

### What's the expected result?
status.conditions[0].message  is  err.Error()

**Comment by tokers** [comment]
@Donghui0 PR's welcome to solve it.

**Comment by gxthrj** [comment]
When `errOrigin == nil`, it should be `_resourceSynced`, else should be `_resourceSyncAborted `
cc https://github.com/apache/apisix-ingress-controller/blob/6a8658db1788c687c70c9f235601cc8224e0b38c/pkg/ingress/apisix_route.go#L275-L283

**Comment by Donghui0** [comment]
> When `errOrigin == nil`, it should be `_resourceSynced`, else should be `_resourceSyncAborted `
> cc
> 
> https://github.com/apache/apisix-ingress-controller/blob/6a8658db1788c687c70c9f235601cc8224e0b38c/pkg/ingress/apisix_route.go#L275-L283

This code will not execute.  line 268 `return` execute.

https://github.com/apache/apisix-ingress-controller/blob/5c9cdbe7fc2c28f3023d635dbbd9bc833388a2bf/pkg/ingress/apisix_route.go#L246-L293

**Comment by gxthrj** [comment]
related to #682

**Comment by gxthrj** [comment]
close this issue as #706 has been merged.
