### ISSUE TITLE
how to set use-forwarded-headers

### ISSUE THREAD

**Issue by aikin-vip** [apache/apisix-ingress-controller#675]
### Issue description
i use aliyun clb and apisix-ingress-controller and  i can't get real client ip 
i found link [https://developer.aliyun.com/article/699074](https://developer.aliyun.com/article/699074) about it 
but the article talk about is nginx-ingress-controller 
how i can i set it in apisix-ingress-controller ?

### Environment
apisix-ingress-controller: 1.0.0
Kubernetes cluster version: 1.20

**Comment by tokers** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/real-ip.md for details, you don't need to modify APISIX Ingress controller.

**Comment by aikin-vip** [comment]
thanks.  i change service externalTrafficPolicy to local  and fix my problem
