### ISSUE TITLE
bug: apisix-ingress-cotroller seems to redirect all services to apisix-dashboard

### ISSUE THREAD

**Issue by superwjc** [apache/apisix-ingress-controller#676]
### Issue description
I haved installed apisix/apisix-dashboard/apisix-ingress-controller locally with helm, the charts tarballs were downloaded from [https://github.com/apache/apisix-helm-chart/releases](url). All the installation steps were ok, but after I created the httpbin service and apply the route rule provided by [http://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service](url), access to http://local.httpbin.org (ie, the test service) was redirected to apisix-dashboard, other services using apisixroute had the same problem.

The format is too ugly, so I redescribe in short:
1. apisix-0.4.0 / apisix-dashboard-0.2.0 / apisix-ingress-controller-0.7.0 / httpbin installed in the "default" namespace, and apply the following apisixroute rule, based on [](http://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service), the only changed filed was spec.http.paths, from "/*" to "/httpbin/*".
That's all the installation steps I took.
```
apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /httpbin/*
    backend:
        serviceName: httpbin
        servicePort: 80
```
2. The apisix-dashboard service has the type "NodePort"(http://172.16.100.101:31803), while the test backend service "httpbin"  has the type "ClusterIP"(http://10.102.62.126:80)
3. The route proxied "local.httpbin.org/httpbin" to the service "httpbin", curl http://local.httpbin.org:31803/httpbin was redirected to apisix-dashboard, that's the problem.

### Environment
* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
Version: 1.2.0
Git SHA: no-git-module
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
* your Kubernetes cluster version (output of `kubectl version`);
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
`Linux k8s-master-1 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Minimal test code / Steps to reproduce the issue

1. install locally from ".tgz" file with helm

`ns="default"; helm install apisix apisix-0.4.0.tgz --set admin.allow.ipList="{0.0.0.0/0}" --set etcd.persistence.enabled=false -n "${ns}" --create-namespace`

`ns="default"; helm install apisix-dashboard apisix-dashboard-0.2.0.tgz --set service.type=NodePort -n "${ns}" --create-namespace`

`ns="default"; helm install apisix-ingress-controller apisix-ingress-controller-0.7.0.tgz --set config.logLevel=debug -n "${ns}" --create-namespace`

2. the pod, service, route, upstream, and apisixroute was ok

`ns="default"; kubectl get svc,pod -n "${ns}"`
```
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/apisix-admin                ClusterIP   10.100.2.176    <none>        9180/TCP            4h13m
service/apisix-dashboard            NodePort    10.110.189.91   <none>        80:31803/TCP        4h3m
service/apisix-etcd                 ClusterIP   10.102.89.66    <none>        2379/TCP,2380/TCP   4h13m
service/apisix-etcd-headless        ClusterIP   None            <none>        2379/TCP,2380/TCP   4h13m
service/apisix-gateway              NodePort    10.101.98.248   <none>        80:31370/TCP        4h13m
service/apisix-ingress-controller   ClusterIP   10.98.45.181    <none>        80/TCP              4h3m
service/httpbin                     ClusterIP   10.102.62.126   <none>        80/TCP              3h21m
service/kubernetes                  ClusterIP   10.96.0.1       <none>        443/TCP             4h36m

NAME                                            READY   STATUS    RESTARTS   AGE
pod/apisix-66cc75967c-pv29j                     1/1     Running   0          4h13m
pod/apisix-dashboard-786f74d8d5-qg6zv           1/1     Running   0          4h3m
pod/apisix-etcd-0                               1/1     Running   0          4h13m
pod/apisix-etcd-1                               1/1     Running   0          4h13m
pod/apisix-etcd-2                               1/1     Running   0          4h13m
pod/apisix-ingress-controller-698c9cc86-vrmfw   1/1     Running   0          4h3m
pod/httpbin                                     1/1     Running   0          3h22m
```

`curl -fsSL 10.100.2.176:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' | jq`
```
{
  "node": {
    "dir": true,
    "key": "/apisix/routes",
    "nodes": [
      {
        "modifiedIndex": 15,
        "value": {
          "uris": [
            "/httpbin/*"
          ],
          "name": "default_httpserver-route_rule1",
          "hosts": [
            "local.httpbin.org"
          ],
          "update_time": 1631357738,
          "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
          "create_time": 1631356750,
          "priority": 0,
          "id": "add8e28c",
          "labels": {
            "managed-by": "apisix-ingress-controller"
          },
          "upstream_id": "5ce57b8e",
          "status": 1
        },
        "createdIndex": 14,
        "key": "/apisix/routes/add8e28c"
      }
    ]
  },
  "count": 1,
  "action": "get"
}
```

`curl -fsSL 10.100.2.176:9180/apisix/admin/upstreams -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' | jq`
```
{
  "node": {
    "dir": true,
    "key": "/apisix/upstreams",
    "nodes": [
      {
        "modifiedIndex": 13,
        "value": {
          "name": "default_httpbin_80",
          "update_time": 1631356750,
          "id": "5ce57b8e",
          "create_time": 1631356750,
          "hash_on": "vars",
          "type": "roundrobin",
          "pass_host": "pass",
          "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
          "labels": {
            "managed-by": "apisix-ingress-controller"
          },
          "scheme": "http",
          "nodes": [
            {
              "port": 80,
              "host": "10.244.196.4",
              "weight": 100,
              "priority": 0
            }
          ]
        },
        "createdIndex": 13,
        "key": "/apisix/upstreams/5ce57b8e"
      }
    ]
  },
  "count": 1,
  "action": "get"
}
```

3.  the apisix-ingress-controller pod log shows:

`ns="default"; kubectl logs -n "${ns}" "$(kubectl -n "${ns}" get pods | grep apisix-ingress-controller | awk '{print $1}')" -f | grep -v 'healthz'`
...
2021-09-11T17:47:29+08:00	warn	ingress/controller.go:574	upstream is not referenced	{"cluster": "name=default; base_url=http://apisix-admin:9180/apisix/admin", "upstream": "default_apisix-etcd_2379"}
2021-09-11T17:47:29+08:00	warn	apisix/upstream.go:70	upstream not found	{"name": "default_apisix-etcd_2380", "url": "http://apisix-admin:9180/apisix/admin/upstreams/7ce0b7cf", "cluster": "default"}
2021-09-11T17:47:29+08:00	warn	ingress/controller.go:574	upstream is not referenced	{"cluster": "name=default; base_url=http://apisix-admin:9180/apisix/admin", "upstream": "default_apisix-etcd_2380"}
2021-09-11T17:47:30+08:00	warn	apisix/upstream.go:70	upstream not found	{"name": "default_apisix-ingress-controller_80", "url": "http://apisix-admin:9180/apisix/admin/upstreams/d517f3c0", "cluster": "default"}
2021-09-11T17:47:30+08:00	warn	ingress/controller.go:574	upstream is not referenced	{"cluster": "name=default; base_url=http://apisix-admin:9180/apisix/admin", "upstream": "default_apisix-ingress-controller_80"}
2021-09-11T17:47:30+08:00	warn	apisix/upstream.go:70	upstream not found	{"name": "default_apisix-ingress-controller_80", "url": "http://apisix-admin:9180/apisix/admin/upstreams/d517f3c0", "cluster": "default"}
2021-09-11T17:47:30+08:00	warn	ingress/controller.go:574	upstream is not referenced	{"cluster": "name=default; base_url=http://apisix-admin:9180/apisix/admin", "upstream": "default_apisix-ingress-controller_80"}
2021-09-11T18:29:08+08:00	warn	apisix/upstream.go:70	upstream not found	{"name": "default_httpbin_80", "url": "http://apisix-admin:9180/apisix/admin/upstreams/5ce57b8e", "cluster": "default"}
2021-09-11T18:29:08+08:00	warn	ingress/controller.go:574	upstream is not referenced	{"cluster": "name=default; base_url=http://apisix-admin:9180/apisix/admin", "upstream": "default_httpbin_80"}

4. the apisixroute status

`ns="default"; kubectl describe apisixroutes.apisix.apache.org -n "${ns}" httpserver-route`
```
Warning: apisix.apache.org/v1 ApisixRoute is deprecated
Name:         httpserver-route
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  apisix.apache.org/v1
Kind:         ApisixRoute
Metadata:
  Creation Timestamp:  2021-09-11T10:39:09Z
  Generation:          2
  Managed Fields:
    API Version:  apisix.apache.org/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:http:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-09-11T10:39:09Z
    API Version:  apisix.apache.org/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         apisix-ingress-controller
    Operation:       Update
    Time:            2021-09-11T10:39:10Z
  Resource Version:  24977
  UID:               74cb7729-496a-4bfa-bb09-6d82ce47da5d
Spec:
  Http:
    Backend:
      Service Name:  httpbin
      Service Port:  80
    Match:
      Hosts:
        local.httpbin.org
      Paths:
        /httpbin/*
    Name:  rule1
Status:
  Conditions:
    Last Transition Time:  2021-09-11T10:39:10Z
    Message:               Sync Successfully
    Reason:                ResourcesSynced
    Status:                True
    Type:                  ResourcesAvailable
Events:
  Type    Reason           Age                From           Message
  ----    ------           ----               ----           -------
  Normal  ResourcesSynced  59m (x3 over 75m)  ApisixIngress  ApisixIngress synced successfully
```
### What's the expected result?
access to any service of ClusterIP proxied by apisix, the behave should be the same as accessing to clusterIP:port service. As in this example, the service of ClusterIP "httpbin" is http://10.102.62.126:80, apisix-dashboard is http://172.16.100.101:31803, the route path is "/httpbin/*", the route host is "local.httpbin.org", so, access to http://local.httpbin.org:31803/httpbin should be the same as accessing http://10.102.62.126:80. 
Am I right?

**Comment by gxthrj** [comment]
Hi, @superwjc, `Ingress` and `dashboard` are independent projects and managed independently. They have had no relationship with each other. Therefore, Ingress will not actively introduce requests to the dashboard.

Please show the route in APISIX by requesting `http://APISIX.svc:9180/apisix/admin/routes`.  If you think that the request is sent to the wrong upstream, first check whether the configuration of routes in APISIX is correct.

**Comment by superwjc** [comment]
> Hi, @superwjc, `Ingress` and `dashboard` are independent projects and managed independently. They have had no relationship with each other. Therefore, Ingress will not actively introduce requests to the dashboard.
> 
> Please show the route in APISIX by requesting `http://APISIX.svc:9180/apisix/admin/routes`. If you think that the request is sent to the wrong upstream, first check whether the configuration of routes in APISIX is correct.

thanks, and sorry for my ugly format.

**curl -fsSL 10.100.2.176:9180/apisix/admin/upstreams -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'**
{"node":{"dir":true,"key":"\/apisix\/upstreams","nodes":[{"modifiedIndex":13,"value":{"name":"default_httpbin_80","update_time":1631356750,"id":"5ce57b8e","create_time":1631356750,"hash_on":"vars","type":"roundrobin","pass_host":"pass","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","labels":{"managed-by":"apisix-ingress-controller"},"scheme":"http","nodes":[{"port":80,"host":"10.244.196.4","weight":100,"priority":0}]},"createdIndex":13,"key":"\/apisix\/upstreams\/5ce57b8e"}]},"count":1,"action":"get"}

**curl -fsSL 10.100.2.176:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'**
{"node":{"dir":true,"key":"\/apisix\/routes","nodes":[{"modifiedIndex":15,"value":{"uris":["\/httpbin\/*"],"name":"default_httpserver-route_rule1","hosts":["local.httpbin.org"],"update_time":1631357738,"desc":"Created by apisix-ingress-controller, DO NOT modify it manually","create_time":1631356750,"priority":0,"id":"add8e28c","labels":{"managed-by":"apisix-ingress-controller"},"upstream_id":"5ce57b8e","status":1},"createdIndex":14,"key":"\/apisix\/routes\/add8e28c"}]},"count":1,"action":"get"}

**Comment by superwjc** [comment]
> Hi, @superwjc, `Ingress` and `dashboard` are independent projects and managed independently. They have had no relationship with each other. Therefore, Ingress will not actively introduce requests to the dashboard.
> 
> Please show the route in APISIX by requesting `http://APISIX.svc:9180/apisix/admin/routes`. If you think that the request is sent to the wrong upstream, first check whether the configuration of routes in APISIX is correct.

@gxthrj Hi, Is there something wrong with my steps, or the way I request?

**Comment by superwjc** [comment]
I reinstalled except apisix-dashboard, and changed the default service type of apisix-ingress-controller from "ClusterIP" to "NodePort", in the "apisix-ingress-controller/templates/service.yaml" file. Without apisix-dashboard, request directly to httpbin by ClusterIP:Port was still as intended, but returned 404 by apisixroute.
The remaining settings kept unchanged.
```
helm list

NAME                     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
apisix                   	default  	1       	2021-09-11 22:03:14.353396758 +0800 CST	deployed	apisix-0.4.0                   	2.7.0
apisix-ingress-controller	default  	1       	2021-09-11 22:04:48.211454527 +0800 CST	deployed	apisix-ingress-controller-0.7.0	1.2.0
```
```
# ns="default"; kubectl get po,svc -n "${ns}"
NAME                                            READY   STATUS    RESTARTS   AGE
pod/apisix-66cc75967c-ftxpz                     1/1     Running   0          26m
pod/apisix-etcd-0                               1/1     Running   0          26m
pod/apisix-etcd-1                               1/1     Running   0          26m
pod/apisix-etcd-2                               1/1     Running   0          26m
pod/apisix-ingress-controller-698c9cc86-dwl9m   1/1     Running   0          24m
pod/apisix-ingress-controller-698c9cc86-mtgmr   1/1     Running   0          24m
pod/httpbin                                     1/1     Running   0          4h

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/apisix-admin                ClusterIP   10.108.12.42    <none>        9180/TCP            26m
service/apisix-etcd                 ClusterIP   10.97.244.157   <none>        2379/TCP,2380/TCP   26m
service/apisix-etcd-headless        ClusterIP   None            <none>        2379/TCP,2380/TCP   26m
service/apisix-gateway              NodePort    10.111.90.162   <none>        80:32632/TCP        26m
**service/apisix-ingress-controller   NodePort    10.96.121.41    <none>        80:31332/TCP        24m**
**service/httpbin                     ClusterIP   10.102.62.126   <none>        80/TCP              4h**
service/kubernetes                  ClusterIP   10.96.0.1       <none>        443/TCP             5h14m
```
```
# curl -sSL -D - 10.102.62.126 -o /dev/null
**HTTP/1.1 200 OK**
Server: gunicorn/19.9.0
Date: Sat, 11 Sep 2021 14:30:12 GMT
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Content-Length: 9593
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```
```
# curl -sSL -D - local.httpbin.org:31332/httpbin/ -o /dev/null
**HTTP/1.1 404 Not Found**
Content-Type: text/plain
Date: Sat, 11 Sep 2021 14:32:11 GMT
Content-Length: 18

# curl -sSL -D - local.httpbin.org:31332/httpbin -o /dev/null
**HTTP/1.1 404 Not Found**
Content-Type: text/plain
Date: Sat, 11 Sep 2021 14:32:18 GMT
Content-Length: 18

#
# curl -sSL -D - local.httpbin.org:31332 -o /dev/null
**HTTP/1.1 404 Not Found**
Content-Type: text/plain
Date: Sat, 11 Sep 2021 14:32:25 GMT
Content-Length: 18
```
Anyone has solution or suggestions?

**Comment by tokers** [comment]
> The apisix-dashboard service has the type "NodePort"(http://172.16.100.101:31803), while the test backend service "httpbin" has the type "ClusterIP"(http://10.102.62.126:80)
> The route proxied "local.httpbin.org/httpbin" to the service "httpbin", curl http://local.httpbin.org:31803/httpbin was redirected to apisix-dashboard, that's the problem.

You sent requests to apisix-dashboard (`:31803`), so of course you saw the apisix-dashboard. By the way, have you add resolution for domain `local.httpbin.org`? How did it map to the Kubernetes worker node or the LB IP?

**Comment by superwjc** [comment]
> > The apisix-dashboard service has the type "NodePort"(http://172.16.100.101:31803), while the test backend service "httpbin" has the type "ClusterIP"(http://10.102.62.126:80)
> > The route proxied "local.httpbin.org/httpbin" to the service "httpbin", curl http://local.httpbin.org:31803/httpbin was redirected to apisix-dashboard, that's the problem.
> 
> You sent requests to apisix-dashboard (`:31803`), so of course you saw the apisix-dashboard. By the way, have you add resolution for domain `local.httpbin.org`? How did it map to the Kubernetes worker node or the LB IP?

@tokers thanks, doesn't the apisix-dashboard act as a api-gateway? That is, by adding a path to the host, all requests  matched the path are forward to the real backend service. So, if http://172.16.100.101:31803 is the apisix-dashboard, then http://172.16.100.101:31803/httpbin is the "httpbin" service.
"local.httpbin.org" is resolved by /etc/hosts, this is not the problem.

**Comment by tokers** [comment]
> > > The apisix-dashboard service has the type "NodePort"(http://172.16.100.101:31803), while the test backend service "httpbin" has the type "ClusterIP"(http://10.102.62.126:80)
> > > The route proxied "local.httpbin.org/httpbin" to the service "httpbin", curl http://local.httpbin.org:31803/httpbin was redirected to apisix-dashboard, that's the problem.
> > 
> > 
> > You sent requests to apisix-dashboard (`:31803`), so of course you saw the apisix-dashboard. By the way, have you add resolution for domain `local.httpbin.org`? How did it map to the Kubernetes worker node or the LB IP?
> 
> @tokers thanks, doesn't the apisix-dashboard act as a api-gateway? That is, by adding a path to the host, all requests matched the path are forward to the real backend service. So, if http://172.16.100.101:31803 is the apisix-dashboard, then http://172.16.100.101:31803/httpbin is the "httpbin" service.
> "local.httpbin.org" is resolved by /etc/hosts, this is not the problem.

Ofcourse not 😂, APISIX Dashboard is a management component of APISIX. Indeed you don't require it as the APISIX Ingress Controller already acts as the manager of APISIX cluster. You should send requests to APISIX cluster, i.e. the `apisix-gateway` service.

**Comment by superwjc** [comment]
Well I ask another way, what should I setup in order to access the real backend service by apisixroute? I just follow the official website, but can't get the right result.

**Comment by superwjc** [comment]
> Ofcourse not 😂, APISIX Dashboard is a management component of APISIX. Indeed you don't require it as the APISIX Ingress Controller already acts as the manager of APISIX cluster. You should send requests to APISIX cluster, i.e. the `apisix-gateway` service.

I send the request to the apisix-gateway, but returns 404.
1. apisix-gateway is avaliable and the NodePort is in listening state:
```
[root@k8s-master-1 ~]# ns="default"; kubectl -n "${ns}" get svc | grep gateway
apisix-gateway              NodePort    10.111.90.162   <none>        80:32632/TCP        72m
[root@k8s-master-1 ~]#
[root@k8s-master-1 ~]#
[root@k8s-master-1 ~]# ss -atn | grep :32632
LISTEN     0      128          *:32632                    *:*
```
2. the apisixroute rule is exists, with no errors.
```
# **curl -fsSL 10.108.12.42:9180/apisix/admin/upstreams -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' | jq**
{
  "action": "get",
  "node": {
    "nodes": [
      {
        "modifiedIndex": 14,
        "value": {
          "scheme": "http",
          "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
          "create_time": 1631369108,
          "type": "roundrobin",
          "id": "5ce57b8e",
          "update_time": 1631369108,
          "labels": {
            "managed-by": "apisix-ingress-controller"
          },
          "hash_on": "vars",
          "nodes": [
            {
              "weight": 100,
              "host": "10.244.196.4",
              "priority": 0,
              "port": 80
            }
          ],
          "pass_host": "pass",
          "name": "default_httpbin_80"
        },
        "createdIndex": 13,
        "key": "/apisix/upstreams/5ce57b8e"
      }
    ],
    "dir": true,
    "key": "/apisix/upstreams"
  },
  "count": 1
}
# **curl -fsSL 10.108.12.42:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' | jq**
{
  "action": "get",
  "node": {
    "nodes": [
      {
        "modifiedIndex": 15,
        "value": {
          "labels": {
            "managed-by": "apisix-ingress-controller"
          },
          "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
          "create_time": 1631369108,
          "upstream_id": "5ce57b8e",
          "id": "add8e28c",
          "update_time": 1631369108,
          "name": "default_httpserver-route_rule1",
          "uris": [
            "/httpbin/*"
          ],
          "priority": 0,
          "status": 1,
          "hosts": [
            "local.httpbin.org"
          ]
        },
        "createdIndex": 15,
        "key": "/apisix/routes/add8e28c"
      }
    ],
    "dir": true,
    "key": "/apisix/routes"
  },
  "count": 1
}
# ns="default"; kubectl -n "${ns}" get apisixroute
Warning: apisix.apache.org/v1 ApisixRoute is deprecated
NAME               HOSTS                   URIS             AGE
httpserver-route   ["local.httpbin.org"]   ["/httpbin/*"]   4h42m
```
3. the "local.httpbin.org" host is reachable 
```
# ping -c 1 local.httpbin.org
PING local.httpbin.org (172.16.100.101) 56(84) bytes of data.
64 bytes from k8s-master-1 (172.16.100.101): icmp_seq=1 ttl=64 time=0.059 ms

--- local.httpbin.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.059/0.059/0.059/0.000 ms
```
4. the "httpbin" service is accessable, by ClusterIP:Port
```
# ns="default"; kubectl get svc | grep httpbin
httpbin                     ClusterIP   10.102.62.126   <none>        80/TCP              4h57m
#
#
#
# curl -sSL -D - 10.102.62.126 -o /dev/null
HTTP/1.1 200 OK
Server: gunicorn/19.9.0
Date: Sat, 11 Sep 2021 15:26:51 GMT
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Content-Length: 9593
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```
5. access to apisix-gateway NodeIP:NodePort with the path "httpbin", 404 returns.
```
# curl -sSL -D - local.httpbin.org:32632/httpbin -o /dev/null
HTTP/1.1 404 Not Found
Date: Sat, 11 Sep 2021 15:29:17 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.7

#
# curl -sSL -D - local.httpbin.org:32632/httpbin/ -o /dev/null
HTTP/1.1 404 NOT FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 233
Connection: keep-alive
Date: Sat, 11 Sep 2021 15:29:22 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/2.7
```

**Comment by superwjc** [comment]
resolved after reading the architecture topology from the apisix official website, it's **NOT** a bug of apisix, but of mine. Thank you all @tokers @gxthrj and sorry for my misunderstanding.
The actual API gateway is service "apisix-gateway" but not the service "apisix-dashboard".  The gateway is response for incoming request after apisixroute/ingress configured, and the dashboard just make the configurations visualized.
For newcomers as me.

**Comment by gxthrj** [comment]
> resolved after reading the architecture topology from the apisix official website, it's **NOT** a bug of apisix, but of mine. Thank you all @tokers @gxthrj and sorry for my misunderstanding.
> The actual API gateway is service "apisix-gateway" but not the service "apisix-dashboard". The gateway is response for incoming request after apisixroute/ingress configured, and the dashboard just make the configurations visualized.
> For newcomers as me.

It's ok. Now we can close this issue, feel free to reopen.
