### ISSUE TITLE
How does APISIX(DP) deployed outside the K8S cluster access the routes created through apisix-ingress(CP)?

### ISSUE THREAD

**Issue by lixjofgithub** [apache/apisix-ingress-controller#681]
### Issue description
因为通过apisix-ingress创建的route中的backends都是K8S中的ep或clusterip，传递到APISIX后，因为APISIX是部署在K8S之外的话会无法访问该后端地址
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
If your network is an **underlay network**, this method will be more convenient.

Otherwise, you need to maintain network connectivity by yourself.

**Comment by gxthrj** [comment]
Yes, this belongs to the k8s network configuration. If you need to deploy DP outside, of course, you need to make sure that the outside DP can access the services (pod IP) inside the k8s cluster.
There are many solutions to open up the network, such as calico + BGP， but it is not the management scope of the Ingress controller.
