### ISSUE TITLE
request help:  error log "failed to delete pod from cache" 

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#684]
### Issue description
When the service version changes, the k8s RollingUpgrade is triggered. The controller will have an error log: 
`"error ingress/pod.go:130 failed to delete pod from cache {"error": pod not running"`

![image](https://user-images.githubusercontent.com/7134928/133383753-fe563b04-383c-4a74-90bb-c0632271c171.png)

**Is there any influences ?**
### Environment

* your apisix-ingress-controller version: v1.1
* your Kubernetes cluster version: v1.16.6

**Comment by Donghui0** [comment]
https://github.com/apache/apisix-ingress-controller/blob/5c9cdbe7fc2c28f3023d635dbbd9bc833388a2bf/pkg/types/pod.go#L68-L77

To delete the cache, you need to determine whether the IP of the POD exists. 
However, deleting the POD will definitely trigger the CNI to remove the IP, So, is there a problem with the logic of deleting podCache?

**Comment by gxthrj** [comment]
Good catch. PR is welcome. 
I think we can remove this condition directly.

**Comment by tao12345666333** [comment]
#714 has been merged, I think we can close this one. If you have any question please feel free to reopen it.
