### ISSUE TITLE
httpcheck error

### ISSUE THREAD

**Issue by xiongyunhua-star** [apache/apisix-ingress-controller#686]
### Issue description

create a httpcheck.yaml and then apply,but the result is error

### Environment
NAME                                 NAMESPACE       REVISION       CHART                                                                 APP VERSION
apisix                                 ingress-apisix      1                     apisix-0.3.5                                                           2.7.0      
apisix-ingress-controller   ingress-apisix      1                     apisix-ingress-controller-0.5.0                              1.0.0    

#################
Yaml file:
################################################
version 1:
                        kind: ApisixUpstream
                        metadata:
                          name: pro-svc
                          namespace: demo-project
                        spec:
                          healthCheck:
                            passive:
                              unhealthy:
                                httpCodes:
                                  - 500
                                httpFailures: 3
                                timeout: 5s
                            active:
                              type: http
                              httpPath: /
                              timeout: 5s
                              healthy:
                                successes: 3
                                interval: 2s
                                httpCodes:
                                  - 200
Error prompt:   spec.healthCheck.active.timeout in body must be of type number: "string"

version 2：
                        kind: ApisixUpstream
                        metadata:
                          name: pro-svc
                          namespace: demo-project
                        spec:
                          healthCheck:
                            passive:
                              unhealthy:
                                httpCodes:
                                  - 500
                                httpFailures: 3
                                timeout: 5s
                            active:
                              type: http
                              httpPath: /
                              timeout: 5
                              healthy:
                                successes: 3
                                interval: 2s
                                httpCodes:
                                  - 200

Error prompt: null
But the yaml-file's status is null and dashboard's httpcheck-contents is null

**Comment by gxthrj** [comment]
related to #604

**Comment by gxthrj** [comment]
#687 has been merged, close this issue, feel free to reopen.
