### ISSUE TITLE
Breaking changes: deprecated the `spec.backend` field in ApisixRoute

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#692]
### Issue description

In the current ApisixRoute CRD definition, there are both `spec.backend` and `spec.backends`

https://github.com/apache/apisix-ingress-controller/blob/957c31522e1b1e5f8ef9cab7eb244473a4e0f675/samples/deploy/crd/v1beta1/ApisixRoute.yaml#L173-L217

And `spec.backends` can completely cover the usage scenarios of `spec.backend`.  Currently maintaining these two fields at the same time has caused a certain burden on us.
For example, when the resource cannot be obtained directly through kubectl, the corresponding information can be displayed. For details, please see https://github.com/apache/apisix-ingress-controller/pull/626#discussion_r686714645

**I suggest that we upgrade ApisixRoute to v2beta2 version as soon as possible, and deprecate `spec.backend` in this version.**

**Comment by tao12345666333** [comment]
I have started a discussion on the mailing list. Please feel free to participate in the discussion in this issue or on the mailing list. 

https://lists.apache.org/thread.html/rb179dc9d953423dc258340622a185ca1b3cfa4cacad8efaea7acc571%40%3Cdev.apisix.apache.org%3E

**Comment by tokers** [comment]
+1, are there any other fields can be deprecated together?

**Comment by gxthrj** [comment]
+1 Look forward to a quick v2 release.
