### ISSUE TITLE
request help:  Ingress 资源不同步 apisix

### ISSUE THREAD

**Issue by yingtxx** [apache/apisix-ingress-controller#708]
### Issue description
通过CRD ApisixRoute 创建路由是正常的
但是通过注解创建Ingress资源不会同步到apisix
ingress.yaml配置如下

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpserver-ingress
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  rules:
    - host: local.httpbin.org
      http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 80
            path: /
            pathType: Prefix
 

### Environment
k8s 1.18
apache/apisix :2.7
apisix-ingress-controller : 0.7

**Comment by gxthrj** [comment]
Please show me the configure of APISIX-ingress-controller, the `kubernetes.ingress_version` need to be specified as `networking/v1beta1`.(You are using `networking/v1beta1` from your declared configure.)

BTW the version of apisix-ingress-controller you are using is too old. Please upgrade.
cc [The compatibility between apisix-ingress-controller and Apache APISIX.]( https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/getting-started.md#compatibility-with-apache-apisix)

**Comment by yingtxx** [comment]
install by apisix-helm-chart 

**yaml of apisix-ingress-controller deployment:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: apisix
    meta.helm.sh/release-namespace: ingress-apisix
  creationTimestamp: "2021-10-13T06:34:01Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/version: 1.2.0
    helm.sh/chart: apisix-ingress-controller-0.7.0
  managedFields:
  - apiVersion: apps/v1
    manager: Go-http-client
    operation: Update
    time: "2021-10-13T06:34:01Z"
  - apiVersion: apps/v1
    manager: kube-controller-manager
    operation: Update
    time: "2021-10-13T06:34:56Z"
  - apiVersion: apps/v1
    manager: tke-apiserver
    operation: Update
    time: "2021-10-13T06:34:56Z"
  name: apisix-apisix-ingress-controller
  namespace: ingress-apisix
  resourceVersion: "3084868080"
  selfLink: /apis/apps/v1/namespaces/ingress-apisix/deployments/apisix-apisix-ingress-controller
  uid: 14036a94-36d7-41d4-b1eb-9ac11efd495e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: apisix-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 7de7d76b8f372d076b361e308ae3cd400affb2e04ddddd059c9a86036bdbb9a9
        qcloud-redeploy-timestamp: "1634106894913"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/name: apisix-ingress-controller
    spec:
      containers:
      - command:
        - /ingress-apisix/apisix-ingress-controller
        - ingress
        - --config-path
        - /ingress-apisix/conf/config.yaml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: apache/apisix-ingress-controller:1.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: apisix-ingress-controller
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ingress-apisix/conf
          name: configuration
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: apisix-apisix-ingress-controller
      serviceAccountName: apisix-apisix-ingress-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: apisix-configmap
        name: configuration
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-13T06:34:11Z"
    lastUpdateTime: "2021-10-13T06:34:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-13T06:34:01Z"
    lastUpdateTime: "2021-10-13T06:34:56Z"
    message: ReplicaSet "apisix-apisix-ingress-controller-7f9666dcc7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
```

**Comment by wadeLouis** [comment]
I also encountered the same problem.  

### Environment
K8S:  v1.18.3
APISIX: 2.10.0
Apisix-ingress-controller:  1.2.0 

### Test native Ingress
```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: apisix
  name: httpserver-ingress
  namespace: ocser
spec:
  rules:
    - host: cloudm.smartgalaxy.net
      http:
        paths:
          - backend:
              serviceName: cloudm
              servicePort: 80
            path: /
            pathType: Prefix

```
### Test result
bash-5.1# curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'
```json
{"count":0,"action":"get","node":{"nodes":{},"dir":true,"key":"\/apisix\/routes"}}
```
### apisix-ingress-controller configmap
```
# log options
log_level: "info"
log_output: "stderr"
http_listen: ":8080"
enable_profiling: true
kubernetes:
  kubeconfig: ""
  resync_interval: "6h"
  app_namespaces:
  - "*"
  ingress_class: "apisix"
  ingress_version: "networking/v1"
  apisix_route_version: "apisix.apache.org/v2beta1"
apisix:
  base_url: "http://apisix-1634008016-admin.apisix.svc.cluster.local:9180/apisix/admin"
  admin_key: "edd1c9f034335f136f87ad84b625c8f1"

```

**Comment by wadeLouis** [comment]
> I also encountered the same problem.
> 
> ### Environment
> K8S: v1.18.3 APISIX: 2.10.0 Apisix-ingress-controller: 1.2.0
> 
> ### Test native Ingress
> ```yaml
> ---
> apiVersion: networking.k8s.io/v1beta1
> kind: Ingress
> metadata:
>   annotations:
>     kubernetes.io/ingress.class: apisix
>   name: httpserver-ingress
>   namespace: ocser
> spec:
>   rules:
>     - host: cloudm.smartgalaxy.net
>       http:
>         paths:
>           - backend:
>               serviceName: cloudm
>               servicePort: 80
>             path: /
>             pathType: Prefix
> ```
> 
> ### Test result
> bash-5.1# curl http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-Key: edd1c9f034335f136f87ad84b625c8f1'
> 
> ```json
> {"count":0,"action":"get","node":{"nodes":{},"dir":true,"key":"\/apisix\/routes"}}
> ```
> 
> ### apisix-ingress-controller configmap
> ```
> # log options
> log_level: "info"
> log_output: "stderr"
> http_listen: ":8080"
> enable_profiling: true
> kubernetes:
>   kubeconfig: ""
>   resync_interval: "6h"
>   app_namespaces:
>   - "*"
>   ingress_class: "apisix"
>   ingress_version: "networking/v1"
>   apisix_route_version: "apisix.apache.org/v2beta1"
> apisix:
>   base_url: "http://apisix-1634008016-admin.apisix.svc.cluster.local:9180/apisix/admin"
>   admin_key: "edd1c9f034335f136f87ad84b625c8f1"
> ```

Oss my god !!!!!!
I found the problem .  apisix ingress controller default configmap is set `ingress_version: networking/v1` by default.  The supported ingress api group version, can be "networking/v1beta1" , "networking/v1" (for Kubernetes version v1.19.0 or higher), and  "extensions/v1beta1", default is "networking/v1".  
Just specificed it !!!
