### ISSUE TITLE
request help: apisixtls已经删除apisix-ingress-controller日志还一直报apisixtls的错

### ISSUE THREAD

**Issue by jimmy-jian** [apache/apisix-ingress-controller#711]
我创建了一个apisixtls，并且把secret指向了cert-manager生成的secret。但是cert-manager生成的secret里保存的key是"tls.crt"和"tls.key",  和apisixtls中要求的"cert","key"不一样，所以我就将apisixtls对象删除了。但好像又没有彻底删掉，apisix-ingress-controller日志里还一直报apisixtls转换的错，有什么办法可以将apisixtls彻底删除吗？还有secret中的字段的"cert","key"是否可以通过参数的方式指定呢

![QQ20211014-0](https://user-images.githubusercontent.com/18340883/137242373-3687d1b6-be66-47e2-a6be-90a0906e7fbc.png)

![F56A72F4E80E404883B915CF80927535](https://user-images.githubusercontent.com/18340883/137242386-a65c8498-5302-47a7-b2f4-a1566293872b.jpg)

### Environment
apisix-ingress-controller:1.2.0
kubernetes :v1.20.4-aliyun.1

**Comment by tokers** [comment]
@jimmy-jian The standard naming in secret is supported in the master branch. And I think the problem is that you delete the resource but it still retries it, this should be a bug in the secret controller. cc @tao12345666333 @gxthrj

**Comment by jimmy-jian** [comment]
I double checked the source on master branch, it still uses 'cert' and 'key' ....blablabla
![WechatIMG6](https://user-images.githubusercontent.com/18340883/137305713-151c5a29-0351-45d7-bc61-f22c63af2450.jpeg)
