### ISSUE TITLE
request help: is Apisix-ingress-controller able to integrate with the Apisix-dashboard

### ISSUE THREAD

**Issue by yunfhu** [apache/apisix-ingress-controller#718]
### Issue description
Actually I have two question about Apisix-ingress-controller.The 1st one is whether is able to integrate with the Apisix-dashboard.Another question is as the kubernets' ingress controller,it is deployed  on the node or deployed as service in the pod ?

**Comment by yunfhu** [comment]
> * For the first question, the answer is yes, you can also use the apisix-dashboard, but we don't recommend you to edit any resources from it, it can be used as a view board.
> * It depends on your demands, you can deploy Apache APISIX Ingress Controller inside the Kubernetes cluster or just outside it.

Could you pls give more details about deploy ingress controller outside the kubernets cluster?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long and I will close it.

If you have other questions, please create a new issue
