### ISSUE TITLE
request help: apisix error：Failed to watch *v2beta1.ApisixRoute

### ISSUE THREAD

**Issue by aiyYu** [apache/apisix-ingress-controller#725]
### Issue description
![2](https://user-images.githubusercontent.com/49424498/139022239-6736ade9-0eaf-4ecf-9aff-6aac94c6b43a.png)

![getall](https://user-images.githubusercontent.com/49424498/139026100-e1c26a6c-e570-47d1-9310-9158393fba22.png)

### Environment
k8s version：v1.16.4

apisix version：2.10.0
apisix-ingress-controller version：1.3.0
from clone https://github.com/apache/apisix-helm-chart.git

**Comment by tao12345666333** [comment]
If you using apisix-ingress v1.3 with latest CRD, you should get the following output

```bash
➜  ~ kubectl api-resources |grep apisix     
apisixclusterconfigs              acc          apisix.apache.org/v2alpha1             false        ApisixClusterConfig
apisixconsumers                   ac           apisix.apache.org/v2alpha1             true         ApisixConsumer
apisixroutes                      ar           apisix.apache.org/v2beta2              true         ApisixRoute
apisixtlses                       atls         apisix.apache.org/v1                   true         ApisixTls
apisixupstreams                   au           apisix.apache.org/v1                   true         ApisixUpstream
```


If you want to use https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1
You need run `kubectl apply -k ./samples/deploy/crd/v1`

**Comment by tao12345666333** [comment]
This issue has not been updated for too long.  You can try to update to the latest version to verify if there are any problems.
I will close this issue. Feel free to reopen it, if you have any question.
