### ISSUE TITLE
ApisixIngress service "" not found

### ISSUE THREAD

**Issue by sumeng001** [apache/apisix-ingress-controller#730]
HI：
I installed apisix-ingress using documentation, but it shows when viewing apisixRoute
ApisixIngress synchronization failed, error: service “” not found

version：
apache/apisix-ingress-controller：1.3.0
![image]（https://user-images.githubusercontent.com/28882514/139646526-0dd07b33-0b3f-43ab-a8ac-1189ef98ec36.png）
![image]（https://user-images.githubusercontent.com/28882514/139646200-2b15f666-3830-445b-ac9c-c6131878c2c1.png）
![image]（https://user-images.githubusercontent.com/28882514/139646352-9fc15e1e-2e74-4152-9c2e-f9207afa2412.png）
kubectl get svc -A
NAMESPACE        NAME                        TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                  AGE
default          httpbin                     ClusterIP   192.168.138.131   <none>        80/TCP                   149m
svc exists

# httpbin-route.yaml
apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backend:
        serviceName: "httpbin"
        servicePort: 80

THANKS

**Comment by tokers** [comment]
> HI： I installed apisix-ingress using documentation, but it shows when viewing apisixRoute ApisixIngress synchronization failed, error: service “” not found
> 
> version： apache/apisix-ingress-controller：1.3.0 ![image]（[https://user-images.githubusercontent.com/28882514/139646526-0dd07b33-0b3f-43ab-a8ac-1189ef98ec36.png）](https://user-images.githubusercontent.com/28882514/139646526-0dd07b33-0b3f-43ab-a8ac-1189ef98ec36.png%EF%BC%89) ![image]（[https://user-images.githubusercontent.com/28882514/139646200-2b15f666-3830-445b-ac9c-c6131878c2c1.png）](https://user-images.githubusercontent.com/28882514/139646200-2b15f666-3830-445b-ac9c-c6131878c2c1.png%EF%BC%89) ![image]（[https://user-images.githubusercontent.com/28882514/139646352-9fc15e1e-2e74-4152-9c2e-f9207afa2412.png）](https://user-images.githubusercontent.com/28882514/139646352-9fc15e1e-2e74-4152-9c2e-f9207afa2412.png%EF%BC%89) kubectl get svc -A NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE default httpbin ClusterIP 192.168.138.131 80/TCP 149m svc exists
> 
> # httpbin-route.yaml
> apiVersion: apisix.apache.org/v2beta1 kind: ApisixRoute metadata: name: httpserver-route spec: http:
> 
> * name: rule1
>   match:
>   hosts:
>   
>   * local.httpbin.org
>     paths:
>   * /*
>     backend:
>     serviceName: "httpbin"
>     servicePort: 80
> 
> THANKS

What's the exact apisix route version that the apisix-ingress-controller watching? See [here](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/templates/configmap.yaml#L36) to learn the details.

**Comment by sumeng001** [comment]
> > HI： I installed apisix-ingress using documentation, but it shows when viewing apisixRoute ApisixIngress synchronization failed, error: service “” not found
> > version： apache/apisix-ingress-controller：1.3.0 ![image]（[https://user-images.githubusercontent.com/28882514/139646526-0dd07b33-0b3f-43ab-a8ac-1189ef98ec36.png）](https://user-images.githubusercontent.com/28882514/139646526-0dd07b33-0b3f-43ab-a8ac-1189ef98ec36.png%EF%BC%89) ![image]（[https://user-images.githubusercontent.com/28882514/139646200-2b15f666-3830-445b-ac9c-c6131878c2c1.png）](https://user-images.githubusercontent.com/28882514/139646200-2b15f666-3830-445b-ac9c-c6131878c2c1.png%EF%BC%89) ![image]（[https://user-images.githubusercontent.com/28882514/139646352-9fc15e1e-2e74-4152-9c2e-f9207afa2412.png）](https://user-images.githubusercontent.com/28882514/139646352-9fc15e1e-2e74-4152-9c2e-f9207afa2412.png%EF%BC%89) kubectl get svc -A NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE default httpbin ClusterIP 192.168.138.131 80/TCP 149m svc exists
> > # httpbin-route.yaml
> > apiVersion: apisix.apache.org/v2beta1 kind: ApisixRoute metadata: name: httpserver-route spec: http:
> > 
> > * name: rule1
> >   match:
> >   hosts:
> >   
> >   * local.httpbin.org
> >     paths:
> >   * /*
> >     backend:
> >     serviceName: "httpbin"
> >     servicePort: 80
> > 
> > THANKS
> 
> What's the exact apisix route version that the apisix-ingress-controller watching? See [here](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/templates/configmap.yaml#L36) to learn the details.

apisix-ingress version map
apiVersion: v1
data:
  config.yaml: |
    # log options
    log_level: "info"
    log_output: "stderr"
    http_listen: ":8080"
    enable_profiling: true
    kubernetes:
      kubeconfig: ""
      resync_interval: "6h"
      app_namespaces:
      - "*"
      ingress_class: "apisix"
      ingress_version: "networking/v1"
      apisix_route_version: "apisix.apache.org/v2beta1"
    apisix:
      base_url: http://apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin
      admin_key: "edd1c9f034335f136f87ad84b625c8f1"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: apisix
    meta.helm.sh/release-namespace: ingress-apisix
  creationTimestamp: "2021-10-29T11:46:25Z"
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-controller
    app.kubernetes.io/version: 1.3.0
    helm.sh/chart: ingress-controller-0.8.0
  name: apisix-configmap
  namespace: ingress-apisix
  resourceVersion: "44895"
  uid: 80a748cf-ca92-42bd-bfd3-4ba31c8396e2



AND  error logs
{
    "apisix_route": {
        "metadata": {
            "annotations": {
                "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apisix.apache.org/v2beta1\",\"kind\":\"ApisixRoute\",\"metadata\":{\"annotations\":{},\"name\":\"httpserver-route\",\"namespace\":\"default\"},\"spec\":{\"http\":[{\"backend\":{\"serviceName\":\"httpbin\",\"servicePort\":80},\"match\":{\"hosts\":[\"local.httpbin.org\"],\"paths\":[\"/*\"]},\"name\":\"rule1\"}]}}\n"
            },
            "creationTimestamp": "2021-11-01T08:29:30Z",
            "generation": 1,
            "managedFields": [
                {
                    "apiVersion": "apisix.apache.org/v2beta1",
                    "fieldsType": "FieldsV1",
                    "fieldsV1": {
                        "f:metadata": {
                            "f:annotations": {
                                ".": {},
                                "f:kubectl.kubernetes.io/last-applied-configuration": {}
                            }
                        },
                        "f:spec": {
                            ".": {},
                            "f:http": {}
                        }
                    },
                    "manager": "kubectl-client-side-apply",
                    "operation": "Update",
                    "time": "2021-11-01T08:29:30Z"
                }
            ],
            "name": "httpserver-route",
            "namespace": "default",
            "resourceVersion": "1048877",
            "uid": "f1fc7b81-718c-406b-9ebd-303016e5ac46"
        },
        "spec": {
            "http": [
                {
                    "authentication": {
                        "enable": false,
                        "keyauth": {},
                        "type": ""
                    },
                    "backend": {
                        "serviceName": "",
                        "servicePort": 0,
                        "weight": null
                    },
                    "match": {
                        "hosts": [
                            "local.httpbin.org"
                        ],
                        "paths": [
                            "/*"
                        ]
                    },
                    "name": "rule1",
                    "websocket": false
                }
            ]
        },
        "status": {
            "conditions": [
                {
                    "lastTransitionTime": "2021-11-01T08:29:31Z",
                    "message": "service \"\" not found",
                    "reason": "ResourceSyncAborted",
                    "status": "False",
                    "type": "ResourcesAvailable"
                }
            ]
        }
    },
    "backend": {
        "serviceName": "",
        "servicePort": 0,
        "weight": null
    },
    "error": "service \"\" not found"
}

**Comment by sumeng001** [comment]
I took  apisix.apache.org/v2beta1 to make apisix.apache.org/v2beta2
Could that be the problem?

httpbin-route.yaml

**_apiVersion: apisix.apache.org/v2beta1_**
kind: ApisixRoute
metadata:
name: httpserver-route
spec:
http:

name: rule1
match:
hosts:
local.httpbin.org
paths:
/*
backend:
serviceName: "httpbin"
servicePort: 80




**_apiVersion: apisix.apache.org/v2beta2_**
kind: ApisixRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apisix.apache.org/v2beta1","kind":"ApisixRoute","metadata":{"annotations":{},"name":"httpserver-route","namespace":"default"},"spec":{"http":[{"backend":{"serviceName":"httpbin","servicePort":80},"match":{"hosts":["local.httpbin.org"],"paths":["/*"]},"name":"rule1"}]}}
  creationTimestamp: "2021-11-01T12:29:20Z"
  generation: 1
  name: httpserver-route
  namespace: default
  resourceVersion: "1107435"
  uid: 0208e39e-0b77-4b78-a4ae-baa0ad10317d
spec:
  http:
  - match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    name: rule1

**Comment by sumeng001** [comment]
Resolved, used v2beta2

**Comment by tao12345666333** [comment]
Thanks for your feedback
