### ISSUE TITLE
DISCUSS: Discovered apisixupstreams by another way

### ISSUE THREAD

**Issue by Patrick0308** [apache/apisix-ingress-controller#737]
Description: 
Now we discover apisixupstream from k8s service. We can discover apisixupstreams from which is xds server, consul, nacos and so on.
What good will this do us: 
The apisix-ingress-controller can be made suitable for use in more situations. Examples :
1. although using k8s to deploy all services, there are deploying consul as a registry. 
2. using k8s and vm to deploy services

**Comment by tokers** [comment]
It seems like we should support more and more discovery registries, we may extend apisix-ingress-controller to do it. Do you have any specific proposals to do this?

**Comment by gxthrj** [comment]
I agree to extend the service discovery to support more third-party registration centers.
