### ISSUE TITLE
request help:  Any plan to support tcp_enable_ssl ?

### ISSUE THREAD

**Issue by jianhaiqing** [apache/apisix-ingress-controller#743]
### Issue description
ssl over tcp support in k8s

**Comment by tokers** [comment]
@jianhaiqing It's already supported, just defining a `ApisixTls` resource and several `ApisixRoute` objects (with the `stream` field).

**Comment by tokers** [comment]
See http://apisix.apache.org/docs/ingress-controller/concepts/apisix_route/#tcp-route for details.

**Comment by tao12345666333** [comment]
I think that question has been answered. i will close it
