### ISSUE TITLE
Feature suggestion: support stream route with plugins

### ISSUE THREAD

**Issue by fracarvic** [apache/apisix-ingress-controller#744]
### Issue description
As far I know, Apisix supports  limit-conn and  ip-restriction plugins in stream routes, but seems apisix-ingress-controller doesn't support stream plugins.

Will it be supported in the future?

Thanks.

### Environment
Apisix-ingress-controller version:
Version: 1.3.0
Git SHA: no-git-module
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64

**Comment by tokers** [comment]
> ### Issue description
> As far I know, Apisix supports limit-conn and ip-restriction plugins in stream routes, but seems apisix-ingress-controller doesn't support stream plugins.
> 
> Will it be supported in the future?
> 
> Thanks.
> 
> ### Environment
> Apisix-ingress-controller version: Version: 1.3.0 Git SHA: no-git-module Go Version: go1.13.8 Building OS/Arch: linux/amd64 Running OS/Arch: linux/amd64

Yeah, it's in our plan to support it. cc @gxthrj @tao12345666333

**Comment by tao12345666333** [comment]
Thanks for your feedback.

**Comment by tao12345666333** [comment]
I modified the title and this has been added to the roadmap.

Can you describe your scene?

**Comment by gxthrj** [comment]
I don't think this is a high priority.  What do you think?

**Comment by tao12345666333** [comment]
Yes. I need more feedback.  No specific feedback on this issue has been seen so far

**Comment by fracarvic** [comment]
I would like to use this feature to improve security ( limit connections, geoip) to my private imap server exposed throught apisix. Currently I can't attach plugins to an ApisixRoute like this:

```apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: imap
spec:
  stream:
  - name: imap
    protocol: TCP
    match:
      ingressPort: 143
    backend:
      serviceName: imap
      servicePort: 143
```

**Comment by tao12345666333** [comment]
Thanks for your information

**Comment by Belyenochi** [comment]
> Thanks for your information

can i try to add this feature?

**Comment by tao12345666333** [comment]
> > Thanks for your information
> 
> 
> 
> can i try to add this feature?

Sure! Thanks

**Comment by Belyenochi** [comment]
@tao12345666333, I found that there is a Golang CRD definition for Stream Route, but I did not find the corresponding Stream Route CRD yaml under samples/deploy/crd/v1. Is there any historical reason for this?

**Comment by tao12345666333** [comment]
#1056 has been merged. APISIX Ingress controller now supports configuring plugins in stream route.

I will close this one. thanks
