### ISSUE TITLE
ApisixRoute does not write to etcd and is not shown on dashboard

### ISSUE THREAD

**Issue by tutuV** [apache/apisix-ingress-controller#749]
env:
k8s 1.21
apisix-helm-chart 0.7.2

install cmd:
helm install apisix apisix
-f apisix/values.yaml
--set apisix.replicaCount=1
--set gateway.type=LoadBalancer
--set admin.allow.ipList="{0.0.0.0/0}"
--set etcd.enabled=true
--set etcd.persistence.enabled=false
--set ingress-controller.enabled=true
--set ingress-controller.config.apisix.serviceNamespace=apisix
--set ingress-controller.config.kubernetes.apisixRouteVersion="apisix.apache.org/v2beta2"
--set dashboard.enabled=true
--namespace apisix

ApisixRoute was created successfully, but neither ETCD nor Dashboard, and ingress-Controller-pod reported no error.
Sometimes, restarting ingress-Controller-pod fixes this problem

**Comment by tokers** [comment]
Please provide the steps to reproduce problems.

**Comment by tutuV** [comment]
@tokers 
kubectl create ns apisix

helm install apisix apisix \
-f apisix/values.yaml \
--set apisix.replicaCount=1 \
--set gateway.type=LoadBalancer \
--set admin.allow.ipList="{0.0.0.0/0}" \
--set etcd.enabled=true \
--set etcd.persistence.enabled=false \
--set ingress-controller.enabled=true \
--set ingress-controller.config.apisix.serviceNamespace=apisix \
--set ingress-controller.config.kubernetes.apisixRouteVersion="apisix.apache.org/v2beta2" \
--set dashboard.enabled=true \
--namespace apisix

vim echo.yaml
---
#The missing item is echo Server
---
apiVersion: apisix.apache.org/v2beta2   #for apisix v2.10
kind: ApisixRoute
metadata:
  name: echo-apisixroute
  namespace: echo
spec:
  http:
  - name: echo-apisixroute
    match:
      paths:
      - "/echo"
    backends:
    - serviceName: echo
      servicePort: 80
    plugins:
    - name: cors
      enable: true

kubectl apply -f echo.yaml

-------------------------
That's all I did

**Comment by tokers** [comment]
@tao12345666333 @gxthrj Please take a look when you have time.

**Comment by gxthrj** [comment]
It should have some error logs in `ingress-controller`, Please show us.
