### ISSUE TITLE
bug:  e2e test will fail randomly

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix-ingress-controller#751]
### Issue description
Because we test UDP route by using kube-dns as backend, we create route in kube-system namespace. But we run e2e in 2 nodes mode, as a result, when the UDP route case is executing, it will affect the accuracy of other cases, because the ingress controller in other cases will also get this UDP route.
This is why e2e failed this time: https://github.com/apache/apisix-ingress-controller/runs/4173189172?check_suite_focus=true
![image](https://user-images.githubusercontent.com/22141303/141255278-24f40715-85f7-4de8-9c72-ec0589564711.png)

**Comment by gxthrj** [comment]
Good catch

**Comment by gxthrj** [comment]
So， I think we should not watch `kube-system` anywhere.

**Comment by nic-6443** [comment]
> So， I think we should not watch `kube-system` anywhere.

Should only be watched in UDP case?

**Comment by gxthrj** [comment]
> > So， I think we should not watch `kube-system` anywhere.
> 
> Should only be watched in UDP case?

Yes, I think so.

**Comment by nic-6443** [comment]
I will fix this issue

**Comment by tao12345666333** [comment]
It seems that the recent e2e is running relatively stable, and related PRs have also been merged, can we close this issue?

**Comment by tokers** [comment]
@nic-6443
