### ISSUE TITLE
bug: The generated consumer name should not just use the ApisixConsumer `metadata.name`

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#752]
### Issue description

Currently, when generate an APISIX consumer object, we just use the `metadata.name` field (see https://github.com/apache/apisix-ingress-controller/blob/da30386c9a4335a82723b46fe7b1342bf0f42867/pkg/types/apisix/v1/types.go#L464) in ApisixConsumer CR, but the schema of APISIX consumer doesn't allow the hyphen character (`-`) (see https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L679), what we need to do is replace the `-` character to another one, say `_`.

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
let me take a look.
