### ISSUE TITLE
bug: If resource synchronization retry occurs, other events of the same resource will be blocked

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#759]
### Issue description
If resource synchronization retry occurs, other events of the same resource will be blocked.

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`); master

### Minimal test code / Steps to reproduce the issue

1. Define an ApisixRoute resource, including backends that does not exist.
2. The ingress controller will report an error and keep retrying.
3. After waiting for a period of time, create another new ApisixRoute resource and find that the synchronization time is slower.
4. At this time, if you create multiple new ApisixRoute resources, the synchronization time will become slower and slower.

### What's the expected result?
The retry of a resource will not affect the synchronization of other resources of the same type.

**Comment by tokers** [comment]
The maximum retry times should be limited just like what the kube-controller-manager does. We may set the amount to a number like `16`.

**Comment by tao12345666333** [comment]
#760 has been merged. I think we can close this issue.
