### ISSUE TITLE
CodeQL job failed on master branch

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#761]
### Issue description

See https://github.com/apache/apisix-ingress-controller/runs/4260643786?check_suite_focus=true for details.

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by tao12345666333** [comment]
I checked the recent execution results of this task and it seems to be an accident.
https://github.com/apache/apisix-ingress-controller/actions/workflows/codeql-analysis.yml

**Comment by tokers** [comment]
Oops, I'd like to watch it for a week, and then close it if no other reports.

**Comment by tao12345666333** [comment]
OK

**Comment by tao12345666333** [comment]
This anomaly has not been seen in recent PRs. I will close it first. If necessary in the future, reopen it

**Comment by Canonical10** [comment]
✅
