### ISSUE TITLE
bug:  typo

### ISSUE THREAD

**Issue by adligo** [apache/apisix-ingress-controller#762]
### Issue description
this yaml file has a typo
https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/proxy-the-httpbin-service.md

### Environment
-serviceName: httpbin
vs this, it should have a space
- serviceName: httpbin
* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by tao12345666333** [comment]
Thanks! Could you help submit a PR to fix it?

**Comment by vancanhuit** [comment]
Hi, new contributors here. I submitted a PR to fix this.

**Comment by tao12345666333** [comment]
#763 has been merged. Thanks.
