### ISSUE TITLE
Install fail ,use Minikube . Any  way to install without use helm?

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#764]
### Issue description
I use Minikube to install  it , but  fail,   Is  that any way to install it ,without use helm?

### Environment
the k8s env:   I use kubeadm to deployment k8s,  one master , and the master is also a work node.

I install it  as the doc  desc: https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/minikube.md :

helm repo add apisix https://charts.apiseven.com
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
kubectl create ns ingress-apisix
helm install apisix apisix/apisix \
  --set gateway.type=NodePort \
  --set ingress-controller.enabled=true \
  --namespace ingress-apisix
  --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix

[root@node-15 minikube]# kubectl get pod -n ingress-apisix
NAME                                        READY   STATUS     RESTARTS   AGE
apisix-69659c949-nln7p                      0/1     Init:0/1   0          114m
apisix-etcd-0                               0/1     Pending    0          114m
apisix-etcd-1                               0/1     Pending    0          114m
apisix-etcd-2                               0/1     Pending    0          114m
apisix-ingress-controller-f68756d54-njwl5   0/1     Init:0/1   0          114m

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`); 
* your Kubernetes cluster version (output of `kubectl version`); 1.19.3
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
@xianshun163 You can install APISIX Ingress controller the hard way (see http://apisix.apache.org/blog/2021/06/28/why-we-need-Apache-APISIX/), or you install it by kustomize (https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/kustomization.yaml).

**Comment by xianshun163** [comment]
thanks, I have find the k8s deployment file  " ingress-controller.yaml" in the source code, 
 I just try to deploy it like a  deployment.
