### ISSUE TITLE
request help: why not reuse the k8s control panel etcd

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix-ingress-controller#765]
### Issue description
Now the helm installation of apisix is using statefulset to deploy the etcd cluster, and I see the community is also not recommended, why not reuse the k8s control panel etcd
Also, I'd like to ask if apisix has support for monitoring the number of api interface calls
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
Yes, it is not recommended to reuse etcd of the k8s control plane, mainly for the following reasons:

* If you want to reset or uninstall APISIX, data management is not easy

* If you have a large amount of data, it will inevitably affect each other

**Comment by tao12345666333** [comment]
I will close this issue, feel free to reopen it if you have any question.
