### ISSUE TITLE
question: The deprecated fields in the crd v1 version are not compatible with k8s v1.18 and earlier versions

### ISSUE THREAD

**Issue by lxm** [apache/apisix-ingress-controller#766]
### Issue description

apisix installed on about 2021-02 and then uninstalled

but crds still in the cluster

recently started a new install, and crds can not upgrade

### Environment

* your apisix-ingress-controller version  1.3.0
* your Kubernetes cluster version  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1. kubectl get crd|grep apisix|awk '{print $1}'|xargs kubectl delete crd
2. kubectl apply -f customresourcedefinitions.yaml 

### What's the actual result? (including assertion message & call stack if applicable)

```
customresourcedefinition.apiextensions.k8s.io/apisixclusterconfigs.apisix.apache.org created
customresourcedefinition.apiextensions.k8s.io/apisixconsumers.apisix.apache.org created
error: error validating "customresourcedefinitions.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[2]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion]; if you choose to ignore these errors, turn validation off with --validate=false
```

### What's the expected result?

crd successfully apply

**Comment by tao12345666333** [comment]
The `CustomResourceDefinition.spec.versions.deprecated` field was added since v1.19 and has not been ported to the previous version. 

So you can run this:

```bash
kubectl apply -f  customresourcedefinitions.yaml --validate=false
```

The Kubernetes project maintains release branches for the most recent three minor releases (1.22, 1.21, 1.20).  I suggest you upgrade K8s version.

**Comment by lxm** [comment]
solved by reinstall the chart
