### ISSUE TITLE
request help: path like /api/*/action

### ISSUE THREAD

**Issue by lxm** [apache/apisix-ingress-controller#768]
### Issue description

using apiroute crd to set path with `/api/*/action` will get an error

how to set path like `/api/*/action` with apiroute

### Environment

* your apisix-ingress-controller version 1.3.0
* your Kubernetes cluster version 1.18
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by jikunchong** [comment]
http://apisix.apache.org/docs/ingress-controller/concepts/annotations/#rewrite-target

**Comment by tokers** [comment]
Currently, APISIX doesn't support an infix wildcard match.

**Comment by lxm** [comment]
> Currently, APISIX doesn't support an infix wildcard match.

any plan to add this support?

**Comment by tao12345666333** [comment]
We need some discussion, or can rewrite meet your needs?

**Comment by lxm** [comment]
> We need some discussion, or can rewrite meet your needs?

rewrite can do this.

I'm using nginx-ingress now, for example , I'm using this to spec different backends

```
/api/srv-1/.*/action1 =>  backend1:port
/api/srv-1/.*/action2 =>  backend2:port
```

**Comment by tokers** [comment]
> 

There is a word around solution, you can use the regex match in the `exprs`.
