### ISSUE TITLE
request help: sync crd labels to apisix

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix-ingress-controller#775]
### Issue description
i have some labels like group,project... in k8s crd,  i want to get the labels in apisix plugins. 
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
Version: 1.3.0
Git SHA: d1afc6e
Go Version: go1.17.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
For the sake of management of other purposes?

**Comment by zlhgo** [comment]
not yet until now

**Comment by zlhgo** [comment]
还是希望能加上这个功能。比如把标签同步到 apisix 后，可以在access_log里多加一些group,project相关的日志信息，这样更方便告警时通知对应项目的负责人。谢谢！

**Comment by tao12345666333** [comment]
Are your alerts log-based rather than metrics-based?
Sounds like this would bring some convenience, but so far I haven't seen other similar feedback.

**Comment by zlhgo** [comment]
都有可能。
