### ISSUE TITLE
request help: Can I use admin  api to define  some  rule， and use the upstream the crd defiled？

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#776]
### Issue description
I  deploy the apisix as a deployment in the k8s, and use the apisix-ingress-controller  ​CRDS  to define some default  rule  for the service.

I have two  questions：

1、 I   want  to    defile  some   complex  ​rules  can  I use  the  admin api  to  defile some other rule, and the rule may use the upstream id  ,which is create  by the  apisix-ingress-controller?

2、I have some  other app, they do not deploy in the k8s,  can  I  use  admin api to  defile some rule for them？

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);1.0.0
* your Kubernetes cluster version (output of `kubectl version`);1.19.3
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
1. yes, you can.

2. Of course you can, as long as you guarantee that there is no conflict.
