### ISSUE TITLE
request help: possible optimization in the installation documentation

### ISSUE THREAD

**Issue by Baoyuantop** [apache/apisix-ingress-controller#783]
### Issue description

I found the problem when I installed it by referring to this document: https://apisix.apache.org/docs/ingress-controller/deployments/minikube

![image](https://user-images.githubusercontent.com/30611190/144389911-c4c5eac0-e781-4c60-909f-d91f7ca43aae.png)

1. Is the ending here missing `\`?
2. Here is a reminder that the user needs to create the ingress-apisix namespace, I created it in advance, but the following steps include creating the namespace, which may be confusing.

**Comment by tokers** [comment]
PR's welcome! I think we can remove the step to create namespace in screenshot 2.

**Comment by tao12345666333** [comment]
we can skip it, and using `--create-namespace` flag for Helm.

**Comment by tao12345666333** [comment]
#785  has merged. I will close this issue. Thanks!
