### ISSUE TITLE
request help: regex_uri in proxy-rewriter 

### ISSUE THREAD

**Issue by brighten1023** [apache/apisix-ingress-controller#784]
### Issue description
I deployed a nginx server for frontend web, and a tomcat server for backend web. I want the traffic to go to backend when accessing '/api/*', and other traffic to go to frontend. Since I use the proxy-rewriter, I write the regex_uri: ["^/api/(.*)$", "/api/$1"] in the backend route, and regex_uri: ["^/(.*)","/$1"] in the frontend route. Now I access frontend web, everything is correct, but when I try to access backend web, it goes 404.  I guess the regex_uri may be wrong, but I don't know how to correct it.

### Environment

* apisix-ingress-controller version 1.3;

**Comment by tokers** [comment]
Please paste more details about the `ApisixRoute` that you created.

**Comment by brighten1023** [comment]
`apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: frontend-route
spec:
  http:
  - name: frontend
    match:
      hosts:
      - test.aaa.com
      paths:
      - /*
    backends:
       - serviceName: frontend
         servicePort: 80
    plugins:
       - name: proxy-rewrite
         enable: true
         config:
           regex_uri: ["^/(.*)", "/$1"]` 
`apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: backend-route
spec:
  http:
  - name: backend
    match:
      hosts:
      - test.aaa.com
      paths:
      - /api/*
    backends:
       - serviceName: backend
         servicePort: 8080
    plugins:
       - name: proxy-rewrite
         enable: true
         config:
           regex_uri: ["^/api/(.*)$", "/api/$1"]`
Temporarily, I use apisix dashboard to create route and upstream, and it goes well
`//route frontend
{
  "uri": "/*",
  "name": "frontend_route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "^/(.*)",
        "/$1"
      ]
    }
  },
  "upstream_id": "384232553139143705",
  "status": 1
}`
`//route backend
{
  "uri": "/api/*",
  "name": "backend_route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/api/(.*)",
        "/api/$1"
      ]
    }
  },
  "upstream_id": "384236511421269017",
  "status": 1
}`

**Comment by tokers** [comment]
> ```
> 
> apiVersion: apisix.apache.org/v2beta2
> 
> kind: ApisixRoute
> 
> metadata:
> 
>   name: frontend-route
> 
> spec:
> 
>   http:
> 
>   - name: frontend
> 
>     match:
> 
>       hosts:
> 
>       - test.aaa.com
> 
>       paths:
> 
>       - /*
> 
>     backends:
> 
>        - serviceName: frontend
> 
>          servicePort: 80
> 
>     plugins:
> 
>        - name: proxy-rewrite
> 
>          enable: true
> 
>          config:
> 
>            regex_uri: ["^/(.*)", "/$1"]
> 
> ```
> 
> and
> 
> ```apiVersion: apisix.apache.org/v2beta2
> 
> kind: ApisixRoute
> 
> metadata:
> 
>   name: backend-route
> 
> spec:
> 
>   http:
> 
>   - name: backend
> 
>     match:
> 
>       hosts:
> 
>       - test.aaa.com
> 
>       paths:
> 
>       - /api/*
> 
>     backends:
> 
>        - serviceName: backend
> 
>          servicePort: 8080
> 
>     plugins:
> 
>        - name: proxy-rewrite
> 
>          enable: true
> 
>          config:
> 
>            regex_uri: ["^/api/(.*)$", "/api/$1"]
> 
> ```
> 
> Temporarily, I use apisix dashboard to create route and upstream, and it goes well
> 
> ```//route frontend
> 
> {
> 
>   "uri": "/*",
> 
>   "name": "frontend_route",
> 
>   "methods": [
> 
>     "GET",
> 
>     "POST",
> 
>     "PUT",
> 
>     "DELETE",
> 
>     "PATCH",
> 
>     "HEAD",
> 
>     "OPTIONS",
> 
>     "CONNECT",
> 
>     "TRACE"
> 
>   ],
> 
>   "plugins": {
> 
>     "proxy-rewrite": {
> 
>       "regex_uri": [
> 
>         "^/(.*)",
> 
>         "/$1"
> 
>       ]
> 
>     }
> 
>   },
> 
>   "upstream_id": "384232553139143705",
> 
>   "status": 1
> 
> }
> 
> ```
> 
> and
> 
> ```//route backend
> 
> {
> 
>   "uri": "/api/*",
> 
>   "name": "backend_route",
> 
>   "methods": [
> 
>     "GET",
> 
>     "POST",
> 
>     "PUT",
> 
>     "DELETE",
> 
>     "PATCH",
> 
>     "HEAD",
> 
>     "OPTIONS",
> 
>     "CONNECT",
> 
>     "TRACE"
> 
>   ],
> 
>   "plugins": {
> 
>     "proxy-rewrite": {
> 
>       "regex_uri": [
> 
>         "^/api/(.*)",
> 
>         "/api/$1"
> 
>       ]
> 
>     }
> 
>   },
> 
>   "upstream_id": "384236511421269017",
> 
>   "status": 1
> 
> }
> 
> ```
> 
> 

The ApisixRoute configurations look good to me. But are there any logs printed by apisix ingress controller?

**Comment by tao12345666333** [comment]
And can you check the route record in Apache APISIX ?

**Comment by brighten1023** [comment]
I almost forgot this issue. The problem was solved by reinstalling the whole apisix and ingress controller, as well as the problem should be related to etcd cluster. This issue can be closed. Many thanks!
