### ISSUE TITLE
request help: ApisixRoute apiversion Inconsistency

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix-ingress-controller#787]
### Issue description
apisix-ingress-controller set apisix_route_version: "apisix.apache.org/v2beta1" but my apisixroute apiVersion still  "apisix.apache.org/v1"。ingress-controller 1.2.0 had this problem, but the problem still occurs when you switch to 1.3.0
![image](https://user-images.githubusercontent.com/92301646/144855227-73879f2e-99fa-413d-8f8a-6365b4602d11.png)

![image](https://user-images.githubusercontent.com/92301646/144855121-4f93b7c1-b264-4ff8-b33e-f7a3f9667b5c.png)

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`):apisix-ingress-controller version 1.3.0-no-git-module-go1.13.8
* your Kubernetes cluster version (output of `kubectl version`):1.18.10
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).linux

**Comment by gxthrj** [comment]
This will not cause the program to fail, and it will not cause you to declare an error in the `ApisixRoute` resource. 
The reason why it is displayed as `apisix.apache.org/v1` is because v1 is the most recent release version.

**Comment by tao12345666333** [comment]
> the problem still occurs when you switch to 1.3.0

How did you upgrade to v1.3?

**Comment by GhangZh** [comment]
> This will not cause the program to fail, and it will not cause you to declare an error in the `ApisixRoute` resource. The reason why it is displayed as `apisix.apache.org/v1` is because v1 is the most recent release version.

So should I configure it according to the definition of v1, or v2beta1?

**Comment by GhangZh** [comment]
> > the problem still occurs when you switch to 1.3.0
> 
> How did you upgrade to v1.3?
Reinstalled via helm uninstall

**Comment by tao12345666333** [comment]
Did you update the CRD again？

**Comment by GhangZh** [comment]
> Did you update the CRD again？

I recreated the crd after the update

**Comment by tao12345666333** [comment]
`delete` then `create` ?

**Comment by tao12345666333** [comment]
And which CRD configuration are you using?

**Comment by GhangZh** [comment]
> And which CRD configuration are you using?
1. Yes, deleted then create.
2.I using apisix.apache.org/v2beta1 ApisixRoute.

**Comment by tao12345666333** [comment]
I mean you are using

* https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml

OR

* https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1

**Comment by GhangZh** [comment]
I am using  [https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml) 
I understand, I need to change the version in the chart too

**Comment by gxthrj** [comment]
> I am using https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml It seems that the latest version of the crd configuration is the v1 version, then I also change all to v1?

I suggest you use v2beta2.

**Comment by tao12345666333** [comment]
> It seems that the latest version of the crd configuration is the v1 version, then I also change all to v1?

yes, we already update CRD apiversion to V1

**Comment by tao12345666333** [comment]
Do you still have problems if you use the latest version?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I will close it, if you still have problems please feel free to reopen it.
