### ISSUE TITLE
bug: after deleting a Route, I could still get it from AdminAPI

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-ingress-controller#793]
### Issue description

This issue is firstly reported from Slack channel: https://the-asf.slack.com/archives/CUC5MN17A/p1639149590142000

Hi everyone!, I'm evaluating using APISIX for our company but ran into a problem. I deployed the latest version (1.3.0) using the helm chart (0.7.2). I created a route through the CRD and everything worked fine, but when I then deleted the created route (through deletion of the apisix route) the route is still there. I tried the admin but it is sometimes it shows me the route is still there and sometimes it shows nothing (looks to me like a sync issue?).
Below is a screenshot of the issue (admin sometimes shows the route and sometimes don't):

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1. Wait for Reporter's update.

### What's the actual result? (including assertion message & call stack if applicable)

Here has one Video https://the-asf.slack.com/archives/CUC5MN17A/p1639149590142000

### What's the expected result?

It should not return the deleted Route.

**Comment by tao12345666333** [comment]
May be the same as #700?

**Comment by tao12345666333** [comment]
Need complete steps.

**Comment by juzhiyuan** [comment]
> May be the same as #700?

Ya

**Comment by gxthrj** [comment]
It seems some cache in APISIX ? 
https://github.com/apache/apisix-ingress-controller/issues/700#issuecomment-989955628

**Comment by juzhiyuan** [comment]
closed due to duplicated as #700

**Comment by juzhiyuan** [comment]
closed due to duplicated as #700
