### ISSUE TITLE
DOC: Adjust the size of the architecture diagram in the README

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#796]
### Issue description

[The image](https://github.com/apache/apisix-ingress-controller#internal-architecture) in README.md is It’s too flat, you should adjust [the size](https://github.com/apache/apisix-ingress-controller/blob/master/docs/assets/images/apisix-ingress-controller-arch.png) so that it is scaled proportionally

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): master
- your Kubernetes cluster version (output of kubectl version): *
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):*

**Comment by zaunist** [comment]
Hi, @gxthrj . I'm pleasure to do this contribution.

**Comment by tokers** [comment]
> Hi, @gxthrj . I'm pleasure to do this contribution.

Thanks! Assigned to you~

**Comment by tao12345666333** [comment]
#805 has been merged. I will close this one. Thanks!
