### ISSUE TITLE
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'

### ISSUE THREAD

**Issue by ccwall3** [apache/apisix-ingress-controller#798]
waiting for apisix-admin
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'
waiting for apisix-admin
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'
waiting for apisix-admin
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'
waiting for apisix-admin
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'
waiting for apisix-admin

rancher deploy  apisix-ingress-controller
![image](https://user-images.githubusercontent.com/7711718/146144466-31a98272-edb1-4871-aa8c-41494833eeb0.png)

![image](https://user-images.githubusercontent.com/7711718/146144490-1e0a0f60-cd91-4ba5-ad1e-545cf07db101.png)

**Comment by tokers** [comment]
Could you check out whether the apisix-admin service exist?

**Comment by tao12345666333** [comment]
it has been fixed

**Comment by tao12345666333** [comment]
@ccwall3  any update?

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, and it is very likely that apache/apisix-helm-chart#143 has been fixed.

I will close it. If you have other questions, please feel free to reopen it.
