### ISSUE TITLE
Flaky test: Ingress LB Status Testing

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#807]
xref: https://github.com/apache/apisix-ingress-controller/runs/4574929212?check_suite_focus=true

**Comment by gxthrj** [comment]
Is this a stably reproduced bug?

**Comment by tao12345666333** [comment]
No, I cannot reproduce it locally. Occasionally appear in GitHub Action.

**Comment by tao12345666333** [comment]
using #869 instead.
