### ISSUE TITLE
bug: kubectl apply -f some_apisix_route.yaml does not take effect

### ISSUE THREAD

**Issue by zenglongfeng** [apache/apisix-ingress-controller#809]
### Issue description

kubectl apply -f some_apisix_route.yaml does not take effect
When I want to add a virtual host to the hosts field, and I execute kubeapply -f some_apisix_route.yaml at the same time, it will not take effect, but kubectl delete -f some_apisix_route.yaml && kubectl create -f some_apisix_route.yaml will have no problem.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
 Version: 1.3.0
Git SHA: no-git-module
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
- your Kubernetes cluster version (output of kubectl version):
1.20.11-aliyun.1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

1. Old configuration
![image](https://user-images.githubusercontent.com/28670395/146893026-33defa95-966a-4a0a-935e-ea6c4b497c16.png)
2. New configuration
![image](https://user-images.githubusercontent.com/28670395/146893167-15a1a4b1-926e-46c8-9ad1-8cc7ea086861.png)
3.  Execute the command kubectl apply -f some_apisixroute.yaml  

### Actual result

access new hosts  "uat-gateway.yyy.cn"  response  {"error_msg":"404 Route Not Found"}

### Error log

no error log

**Comment by tokers** [comment]
Anyway error logs reported by APISIX Ingress Controller?

**Comment by tao12345666333** [comment]
Please provide more information, such as logs, installation methods, etc.

**Comment by tao12345666333** [comment]
This issue has not been updated for a long time, I will close it, if you still have questions please feel free to open it again.
