### ISSUE TITLE
bug: service not found，and  then I edited it and it still kept reporting errors.

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix-ingress-controller#810]
### Issue description

My original configuration of ApisixRoute had a service that didn't exist, and then I edited ApisixRoute and it still kept reporting errors.
![image](https://user-images.githubusercontent.com/92301646/147242908-1f215777-70ac-4710-8c01-9655e6d792af.png)
![image](https://user-images.githubusercontent.com/92301646/147243156-af89b78f-6847-4866-a7df-f8608291f39c.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.3.0
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):Linux

### Minimal test code / Steps to reproduce

kubectl edit ar
kubectl logs -f apisix-ingress-controller 

### Actual result

Successful

### Error log

failed to translate old ApisixRoute service not found

**Comment by tao12345666333** [comment]
Thanks for report. I will try to reproduce it

**Comment by gxthrj** [comment]
Do you mean that after deleting the `service` that does not exist in `ApisixRoute`, `ingress-controller` is still converting the old `service`?

**Comment by gxthrj** [comment]
This is indeed a bug.
When the `ApisixRoute` resource is updated, the old `ApisixRoute` resource object is indeed recorded, so this wrong object always exists.

**Comment by GhangZh** [comment]
> This is indeed a bug. When the `ApisixRoute` resource is updated, the old `ApisixRoute` resource object is indeed recorded, so this wrong object always exists.

At the moment I can only restart the ingress-controller after updating the service pod?
