### ISSUE TITLE
request help: Rewrite URL using ApisixRoute

### ISSUE THREAD

**Issue by hoanhax** [apache/apisix-ingress-controller#817]
### Issue description

I want to rewrite my request using **ApisixRoute**.
For example any requests with **/app** prefix will be forwarded to backend without the **/app/** part, e.g. request **/app/ip** will be forwarded to **/ip** 
As the example in rewrite-target annotation for Ingress (https://apisix.apache.org/docs/ingress-controller/concepts/annotations/#rewrite-target)

Could you please help?

### Environment

- latest version

**Comment by tao12345666333** [comment]
You can find some examples at https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e

**Comment by hoanhax** [comment]
thanks for your quick answer.
I have checked and I can use plugin proxy-rewrite for ApisixRoute.
Thanks again
