### ISSUE TITLE
bug: panic when upgrade from 1.2 to 1.3 because of not set spec.http[].backends in v1beta1/ApisixRoute

### ISSUE THREAD

**Issue by suninuni** [apache/apisix-ingress-controller#823]
### Issue description

I upgraded apisixroute from v1alpha1 to v2beta1 before, so I kept `spec.http[].backend` in ApisixRoute.

And now, I'm trying to upgrade apisix-ingress-controller from 1.2 to 1.3, then I ran into this problem.

After investigation, this is because in the new version of CRD, ApisixRoute is stored as the v2beta2 version, but because the previous configuration file does not set `spec.http[].backends`, so `spec.http[].backends` is none in ApisixRoute v2beta2 version.

### Environment

- 1.2 1.3

### Minimal test code / Steps to reproduce

1. upgrade from 1.2 to 1.3

### Actual result

apisix-ingress-controller crashed.

### Error log

```
panic: runtime error: index out of range [0] with length 0
goroutine 300 [running]:
github.com/apache/apisix-ingress-controller/pkg/kube/translation.(*translator).translateHTTPRouteV2beta2(0xc000402000, 0xc000246cb0, 0xc00076e000, 0x1cb68b9, 0x1cb68b9)
	/build/controller/pkg/kube/translation/apisix_route.go:320 +0x2400
github.com/apache/apisix-ingress-controller/pkg/kube/translation.(*translator).TranslateRouteV2beta2(0xc000402000, 0xc00076e000, 0x19, 0x1, 0x1)
	/build/controller/pkg/kube/translation/apisix_route.go:287 +0x7c
github.com/apache/apisix-ingress-controller/pkg/ingress.(*apisixRouteController).sync(0xc0007646a0, 0x1fdabe0, 0xc00003c280, 0xc00046ec00, 0x8, 0xc000948780)
	/build/controller/pkg/ingress/apisix_route.go:178 +0x2227
github.com/apache/apisix-ingress-controller/pkg/ingress.(*apisixRouteController).runWorker(0xc0007646a0, 0x1fdabe0, 0xc00003c280)
	/build/controller/pkg/ingress/apisix_route.go:79 +0x57
created by github.com/apache/apisix-ingress-controller/pkg/ingress.(*apisixRouteController).run
	/build/controller/pkg/ingress/apisix_route.go:68 +0x245
```

### Expected result

Avoid panic

**Comment by suninuni** [comment]
related https://github.com/apache/apisix-ingress-controller/issues/672#issuecomment-973047308

@tao12345666333 

And after I applied the new version of crd, I couldn't get ApisixRoute through k8s cli for a long time. Is there any way to refresh k8s api server?

```
Error from server (NotFound): Unable to list "apisix.apache.org/v1, Resource=apisixroutes": the server could not find the requested resource (get apisixroutes.apisix.apache.org)
```

**Comment by tao12345666333** [comment]
Can you try to run `kubectl api-resources --api-group=apisix.apache.org` ?

```
$ kubectl api-resources --api-group=apisix.apache.org
NAME                   SHORTNAMES   APIVERSION                  NAMESPACED   KIND
apisixclusterconfigs   acc          apisix.apache.org/v2beta3   false        ApisixClusterConfig
apisixconsumers        ac           apisix.apache.org/v2beta3   true         ApisixConsumer
apisixpluginconfigs    apc          apisix.apache.org/v2beta3   true         ApisixPluginConfig
apisixroutes           ar           apisix.apache.org/v2beta3   true         ApisixRoute
apisixtlses            atls         apisix.apache.org/v2beta3   true         ApisixTls
apisixupstreams        au           apisix.apache.org/v2beta3   true         ApisixUpstream

```

**Comment by suninuni** [comment]
> Can you try to run `kubectl api-resources --api-group=apisix.apache.org` ?
> 
> ```
> $ kubectl api-resources --api-group=apisix.apache.org
> NAME                   SHORTNAMES   APIVERSION                  NAMESPACED   KIND
> apisixclusterconfigs   acc          apisix.apache.org/v2beta3   false        ApisixClusterConfig
> apisixconsumers        ac           apisix.apache.org/v2beta3   true         ApisixConsumer
> apisixpluginconfigs    apc          apisix.apache.org/v2beta3   true         ApisixPluginConfig
> apisixroutes           ar           apisix.apache.org/v2beta3   true         ApisixRoute
> apisixtlses            atls         apisix.apache.org/v2beta3   true         ApisixTls
> apisixupstreams        au           apisix.apache.org/v2beta3   true         ApisixUpstream
> ```

```
# kubectl api-resources --api-group=apisix.apache.org
NAME                   SHORTNAMES   APIVERSION                   NAMESPACED   KIND
apisixclusterconfigs   acc          apisix.apache.org/v2alpha1   false        ApisixClusterConfig
apisixconsumers        ac           apisix.apache.org/v2alpha1   true         ApisixConsumer
apisixroutes           ar           apisix.apache.org/v2beta2    true         ApisixRoute
apisixtlses            atls         apisix.apache.org/v1         true         ApisixTls
apisixupstreams        au           apisix.apache.org/v1         true         ApisixUpstream
```

Now I can get it normally, maybe I can try it when I upgrade other environments

**Comment by tao12345666333** [comment]
When upgrading from APISIX Ingress v1.2 to v1.3, you need to upgrade ApisixRoute resources first, because we have removed the support for the following:

* remove `spec.backend` using `spec.backends` instead
* remove `spec.tcp` using `spec.stream` instead

xref: https://github.com/apache/apisix-ingress-controller/pull/698

And we have introduced the `v2beta2` version of ApisixRoute, it's will be the default api version.

**Comment by suninuni** [comment]
> Can you try to run `kubectl api-resources --api-group=apisix.apache.org` ?
> 
> ```
> $ kubectl api-resources --api-group=apisix.apache.org
> NAME                   SHORTNAMES   APIVERSION                  NAMESPACED   KIND
> apisixclusterconfigs   acc          apisix.apache.org/v2beta3   false        ApisixClusterConfig
> apisixconsumers        ac           apisix.apache.org/v2beta3   true         ApisixConsumer
> apisixpluginconfigs    apc          apisix.apache.org/v2beta3   true         ApisixPluginConfig
> apisixroutes           ar           apisix.apache.org/v2beta3   true         ApisixRoute
> apisixtlses            atls         apisix.apache.org/v2beta3   true         ApisixTls
> apisixupstreams        au           apisix.apache.org/v2beta3   true         ApisixUpstream
> ```

In  1.4, apisix.apache.org/v2beta3 will be the stored version? Can I wait until version 1.5 to upgrade ApisixRoute from v1beta1 to v2? There are too many changes in our clusters for each modification.

**Comment by tao12345666333** [comment]
>In 1.4, apisix.apache.org/v2beta3 will be the stored version?

Yes. In the last few versions, we are upgrading the api version, in order to make it easier to use.

It is explained in the release note of version 1.3 and #707

https://github.com/apache/apisix-ingress-controller/blob/master/CHANGELOG.md#roadmap-1

> In next release(v1.4), all custom resource versions will be upgraded to version v2beta3, and version v2 will be GA released in version 1.5. Please go to #707 for detail.

**Comment by tao12345666333** [comment]
> Can I wait until version 1.5 to upgrade ApisixRoute from v1beta1 to v2? There are too many changes in our clusters for each modification.

Yes, you can.

Note the following configuration before upgrading:

* `spec.http.bakend`
* `spec.stream`

There is not much breaking change in other parts.

**Comment by suninuni** [comment]
Thanks, I have no other questions.

And for this panic, it depends on you whether to resolve it or not.

**Comment by tao12345666333** [comment]
Thanks for your report. 

I will close this issue, maybe we need to add some upgrade practice documents. (Using https://github.com/apache/apisix-ingress-controller/issues/824 for tracking)

**Comment by suninuni** [comment]
> Thanks for your report.
> 
> I will close this issue, maybe we need to add some upgrade practice documents. (Using #824 for tracking)

I think this problem still needs to be fixed. If someone re-applies the ApisixRoute of the v2beta1 version with http.backend after the upgrade, it will cause apisix-ingress-controller crashed.

**Comment by suninuni** [comment]
> > Thanks for your report.
> > I will close this issue, maybe we need to add some upgrade practice documents. (Using #824 for tracking)
> 
> I think this problem still needs to be fixed. If someone re-applies the ApisixRoute of the v2beta1 version with http.backend after the upgrade, it will cause apisix-ingress-controller crashed.

https://github.com/apache/apisix-ingress-controller/blob/a1ef63963c5ee9f4b225e5e663ec060afd4da2f8/pkg/kube/translation/apisix_route.go#L946-L949

Here we need to deal with the situation of http.backend.

**Comment by suninuni** [comment]
@tao12345666333 you need reopen this issue.

**Comment by suninuni** [comment]
https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix-ingress-controller/crds

I can't find CRD file with v2beta3...
