### ISSUE TITLE
doc: need some upgrade practice documents

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#824]
Starting from the Apache APISIX Ingress v1.2 version, we are continuing to unify the api version in order to make it easier to use. #707

However, the upgrade process will contain some destructive changes, we need to add documents to explain it, in order to ensure that users can upgrade smoothly.

**Comment by suninuni** [comment]
```
CustomResourceDefinition.apiextensions.k8s.io "apisixconsumers.apisix.apache.org" is invalid: status.storedVersions[0]: Invalid value: "v2alpha1": must appear in spec.versions
CustomResourceDefinition.apiextensions.k8s.io "apisixupstreams.apisix.apache.org" is invalid: status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions
CustomResourceDefinition.apiextensions.k8s.io "apisixtlses.apisix.apache.org" is invalid: status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions
```

@tao12345666333 When applying the crd of v2beta3 version, I encountered the above error, which made me have to delete these CRD before reapplying, and related resources would also be deleted, resulting in short-term unavailability.

**Comment by tao12345666333** [comment]
@suninuni You can use the CRD from the Helm chart, we have optimized and fixed it

**Comment by tao12345666333** [comment]
@AlinsRan will pick this up.
