### ISSUE TITLE
clean up:  remove BaseURL and AdminKey in config

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#825]
`BaseURL` and `AdminKey` have been marked as obsolete a long time ago. I think we can remove it safely.

Just need to remove these two configuration items, and clean up the related logic.

https://github.com/apache/apisix-ingress-controller/blob/ae69cd3ee42245100b1c559df4518a418f66f6bd/pkg/config/config.go#L107-L114

**Comment by gxthrj** [comment]
Right，I agree.

**Comment by zaunist** [comment]
Hi, please assign to me, I will work for this issue.
