### ISSUE TITLE
discuss: New feature in Apache APISIX Ingress controller v1.5

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#831]
Hi, folks

The Apache APISIX Ingress controller v1.4 version has been released, and it is time to discuss the plans in the v1.5 version together.

I think the following features need to be included:

* [x] Implement v2 version of CRD resources. https://github.com/apache/apisix-ingress-controller/issues/954 
    more details: https://github.com/apache/apisix-ingress-controller/issues/707

* [x] Implement `HTTPRoute` controller loop for Gateway API.  #1037 
  more details: https://github.com/apache/apisix-ingress-controller/issues/644

What features do you want Apache APISIX Ingress controller v1.5 to include?

You can reply to this issue or reply in the mailing list 
https://lists.apache.org/thread/b70vcjrl6sdg4vhgt3k76pd3x0prb0xf

**Comment by tao12345666333** [comment]
* docs: add doc for  ApisixPluginConfig  https://github.com/apache/apisix-ingress-controller/issues/638#issuecomment-1005397071

**Comment by zlhgo** [comment]
ApisixGlobalRule crd

**Comment by tao12345666333** [comment]
> ApisixGlobalRule crd

can you add some details?

**Comment by zlhgo** [comment]
> > ApisixGlobalRule crd
> 
> can you add some details?

only two global plugins can now be enabled via ApisixClusterConfig, when i want to enable more i can only go through admin api or dashboard.
hopefully, enable it via k8s crd.

**Comment by tokers** [comment]
I think if we can also optimize the documentations, that would be grateful for users' self-education.

**Comment by zlhgo** [comment]
@tao12345666333 @tokers i am very sorry, is there already this feature?

**Comment by tokers** [comment]
> 

Sorry, what did you mean?

**Comment by zlhgo** [comment]
非常抱歉，我英语不好，就用中文吧。
我是想通过k8s crd添加全局插件，好想目前只能在ApisixClusterConfig配置开启prometheus和skywalking作为全局插件。

**Comment by tao12345666333** [comment]
@zlhgo we can change `ApisixClusterConfig`  https://github.com/apache/apisix-ingress-controller/blob/de522437bd3db3dc3e8d8f33c92f322de67531b8/samples/deploy/crd/v1/ApisixClusterConfig.yaml#L55-L71  ref to `ApisixPluginConfig` resource.

**Comment by stillfox-lee** [comment]
May be include [mqtt proxy](https://github.com/apache/apisix-ingress-controller/issues/966) ? There is a clear market demand for this feature.

**Comment by tao12345666333** [comment]
The development window for v1.5 has been closed, we are currently in the release window, I will close this issue, thank you everyone
