### ISSUE TITLE
bug: the tranlsation of route with plugin_config is pathological

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#836]
### Issue description

https://github.com/apache/apisix-ingress-controller/blob/de522437bd3db3dc3e8d8f33c92f322de67531b8/pkg/kube/translation/apisix_route.go#L534-L539

The code snippet pasted above has two problems:

1). The plugin config id generation should not rely on the name of backend service name, which will cause all routes with the same backend generated with the same plugin config id.
2). add the plugin_config id reference even if users don't specify the plugin config on the `ApisixRoute` explicitly

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

Nope.

### Actual result

Nope.

### Error log

Nope.

**Comment by tao12345666333** [comment]
cc @neverCase

**Comment by neverCase** [comment]
ok, got it.

**Comment by tao12345666333** [comment]
#845 has been merged. I will close this issue. If you have any question, feel free to reopen it.
