### ISSUE TITLE
question: dashboard modified records are overwritten after controller restart

### ISSUE THREAD

**Issue by 283713406** [apache/apisix-ingress-controller#837]
### Issue description

首先利用apisix-ingress-controller的ApisixRoute这个CRD资源创建了一个route，接着在apisix-dashbord修改并添加了一个limit-conn插件，添加后插件能正常使用。但是当apisix-ingress-controller重启后，在apisix-dashbord添加的limit-conn插件就丢失了。这是不是不合理？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
apisix-ingress-controller version 1.4.0-b7dd90a-go1.16

- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/arm64"}

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
Linux master1 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by tao12345666333** [comment]
Yes. This is normal.
Resources created by Apache APISIX Ingress cannot be modified manually.

After the APISIX Ingress controller restarts, it will re-synchronize resources, so it will overwrite your modified routes.

**Comment by gxthrj** [comment]
Note: Please do not modify the configuration through multiple tools.
`apisix-ingress` using declarative configuration, which will be synchronized with APISIX according to the YAML you declare,
`apisix-ingress` will not synchronize the configuration in the dashboard, because those are not declared and not persisted in k8s.

It is recommended that you use the `apisix-ingress` CRD to declare the configuration. If you must use it with the dashboard, please set the dashboard to read-only.

**Comment by tao12345666333** [comment]
I edited the title, I think the above answer should solve your confusion. I will close this issue, thanks!

**Comment by 283713406** [comment]
@tao12345666333   通过apisix-ingress-controller的crd配置插件，有详细的文档吗？

**Comment by tao12345666333** [comment]
You can see related examples here:
https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/plugins

**Comment by 283713406** [comment]
@tao12345666333  thanks!
