### ISSUE TITLE
resolveGranularity doesnt sync service clusterIP when set to "service"

### ISSUE THREAD

**Issue by gardun0** [apache/apisix-ingress-controller#838]
Hello,

I have this issue where the ingress controller doesn't sync the 'clusterIP' from service once node is terminated. 
I have this scenario because I'm using Preemptible/Spot VMs within my cluster, so once the node and pods are recreated the ingress fallback to Pod IP instead of service and my 'resolveGranularity' is set to 'service'

**Comment by tao12345666333** [comment]
Thanks for your report. What's the version of your APISIX ingress controller?

There is a typo in our CRD which is causing this bug. Please see  https://github.com/apache/apisix-ingress-controller/pull/830

**Comment by gardun0** [comment]
> Thanks for your report. What's the version of your APISIX ingress controller?
> 
> There is a typo in our CRD which is causing this bug. Please see #830

APISIX Ingress Controller version is `1.3.0`

**Comment by tao12345666333** [comment]
What is your installation method?

**Comment by gardun0** [comment]
> What is your installation method?

It's installed by helm and managed by Terraform.

**Comment by tao12345666333** [comment]
Can you check the api-version used by the `ApisixRoute` resource?

I fixed it when I released the v1.3 Helm chart. (v2beta2 version)

**Comment by gardun0** [comment]
> Can you check the api-version used by the `ApisixRoute` resource?
> 
> I fixed it when I released the v1.3 Helm chart. (v2beta2 version)

That's `v2beta2 `, i also changed the `ApisixRoute` version on ingress.

<img width="334" alt="Screen Shot 2022-01-18 at 23 26 37" src="https://user-images.githubusercontent.com/3385668/150069499-d906e045-7154-4b4b-8911-9a26436fcfe2.png">

I can see the typo within the CRD:

<img width="322" alt="Screen Shot 2022-01-18 at 23 24 10" src="https://user-images.githubusercontent.com/3385668/150069275-ddf3a764-945d-442e-9a9e-61426c6cb6b4.png">

The scenario is: Everything is setup, when node is gracefully terminated, it's created again, so there's a new service cluster IP, that new clusterIP is not synced.

**Comment by tao12345666333** [comment]
There are two problems here:

1. When checking the ApisixRoute resource version, I hope you can check the version in YAML.

2. Why does deleting and re-creating your node cause the cluster IP of the service to change? What is your CNI? Usually Service IP is an overlay network IP

**Comment by gardun0** [comment]
> There are two problems here:
> 
> 1. When checking the ApisixRoute resource version, I hope you can check the version in YAML.
> 2. Why does deleting and re-creating your node cause the cluster IP of the service to change? What is your CNI? Usually Service IP is an overlay network IP

1. If you mean the Kubernetes resource, there you have, this is the resource created:
```yaml
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  creationTimestamp: "2022-01-18T23:02:16Z"
  generation: 2
  name: service
  namespace: namespace
  resourceVersion: "36585833"
  uid: 4f9a0aef-8129-4426-af43-99185eb0d3bc
spec:
  http:
    - authentication:
        enable: true
        keyAuth:
          header: X-ApiKey
        type: keyAuth
      backends:
        - resolveGranularity: service
          serviceName: service
          servicePort: 3000
      match:
        hosts:
          - host
        methods:
          - GET
          - POST
          - HEAD
          - OPTIONS
        paths:
          - /*
      name: service
```
2. I was wrong about it, it's not changed, but for some reason APISIX couldn't reach the upstream, for example this is the service IP `10.28.14.200` and this is the one set by the Ingress Controller `10.24.1.9` which is endpoint IP and `resolveGranularity` is set to `service`. My workload http services are inside a service mesh (Kuma) and about the CNI it's managed by GKE

**Comment by gardun0** [comment]
@tao12345666333 I've managed to fix this by let APISIX within Kuma to have direct access to Pod's IP, anyways, the expected behavior when `resolveGranularity` set to `service` to always keep the service IP which it's not happening. For now everything is working.

**Comment by tao12345666333** [comment]
It looks like your problem has been solved.
I am going to close this issue.

Another similar issue is https://github.com/apache/apisix-ingress-controller/issues/853
