### ISSUE TITLE
request help:  panic happen in my cluster

### ISSUE THREAD

**Issue by gavinhot** [apache/apisix-ingress-controller#840]
### Issue description

apisix_ingress_controller run in my cluster,but there is a panic. 
![1](https://user-images.githubusercontent.com/19619272/150674527-babfec21-78f1-4fbd-9e46-b551194185e6.png)

what should i do

### Environment

2022-01-23T17:30:26+08:00	info	ingress/ingress.go:112	apisix ingress controller started
2022-01-23T17:30:26+08:00	info	ingress/ingress.go:114	version:
Version: 1.4.0
Git SHA: no-git-module
Go Version: go1.16.12
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
K8S Version: 1.18.10

**Comment by tao12345666333** [comment]
How did you install it?

And can you run `kubectl get ar -A`?

**Comment by gavinhot** [comment]
Step for it and APISIX of  Version is  1.4.0
1、cd samples/deploy/ 
2、kubectl apply -f .yaml

**Comment by tao12345666333** [comment]
The content in this directory only contains the APISIX Ingress controller itself, not the deployment of APISIX.

From the logs it looks like you have made changes to the https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/configmap/apisix-ingress-cm.yaml file, but I don't Determine what exactly you modified.

This file is out of sync with the config file we are currently using https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml

**Comment by tao12345666333** [comment]
And the image version of the APISIX Ingress controller in this directory is still 1.0 and needs to be updated.

**Comment by tao12345666333** [comment]
Hi, Any update?

**Comment by gavinhot** [comment]
I unmount webhook-certs and it's fine. I do this because my Dev environment is fine on my MAC laptop。

**Comment by gavinhot** [comment]
I'm still on the road to discovery and I'm using ApisixUpstream only. But I found that my app was not registered with Apisix

**Comment by gavinhot** [comment]
> I'm still on the road to discovery and I'm using ApisixUpstream only. But I found that my app was not registered with Apisix。 I found through debug that the svcLister had obtained service, but did not register Apisix directly。 ![image](https://user-images.githubusercontent.com/19619272/151477434-8a54593b-e412-4170-b7ae-4f87f2960879.png)

my ApisixUpstream :

apiVersion: apisix.apache.org/v2bate3
kind: ApisixUpstream
metadata:
  name: test-a
spec:
  loadbalancer:
    type: roundrobin

**Comment by tao12345666333** [comment]
>I'm still on the road to discovery and I'm using ApisixUpstream only

If you only using ApisixUpstream, it will not be sync to APISIX

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-ingress-controller/issues/864

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I think the above reply should have solved your problem.
I will close this issue, if your problem is solved, please feel free to reopen it, thanks.
