### ISSUE TITLE
request help:   Can we split the route crd and plugin crd?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#841]
### Issue description

When i want to add a plugin for different uri ,I have to write two times same backends like below. So can we split the route crd  to route crd and plugin crd ? If i am wrong ,please tell me ,thanks in advance 

`spec:
  http:
    - name: rule1
      match:
        hosts:
          - www.hh.com
        paths:
          - /a/b/c
      backends:
        - serviceName: gateway
          servicePort: 8080
      plugins:
        name: cors
    - name: rule2
        match:
          hosts:
            - www.hh.com
          paths:
            - /a/c/d
        backends:
          - serviceName: gateway
            servicePort: 8080
        plugins:
          name: req-limit`

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Thanks. Now we can using `ApisixPluginConfig`  resource to split route and plugin configurations.

**Comment by purekeeper** [comment]
你没明白我意思， 我的意思是 能不能增加一个ApisixPlugin CRD 专门用于给某些uri 指定plugin,  因为现在APISixRoute 里面backed是必须的,适合定义route ，举个列子，  ApisixRoute 我定义了spec http[0]  path /aa/*   backend 是 xxx,,,, 但是 我想给 aa/bb 定义个plugin 这时候 我该怎么写 ？按照我现在的理解是 再增加一个 spec http[1] ?   为什么不能像Admin api 那样 route的配置和plugin的配置是两个API

**Comment by tokers** [comment]
@purekeeper I think @tao12345666333 really understood your means, `ApisixPluginConfig` works like you said.
