### ISSUE TITLE
request help:  How to set global rule ?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#842]
### Issue description

request help:  How to set global rule ?  such as I want to add a ip-limit plugin for all path no matter what host and uri it is ?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tokers** [comment]
Hi, @purekeeper 

We haven't expose the global rules to the declarative configurations level yet, indeed, currently the `ApisixClusterConfig` will be translated into the global rule but it can only used to configure some observability features so far.

**Comment by tao12345666333** [comment]
We can add this feature. Please see
https://github.com/apache/apisix-ingress-controller/issues/831#issuecomment-1016120453
