### ISSUE TITLE
request help: Deployments of k8s are scaled down. Will the upstream be updated automatically?

### ISSUE THREAD

**Issue by siaron** [apache/apisix-ingress-controller#843]
### Issue description

- k8s 缩容某个Deployment

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): laster version
- your Kubernetes cluster version (output of kubectl version): v1.22.5
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): macos

**Comment by tao12345666333** [comment]
Yes. Apache APISIX Ingress controller will watch resources and update upstream.

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I will close it. Please feel free to reopen it if needed.
