### ISSUE TITLE
request help:  Using the client control plug-in, call the interface to return 501 Not Implemented

### ISSUE THREAD

**Issue by 283713406** [apache/apisix-ingress-controller#844]
### Issue description

给ApisixRoute添加一个client-control的plugin，访问route直接返回501 Not Implemented，如图：
![image](https://user-images.githubusercontent.com/19170385/151097225-ffcfb6d1-7121-4193-b0d2-1636be8d5e5e.png)

![image](https://user-images.githubusercontent.com/19170385/151097136-304187b9-a599-4498-a1fd-74e42f94e660.png)

不加这个插件时能正常访问
![image](https://user-images.githubusercontent.com/19170385/151097164-2af318b3-46df-4bbe-aac5-cc7ff325de83.png)
请问这个插件应该怎么使用?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
apisix-ingress-controller version 1.4.0-b7dd90a-go1.16

- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/arm64"}

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
[](url)
Linux master1 4.19.90-17.ky10.aarch64 misc: some basic goals #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by tao12345666333** [comment]
you can refer to this doc https://apisix.apache.org/docs/apisix/plugins/client-control/#name

notice: This plugin requires APISIX to run on [APISIX-OpenResty](https://apisix.apache.org/docs/apisix/how-to-build#step-6-build-openresty-for-apache-apisix).

**Comment by 283713406** [comment]
Upgrade the version of APISIX and the problem is solved，Please close this issue。thanks！
