### ISSUE TITLE
request help: proxy-rewrite  plugin does not work when apply by ApisixRoute ?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#846]
### Issue description

proxy-rewrite  plugin does not work when apply by ApisixRoute ,right ? i had test it and found it not work 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tokers** [comment]
@purekeeper Please provide some steps that you test it.

**Comment by tao12345666333** [comment]
Or you can refer to the test case https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/plugins/proxy_rewrite.go
