### ISSUE TITLE
leaderelection

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#85]
Currently, all apisix-ingress-controller instances will try to synchronize config changes to APISIX cluster(s), which is duplicate, actually we can elect a leader to synchronize, other instances should be standby and start re-election if the leader is down.

**Comment by tokers** [comment]
We can use https://github.com/kubernetes/kubernetes/tree/323f34858de18b862d43c40b2cced65ad8e24052/staging/src/k8s.io/client-go/tools/leaderelection to achieve this.

**Comment by gxthrj** [comment]
> We can use https://github.com/kubernetes/kubernetes/tree/323f34858de18b862d43c40b2cced65ad8e24052/staging/src/k8s.io/client-go/tools/leaderelection to achieve this.

Agree, related to #11
