### ISSUE TITLE
bug: the secret controller cannot handle secret update events in sometime

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix-ingress-controller#850]
### Issue description

In our environment, there is a bug that the certificate in secret is updated, but the ingress controller does not update the new certificate to APISIX. The reason for this is not known yet. 
Since the environment where the bug occurred is no longer present, we cannot provide more information for now. If we reproduce it later, we will provide further information.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

/

### Actual result

/

### Error log

/

**Comment by tao12345666333** [comment]
Thanks! What's your APISIX Ingress version? And did you use the ApisixTls resource?

**Comment by tokers** [comment]
@nic-6443 .

**Comment by nic-6443** [comment]
> What's your APISIX Ingress version? 

It's a bit complicated, because the version we use is a branch we maintain for special reasons, using code from: https://github.com/nic-6443/apisix-ingress-controller/tree/patch-1 to support upstream mtls, but the code has been merged to upstream.

>  And did you use the ApisixTls resource?

Yes

**Comment by tao12345666333** [comment]
If you're not using this repository but a fork version, I can't easily provide support.

**Comment by tao12345666333** [comment]
And it's not easy to reproduce.

**Comment by tokers** [comment]
> Yes

We may try to reproduce this problem with the standard version. @nic-6443

**Comment by nic-6443** [comment]
Okay, we will try to test with the latest version of the ingress controller and sync up if we get any new clues
