### ISSUE TITLE
request help: Install by Kustomize  fail

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#860]
### Issue description

I clone the code  from the github， and  install by kustomize：
cd  apisix-ingress-controller/samples/deploy
kubectl create namespace ingress-apisix
kubectl kustomize ./ | kubectl apply -f -
It  have a  err msg like this, anyone know what is the problem?

customresourcedefinition.apiextensions.k8s.io/apisixclusterconfigs.apisix.apache.org configured
customresourcedefinition.apiextensions.k8s.io/apisixconsumers.apisix.apache.org configured
customresourcedefinition.apiextensions.k8s.io/apisixpluginconfigs.apisix.apache.org configured
customresourcedefinition.apiextensions.k8s.io/apisixroutes.apisix.apache.org configured
customresourcedefinition.apiextensions.k8s.io/apisixtlses.apisix.apache.org configured
customresourcedefinition.apiextensions.k8s.io/apisixupstreams.apisix.apache.org unchanged
serviceaccount/apisix-view-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/apisix-view-clusterrole unchanged
clusterrolebinding.rbac.authorization.k8s.io/apisix-view-clusterrolebinding unchanged
configmap/apisix-ingress-cm unchanged
secret/webhook-certs configured
service/apisix-admission-server unchanged
deployment.apps/ingress-controller configured
Error from server (BadRequest): error when creating "STDIN": ValidatingWebhookConfiguration in version "v1" cannot be handled as a ValidatingWebhookConfiguration: v1.ValidatingWebhookConfiguration.Webhooks: []v1.ValidatingWebhook: v1.ValidatingWebhook.ClientConfig: v1.WebhookClientConfig.Service: CABundle: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|A_BUNDLE}","service"|..., bigger context ...|1beta1"],"clientConfig":{"caBundle":"${CA_BUNDLE}","service":{"name":"apisix-admission-server","name|...
[root@node-15 deploy]# ls

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4
- your Kubernetes cluster version (output of kubectl version):1.19.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
apisix-ingress-controller/samples/deploy cannot be used directly for installation.

If you look at the content, you will find that other than the CRD, the other content has expired

**Comment by xianshun163** [comment]
if this a good way to install : https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/the-hard-way.md

when I look at the install.md ,  it  like below, there are almost  base the  cloud.  My k8s  is  deploy in my linux local home.

Installation
This is an index page about installing Ingress APISIX in several environments. Click the following links on demands.

[Install Ingress APISIX on Azure AKS](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/azure.md)
[Install Ingress APISIX on AWS EKS](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/aws.md)
[Install Ingress APISIX on ACK](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/ack.md)
[Install Ingress APISIX on Google Cloud GKE](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/gke.md)
[Install Ingress APISIX on Minikube](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/minikube.md)
[Install Ingress APISIX on KubeSphere](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/kubesphere.md)
[Install Ingress APISIX on K3S and RKE](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/deployments/k3s-rke.md)[](https://github.com/apache/apisix-ingress-controller/blob/master/install.md#kustomize-support)
Kustomize Support

**Comment by xianshun163** [comment]
hi, @tao12345666333   
I have deploy the ingress  version 1.3.0 by the follow step：
1、kubectl apply -k  samples/deploy/crd -n  ingress-apisix
2、kubectl apply  -k samples/deploy/rbac -n ingress-apisix
3、kubectl apply -k samples/deploy/admission -n ingress-apisix
4、kubectl apply -k samples/deploy/configmap -n ingress-apisix
5、kubectl apply -k samples/deploy/deployment -n ingress-apisix
It work ok,  I can create some apisixroute for the apisix.

but, when  I change the images version  to 1.4.0  , the po can not run,  it is a err like this, do you know how to upgrade to 1.4.0?
:
`bash
I0211 15:46:23.897763       1 leaderelection.go:248] attempting to acquire leader lease ingress-apisix/ingress-apisix-leader...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde92db]

goroutine 52 [running]:
github.com/apache/apisix-ingress-controller/pkg/apisix.(*cluster).getList(0xc0000d06c0, 0x1fd9c28, 0xc0000c0018, 0xc0002da000, 0x33, 0x1d3fef7, 0x6, 0x0, 0x0, 0x0, ...)
        /build/controller/pkg/apisix/cluster.go:739 +0x19b
github.com/apache/apisix-ingress-controller/pkg/apisix.(*pluginClient).List(0xc00041fd40, 0x1fd9c28, 0xc0000c0018, 0x0, 0x0, 0x0, 0x1, 0x0)
        /build/controller/pkg/apisix/plugin.go:44 +0x3b9
github.com/apache/apisix-ingress-controller/pkg/apisix.(*cluster).syncSchemaOnce(0xc0000d06c0, 0x1fd9c28, 0xc0000c0018, 0x0, 0x0)
        /build/controller/pkg/apisix/cluster.go:388 +0x74f
github.com/apache/apisix-ingress-controller/pkg/apisix.(*cluster).syncSchema(0xc0000d06c0, 0x1fd9c28, 0xc0000c0018, 0x13a52453c000)
        /build/controller/pkg/apisix/cluster.go:352 +0xa5
created by github.com/apache/apisix-ingress-controller/pkg/apisix.newCluster
        /build/controller/pkg/apisix/cluster.go:152 +0x8f4
`

**Comment by xianshun163** [comment]
I can not use helm, because I have modify some code of the apisix, 
I find "the-hard-way.md"  and the kustomize   install doc  is  not work right.
Is that another  guide  doc to install the new version?

**Comment by tao12345666333** [comment]
This documentation is outdated.  Probably written in version 0.5. 

The recommended way to install is to use Helm.

Even if you modify the apisix code, you can use Helm to install only the ingress controller.

**Comment by xianshun163** [comment]
ok, I  have use the helm   sucessful.

**Comment by tao12345666333** [comment]
> ok, I have use the helm sucessful.

This is really good news.  @xianshun163 

If you're interested, I really hope you can add kustomize support to this project.
Currently I have some other high priority tasks working on it.

**Comment by cmssczy** [comment]
> This documentation is outdated. Probably written in version 0.5.

`apisix-ingress-controller` process will also panic if we use the image builded by master branch source code.

**Comment by cmssczy** [comment]
> This documentation is outdated. Probably written in version 0.5.

`apisix-ingress-controller` process will also panic **occasionally** when I use the image build from master branch source code.

```
panic: runtime error: index out of range [0] with length 0

goroutine 98 [running]:
github.com/apache/apisix-ingress-controller/pkg/kube/translation.(*translator).translateHTTPRouteV2beta3NotStrictly(0xc0002061a8, 0xc00001e180, 0xc00040c6e0, 0x160, 0x1bf5860)
	/build/pkg/kube/translation/apisix_route.go:949 +0xd34
github.com/apache/apisix-ingress-controller/pkg/kube/translation.(*translator).TranslateRouteV2beta3NotStrictly(0xc0002061a8, 0xc00040c6e0, 0xc000350cc0, 0x0, 0x0)
	/build/pkg/kube/translation/apisix_route.go:314 +0x85
github.com/apache/apisix-ingress-controller/pkg/ingress.(*Controller).CompareResources.func1.1(0xc000521250, 0xc0004ae2c0, 0x1fdad50, 0xc000350cc0, 0xc0006903f0, 0xc000690420, 0xc000690450, 0xc000690480, 0xc0006904e0, 0xc0006904b0, ...)
	/build/pkg/ingress/compare.go:78 +0x67a
created by github.com/apache/apisix-ingress-controller/pkg/ingress.(*Controller).CompareResources.func1
	/build/pkg/ingress/compare.go:68 +0x178
```

**Comment by tao12345666333** [comment]
@cmssczy Can you create a new issue for track? And we need more informations

**Comment by cmssczy** [comment]
> @cmssczy Can you create a new issue for track? And we need more informations

@tao12345666333  Maybe the `ApisixRoute` defination is incorrect in your [document](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/the-hard-way.md#install-apisix-ingress-controller). The apisix-ingress-controller pod could start successfully when I delete the `ApisixRoute` defined in this doc.😓
