### ISSUE TITLE
How can I get value for path variable ？

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#862]
### Issue description

I define Apisix Route  and use exprs field :

- name: test 
      match:
        hosts:
          - service.xx.cn
        paths:
          -  /aaa/**:var1**/test
      exprs:
        - subject:
            scope: Path or Query ?
            name: **var1**
          op: RegexMatch
          value: "^[^/]{16,}"

I want get the **### va1** value and use exprs to filter request ,so how to write ?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by purekeeper** [comment]
@tao12345666333   Do you know about the issue?

**Comment by tao12345666333** [comment]
you can see https://github.com/api7/lua-resty-expr docs.
