### ISSUE TITLE
request help: 创建apisixupstream对象抛upstream is not referenced异常

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#864]
### Issue description

1. 我在使用apisix ingress controller的情况下，只创建apisixupstream对象，发现etcd中没有生产对应的upstream，如下：
![图片](https://user-images.githubusercontent.com/7006014/153744168-66f0ae55-500a-49b9-bfd0-cdfc8abaa72d.png)
apisix ingress controller输出如下类似的日志：
2022-02-13T15:16:29+08:00	warn	apisix/upstream.go:70	upstream not found	{"name": "apisix_httpbin_80", "url": "http://10.115.21.113:9180/apisix/admin/upstreams/f7a2533e", "cluster": "default"}
2022-02-13T15:16:29+08:00	warn	ingress/controller.go:653	upstream is not referenced	{"cluster": "name=default; base_url=http://10.115.21.113:9180/apisix/admin", "upstream": "apisix_httpbin_80"}
![图片](https://user-images.githubusercontent.com/7006014/153744183-c7247240-1aec-40bc-b663-cce4cd9617d4.png)

2. 如果我删掉apisixupstream对象后，仅创建apisixroute对象，发现etcd中不仅创建对象了upstream，还创建了route，如下：
![图片](https://user-images.githubusercontent.com/7006014/153744199-135c744f-260d-48a9-8dd5-f69b2dbf533c.png)
![图片](https://user-images.githubusercontent.com/7006014/153744203-4bbf3f14-19b1-4145-bdfc-153da318ca63.png)
![图片](https://user-images.githubusercontent.com/7006014/153744208-2484f0f9-bfd8-41a5-bebf-c7cdd9695f54.png)

3. 述求：结合我们的实际使用场景，我只想在创建apisixupstream后，控制器调用apisix管理api在etcd中生成相应的upstream，并实时更新，其他的对象比如route、plugin、customer等统一通过dashbord创建，但是按照以上我实际测试出来的情况，满足不了我的诉求，不确定apisix ingress controller就是这么设计的，还是有问题

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
![图片](https://user-images.githubusercontent.com/7006014/153744397-06b222da-8791-4c42-8205-03d0c8ab3384.png)

- your Kubernetes cluster version (output of kubectl version):
![图片](https://user-images.githubusercontent.com/7006014/153744391-02b90b92-091f-4b88-9f5d-0d9beaf2ab59.png)

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
![图片](https://user-images.githubusercontent.com/7006014/153744447-b25e4c1a-9586-40ed-9f51-af5f7db51041.png)

**Comment by marchlhw** [comment]
> @marchlhw Unless the Kubernetes Service is referenced (used in ApisixRoute`), or the underlying APISIX Upstream won't be created, even if ApisixUpstream existing.

请问apisix-ingress-controller中apisixupstream的用途是什么？或在什么场景下使用？

**Comment by marchlhw** [comment]
apisix-ingress-controller中apisixupstream的逻辑有可能会调整吗？创建apisixupstream crd并与kubernetes service关联也会创建upstream

**Comment by tao12345666333** [comment]
This may be up for discussion.

**Comment by tao12345666333** [comment]
If you have time, you can join the meeting this Wednesday #614

**Comment by xuminwlt** [comment]
yes，we need too.
same to @marchlhw 
Combined with our actual usage scenarios, I just want to create the apisix upstream, the controller calls the apisix management api to generate the corresponding upstream in etcd, and update it in real time. Other objects such as route, plugin, customer, etc. are uniformly created through dashbord, but according to The above situation I actually tested can not meet my demands

**Comment by tao12345666333** [comment]
I want to know, why not use declarative configuration directly in the Kubernetes environment, but rather a combination of declarative + dashboard? @xuminwlt @marchlhw

**Comment by xuminwlt** [comment]
We need a k8s-based service discovery function that can synchronize to the latest service pods information in real time. At present, only ingress has such a function, but the routing and consumer functions of the management side are currently carried out in the dashboard. Based on the current status , which is an optimal choice.

Our implementation process is:
1. The business applies for service access and generates the corresponding ingress apisixupstream.
2. After the business application is passed, you can go to the management platform to perform routing operations, and configure the corresponding Service, Route, and Consumer, which is actually the upstream in the Ingress synchronized to etcd.

This is our scene.

**Comment by tao12345666333** [comment]
got it.

**Comment by tao12345666333** [comment]
> why: In most scenarios, we only need to define a ApisixRoute, and we don't need to bother to define ApisixUpstream. but, if we proxy a grpc service , we have to define ApisixUpstream like
> 
> ```
> apiVersion: apisix.apache.org/v1
> kind: ApisixUpstream
> metadata:
>   name: yages
>   namespace: ingress-apisix
> spec:
>   scheme: grpc
> ```
> 
> so suggest：proxy scheme should be in ApisixRoute not ApisixUpstream, that way we can do less work

copy from #871  @myselfghost

**Comment by jerrytaotz** [comment]
Yes！We need this feature too, eagerly

**Comment by xiangtianyu** [comment]
Our team have the same scenary, we may need this feature! Is there any schedule about this?

**Comment by xuminwlt** [comment]
In many cases, upstream is actually some kind of metadata. It is a system configured based on metadata, such as the publishing system. Routing is a dynamic configuration in which the control surface controls how traffic enters the corresponding upstream. It is more processed by the micro service traffic management system. If the two can be configured separately, it will bring great flexibility.

**Comment by tao12345666333** [comment]
@jerrytaotz @xiangtianyu @xuminwlt  Thanks for your feedback.   Based on discussions on multiple issues and community meetings, I added a `triage/accepted` label for this and added this feature to our roadmap.

I will write a proposal for the specific implementation plan.

**Comment by xuminwlt** [comment]
Great to me.

**Comment by jinjianming** [comment]
> @marchlhw Unless the Kubernetes Service is referenced (used in ApisixRoute`), or the underlying APISIX Upstream won't be created, even if ApisixUpstream existing.

@tokers Hello, I encountered a similar issue on #1855, but my 'ApisixRoute' is bound to the correct Kubernetes Service, which periodically prompts' warn Apisix/upstream. go: 69 upstream not found ', causing Apisix to process many useless requests;

**Comment by tao12345666333** [comment]
These are two different issues.  The core requirement in this issue has been resolved through #1019.

We can continue discussing your current issue in #1855. I will close this issue. Thanks
