### ISSUE TITLE
question: ApisixTls resource not syncing due to not upgrade CRD

### ISSUE THREAD

**Issue by Phoebus888** [apache/apisix-ingress-controller#865]
### Issue description

ApisixTls创建  Apisix后台不会自动创建证书
apiVersion: apisix.apache.org/v1
kind: ApisixTls
metadata:
  name: lylb1
  namespace: test
spec:
  hosts:
    - lylbnew.01lb.vip
  secret:
    name: lylb1
    namespace: test

web后台不会自动创建  需要手动填写和上传证书
![image](https://user-images.githubusercontent.com/45359605/153761900-a07a1ed5-8631-492b-b718-1c07ec0077c3.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

apisix2.12.0
apisix-dashboard2.10.1
ingress-apisix1.4.0

### Minimal test code / Steps to reproduce

1

### Actual result

1

### Error log

E0214 00:06:00.392554 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixTls: failed to list *v2beta3.ApisixTls: the server could not find the requested resource (get apisixtlses.apisix.apache.org)

![image](https://user-images.githubusercontent.com/45359605/153761938-15aec356-4769-4a5c-8316-124976e2a9e8.png)

**Comment by tokers** [comment]
@Phoebus888 After you created the Secret, is the certificate created also?

**Comment by tao12345666333** [comment]
Can you run ` kubectl api-resources --api-group=apisix.apache.org` ?

In v1.4, the API version used by the ApisixTls resource is v2beta3.

**Comment by Phoebus888** [comment]
[root@k8s-mast1 apisix-ingress]# kubectl api-resources --api-group=apisix.apache.org
NAME                   SHORTNAMES   APIGROUP            NAMESPACED   KIND
apisixclusterconfigs   acc          apisix.apache.org   false        ApisixClusterConfig
apisixconsumers        ac           apisix.apache.org   true         ApisixConsumer
apisixpluginconfigs    apc          apisix.apache.org   true         ApisixPluginConfig
apisixroutes           ar           apisix.apache.org   true         ApisixRoute
apisixtlses            atls         apisix.apache.org   true         ApisixTls
apisixupstreams        au           apisix.apache.org   true         ApisixUpstream

我的是这个  和你的不一样

**Comment by tao12345666333** [comment]
How did you install the APISIX Ingress controller? Or you can update the CRD.

**Comment by Phoebus888** [comment]
helm install apisix  \
 --create-namespace \
 --set gateway.type=NodePort  \
 --set ingress-controller.enabled=true \
 --set dashboard.enabled=true  \
 --set gateway.tls.enabled=true \
 --set etcd.persistence.size="300Gi" \
 --set admin.allow.ipList="" \
 --namespace ingress-apisix apisix/

**Comment by Phoebus888** [comment]
how to update crd?

**Comment by Phoebus888** [comment]
大佬  我重新找了一个k8s集群安装   新安装的APIGROUP都是apisix.apache.org  不是apisix.apache.org/v2beta3

**Comment by tao12345666333** [comment]
> how to update crd?

you can just using this CRD.

**Comment by Phoebus888** [comment]
> > 如何更新crd？
> 
> 你可以只使用这个 CRD。https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml

没问题了  使用新的crd就可以了    helm包安装后面是不是要改一下

**Comment by tao12345666333** [comment]
Unfortunately, Helm currently does not have the ability to upgrade CRDs. For details, see 
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

**Comment by tao12345666333** [comment]
I will close this issue. Feel free to reopen it if you have any question.
