### ISSUE TITLE
request help: failed to list stream_routes

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-ingress-controller#866]
### Issue description

apisix-ingress-controller报错输出：
![图片](https://user-images.githubusercontent.com/7006014/153836221-627744ba-7f37-40dd-a5e2-8620ea0ad182.png)
apisix报错输出：
![图片](https://user-images.githubusercontent.com/7006014/153836335-82ffac8e-56d6-4ba6-b634-3c4c73ab3569.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
![图片](https://user-images.githubusercontent.com/7006014/153835311-c4fcdb9e-87c4-44e6-91b1-4f5171014025.png)

- your Kubernetes cluster version (output of kubectl version):
1.18

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tao12345666333** [comment]
Please upgrade your Helm chart version.

xref: https://github.com/apache/apisix-ingress-controller/issues/851#issuecomment-1026306420
https://github.com/apache/apisix-helm-chart/pull/233

duplicate: https://github.com/apache/apisix-ingress-controller/issues/858

**Comment by tao12345666333** [comment]
I will close this issue.  It will be fixed in https://github.com/apache/apisix-ingress-controller/pull/868
