### ISSUE TITLE
通过dashboard  更新ingress-controller生成的路由信息

### ISSUE THREAD

**Issue by xiongyunhua-star** [apache/apisix-ingress-controller#876]
### Issue description

操作步骤：

1.  通过Yaml创建的AR资源,形成路由信息之后，在dashboard上编辑上游信息，删除一个上游Pod实例

问题：
在没有更新业务deployment和ingress-controller pod 的情况下，什么时候会把上有信息恢复原有的默认配置？
是通过ingress-controller pod 加载的cm的 resync_interval: "1h"   进行周期性 同步？
apiVersion: v1
data:
  config.yaml: |
    # log options
    log_level: "info"
    log_output: "stderr"
    http_listen: ":8080"
    enable_profiling: true
    kubernetes:
      kubeconfig: ""
      resync_interval: "1h"   【此字段进行】
      app_namespaces:
      - "default"
      ingress_class: "apisix"
      ingress_version: "networking/v1beta1"
      apisix_route_version: "apisix.apache.org/v2beta2"

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by xiongyunhua-star** [comment]
现象没有复现

**Comment by tao12345666333** [comment]
it's not recommanded.

**Comment by tao12345666333** [comment]
In fact, we recommend setting the APISIX dashboard to be read-only.
It is not safe to manage resources in two ways at the same time

**Comment by tao12345666333** [comment]
> In fact, we recommend setting the APISIX dashboard to be read-only. It is not safe to manage resources in two ways at the same time

I think we've explained why, I'll close this issue, feel free to open it again if you have other ideas
