### ISSUE TITLE
can  it  let  apsix's upstream directly use k8s's service name

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#889]
### Issue description

can  it  let  apsix's upstream directly use k8s's service name? 
just like  nginx  annotations:  ingress. kubernetes. IO / service upstream: true 
this will let the nginx ingress the config the nginx upstream as a service name ,not the pod ip.

this is usefull for the service mesh 。 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4
- your Kubernetes cluster version (output of kubectl version):1.19
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Please use 

```

resolveGranularity: service

```

**Comment by xianshun163** [comment]
ok， thanks
