### ISSUE TITLE
[TODO] Add a complete demo to run with ingress-controller

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#9]

**Comment by mtx2d** [comment]
Hi @gxthrj , 
This means we need a `Get Started`  session, right?
I really wish this demo integrates with `Helm` as well.

**Comment by mtx2d** [comment]
I am in the process of deploying APISIX to my GCP cluster.
Will document the process here and hopefully we can compile it into a working demo.

**Comment by gxthrj** [comment]
> I am in the process of deploying APISIX to my GCP cluster.
> Will document the process here and hopefully we can compile it into a working demo.

Great，I think it's a good way to use `helm`, Looking forward to your document

**Comment by gxthrj** [comment]
hello， @mtx2d , any update ?

**Comment by gxthrj** [comment]
Related to #69

**Comment by gxthrj** [comment]
Close this issue now, Feel free to reopen if you have any question.
