### ISSUE TITLE
request help: 代理grpc服务性能低

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix-ingress-controller#903]
### Issue description

当我使用apisix代理grpc服务进行性能测试的时候，发现性能较低
![image](https://user-images.githubusercontent.com/31987918/156999259-ce167c01-6926-48f4-8e4b-7f30a7159e72.png)
并且发现一个现象：压测pod时候，对应端口只有几个TCP连接，但是通过apisix压测时候，pod里有上千条TCP连接，是因为没有复用tcp连接吗。
还是和k8s环境有关系啊，有什么可以优化的地方吗？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by nic-chen** [comment]
hi, here is your prev issue:
https://github.com/apache/apisix/issues/6511

could you please provide some detail? thanks

**Comment by tao12345666333** [comment]
Please add more information to your previously submitted issue https://github.com/apache/apisix/issues/6511

I will close this one.
