### ISSUE TITLE
docs: Update apiversion in documentation.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#915]
Currently APISIX Ingress controller has upgraded the default supported custom resource version to `v2beta3` ,but our documentation is a bit outdated.

We need to upgrade the `v2beta1` or `v2beta2` used in these documents to `v2beta3`.

**Comment by Belyenochi** [comment]
if no one else, pls assign it to me.

**Comment by tao12345666333** [comment]
Sure, thanks!
