### ISSUE TITLE
bug: we should create APISIX routes even if Service is created later

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#926]
> https://github.com/apache/apisix-ingress-controller/blob/c9e0c965cd2226e2c44aa4e692a8bf57d1586aa3/pkg/ingress/apisix_route.go#L261-L271
> 
> We will delete this event from workqueue if we have an `ApisixRoute` resources without any valid backends. It is reasonable?

@cmssczy  This change is to fix the #810 and was introduced in #893 

**This does cause some problems.**

For example, create an ApisixRoute first, which references a service that does not exist.
But when a Service is created, the APISIX Ingress controller can't actually create a route.

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/issues/925#issuecomment-1072128249_

**Comment by tao12345666333** [comment]
@cmssczy Are you interested in fixing this problem?

**Comment by cmssczy** [comment]
I think we should discuss a plan first.

IMO, first we should return `nil` if we got an `ApisixRoute` with no backends existed.
https://github.com/apache/apisix-ingress-controller/blob/2178857fbe2608cec1dc8ce5b1e0ec232568b375/pkg/kube/translation/util.go#L37-L41

Then we need a `service` controller to list/watch `update/create/delete` event which will be used to apply to apisix admin API.(maybe need more details)

Or could we stop supporting `resolveGranularity`?

**Comment by tao12345666333** [comment]
> Or could we stop supporting `resolveGranularity`?

This feature is useful and we will not stop supporting it

**Comment by tao12345666333** [comment]
Maybe we can discuss it at the community meeting on Wednesday

**Comment by cmssczy** [comment]
we should create an apisix `upstream` with an empty `nodes` when user creates a `ApisixRoute` with a non-existent `service`.
I write a demo for this solution. PTAL, https://github.com/cmssczy/apisix-ingress-controller/commit/3a729d9927d10481403ea0f5169c9a12b450fd8d

**Comment by tao12345666333** [comment]
Creating an empty Upstream sounds good.
In this way, when the Service is actually created, we can update it again.
WDYT @lingsamuel @gxthrj

**Comment by lingsamuel** [comment]
Sorry for the late reply.
Instead of creating a placeholder, I think it would be better to resync the routes that references the newly created service.

**Comment by tao12345666333** [comment]
@lingsamuel  But currently we have discarded the event, how to resync it?

We discussed the compensation mechanism for adding timing before https://github.com/apache/apisix-ingress-controller/issues/234   but this method is not real-time enough

**Comment by lingsamuel** [comment]
Perhaps we need a cache to store the reference relationships.
This cache should always store the relationships, regardless of whether sync raises an error or not.

**Comment by tao12345666333** [comment]
Currently, we have a cache https://github.com/apache/apisix-ingress-controller/blob/master/pkg/apisix/cache/memdb.go
we can extend it. WDYT?  @lingsamuel @gxthrj @tokers

**Comment by gxthrj** [comment]
I think it is OK.
Before, we had to create an upstream because of the limitation of APISIX, an error will be reported when there is no upstream. Now that APISIX can support the creation of routes without upstream, I think it is time to let `ApisixRoute` manage its own life cycle independently.

**Comment by tokers** [comment]
> I think it is OK. Before, we had to create an upstream because of the limitation of APISIX, an error will be reported when there is no upstream. Now that APISIX can support the creation of routes without upstream, I think it is time to let `ApisixRoute` manage its own life cycle independently.

Could you show some cases about " that APISIX can support the creation of routes without upstream".

**Comment by tao12345666333** [comment]
I think this is an important question.

If you have no other comments, I will consider extending cache to solve it.

After my recent v2 apiversion resource upgrade task finished, I will propose a specific scheme design or directly implement it.

**Comment by cmssczy** [comment]
> extending cache to solve it

I don't understand how to solve this problem by extending the cache. Can you provide more details about this solution? @tao12345666333

**Comment by tokers** [comment]
> I think this is an important question.
> 
> If you have no other comments, I will consider extending cache to solve it.
> 
> After my recent v2 apiversion resource upgrade task finished, I will propose a specific scheme design or directly implement it.

I don't have doubts except the words written by @gxthrj .

**Comment by AlinsRan** [comment]
> @lingsamuel But currently we have discarded the event, how to resync it?
> 
> We discussed the compensation mechanism for adding timing before #234 but this method is not real-time enough

This PR #1022 can solve this problem, which is equivalent to retrying resource operations, but the default interval is 300s (Changeable). This interval is a little long, Should we shorten the time?

**Comment by lingsamuel** [comment]
Instead of using a cache, I decided to add a handler to the service informer of the ApisixRoute controller. This is consistent with the way K8s does it.

**Comment by tao12345666333** [comment]
> Instead of using a cache, I decided to add a handler to the service informer of the ApisixRoute controller. This is consistent with the way K8s does it.
> 
> 
> 
> @tao12345666333 PTAL

SGTM 

When the svc is created, do you want to check the status of the ApisixRoute to determine whether to synchronize?  Or in another way?
