### ISSUE TITLE
CI: Split e2e test cases to reduce overall time consumption

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#932]
Currently, it takes more than an hour to run a complete e2e test case, which is a bad experience both for the developer experience and for the development progress.

Although we can specify to run specific test cases before submitting code, in a CI environment, we want to run all cases in full to ensure the quality of our code.

I suggest that we can split and run the current test cases to reduce the overall time-consuming.

**Comment by fgksgf** [comment]
We can refer to this [PR](https://github.com/jaegertracing/jaeger-operator/issues/1726).

**Comment by tao12345666333** [comment]
> We can refer to this [PR](https://github.com/jaegertracing/jaeger-operator/issues/1726).

@fgksgf Great! This is exactly what I expected

**Comment by fgksgf** [comment]
Ok, i will have a try. Assign it to me, pls.
