### ISSUE TITLE
what is the best practices for plugin configuration shared by multiple services in apisixingress

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#936]
### Issue description

what is the best practices for plugin configuration shared by multiple services in apisixingress? 

when I use dashboard  or  admin api  I  found it can do like this:
1、use the  public service  when  config a route:
![image](https://user-images.githubusercontent.com/32457473/160088583-afe62250-4793-403f-af39-30635b246354.png)

2、use the  plugin template when config a route:
![image](https://user-images.githubusercontent.com/32457473/160088768-312b4947-4e14-4a52-8329-14d8c8c3220e.png)

in the ingress mode,   I  use the  pluginconfig  crd,  but  it make a problem as I  describe in #854 
I create the pluginconfig crd, but the  route can not use it .
this is my  yaml file:

[xsapp-route-pluginconfig.zip](https://github.com/apache/apisix-ingress-controller/files/8349080/xsapp-route-pluginconfig.zip)

Is that  any way to do it? 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.0
- your Kubernetes cluster version (output of kubectl version): 1.19.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Thanks for your feedback, I'll try to reproduce your problem first
