### ISSUE TITLE
how to start this controller in goland ide

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#940]
### Issue description

![image](https://user-images.githubusercontent.com/32457473/160407758-ddd39e16-16fa-4462-b03b-7bbf67299719.png)

I  use the goland  ide  and  start it with the  program  arguments like this : 
ingress --kubeconfig D:\dev\config --http-listen :8080 --log-output stderr --default-apisix-cluster-base-url http://172.16.11.15:30980/apisix/admin --default-apisix-cluster-admin-key edd1c9f034335f136f87ad84b625c8f1

is it  the right way to  start it in the  goland   or in the windows  local  .

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.0
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Sorry I have no experience with IDEs. I only use Vim.

Usually, if you want to start outside the Kubernetes cluster, you would use the following command:

```
./apisix-ingress-controller ingress --config-path  path-of-your-config-file.yaml
```

Your above parameters seem to be fine.

**Comment by xianshun163** [comment]
ok, thanks
