### ISSUE TITLE
request help: How to rewrite http to https in the apisix ingress controller

### ISSUE THREAD

**Issue by brighten1023** [apache/apisix-ingress-controller#945]
### Issue description

I have a web-based cluster and it can be accessed by using http successfully. Now I am prepared to use https, but after browsing https://apisix.apache.org/docs/apisix/plugins/redirect/ and https://apisix.apache.org/docs/apisix/FAQ/#how-to-redirect-http-to-https-via-apache-apisix, I still confusing what should I do first. Could you please give some advice? am 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.3.0
- your Kubernetes cluster version (output of kubectl version):1.22.3

**Comment by tao12345666333** [comment]
You have two ways:

1. You can use the Ingress resource and add `k8s.apisix.apache.org/http-to-https: "true"` annotation.   ref: https://github.com/apache/apisix-ingress-controller/blob/3b993533d66b25c186f4096727d373e5ed4131c6/test/e2e/annotations/redirect.go#L39

2. You can use the ApisixRoute resource, and add plugin configuration:
```
   plugins:
   - name: redirect
     enable: true
     config:
       http_to_https: true
```
ref: https://github.com/apache/apisix-ingress-controller/blob/3b993533d66b25c186f4096727d373e5ed4131c6/test/e2e/plugins/redirect.go#L57-L61
