### ISSUE TITLE
feat request: rotate log

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix-ingress-controller#950]
### Issue description

当日志输出到文件时增加日志切割功能。
比如在我的环境，有一个自动删除3天没有写入日志的文件，ingress-controller是candidate状态的时候，就算是开启debug级别的日志也不会有日志输出，所以当过了3天日志文件就被清理了。之后ingress-controller成为了leader, 不过文件句柄还在，ingress-controller程序也能正常工作写入日志，但是日志采集程序就采不到日志了。希望能增加日志切割功能或定时写点日志也行。谢谢。

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
Version: 1.4.0
Git SHA: 1159522
Go Version: go1.17.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
In a Kubernetes environment, we usually recommend writing logs to stdout/stderr, which I don't think is a high priority requirement.


https://github.com/apache/apisix-ingress-controller/blob/7e4ec36e36c9114d99156e72b19142d2026533fc/conf/config-default.yaml#L24-L28

Why are you writing the log to a file?

**Comment by zlhgo** [comment]
@tao12345666333 嗯，只是一个建议，合理的话希望能考虑下。

**Comment by tao12345666333** [comment]
@zlhgo Thanks for your advice. We can discuss it at the next community meeting.

**Comment by tao12345666333** [comment]
#1200 has been merge. It has been implemented.
