### ISSUE TITLE
Docs: How to access Apache APISIX Prometheus Metrics on Kubernetes

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#953]
I think it's worthy to write some documents about "How to access Apache APISIX Prometheus Metrics on Kubernetes".

_Originally posted by @tokers in https://github.com/apache/apisix-ingress-controller/pull/942#discussion_r843745233_

**Comment by Chever-John** [comment]
I am looking forward to this task.
Let me do it!

**Comment by tao12345666333** [comment]
Assigned

**Comment by tao12345666333** [comment]
#973 has been merged. I will close this one.
