### ISSUE TITLE
feat: Add v2 API version support for all resources

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#954]
The background has already been introduced in #707.
This issue is tracked for tasks in v1.5.
This will be the last task blocking the v1.5 release.

To achieve this goal we have a lot of tasks to do.  In order to facilitate the review, we need to split it into multiple tasks. (There was a huge PR, #820 was closed)

- [x] Base code to initialize v2 version  #939 
- [x] ApisixRoute  #943 
- [x] ApisixUpstream #1141 
- [x] ApisixTls #967
- [x] ApisixConsumer #989
- [x] ApisixClusterConfig #977
- [x] ApisixPluginConfig #984
- [x] Update `samples/deploy/crd` CRD to add v2 resources 
- [x] Add e2e tests for v2 resources
    - [x] #1103 
    - [x] #1014 
    - [x] #1067
    - [x] #1044
    - [x] #1016    
    - [x]  #1147
- [x] Add docs #1063 

In this process, we need to increase the support for multiple versions of various resources, instead of directly replacing the current v2beta3 with v2. So we need to be more careful. 
This issue is used to track the progress of this task, if anyone is interested in this task, can comment and choose any task to implement.

**Comment by lingsamuel** [comment]
https://github.com/apache/apisix-ingress-controller/pull/967#discussion_r857082894
