### ISSUE TITLE
CI: Encapsulate functions to reuse code

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#969]
I think we can encapsulate a method `ensureAdminOperationIsSuccessful`, and pass the request, so that we can reuse the code base of `ensureHTTPPutSuccess`.

_Originally posted by @tokers in https://github.com/apache/apisix-ingress-controller/pull/937#discussion_r844945283_

**Comment by tao12345666333** [comment]
@cmssczy Are you interested in this?

**Comment by cmssczy** [comment]
ok, pls assign to me.

**Comment by tao12345666333** [comment]
Assigned

**Comment by tao12345666333** [comment]
#971 fixed this one
