### ISSUE TITLE
bug: plugin config in APISIX but do not in declare yaml

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix-ingress-controller#974]
### Issue description

After upgrading apisix 1.13and apisix-ingress-controller 1.4 through helm, ingress-controller will automatically synchronize the current ar file to apisix and add the field plugin_config_id
```bash
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: test
  namespace: test
spec:
  http:
  - backends:
    - serviceName: test
      servicePort: 80
    match:
      hosts:
      - apisix-test.com
      paths:
      - /cluster/idc*
    name: test
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/cluster/idc(.*)", "/$1"]
```

![image](https://user-images.githubusercontent.com/92301646/164189340-f4d68eda-8469-42cc-aaac-bcba700b4681.png)

apisix-ingress-controller log
![image](https://user-images.githubusercontent.com/92301646/164189436-bf6d8b0e-c0c9-43f9-865c-ee85dc5c613c.png)

curl http://127.0.0.1:9180/apisix/admin/plugin_configs -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

![image](https://user-images.githubusercontent.com/92301646/164190770-680c96f4-fd68-4f47-846e-a78e776b9110.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

kubectl apply -f test.yaml

kubectl exec -it apisix-544b6cbf74-npr5z -n ingress-apisix bash

curl http://127.0.0.1:9180/apisix/admin/plugin_configs -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

### Actual result

No  plugin_config_id

### Error log

```bash
	warn	ingress/compare.go:186pluginConfig: 2930e8f3 in APISIX but do not in declare yaml
2022-04-20T16:13:34+08:00      
	warn	ingress/compare.go:186pluginConfig: 2930e8f3 in APISIX but do not in declare yaml
```

**Comment by GhangZh** [comment]
> The problem has been fixed
> 
> #836

Is there a way to circumvent it now. Even if I call the admin-api interface to remove it, the ingresscontroller will still add this field to apisix again

**Comment by tao12345666333** [comment]
@GhangZh you need to use the master branch to build the image

**Comment by GhangZh** [comment]
> @GhangZh you need to use the master branch to build the image

ok,thanks

**Comment by tao12345666333** [comment]
@GhangZh After discussions we decided to release v1.4.1  #980

**Comment by tao12345666333** [comment]
After v1.4.1 is released, you can upgrade to fix this issue. I will close this issue, we will track it with #980
