### ISSUE TITLE
v1.5版本发布时间

### ISSUE THREAD

**Issue by Gerrylinux** [apache/apisix-ingress-controller#978]
### Issue description

确认下 V1.5版本发布时间

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Horus-K** [comment]
I also want to confirm 1.5 release time, we are going to use v2 api for production environment

**Comment by tao12345666333** [comment]
plz see #954

**Comment by tao12345666333** [comment]
#954 will take a lot of time, we need to make sure it's correct and stable.

Currently under active development.

If you have any questions please comment under #954 , I will close this issue, thanks for your attention
