### ISSUE TITLE
request help: support hmac-auth plugin for ApisixConsumer

### ISSUE THREAD

**Issue by wangyp0701** [apache/apisix-ingress-controller#990]
### Description

What I learned is
At present, only basic-auth and key-auth are supported
Do you have any plans to add functions

**Comment by tokers** [comment]
@tao12345666333 PTAL, thanks!

**Comment by tao12345666333** [comment]
Thanks for your report.

ref: https://github.com/apache/apisix-ingress-controller/issues/986#issuecomment-1110543942

We can add this supprt.
Currently adding wolf-rbac plugin

**Comment by Chever-John** [comment]
Please assign this to me~

**Comment by tao12345666333** [comment]
Assigned

Thanks

**Comment by Fatpa** [comment]
Please assign this to me, and I have already submitted the pull request.

**Comment by Chever-John** [comment]
> Please assign this to me, and I have already submitted the pull request.

Wow, Thanks for your contribution, I'm busy with my thesis lately and may not be able to address this issue very well. Thanks again for your timely contribution.

**Comment by tao12345666333** [comment]
@Fatpa thanks, assigned

**Comment by tao12345666333** [comment]
#1035 has been merged. I will close this one.
