### ISSUE TITLE
request help: apisix-ingress-controller：stream mode is disabled, can not add stream routes

### ISSUE THREAD

**Issue by helloxubo** [apache/apisix-ingress-controller#991]
### Issue description

I use the latest chart(https://charts.apiseven.com) install apisix、apisix-dashboard and apisix-ingress-controller;
apisix version is 0.9.1，  apisix-ingress-controller  version is 0.9.0,
but also has the same problem "stream mode is disabled, can not add stream routes"
#858 
![图片](https://user-images.githubusercontent.com/38270190/165733432-625b6d33-1e67-4f27-a216-4fff9b4713c6.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by xuminwlt** [comment]
https://github.com/apache/apisix-helm-chart/pull/233

heml-chart已经修复了。

**Comment by helloxubo** [comment]
> [apache/apisix-helm-chart#233](https://github.com/apache/apisix-helm-chart/pull/233)
> 
> heml-chart已经修复了。
![QQ图片20220428214947](https://user-images.githubusercontent.com/38270190/165769011-cbb8537e-3c9c-442f-86e3-fbeb9a94c8f1.png)

![QQ图片20220428215529](https://user-images.githubusercontent.com/38270190/165769038-663081f0-2aed-43b1-ad9a-cc159fc2e59c.png)

你好，在安装apisix的时候，只需将dashboard和ingress-controller的enabled设置为true，就会自动安装dashboad和ingress-controller；不需要再使用另外两个chart包单独安装dashbord和ingress-controller了吗？

**Comment by tao12345666333** [comment]
> 你好，在安装apisix的时候，只需将dashboard和ingress-controller的enabled设置为true，就会自动安装dashboad和ingress-controller；不需要再使用另外两个chart包单独安装dashbord和ingress-controller了吗？

Yes, this is the most recommended way.
