### ISSUE TITLE
request help: About apisix-ingress-controller logs

### ISSUE THREAD

**Issue by helloxubo** [apache/apisix-ingress-controller#995]
### Issue description

Why  apisix-ingress-controller check these services?   
![QQ图片20220429175608](https://user-images.githubusercontent.com/38270190/165923559-c7e3e09c-43bc-4656-913c-588e87af804c.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Apache APISIX Ingress controller will watch all services (all namespaces) by default.
You can change the configuration.

**Comment by helloxubo** [comment]
> Apache APISIX Ingress controller will watch all services (all namespaces) by default.
> You can change the configuration.

ok thinks!
