### ISSUE TITLE
APISIX Ingress Is cross namespace supported？

### ISSUE THREAD

**Issue by souljessi** [apache/apisix-ingress-controller#997]
### Issue description

Is cross namespace supported?

**Comment by cmssczy** [comment]
yes.
you can also select the namespaces which you want apisix-ingress-controller to watch via `namespace_selector `.
https://github.com/apache/apisix-ingress-controller/blob/92b89b37d2f63eab6f5c6deb6e3d2a5ccae975aa/conf/config-default.yaml#L58-L60

**Comment by tao12345666333** [comment]
As [cmssczy](https://github.com/cmssczy) 's answer, APISIX Ingress can use multiple namespaces.

**Comment by tao12345666333** [comment]
I will close the one. If you have any questions please feel free to reopen it. thanks
