### ISSUE TITLE
docs: Documentation page on certificate management has a broken link to example files

### ISSUE THREAD

**Issue by Kowsz** [apache/apisix-ingress-controller#998]
### Issue description

Hello,

Apache APISIX documentation page [Manage Ingress Certificates With Cert Manager](https://apisix.apache.org/docs/ingress-controller/practices/manage-ingress-certificates-with-cert-manager/) link to example cert-manager manifests is broken. The link https://apisix.apache.org/docs/ingress-controller/practices/cert-manager returns a 404 error.

![image](https://user-images.githubusercontent.com/11330497/166910060-bc5033e5-663d-4694-8294-a9ed403d6496.png)

Best regards,
Kowsz

### Environment

not applicable

### Minimal test code / Steps to reproduce

1. Go to https://apisix.apache.org/docs/ingress-controller/practices/manage-ingress-certificates-with-cert-manager/
2. Click on the "For testing purposes, we will use a simple CA issuer. All required files can be found [here](https://apisix.apache.org/docs/ingress-controller/practices/cert-manager)." link

### Actual result

![image](https://user-images.githubusercontent.com/11330497/166910476-6354adff-6ae7-40e0-a1d9-7a86b0b8c9f0.png)

### Error log

not applicable

### Expected result

The webserver serves the correct files

**Comment by tao12345666333** [comment]
Thanks for your report, it should link to https://github.com/apache/apisix-ingress-controller/tree/master/docs/en/latest/practices/cert-manager

Are you interested in submitting a PR to fix it?

**Comment by Kowsz** [comment]
Yeah, sure.
As far as I can tell, the files to be updated are:

1. [/docs/en/latest/practices/manage-ingress-certificates-with-cert-manager.md](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/manage-ingress-certificates-with-cert-manager.md) 
2. [/docs/en/latest/practices/manage-certificates-with-cert-manager.md](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/manage-certificates-with-cert-manager.md)

Should I also bump the patch version in [/docs/en/latest/config.json](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/config.json)?

**Comment by tao12345666333** [comment]
only update the two markdown files. Thanks
